### ISSUE TITLE
"Open Terminix Here" fails to open MTP/remote location

### ISSUE THREAD

**Issue by brunelli** [gnunn1/terminix#100]
When you have a sftp or mtp location (probably also other protocols) mounted in Nautilus, opening it and selecting "Open Terminix Here" does nothing.

So I have to open a Terminix instance and `cd /run/user/1000/gvfs/$DEVICE`. IIRC it used to work with gnome-terminal.

**Comment by gnunn1** [comment]
Thanks for the report, it also fails if a directory has a space in it.

**Comment by gnunn1** [comment]
I had a quick look at this, there is a couple of issues here. The first is the python extension converts the URI to a directory by stripping off the file:/// portion, of course you need the full URI for anything other then a bog-standard file. The second issue is that terminix may need a way to accept a URI rather then a plain file, more investigation on this part required. I'll look into how gnome-terminal is handling this.

**Comment by gnunn1** [comment]
That was surprisingly easy, turns on the gnome-terminal plugin just converts it to a local path. While my python foo is weak, I managed to figure out how to do the same thing in the python code. I tested with my Nexus 6 and confirmed it works, unfortunately I'm working away from home and don't have ready access to a remote server to test that, please try it out and see how it goes.

I noticed the gnome-terminal plugin does some specific handling and parsing for FTP and SSH URIs so more work in that area may be required but I'll wait for a bug report on that first.

I also fixed the issue with spaces in the directory.
