### ISSUE TITLE
Terminix closes when opening an URL without the protocol string

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#104]
Steps to reproduce:

- Open terminix
- Enter an URL without the protocol string (http://), p.e.: www.google.com
- Click on the URL
- Terminix closes with the error:

```
2016-02-24T01:17:38.081:app.d:main:62 Unexpected exception occurred
2016-02-24T01:17:38.081:app.d:main:63 Error: Operation not supported
```

Environment: 

- Terminix v0.50.2
- Debian Testing
- GNOME 3.18

**Comment by gnunn1** [comment]
I had a look at how Gnome Terminal impements this, looks like I didn't fully implement all of the parts required. I'll try to get this fixed for the next release.

**Comment by edubxb** [comment]
Thanks!

**Comment by edubxb** [comment]
Thanks, now works perfectly!
