### ISSUE TITLE
The whole session is closed after closing a maximized tile

### ISSUE THREAD

**Issue by brunelli** [gnunn1/terminix#107]
Steps to reproduce:

1. Open a new tile

2. Maximize one of the tiles

3. Close the maximized tile

![captura de tela de 2016-02-24 14-58-50](https://cloud.githubusercontent.com/assets/5755892/13295371/364d6606-db07-11e5-8c87-82f781b890ad.png)

**Comment by gnunn1** [comment]
Whoops, good catch. Fortunately should be an easy fix.

**Comment by gnunn1** [comment]
This was a little more complicated then expected but think I have it fixed now. I also took care of an edge case where a terminal is maximized and one of other terminals in the session closes via an exit command or something similar.
