### ISSUE TITLE
Copy/Paste issue

### ISSUE THREAD

**Issue by klingtnet** [gnunn1/terminix#108]
~~Copy/Paste works only in first session~~.

I'm using terminix `0.50.2` in Arch Linux, details follow later.

**Comment by klingtnet** [comment]
UPDATE: Copy/paste doesn't work (sometimes) when I ssh into a remote machine.

**Comment by phw** [comment]
> UPDATE2: There is also a configuration warning (VTE something) whenever I open a shell via ssh.

For this see https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue, also linked in that dialog ;)

**Comment by klingtnet** [comment]
I'm using the `run command as login shell` fix and will check if the problem still persists.

**Comment by gnunn1** [comment]
I can't reproduce this, please update if the login shell made any difference when you get a chance. Also, I need to test with ssh more myself, I don't think the VTE warning should appear in the SSH case.

**Comment by klingtnet** [comment]
Sorry, I had some work to do. Fortunately I can say that the error hasn't occured since I use the login shell. Nonetheless, the only time I got the *VTE warning* was when I started an SSH session. I will close this issue.
