### ISSUE TITLE
Launching Terminix with session file on CentOS 7.2

### ISSUE THREAD

**Issue by dbasinge** [gnunn1/terminix#109]
Terminix crashes on my with launching it with a session json file. Works fine on Arch.
 ~  terminix -s /home/dbasinge/personal/3-pane.json                     
object.Error@(0): The function you are calling is not pressent in your version of GTK+.
----------------
??:? extern (C) void gtkc.Loader.Linker.unsupportedSymbol() [0x9be881]
??:? void gtk.Paned.Paned.setWideHandle(bool) [0x8b995c]
??:? gtk.Paned.Paned gx.terminix.session.Session.createPaned(gtkc.gtktypes.GtkOrientation) [0x813f62]
??:? gtk.Paned.Paned gx.terminix.session.Session.parsePaned(std.json.JSONValue, gx.terminix.session.SessionSizeInfo) [0x815b4b]
??:? gtk.Widget.Widget gx.terminix.session.Session.parseNode(std.json.JSONValue, gx.terminix.session.SessionSizeInfo) [0x815a05]
??:? void gx.terminix.session.Session.parseSession(std.json.JSONValue, gx.terminix.session.SessionSizeInfo) [0x815e13]
??:? gx.terminix.session.Session gx.terminix.session.Session.__ctor(std.json.JSONValue, immutable(char)[], int, int, bool) [0x816051]
??:? void gx.terminix.appwindow.AppWindow.loadSession(immutable(char)[]) [0x8073fe]
??:? void gx.terminix.appwindow.AppWindow.initialize() [0x807a94]
??:? void gx.terminix.application.Terminix.createAppWindow() [0x802872]
??:? void gx.terminix.application.Terminix.onAppActivate(gio.Application.Application) [0x802c0f]
??:? extern (C) void gio.Application.Application.callBackActivate(gtkc.giotypes.GApplication*, gio.Application.Application) [0x842868]
??:? g_closure_invoke [0x55f86e37]

**Comment by dbasinge** [comment]
Here is the json file in question
{
    "child": {
        "child1": {
            "directory": "\/home\/xxxxx",
            "height": 1161,
            "profile": "5a518637-9663-4c15-bdc5-16462b57e7e7",
            "type": "Terminal",
            "width": 960
        },
        "child2": {
            "child1": {
                "directory": "\/home\/xxxxx",
                "height": 580,
                "profile": "5a518637-9663-4c15-bdc5-16462b57e7e7",
                "type": "Terminal",
                "width": 956
            },
            "child2": {
                "directory": "\/home\/xxxxx",
                "height": 577,
                "profile": "5a518637-9663-4c15-bdc5-16462b57e7e7",
                "type": "Terminal",
                "width": 956
            },
            "orientation": 1,
            "position": 49,
            "type": "Paned"
        },
        "orientation": 0,
        "position": 50,
        "type": "Paned"
    },
    "height": 1161,
    "name": "Default",
    "type": "Session",
    "version": "1.0",
    "width": 1920
}

**Comment by gnunn1** [comment]
Lol it's me not you. I was fooling around with the splitters trying to
improve the look in Ubuntu. I'll check if that call is actually needed and
either remove or put a GTK version check on it.

**Comment by gnunn1** [comment]
Added a version check around panned.setWideHandle. Thanks for reporting this, found another bug at the same time which was good :)
