### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by karabuta** [gnunn1/terminix#110]
I tried to compile terminix using dmd  v2.070.0 and got this error (Ubuntu 14.04.03, x86);

source/gx/terminix/application.d(110,49): Error: function glib.Variant.Variant.getString (out uint length) is not callable using argument types (ulong)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, AppWindow[], long) error instantiating
source/gx/terminix/application.d(344,29):        instantiated from here: remove!(AppWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, ProfileWindow[], long) error instantiating
source/gx/terminix/application.d(355,29):        instantiated from here: remove!(ProfileWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, bool delegate(ActionType)[], long) error instantiating
source/gx/terminix/common.d(44,29):        instantiated from here: remove!(bool delegate(ActionType))
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, void delegate(string, string, string, string)[], long) error instantiating
source/gx/terminix/common.d(83,29):        instantiated from here: remove!(void delegate(string, string, string, string))
source/gx/terminix/cmdparams.d(57,35): Error: function glib.Variant.Variant.getString (out uint length) is not callable using argument types (ulong)
source/gx/terminix/cmdparams.d(80,26): Error: cannot implicitly convert expression (i) of type ulong to uint
source/gx/terminix/cmdparams.d(81,38): Error: cannot implicitly convert expression (i) of type ulong to uint
dmd failed with exit code 1.

**Comment by gnunn1** [comment]
That's a lot of errors, it's building fine for me using v2.070. Can you confirm you are using ```dub build`` as the build command. Also, what is the output of ```dmd --version```?

**Comment by karabuta** [comment]
Yes I used the dub command as indicated at the instructions section. Also I use v2.070 just like you but on a x86 machine Ubuntu 14.04. My Gtk version is 3.14 and I don't think I have manually installed the `GTK VTE Widget 0.42`. Could that be the problem? Sorry for posting so much errors above, I thought that will help deduce the problem :smile:

**Comment by gnunn1** [comment]
Thanks for the info, I think the issue is the 32 bit x86 you are using, I've never tried to compiled Terminix for a 32 bit environment as I only support 64 bit given that most people have moved on to 64 bit machines (no insult intended!).

If you want to adjust the code so that it compiles for both 32 and 64 bit compilers I would be happy to take any PRs you submit but I don't have any plans to do this work myself.

**Comment by karabuta** [comment]
I understand. x86 pulls be back. Thanks anyway.

**Comment by gnunn1** [comment]
No worries
