### ISSUE TITLE
Use matchCheckEvent

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#111]
Please don't use vte.matchCheck, use vte.matchCheckEvent instead.

The former is deprecated since 0.43 because it doesn't make sense with the new smooth scrolling feature (i.e. the scrollbar scrolls pixel by pixel, rather than row by row).

(And is also prone to off-by-padding errors.)

**Comment by gnunn1** [comment]
Thanks for the pointer, I'll make that change
