### ISSUE TITLE
Add shebang to install.sh

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#112]
xenial$ sudo ./install.sh 
Installing to prefix /usr
./install.sh: 14: ./install.sh: function: not found
Processing 
msgfmt: no input file given
Try 'msgfmt --help' for more information.
./install.sh: 19: ./install.sh: Syntax error: "}" unexpected

This is because sudo tries to execute it via /bin/sh which is a symlink to dash on Ubuntu, whereas the script apparently needs bash. Please add a "#!/bin/bash" or "#!/usr/bin/env bash" line to the top.

**Comment by dsboger** [comment]
Adding the shebang pointing to bash would solve the problem. Also, it is possible to use a more portable function declaration by omitting the `function` word and adding parenthesis after the function name:

`function processPOFile {`

becomes

`processPOFile() {`

In this case, a shebang could point to `sh` and it should work with `dash` also.

**Comment by dsboger** [comment]
I tested my previous workaround and saw that `export -f` is also bash-only. I've made a PR that seems to fix this issue.
