### ISSUE TITLE
Inconsistent behaviour with "Switch to next/previous terminal" shortcuts

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#116]
There is inconsistency how `switch to next terminal` and `switch to previous terminal` works.

If you keep pressing `switch to next terminal` shortcut, that just keeps going through terminals, which is what it should do IMO.

However, `switch to previous terminal`  just goes back until it reaches terminal 0.

**Comment by gnunn1** [comment]
Thanks, you are right it should be consistent, I'll take care of that.
