### ISSUE TITLE
 undefined identifier 'math' in package 'std'

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#118]
$ dub build --build=release

source/gx/terminix/appwindow.d(490,48): Error: undefined identifier 'math' in package 'std', did you mean module 'path'?
dmd failed with exit code 1.

**Comment by gnunn1** [comment]
Not sure why you are having a problem, works fine for me. I just checked in a change to explicitly import std.math, see if that works for you.

**Comment by alex285** [comment]
that worked!
