### ISSUE TITLE
Clicking on some terminal top bar should give it focus

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#122]
If I have multiple terminal tiles, and I click on the top bar of some unfocused one, the focus remains with the previously focused terminal. It would be nice to transfer focus when any area of the terminal tile is clicked, be the content area or the top bar.

**Comment by dsboger** [comment]
Maybe also the scrollbar? :)

**Comment by gnunn1** [comment]
I'm fine with titlebar but very reluctant about scrollbar, it's not unusual to want to scroll an unfocused terminal to see something I'm loath to change keyboard focus.

As a point of comparison, I checked Terminator and they don't focus the terminal when either titlebar or scrollbar is clicked.

**Comment by dsboger** [comment]
Maybe I'm not used to tiled interfaces enough. Looks like I'm expecting each tile to be analogous to a window, focus-wise. I see myself clicking on the titlebar to change focus frequently, but I almost never click the scrollbar, so no strong feelings towards that. An issue is that clicking on content sometimes has a meaning, depending on what is running in that terminal (e.g. vim visual mode), so the titlebar makes for a "neutral" area.
