### ISSUE TITLE
Terminix does not open after update

### ISSUE THREAD

**Issue by TasosKan** [gnunn1/terminix#125]
I updated to the latest version through the Antergos repository. Now every time I try to open it I get the error : 
" GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Settings' does not contain a key named 'menu-accelerator-enabled'
Trace/breakpoint trap (core dumped) "

I am using Antergos Linux x86_64, GNOME 3.18.2 with kernel 4.4.3-1-ARCH.

**Comment by gnunn1** [comment]
As far as I can tell the release has the correct settings file as I see menu-accelerator-enabled in it. The Arch ```terminix``` package worked fine for me, is Antergos using the AUR package?

**Comment by frnogueira** [comment]
In my Arch 4.4.3-1 works fine! 
Without errors.

**Comment by dsboger** [comment]
Last time I saw, antergos repo package was stuck in 0.40.0 or so.

**Comment by dsboger** [comment]
Check this out: https://build.antergos.com/build/2248

It says the following in the build log:

```
237  [03/05/2016 09:24AM]: ==> Validating source files with md5sums...
238  [03/05/2016 09:24AM]:     terminix.zip ... Passed
239  [03/05/2016 09:24AM]:     com.gexperts.Terminix.gschema.xml ... Passed
```

Maybe Antergos build uses a different gschema?

**Comment by gnunn1** [comment]
I found that as well, see here https://github.com/Antergos/antergos-packages/tree/master/terminix

Opening an issue with them as we speak.

**Comment by TasosKan** [comment]
Hmmm didn't check the version. I assumed it was the AUR versiin mirrored on a repository. I will close the issue here and check the issue with the Antergos team.
