### ISSUE TITLE
Sidebar issue

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#126]
every click on left side, it shows sidebar
I make a video for this https://youtu.be/NxywfkxgTLY

**Comment by gnunn1** [comment]
Thanks, unfortunately I cannot reproduce. Can you provide some details on your environment:

a. Distro
b. GTK version
c. Theme

Thanks!

**Comment by arshavindn** [comment]
I'm using Ubuntu 15.10 with Gnome 3.18, theme is MosCloud

**Comment by gnunn1** [comment]
I don't have that version of Ubuntu setup but no issues in 16.04, If you use the default theme do you still have the same issue?

**Comment by arshavindn** [comment]
yes, default theme has the issue too. First I click on button on header bar to show sidebar, then whenever I click on left side like in the video, the sidebar shows up.

**Comment by gnunn1** [comment]
PK thanks, I'll have a look. May take some time as I'll need to install
that version of Ubuntu.

**Comment by arshavindn** [comment]
here is a video with default theme and mouse click record. The left side I mentioned is the area that sidebar will appear.
https://youtu.be/Jj27T4unjqs

**Comment by arshavindn** [comment]
I dont know why but now the issue is gone

**Comment by gnunn1** [comment]
Good to know, thanks for closing the issue. If it happens again just re-open and I'll have a look at it.
