### ISSUE TITLE
Changing profile preferences will change solarized light to dark

### ISSUE THREAD

**Issue by liamnoone** [gnunn1/terminix#128]
When I change the colorscheme to use the Solarized Light built-in colorscheme, then edit the profile's preferences, the colorscheme will automatically change to Solarized Dark.

It happens whether I change it via Preferences -> Profiles, and edit the profile though there, or when I go directly from the profiles list. It also doesn't matter if I close Terminix inbetween changing the profile preferences.

It doesn't happen for all colorschemes; this only seems to happen with Solarized Light. I haven't customized any of the exiting colorschemes, or added any new ones.

I'm running Terminix from AUR with Gnome 3.18.2. It happens with both 0.51.1-1 (current terminix version in aur) and 0.52.1.r0.23a14fa-1 (current terminix-git version in aur) versions.

**Comment by gnunn1** [comment]
Terminix doesn't actually save the color scheme you select, it just saves the colors and then uses a simple matching algorithm to see if the current colors match a pattern and sets the combobox accordingly. Solarized Light and Dark are very similar, likely my matching algorithm has a bug in it.
