### ISSUE TITLE
Send right-click to apps

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#130]
Right click with the mouse should send the event to the application running inside the terminal if that application is interested in it (e.g. midnight commander), instead of bringing up the context menu.

The context menu could still be presented on e.g. Shift + Right click.

See https://bugzilla.gnome.org/show_bug.cgi?id=13299#c34 for how gnome-terminal does it. Basically the Vte widget returns true/false depending on whether it handled the event, and only if it didn't then should Terminix present its own menu.

**Comment by gnunn1** [comment]
Thanks for the insight, I'll take care of that.
