### ISSUE TITLE
Quick session switcher

### ISSUE THREAD

**Issue by noirbizarre** [gnunn1/terminix#137]
Right now, to switch sessions, we have 2 choices:
- display the left session sidebar and chose the right one
- go directly to a session given its number (which requires to know them)

It would be nice to be able to switch directly to the previous and next session.

As a bonus, it would be awesome to:
- display the session name on change (like a temporary overlay with the name)
- display the sessions names in the session sidebar

**Comment by gnunn1** [comment]
I can add new shortcuts for next and previous sessions as it makes perfect sense to me.

I'm not sure about displaying the session names in the sidebar or in some sort of overlay, I'm kind of moving towards removing the session name to be honest as I'm not sure people find it overly useful. Input from users on this would be helpful.

**Comment by noirbizarre** [comment]
I work with multiple sessions and I find the ability to name them very useful !

For the overlay part, as the session name is displayed in main titlebar, an extra overlay on switch is useless, I agree. But, when you are in fullscreen (which I am), the session name is not displayed, this is why I think of a temporary overlay on switch.

In the sidebar, I don't use the numbering and I find names more useful (most of the times, I have multiple sessions open, and when I resume my laptop, it's easier to see what's in each session with names). As it's very personnal, an option to switch from numbering to naming in the sidebar could be another solution (it's a proposal).

**Comment by gnunn1** [comment]
Added next/prev session shortcuts

**Comment by noirbizarre** [comment]
Great :+1:

**Comment by gnunn1** [comment]
I've added displaying the session name to the sidebar and I'm going to close this issue as I've taken it as far as I want to go. Since the session name is displayed in the title already no plans to start showing overlays at this time.

**Comment by noirbizarre** [comment]
Fine too me. Thanks by the way for the feature !!
