### ISSUE TITLE
Keybinding are misrecorded (<Primary> instead of <Ctrl>)

### ISSUE THREAD

**Issue by noirbizarre** [gnunn1/terminix#138]
When I try to record some keybinding, the `<Ctrl>` is misrecorded as `<Primary>` and I have to change it manually with `dconf-editor`.

I'm using Terminix 0.52.1 on Archlinux with Gnome 3.18 and `fr` keyboard layout.

**Comment by gnunn1** [comment]
That's the way the shortcut in GTK works, Primary is the same as Ctrl so should work fine, at least it does for me. Are you having an issue with the shortcut not working?

**Comment by noirbizarre** [comment]
Yes, I have to change them in dconf-editor in order to have them to work :/

**Comment by gnunn1** [comment]
Thanks for the feedback, I'll have a look and see what I can find about it.

**Comment by egmontkob** [comment]
FYI: Shortcuts recorded as &lt;Primary&gt;foo do work for me. However, it's disturbingly inconsistent that the factory ones show as &lt;Ctrl&gt; whereas the custom ones as &lt;Primary&gt;.

I've no clue about Gtk+'s decision why it calls it Primary. I think it's a stupid thing to do. All computers have a Ctrl key and not a Primary key. In my opinion, the word "Primary" should never appear on the UI. I'm sure there are valid technical reasons behind the story, but users just don't care.

**Comment by gnunn1** [comment]
With respect to Primary being shown, I think there is something here that I can handle better, the AccelsGroup API has two similar operations, one returns the name of the accelerator while the other returns a label meant to be displayed to users. I need to look at this more and figure out to wire CellRendererAccel to use the label version for dispay but store the name. Gnome terminal seems to handle this just fine.

**Comment by gnunn1** [comment]
I pushed a commit so the shortcuts are displayed with the label instead of the name. I can't reproduce your problem though with regards to the shortcuts not taking effect, I wonder if it's related to the fr keyboard. Does gnome terminal shortcuts work fine for you?

**Comment by noirbizarre** [comment]
I just restested, and it works (wasn't working by the time I submitted the issue).
Sorry for the trouble, it seems to be fixed.

**Comment by gnunn1** [comment]
No trouble at all, thanks to this I fixed the shortcut preferences to get rid of Primary and it looks much better now so mission accomplished. :)
