### ISSUE TITLE
dep: use system gtkd?

### ISSUE THREAD

**Issue by MingcongBai** [gnunn1/terminix#139]
As it seems, `dub build --build=release` will pull a copy of `gtk-d` from its Git (?) master, regardless of system dependency status.

Will it be possible to build Terminix with system dependencies?

**Comment by gnunn1** [comment]
Fixed, I hadn't realized that GtkD updated the package to 3.2.3, previously I had to force master in order to ensure people were getting the memory fixes. Otherwise people building from source kept reporting the same problem that had already been addressed in GtkD.

**Comment by MingcongBai** [comment]
> Fixed, I hadn't realized that GtkD updated the package to 3.2.3, previously I had to force master in order to ensure people were getting the memory fixes. Otherwise people building from source kept reporting the same problem that had already been addressed in GtkD.

Gotcha, guess I will need to do more homework on `dub` anyways...

**Comment by MingcongBai** [comment]
Oh wait... with that patch, `dub build` will still try to pull `gtk-d`?

**Comment by gnunn1** [comment]
Oops, think i misunderstood. Yes, dub always pulls the dependency as that is what it does, removes the need for the developer to worry about it. It's similar in concept to the Maven build tool in Java.

**Comment by MingcongBai** [comment]
> Yes, dub always pulls the dependency as that is what it does, removes the need for the developer to worry about it.

Guess I don't have to worry about it then... It's static anyways.
