### ISSUE TITLE
Drop area highlight not always visible

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#141]
The color selection used to highlight a drop area when you drag one terminal over another needs some work, it's not always visible as per this video here: https://www.youtube.com/watch?v=zGR_J3-xxX0

Might be something specific to Gnome 3.20.

**Comment by dsboger** [comment]
I didn't know there was an indication for drop area, as I've never seen one. I'm on 3.18. Let me know if there is anything I can do to help debug the issue.

**Comment by gnunn1** [comment]
@dsboger If you switch to a color scheme that explicitly sets the background color like Orchis you will see it. I appreciate the offer, don't think I'll have any problem reproducing it but if I do I'll let you know.

**Comment by dsboger** [comment]
I see them now! Amazing!
