### ISSUE TITLE
Header bar transparent after maximizing a terminal

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#146]
Split the window into multiple terminals, and then click on the rectangle icon of one of them so that it occupies the entire terminix window.

The header bar becomes transparent. See screenshots.

On focus out, the three buttons on the header bar receive a gray background, but the rest stays transparent.

When hovering the scrollbar, a transparent gap appears between the scrollbar and the terminal area.

I'm on Ubuntu Xenial beta and its default Unity desktop with its default Ambiance theme.

![terminix-transparent-1](https://cloud.githubusercontent.com/assets/5750745/13791118/e391c3f4-eaeb-11e5-9740-4555b39df8ac.png)

![terminix-transparent-2](https://cloud.githubusercontent.com/assets/5750745/13791125/f07f08d8-eaeb-11e5-92e2-e44e85b0040c.png)

**Comment by gnunn1** [comment]
There is an issue with Ambiance that I work around in the non-maximized terminals by assigning a style with a background to the underlying box. I had to re-work the hierarchy when I introduced the sidebar  and I probably missed assigning the css class to the Box that holds the maximized terminal, should be an easy fix.

**Comment by egmontkob** [comment]
At some point, gnome-terminal officially dropped transparency and vte changed the way it's implemented. It was probably around the vte-0.38/gnome-terminal-3.14 days.

Fedora then created a first transparency patch which suffered from pretty much the same kind of bug. Then Ubuntu went ahead and improved their patch to fix this problem.

It could be useful to dig up these patches and figure out what Ubuntu improved. They didn't do one-offs for certain widgets, but found the ultimate proper solution where this issue could not occur anymore.

**Comment by egmontkob** [comment]
If you look at e.g. http://packages.ubuntu.com/xenial/gnome-terminal -> gnome-terminal_3.18.2-1ubuntu3.debian.tar.xz -> 0001-Restore-transparency.patch, you'll find a worthful comment at the top of the patch. If I recall correctly, hijacking the draw signal was the key to the proper solution.
