### ISSUE TITLE
Terminology and tooltip for "Maximize"

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#147]
For reporting the previous bug, I was wondering what that rectangle button was called.

I had to try the shortcuts to see which one does the same action until I found that it's called "Maximize".

A tooltip (aka balloon help) over the button would help use a consistent terminology, as well as find the proper entry under the shortcuts if I wanted to assign a shortcut.

Also you might want to choose a different word, so that it can't be confused with the window manager's maximize functionality. Maybe "expand", "spill"?? Dunno.

**Comment by gnunn1** [comment]
I think I'm going to stick with Maximize, people know what it means so why invent a new word for it?
