### ISSUE TITLE
We need a better visual indication which session is being used

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#152]
Currently, when I open a new session, the counter increases at the top left corner, that tells me how many sessions I have open.

However, I have no idea which session I am currently in. The only way for me to know is based on what's displayed in terminal window, but what if my terminal windows are all the same?

Tabs would come in handy here, but #114 already explained why we're not going to have tabs.

Any ideas?

**Comment by gnunn1** [comment]
You can name each session and the name is shown in the title, I.e Default.

Only other thing I can think of right now is changing the session count badge to a session indicator badge. So if you had three sessions but we're on session 2 it would show 2 not 3 with this change.

**Comment by vaijab** [comment]
> changing the session count badge to a session indicator badge

That could work when in non-fullscreen mode.

What about dynamically changing window title?
At the moment it says `Terminix: Default`.

Proposed window title: `Session 1: Default` or something similar. However, again, this won't work when in full screen mode, but I guess the idea of fullscreen mode is to have as much usable terminal space and isolate away all distractions.

**Comment by gnunn1** [comment]
That could work as well, let's leave this open for a week or two and see if any else has suggestions.

**Comment by edubxb** [comment]
How about showing toast a message or something like that when changing the session?

This "message" can have the session name and/or number.

**Comment by alex285** [comment]
@gnunn1
>Only other thing I can think of right now is changing the session count badge to a session indicator badge. So if you had three sessions but we're on session 2 it would show 2 not 3 with this change.

Why to do that? See a number like 2? How that is any helpful? If you mean for easy switching sessions with shortcuts, you could add the number of current session of the session titlebar.  Is that more meaningful?

@vaijab 
> However, I have no idea which session I am currently in. 

hmm? You don't know what session are you in, in current session that you see? I'm trying to understand what is the bug here. Any examples?

**Comment by alex285** [comment]
Also a small vertical bar with indicators on the left edge of terminal, plus for launching sessions thumbnails, maybe could fit.

**Comment by gnunn1** [comment]
I've updated the title to include the current session number when there is more then one session active.

**Comment by gnunn1** [comment]
I'm closing this now as I'm pretty happy with where things are at.
