### ISSUE TITLE
Color schems from terminal.sexy

### ISSUE THREAD

**Issue by klingtnet** [gnunn1/terminix#155]
I've made a little python3 script (/wo dependencies) that converts and installs all color schemes from [http://terminal.sexy] in terminix's scheme folder.
Link to the [repo](https://github.com/klingtnet/terminix-sexy).
Maybe you can mention this in the Terminx README/wiki?

**Comment by gnunn1** [comment]
Thanks for that work, looks cool. I would be OK if you update the FAQ section of the Terminix wiki to include a section about how to customize color schemes and put a link to your repo there.

https://github.com/gnunn1/terminix/wiki/FAQ

**Comment by klingtnet** [comment]
Ok, i will do that! Thanks!
