### ISSUE TITLE
Feature Request: Session sidebar ammends

### ISSUE THREAD

**Issue by tr33m4n** [gnunn1/terminix#156]
Hi there,

I've literally been using Terminix for about 10 mins and it's great so far. Thought I'd suggest some things for the session sidebar.

- It'd be good if the sidebar would not close (perhaps as an option) when you select a session, for the ease of quickly switching between them

- #137 made some good points about naming the sessions... If I have numerous sessions open on different servers, it'd be good to know which one I'm moving to/selecting!

Cheers!

**Comment by gnunn1** [comment]
There are no plans to make the sidebar anything but transient, I can understand the ask for it to be semi-permanently or permanently open however there are technical reasons why it can't happen. The biggest is if the sidebar gets left open, the expectation is that the thumbnails it shows should be updated live which isn't feasible in GTK. There are other reasons as well, but the long and short of it is no plans to make this change.

The second point is being in tracked in #137 so I'm going to close this as a duplicate and leave that one open.

I do appreciate the feedback and suggestions though so thank you.
