### ISSUE TITLE
[Feature request] Option to hide top bar

### ISSUE THREAD

**Issue by gutigen** [gnunn1/terminix#159]
Could we get an option to hide top bar?
![zrzut ekranu z 2016-03-20 02-10-13](https://cloud.githubusercontent.com/assets/1865041/13902240/7fb93f70-ee41-11e5-84be-7ec7b7d53fae.png)

Thanks!

**Comment by gnunn1** [comment]
I assume you mean the terminal title bar and not the header bar (CSD)?

**Comment by gutigen** [comment]
Exactly ;)

**Comment by gutigen** [comment]
To clarify, I mean top panel with session and sidebar buttons.

**Comment by alex285** [comment]
@gnunn1 I think he actually means the CSD! Which is not possible obviously :)

**Comment by gnunn1** [comment]
@gutigen Unfortunately it's not feasible to hide the top bar since that is what is used to drag the window around. Hiding the terminal titles is more do-able but even there you lose certain functionality like dragging and dropping terminals I'd have to think long and hard about doing it.

**Comment by gutigen** [comment]
Yea, but some of us use terminal with keyboard, so how about:

* add option to hide top bar
* add shortcuts to cover now missing feature with keyboard

Just a thought ;)

**Comment by gnunn1** [comment]
Sorry but it's not happening. You can get rid of the top bar though by switching to fullscreen mode, that's the most I'm willing to do on this front.

**Comment by Zeioth** [comment]
At least there should be a keyboard shortcut to hide/unhide all bars.
