### ISSUE TITLE
Equally sizing terminals

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#161]
Terminator has a feature where by double clicking on a separator triggers the terminals in that row/column to be equally sized.  For example
```
|---------------------|
|         |           |
|    1    |      2    |
|         |           |
|---------------------|
| 3 |   4   |   5   |6|
|---------------------|
```
- Double clicking between 1 and 2 makes 1 and 2 50% width each
- Double clicking between 3 and 4, 4 and 5 or 5 and 6 would make 3, 4, 5, and 6 each 25% width
- Double clicking the horizontal separator would make both rows 50% height

**Comment by gnunn1** [comment]
That's one of Terminators features I wasn't planning on implementing, due to the nature of GTKPaned it's a complete pain in the ass and I'm less then convinced that many people actuallt use it. Have a look at this bug report on it that @egmontkob linked to previously.

https://bugs.launchpad.net/terminator/+bug/1520969

**Comment by alexwhitman** [comment]
That's definitely an... interesting bug.  Feel free to close this if you want.  Maybe I'll give implementing it a go at some point.

**Comment by egmontkob** [comment]
It's not that terribly hard once you figure out how Gtk+ works, although it's indeed not too logical and is a bit of a PITA.

The most important bit: At least for the duration of this operation, all Paneds in the game need to have child1's "resize" property disabled and child2's "resize" enabled. This is the only way when Gtk+ doesn't kick back asynchronously later, trying to override the "position" values you set.

The next step is, from the outermost Paned towards the innermost ones, manually set the "position" property to the final desired amount of pixels (the width/height of child1) which you need to compute manually. While computing the values, you shouldn't rely on the widgets' properties (like "position", "allocation" etc.), since I don't think you can know whether Gtk+ has updated them already or not yet. Instead, you should on your own "imagine" how the layout will look like without getting any help from Gtk+, and ask explicitly for those "position" numbers.

**Comment by gnunn1** [comment]
@alexwhitman I have checked in an early implementation of this, it works in some cases but I still need to do some work. I ended up implementing a tree model to represent the Paned layout and then used the model to calculate the size/position for each Paned. After that it's a matter of iterating over the model and setting the positions. 

Don't get too excited though, my model approach still has a number of issues to work out but it's a start. Note that I've disabled this functionality in git by commenting out the event handler in createPaned. I'll do some more work on this tomorrow and hopefully clean things up to the point where it is workable.

Thanks @egmontkob for the pointers, really appreciate it and it was very helpful.

**Comment by gnunn1** [comment]
@alexwhitman All done, I've tested it a few different ways and it seems to work fine. Having said that, I would not be surprised if there are a few edge cases I missed so I would really appreciate it if you could find some time to test it.

Thanks again @egmontkob, I would have been really scratching my head without that tip about the child resize properties.

**Comment by alexwhitman** [comment]
@gnunn1 Thanks for implementing, it works really well but I have spotted a very small alignment issue.

If you add terminals so that it looks like this
![terminx-before](https://cloud.githubusercontent.com/assets/422013/14225418/3ade2964-f8ba-11e5-8519-b6a6b52a8412.png)
and then equalise each column it'll look like this
![terminix-after](https://cloud.githubusercontent.com/assets/422013/14225421/4f519138-f8ba-11e5-838b-e3bd8fea17ad.png)
Notice how the separators of the bottom two terminals don't align.

If you start with either both the top or bottom halves being split rather than one top and one bottom then it works fine.

As I said, small issue but otherwise works well. :+1:

**Comment by egmontkob** [comment]
It could be that the width of the separator is not properly taken into account when computing the desired sized. And even if it was properly taken into account, a give-or-take 1 pixel could easily occur unless some very special care is taken (it's really tricky to get it right).

**Comment by gnunn1** [comment]
@egmontkob Yeah I'm not currently looking at the width of the separators, I'll try including that and see if it helps. Thanks @alexwhitman for testing it, really appreciate it.

**Comment by gnunn1** [comment]
@alexwhitman I incorporated the handle size but the bottom right terminal is still off by a pixel compared to the left one. I'm not sure there is much else I can do, when you run it with tracing on I output the maths I am using and as far as I can tell it's using the same values for both the left and the right so it should size the same but it doesn't. Maybe just chalk this one up as one of the mysteries of GTK.

I did find one other annoying bug though thanks to playing with this so thanks for that :)

**Comment by alexwhitman** [comment]
Just tried this, the alignment is about the same as the screenshot above.  Debug output is
```
2016-04-03T09:54:15.039:session.d:redistributePanes:239 Handle size is 6
2016-04-03T09:54:15.039:session.d:redistributePanes:243 Redistributing 3 terminals with pos 294 out of total size 894
2016-04-03T09:54:15.039:session.d:updateResizeProperty:1417 Updating resize property
2016-04-03T09:54:15.039:session.d:updateResizeProperty:1417 Updating resize property
2016-04-03T09:54:15.039:session.d:resize:1396 Resizing
2016-04-03T09:54:15.039:session.d:resize:1399 Branch 0 has 1 nodes
2016-04-03T09:54:15.039:session.d:resize:1401     1st pass, Node set to pos 588 from pos 447
2016-04-03T09:54:15.039:session.d:resize:1399 Branch 1 has 1 nodes
2016-04-03T09:54:15.039:session.d:resize:1401     1st pass, Node set to pos 294 from pos 223
2016-04-03T09:54:15.042:session.d:__dgliteral5:1406     2nd pass, Node set to pos 294 from pos 294
2016-04-03T09:54:15.042:session.d:__dgliteral5:1406     2nd pass, Node set to pos 294 from pos 294
2016-04-03T09:54:16.022:session.d:redistributePanes:239 Handle size is 6
2016-04-03T09:54:16.022:session.d:redistributePanes:243 Redistributing 3 terminals with pos 294 out of total size 894
2016-04-03T09:54:16.022:session.d:updateResizeProperty:1417 Updating resize property
2016-04-03T09:54:16.022:session.d:updateResizeProperty:1417 Updating resize property
2016-04-03T09:54:16.022:session.d:resize:1396 Resizing
2016-04-03T09:54:16.022:session.d:resize:1399 Branch 0 has 1 nodes
2016-04-03T09:54:16.022:session.d:resize:1401     1st pass, Node set to pos 294 from pos 447
2016-04-03T09:54:16.022:session.d:resize:1399 Branch 1 has 1 nodes
2016-04-03T09:54:16.022:session.d:resize:1401     1st pass, Node set to pos 294 from pos 220
2016-04-03T09:54:16.025:session.d:__dgliteral5:1406     2nd pass, Node set to pos 294 from pos 294
2016-04-03T09:54:16.025:session.d:__dgliteral5:1406     2nd pass, Node set to pos 294 from pos 294
```
In what order are the terminals resized?  I'm going to guess in the order of the 'stack' without looking at the code.  Maybe ordering by position, top to bottom (or left to right for horizontal) would even it out.

**Comment by gnunn1** [comment]
@alexwhitman It's ordered from the outer most GTKPaned to the inner most one. If multiple panes are located at the same branch level in the tree the order would be determined by the order the tree was built. I'll keep this in mind and see if I can think of something to even it out but I suspect these sort of out by 1 or 2 pixel type issues would be hard to eradicate completely given the nature of GTKPaned.
