### ISSUE TITLE
"Open in Terminal" in Nemo does not open with the current directory

### ISSUE THREAD

**Issue by cuatro** [gnunn1/terminix#162]
The function "Open in Terminal" of the file manager Nemo (and probably others) does open Terminix correctly, but not with the current directory. Instead an new Terminix instance is opened with the default directory (user directory).

Terminix is set as the default terminal with:
`gsettings set org.cinnamon.desktop.default-applications.terminal exec terminix`
Using the -w parameter does not help here ("Open in Terminal" does nothing at all then).

Expected behavior: Terminix opens with the working directory set to the currently open/selected directory in Nemo.

Other terminal emulators like lxterminal or gnome-terminal work like expected.

**Comment by gnunn1** [comment]
Unfortunately, I don't use Nemo at all, I assume this is with the default Nemo "Open in Terminal" extension and not the Nautilus extension that Terminix ships? If you run Terminix manually with -w does it open as expected in the specified directory?

**Comment by cuatro** [comment]
Yes, the function "Open in Terminal" is inbuilt and directly ships with Nemo. It provides a menu item in the right-click context menu and (my favorite) an optional icon for the toolbox.

Both the `-w` and the `--working-directory` parameters work as expected when manually running Terminix. The strange fact is that a working directory in gnome-terminal is also set with the parameter `--working-directory`. So it seems that the working directory is passed in a different way?

**Comment by gnunn1** [comment]
Thanks, I'll have a look and see what it is going on. In general if it works with gnome-terminal it should work with Terminix as I tried to mimic the command line arguments for compatibility.

**Comment by phw** [comment]
I think I found the answer. Nemo actually does not set the directory via any command line argument, it just sets the working directory before spawning the command with `g_spawn_async`

See https://github.com/linuxmint/nemo/blob/5192708b0d4c46cf106a2ca623711d96b59553e6/src/nemo-view.c#L7077

I tested it: If I am inside `$HOME/test` and launch `gnome-terminal`, the instance of `gnome-terminal` will have `$HOME/test` set as the current directory. If I do the same with Terminix I end up in `$HOME`

**Comment by gnunn1** [comment]
Thanks @phw, yeah I'm naively using the user's home directory as the default. I'll switch this to using the cwd instead, should be an easy fix.

**Comment by cuatro** [comment]
First of all I want to thank you, gnunn1 and all contributors, for all your hard work and efforts in the development of Terminix and your quick responses and solutions in regard to reported issues!

Unfortunately, the issue not completely solved yet. If an instance of Terminix is already open, then every new instance that is opened via the "Open in Terminal" function is set to the CWD of the old instance. But if there is no running instance of Terminix, then it works perfectly as expected.

**Comment by gnunn1** [comment]
I can reproduce outside of Nero, thanks for reporting it and I'll take care of it.
