### ISSUE TITLE
Provide uninstallation instructions

### ISSUE THREAD

**Issue by PombaM** [gnunn1/terminix#163]

**Comment by gnunn1** [comment]
I've added an uninstall script for people who are installing terminix manually. I've tested it and it seems to work fine, however could somebody do a quick review of it as a secondary check, I'm always nervous about scripts that delete things from /usr.

**Comment by PombaM** [comment]
@gnunn1 I've used your uninstaller script, worked like a charm!
It worked for me so i am closing the issue. Thanks man.
