### ISSUE TITLE
Dynamically link

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#170]
"dub build --build=release" produces an executable that's 14 MB large; 9 MB after stripping. It is dynamically linked against basic libc libraries but nothing else (according to "ldd"), that is, I guess it contains Gtk+ statically linked.

I'm not familiar with D and the build infrastructure around it at all, but would it be possible to dynamically link against all the libraries, and come up with a reasonable executable size?

**Comment by gnunn1** [comment]
I've only been using D for about 5 months now and this is my first time back with native code since the 90s as my day job is in the Java/J2EE world so take this with a grain of salt. AFAIK GtkD already links to GTK dynamically as per the code here:

https://github.com/gtkd-developers/GtkD/blob/master/src/gtkc/Loader.d
https://github.com/gtkd-developers/GtkD/blob/master/src/gtkc/paths.d

However the GtkD API dependency is quite huge as you can see from the size of the static libraries that get generated in your local .dub/packages/gtk-d-3.2.3. One option would be to create a shared library for gtkd but that doesn't really do much as I'd still be shipping the shared library with every release and would complicate package management.

I've tried limiting my dependencies on just the sub-packages in GtkD that I'm using but it doesn't have any impact on the size as far as I can tell.

I'll look into it some more when I get a chance.

**Comment by gnunn1** [comment]
So I had a look at this and managed to get dynamic linking working, however I wouldn't recommend shipping terminix this way personally given that gtkd is not widely shipped and supported on distros as a shared library. Using dynamic linking, the executable size goes down from 14 MB (9 MB with strip) to about 4 MB (2.8 MB with strip). 

While the executable is smaller, the libgtkd-3.so is 20 MB in size so overall system space is worse off. Given that pretty much no one will have a bunch of dynamically linked D/GtkD apps on their system I just don't see this as being worth the pain and effort for packagers.

I've checked in a new version of dub.json that optionally supports dynamic linking. For people interested in playing with it, here are the steps I used to get it going:

1. For convenience I installed the gtkd-git package on Arch to install the gtkd shared libraries. If no package is available, this should be doable manually quite easily using the make file GtkD provides. If someone needs help with the make file let me know and I'll look into it.

2. You need to get the latest version of dub from git as there have been some recent merged PRs to fix dynamic linking to GtkD (see https://github.com/D-Programming-Language/dub/issues/782). This can be done by cloning dub locally and running build.sh

3. Using that version of dub specifically, build terminix using the following command:

```
dub build --build=release --config=dynamic
```

4. And that should be it, run ldd against the executable to confirm that it is dynamically linked:

```
	linux-vdso.so.1 (0x00007ffd0d4f0000)
	libgtkd-3.so.0 => /usr/lib/libgtkd-3.so.0 (0x00007fdd41ad2000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fdd418ce000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fdd416b1000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fdd413ac000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fdd411a4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fdd40f8e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fdd40bed000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdd42c01000)
	libphobos2.so.0.70 => /usr/lib/libphobos2.so.0.70 (0x00007fdd403d4000)
```

**Comment by dsboger** [comment]
I'm exploring the possibility of making AUR package `terminix-git` build with `--config=dynamic`. I tried following the instructions above, but it seems `gtkd-git` only builds static libs by default. Did you customize the PKGBUILD to build .so files too?

**Comment by dsboger** [comment]
I've managed to make a custom PKGBUILD for `gtkd-git` and installed shared libraries for gtkd. I also built terminix using `--config=dynamic` and it works fine (using `dub-git`). The only (small) problem is that dub still fetches gtkd, even though it is installed system-wide. Is there a way to stop that?

**Comment by gnunn1** [comment]
Me bad, I was having trouble getting the make file going and installed gtkd-git then checked /usr/lib for them, saw them there and figured it came from the package. I guess the make did work after all despite some complaints. What's weird is I see the shared libraries in ```/usr/lib``` but I'm not sure what put them there.

If I run ```sudo make shared install``` it seems to run fine but installs everything in /usr/local/lib. Very weird, I'll look into it some more.

**Comment by gnunn1** [comment]
@dsboger I didn't spend a ton of time on this since as per my explanation earlier I didn't see it being very useful. I was mostly interested in it from the point of view of improving compile times to speed the development cycle but there was no change, about 9 seconds on my laptop for either static or dynamic.

I tried removing the dependencies block but it wouldn't compile despite having the libs dependency. At this point I'd need to dig into dub to figure it out.

**Comment by gnunn1** [comment]
Actually, thinking about this more I wonder if it's possible. In C I'm thinking you would need the .h file to compile against a shared library and D doesn't have a similar artifact hence the source code requirement. Let me look into it some more tomorrow morning.

**Comment by dsboger** [comment]
@gnunn1 I think you are right about the need to have access to the sources. Gtkd makefile installs the full source into `/usr/include/d/gtkd-3/`, but I don't know if dub supports looking there. 

You don't need to spend time with this, as I'm doing unsupported experimental stuff. Let me look for it myself and I'll bother you again if I get stuck.

**Comment by gnunn1** [comment]
You could register the source GtkD registers as a local package in dub and
then reference it in Terminix dub.json.

**Comment by dsboger** [comment]
I think I've found an issue with dub.json regarding the `"dynamic"` configuration. The way it is now, it links dynamically against `"gtkd-3"` but it still links statically against `"vted-3"`. To solve that, just add `"vted-3"` to `"libs"` in the configuration.

Also it seems dub does not figures the import path correctly. I suppose it should use `pkg-config --cflags $libs` and pass the result for `dmd`, but somehow it does not work (I'm not sure it is supported, though). I had to manually add the following line to the configuration to make the sources available during compilation: `"importPaths": ["/usr/include/d/gtkd-3/"]`. 

In the end, I've managed to successfully compile terminix with everything dynamically linked using the following configuration, while also removing `"dependencies"` entry:

```
{
  "name": "dynamic",
  "targetType": "executable",    
  "libs": ["gtkd-3", "vted-3"],
  "importPaths": ["/usr/include/d/gtkd-3/"]
}
```

(It seems the `"lflags"` entry is not needed?)

Another problem is how to tell dub that the `"dynamic"` configuration does not have dub-fetched dependencies. I've tried moving the `"dependencies"` entry inside the `"default"` config, but dub still fetches gtk-d for `"dynamic"`. I've also tried using `"subConfigurations"` entry, as I understood it is supposed to limit dependencies to certain configs, but no success either. Only hack I've found is setting "gtk-d" as an optional dependency and building with `--nodeps` (I'm not sure how will that affect a `"default"` build, though). 

Next step is to ask dub devs for help.

**Comment by gnunn1** [comment]
@dsboger Thanks for all your work on this, it's been quite interesting to see what you find. I suspect as you noted that subConfigurations is the way to go here for dependencies, have a look at this thread here http://forum.dlang.org/thread/kgajnfnsmxidzefmehms@forum.dlang.org. If subConfigurations is not working I'd open a bug with bug, feel free to link to it here if you do.

BTW, out of curiosity with both gtkd and vted linked dynamically, what is the size of the executable?

Also, I'm quite happy to accept any PR you want to submit that improves dynamic linking.
