### ISSUE TITLE
Visual Cleanup

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#179]
A couple of visual cleanup items so I don't lose track of them:

* Add an etched border between search and titlebar, otherwise looks to much like a big slab
* Showing the title on teh sidebar needs to be centered on the image when notification badge isn't present, need a transparent placeholder for spacing purposes when no notifications are present.

**Comment by dsboger** [comment]
Another small issue is that the search entry and the search options menu button do not have the same height (the entry is 1 px shorter). Maybe setting vexpand=true and valign=fill on the search entry will solve it?

**Comment by gnunn1** [comment]
@dsboger Thanks, I'll look at that as well.

**Comment by gnunn1** [comment]
All fixed, @dsboger can you double-check the search entry border issue on your machine. The only way I could fix it was but adjusting the padding of the search entry in CSS.

**Comment by dsboger** [comment]
It's perfect now!
