### ISSUE TITLE
Make search more intuitive to use

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#180]
I currently struggle a bit using the search effectively. I can open the search with Ctrl+Shift+F and enter a search term, but then I am stuck and must reach to the mouse. Also when toggling through the results after reaching the last matching result in any direction hitting the "next result" button again just causes the selection to disappear.

I suggest the following changes changes:

1. When inside the search input field make the Enter key search forward. Maybe also use Shift+Enter to search backwards

2. When reaching the last search result in one direction and hitting "next result" again, cycle to the first result. This could be an option, but I would enable it by default

3. If 2. is optional and the cycling is disabled, when reaching the last result and and hitting "next result" again just keep the last result highlighted

**Comment by gnunn1** [comment]
Some comments as follows:

1. There are shortcuts already available for Find Next/Find Previous, I'm not sure I want to add a new local shortcut tied specifically to when the search box is focused when a global one is already available. Do any other Gnome apps behave this way?

2. I think this is already an option,  hit the down arrow after the search box and check "Wrap around" from the options. If I'm misunderstanding let me know. Although I'm noticing you need at least two matches for this to work as expected, with one match it gives odd behavior. With one match the highlighting disappears and never wraps, I'd expect Match > Disappear > Match when wraparound is enabled. I see the same behavior in Gnome Terminal, I'll review and see if it can be improved.

3. I agree on this one, I also dislike how the search result loses focus after the last result is hit. I'll review how I'm interacting with the VTE search capabilities and see what I can do. From what I can tell though, Gnome Terminal has the same behavior.

**Comment by phw** [comment]
> There are shortcuts already available for Find Next/Find Previous, I'm not sure I want to add a new local shortcut tied specifically to when the search box is focused when a global one is already available. Do any other Gnome apps behave this way?

For me the Enter key is just the natural choice for any input. So after I entered a search term I expect that key to acknowledge my input and do something. Gnome Terminal behaves that way and basically every other app that allows one to do a full text search in a document.

> I think this is already an option, hit the down arrow after the search box and check "Wrap around" from the options. If I'm misunderstanding let me know.

Indeed, that's working as expected. I just did not find that option due to a bad German translation :D My fault, will fix it.

**Comment by gnunn1** [comment]
Makes sense about the Enter key being the natural input, I'll take care of that.

**Comment by gnunn1** [comment]
@phw The Enter/Shift Enter key is wired up and I also changed the search so when wraparound is not on the last search item stays selected, much better experience IMHO. Please test it out and let me know if it works OK for you.

**Comment by phw** [comment]
The new behavior is cool, like it very much
