### ISSUE TITLE
DnD file paths from network will crash terminix

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#184]
https://www.youtube.com/watch?v=xn-wWGj2EGs

**Comment by gnunn1** [comment]
Thanks for finding this, I need to do the same thing that the Open In Terminix plugin is doing which is convert it to a local path.

**Comment by arshavindn** [comment]
also, in terminix type `terminix -x blabla`, a new terminix window appears and has nothing, then close it, another terminix closes too

**Comment by gnunn1** [comment]
@arshavindn I've fixed this as well, in the future please open new bug reports for unrelated issues rather then chaining it to an existing one. Makes it easier to associate commits with issues. Thanks for reporting it, much appreciated.
