### ISSUE TITLE
[feature request] add visual effect when close sidebar

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#185]

**Comment by gnunn1** [comment]
Sorry, you are going to have to be more explicit, what sort of visual effect are you thinking of?

**Comment by alexwhitman** [comment]
I'm guessing @arshavindn means a slide left, the inverse of the slide right transition `setTransitionType(RevealerTransitionType.SLIDE_RIGHT);`.  Looking at the GTK Revealer class there doesn't appear to be a visible->invisible transition, only an invisible->visible transition.

**Comment by gnunn1** [comment]
It's probably because I'm explicitly hiding the sidebar to fix an issue where GTK thinks it's still open and keeps sending button presses to it as reported in #142.
