### ISSUE TITLE
Add the names of the current sessions in the sidebar

### ISSUE THREAD

**Issue by ivoarch** [gnunn1/terminix#186]
Hi @gnunn1, first of all great work!

It would be really nice if you can add the names of the current sessions in the sidebar, not only session numbering .

Something like that (three open sessions)
+--------------+
| Default (1) |
+--------------+
+--------------+
|   Zsh (2)     |
+--------------+
+--------------+
|  Emacs (3) |
+--------------+ 
.. etc

What about this?

**Comment by gnunn1** [comment]
Already done, I added it earlier this week and it will be in the next release.

![screenshot from 2016-03-26 20-39-51](https://cloud.githubusercontent.com/assets/9358238/14063180/00db004c-f393-11e5-90f7-1b865e2f6911.png)
