### ISSUE TITLE
Optimize Shortcuts

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#187]
I just added support for the new GtkShortcutsWindow feature added in 3.20, well most people won't benefit from it for awhile, Arch users should be getting 3.20 in the next few weeks and I wanted to get ahead of the curve.

One thing that is apparent is that the default Terminix shortcuts could really use some attention. If someone has a few cycles to spare and optimize the shortcuts plus assign shortcuts where it makes sense that would be great. The assigned shortcuts should follow Gnome HIG conventions as much as possible where they don't conflict with terminal operations.

If you are interested, the default shortcuts are in /data/gsettings/com.gexperts.Terminix.gschema.xml.

**Comment by gnunn1** [comment]
See here for more info on Gnome HIG guidelines for shortcuts:

https://developer.gnome.org/hig/stable/keyboard-input.html.en

**Comment by edubxb** [comment]
Use the same shortcuts that GNOME Terminal have a lot of sense IMHO, p.e. `Ctrl + PageUp/PageDown` to switch between session (GNOME Terminal switchs tabs).

**Comment by doubleloop** [comment]
Is it possible to support shortcuts with prefix (it would be easy transition from tmux if for example split window could be a sequence ctrl+b + " or ctrl+b + %) Right now I can not see the anything wich would enable such 2step shortcut in terminix.

**Comment by gnunn1** [comment]
@doubleloop Do you mean by sequence two separate key presses (i.e. press ctrl+a, release, press ctrl +b), if so you are right that would not be supported.

**Comment by doubleloop** [comment]
@gnunn1  yes, I did mean that. Are there any chances that it will be supported in the future?

**Comment by gnunn1** [comment]
@doubleloop Never really considered it, right now I'm using GTKs accelerator handling and I'm not sure it handles this sort of thing. I wonder if it could be done using an accessibility API perhaps, I'll check into it but the odds of me implementing this are pretty low unless GTK has built-in support for it.

**Comment by gnunn1** [comment]
I'm going to change the default sidebar shortcut from ctrl+s to something else since that it is the default binding for save. F9 would be the natural choice since gedit and nautilus both use that but it conflicts with apps like mc that use f1-f10, any objections to f12?

**Comment by edubxb** [comment]
How about Ctrl+Shift+S?

**Comment by gnunn1** [comment]
@edubxb Unfortunately Ctrl+Shift+S is supposed to be used for Save As according to the HIG so I assigned to that

**Comment by edubxb** [comment]
You're right.

Another option to not interfere with the shortcuts of the apps running in the terminal is to use combinatios like `Super` +` Shift/Control/Alt` + `Key`.

**Comment by gnunn1** [comment]
I'm closing this for now, I went through and updated the defaults in the commit referenced earlier and I'm happy with them. As noted here, the new default sidebar shortcut is F12.

**Comment by doubleloop** [comment]
@gnunn1
>right now I'm using GTKs accelerator handling and I'm not sure it handles this sort of thing. I wonder if it could be done using an accessibility API perhaps, I'll check into it but the odds of me implementing this are pretty low unless GTK has built-in support for it

Just noticed that gnome builder has a very nice support for this kind of shortcuts (when vim emulation is enabled). IMO it would be a great advantage, you can group logically tilix shortcuts by one prefix without using up the whole shortcut space (conflicts with system shortcuts, terminal apps shortcuts etc). 

Below are proposed defaults of the most recently used (in my case) shortcuts: 

| prefixed key | action                  |
| ---------------- | ----------------------- |
| c         | create new session |
| n/p      | next/previous session |
| v         | vertical split |
| s         | horizontal split |
| w        | switch to the next terminal |
| h/j/k/l  | switch the terminal left/down/up/right |
| z         | maximize terminal (toggle) |

This kind of shourtcuts could coexists with others (for example ctr+shift+f for find etc)
