### ISSUE TITLE
Compilation problem with `terminix-git` in AUR

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#188]
I'm having this failure message when I try to compile terminix using the `terminix-git` PKGBUILD from AUR [1]:

```
source/gx/terminix/shortcuts.d(19,8): Error: module ShortcutsShortcut is in file 'gtk/ShortcutsShortcut.d' which cannot be read
```

Is that a new dependency or some missing file in the tree?

Also, I get the following warnings a few times:

```
Selected package gtk-d 3.3.0 does not match the dependency specification >=3.2.0 <3.3.0 in package gtk-d. Need to "dub upgrade"?
```

[1] https://aur.archlinux.org/packages/terminix-git/

**Comment by gnunn1** [comment]
The upgrade of GtkD to 3.30 added support for the new GTKShortcutsWindow so I added early support for it. I updated dub.json and dub.selections.json to 3.30 so it should compile fine and the warnings you are getting indicate that it is using that.

I think the warnings can be ignored, they never caused me any issue. See https://github.com/gtkd-developers/GtkD/issues/150

**Comment by gnunn1** [comment]
Also, try running ```dub upgrade```

**Comment by dsboger** [comment]
Ok, the problem was I didn't properly clean my build folder and had some cached gtk-d tree. Built everything from scratch and it all worked fine.
