### ISSUE TITLE
Wrong category in desktop-file

### ISSUE THREAD

**Issue by HeikoAdams** [gnunn1/terminix#195]
The category "Utilities" needs to be changed to "Utility" otherwise desktop-file-validate fails.

**Comment by gnunn1** [comment]
When I run it on my Arch Linux I get the following:

```
/usr/share/applications/com.gexperts.Terminix.desktop: error: value "Utilities" for string list key "Categories" in group "Desktop Entry" does not have a semicolon (';') as trailing character
```

Which implies the category is fine but it's just missing the semi-colon. I lot's of apps on my system using Utilities, I wonder if this is a distro/desktop difference? What distro and desktop environment are you using?

**Comment by gnunn1** [comment]
Oh, I see the problem now after comparing it to Fileroller, It needs to be set to ```Utility;X-GNOME-Utilities;```

I'll take care of that, thanks for reporting this.
