### ISSUE TITLE
Add option to hide terminal titlebars

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#196]
Add an option to hide the terminal titlebars and drive functionality off of shortcuts and the context menu instead. Activating this option means you lose the ability to drag and drop terminals but gain some extra space. Other thoughts:

a. Should the title of the currently focused terminal appear in headerbar?

b. When a terminal is maximized does the state need to be indicated anywhere?

**Comment by gnunn1** [comment]
I'm going to handle this by changing the small title option to an enumerated option with possible values of Normal, Small, None. The context menu will build on @alexwhitman work and add some, but not all, of the items from the title drop down menu plus maximize.

**Comment by gnunn1** [comment]
Added initial support for this, when the title style option is set to None, the right click context popover will have the additional options that would normally be in the title menu. I've opted not to show the focused terminal title anywhere at this time. The maximized state is shown in the context menu as the menu item toggles between maximized/restore.

Note that the old small title option has been superseded with a new title style option with a three way toggle (Normal, Small and None).

Suggestions for improvements are welcome as always.

**Comment by alex285** [comment]
@gnunn1 Great work! There is a missing way for de-attaching the shell though. Could be a DnD area somewhere? As a workaround we can open Search and DnD it.

**Comment by gnunn1** [comment]
@alex285 Unfortunately that's the price you pay for no title and why I was semi-reluctant about doing it. The act of selecting text is the same as dragging so I don't see a way to have users drag the terminal directly. No plans to add an extra space somewhere as a DND area, that's what the title is meant to be :)

**Comment by alex285** [comment]
@gnunn1 It's fine! But what if you redesign the menu a bit, like putting {Copy, Paste, Select All} in the same line with icons, save some space, add a "Show Titlebars" item, and have "Hide" only on titlebars menu? Perhaps it will work better than having this option on preferences

**Comment by gnunn1** [comment]
@alex285 The issue for me is that the context menu should really only provide actions related to the current terminal. While I could create a local override for individual terminals to show/hide titles it adds to the complexity and I'd prefer to keep it simple for now.

I'm not adverse to making the copy, paste and select all a row of horizontal buttons but would need to see how it looks as I think a context menu festooned with too many buttons wouldn't look that great.

**Comment by alex285** [comment]
@gnunn1 
>The context menu should really only provide actions related to the current terminal.
Good point, but also the title bar it is applied (and) to current terminal. What if a submenu in the very end for such options?

> but would need to see how it looks
Yeap that comes with the use. FWIW Firefox menu does that, also Alt+E menu in Chrome does that, and of course Terminix already does that with Split Views. Which btw I think they have to move somewhere in the top perhaps. When you hide titlebars and menu gets expanded, split views goes in the very bottom, although not the less popular option, I guess!
