### ISSUE TITLE
user password is not recognized

### ISSUE THREAD

**Issue by zeronote** [gnunn1/terminix#202]
Just compiled and installed terminix on a clean Debian testing machine.
I have a very strange issue: my user password is not recognized, and it appens ONLY in terminix,
other terminals like gnome-terminal, xterm, terminator (as well as other system apps) doesn't have this issue.

Could be something related to user groups settings?

**Comment by gnunn1** [comment]
I have no idea what the issue could be, under the hood terminix is using the exact same VTE component as gnome-terminal so in general the behavior should be the same. When you say the password is not recognized do you mean you can't type the password in or you type it in but the application requesting it doesn't accept it?

**Comment by zeronote** [comment]
the last case: I can type the password in the terminal window but it tells me that the password is wrong.

ASAP I'll reproduce the terminix installation on another debian testing machine and come back with some comparison infos.

**Comment by zeronote** [comment]
In case anyone wants to try to compile and install terminix on a debian machine:
(obviously clone the repo or obtain the .zip before the next steps)

```
# install required packages
sudo apt-get install dub gettext libxml2-utils

# obtain and install dmd
wget http://downloads.dlang.org/releases/2.x/2.070.1/dmd_2.070.1-0_amd64.deb .
sudo dpkg -i dmd_2.070.1-0_amd64.deb

# compile and install
dub build --build=release
sudo ./install.sh
```

**Comment by alex285** [comment]
@zeronote Tried copy paste password instead of typing it?

**Comment by zeronote** [comment]
@alex285  paste the password instead of typing it **worked**, so....wth??
Never seen an issue like this before.

**Comment by gnunn1** [comment]
Try typing this to enter a password at the command prompt:

''
'read -s -p "Enter Password: " mypassword
'''

And then this to view the password, does it match what you typed?

'''
echo $mypassword
'''

**Comment by zeronote** [comment]
There is a mismatch between what I type and what the var contains, the funny fact is that
only the first char is missed and, to be more detailed (and to add more fun):

my password starts with the char **4**, which is the one missed, but I have tried with other chars like 
[0,9] and [a,z], and none of them is missed.

```
libvte-2.91-0:amd64                   0.44.0-1
libvte-2.91-common                    0.44.0-1
libvte-common                         1:0.28.2-5
libvte9                               1:0.28.2-5+b1 
```

it would be really helpful if someone could try the same on another debian machine.

**Comment by zeronote** [comment]
Indeed is my fault, I should stay away from my pc when I am really tired.

I was re-configuring some terminix shortcuts to change session, and by mistake I've assigned **4** instead of **ctrl + 4** for switching to session-4 (all other sessions are switched by a ctrl+n shortcut).

Thanks for your time and sorry for the fake-bug.
Keep up the good work :+1:

**Comment by gnunn1** [comment]
No worries, glad you figured it out.
