### ISSUE TITLE
Change split shortcuts

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#208]
IMHO, the split shortcuts are counterintuitive, currently, Crtl+Alt+V split the current terminal adding a new one at bottom, and Crtl+Alt+H, split the current terminal adding a new one at right, I think that these shortcuts need to be interchanged.

For me, split vertically means adding a new terminal vertically positioned (at right), and split Horizontally means adding a new terminal horizontally positioned (at bottom).

The shortcut name need to be renamed too.

Terminator works in this manner.

¿What do you think?

**Comment by gnunn1** [comment]
I tend to think the opposite personally so I'm fine with the current arrangement, I'm happy to hear opinions about it.

**Comment by phw** [comment]
I agree with @edubxb. I always interpreted a horizontal split with the direction of the separator. Like if you told me to cut a piece of paper horizontally I would make a horizontal cut, which would result in an upper and lower part.

**Comment by egmontkob** [comment]
http://english.stackexchange.com/questions/293520/split-horizontally-or-vertically-which-one-is-which

**Comment by phw** [comment]
Funny, that's probably something everybody thought is crystal clear (no matter how you thought it should be) :) Possible that we won't agree on one way or the other, language is a messy thing.

But at least I noticed that I had the German translation of the split button labels inconsistent with the shortcut key description.

**Comment by gnunn1** [comment]
Thanks @egmontkob, interesting how inconsistent it is across different applications. I don't feel so bad about my choice now!

**Comment by egmontkob** [comment]
Ctrl+Shift+V for Vertical split (no matter which one it means) is also misleading since this shortcut is typically used for Paste. How about instead of using the word "Split", use the term "New to the Right" (Ctrl+Shift+R) and Down or Bottom (D or B). Maybe correspondingly add the options to open a new one to the Left and Up/Top.

**Comment by gnunn1** [comment]
@egmontkob I like your idea of using cardinal directions (Right, Down) instead of the current horizontal/vertical, it completely removes the ambiguity which is great. In terms of a verb, I'm not a fan of "New to the ..." as "New to the Down" or "New to the Below" sounds a bit odd to me. It could be shortened to just the verb New though I have mixed feelings between New and Split:

Split Right/Split Down
New Right/New Down

I still like Split but that might just be inertia based on having used it from the start.

**Comment by edubxb** [comment]
I agree with @egmontkob, Ctrl+Shift+V is used for Paste (Gnome Terminal uses it), so better if is changed.

How about using scheme or something like this:

Ctrl+Shift+Left → Split at Left
Ctrl+Shift+Up → Split at Top
Ctrl+Shift+Down → Split at Bottom
Ctrl+Shift+Right → Split at Right

**Comment by gnunn1** [comment]
@edubxb It's actually using Ctrl-Alt-v and Ctrl-Alt-h for the split vertical/horizontal, not Ctrl-Shift-v/Ctrl-Shift-h though I agree the closeness in shortcuts is confusing.

I'm OK with using Ctrl+Shift+Direction for the splits.

**Comment by edubxb** [comment]
@gnunn1, you're right :tongue:

**Comment by egmontkob** [comment]
Oh, I totally missed that the modifiers are different. Also, I'm not a native English speaker. I'm just throwing in random ideas and you decide on the best shortcuts/wording/etc.

**Comment by egmontkob** [comment]
Ctrl+Shift+Up/Down is VTE's built-in hardcoded shortcut to scroll the scrollback buffer by a single line. (One might easily live without this feature though.)

**Comment by edubxb** [comment]
You're right @egmontkob, I don't usually use this shortcut, normally I use Shift+PgUp/PgDown...

What about this:

Alt+Shift+Left → Split at Left
Alt+Shift+Up → Split at Top
Alt+Shift+Down → Split at Bottom
Alt+Shift+Right → Split at Right

**Comment by gnunn1** [comment]
@edubxb It's already being used for resizing the terminal, you can see the list of default shortcuts already assigned in this file starting at line 460:

https://github.com/gnunn1/terminix/blob/master/data/gsettings/com.gexperts.Terminix.gschema.xml

**Comment by gnunn1** [comment]
And note I'm only supporting splitting to the right and bottom, no plans to add split to top or left.

**Comment by edubxb** [comment]
Thanks for the point @gnunn1!
