### ISSUE TITLE
Failed to execute child process ""

### ISSUE THREAD

**Issue by alcir** [gnunn1/terminix#209]
I'm using Ubuntu Gnome 15.10

(terminix:5787): Gtk-WARNING **: /build/gtk+3.0-pIzeMy/gtk+3.0-3.16.7/./gtk/gtkwidget.c:8554: widget not within a GtkWindow
2016-04-05T15:10:38.804:terminal.d:spawnTerminalProcess:1227 Unexpected error occurred: Failed to execute child process "" (No such file or directory)

**Comment by gnunn1** [comment]
I'm going to need some more information:

I assume gnome terminal is working fine for you? 

What shell are you using? (bash, zsh, fish)

What directory did you execute terminix within, your home directory?

**Comment by gnunn1** [comment]
Fixing #214 may have corrected this as well

**Comment by gnunn1** [comment]
No response from OP, closing.

**Comment by curaloucura** [comment]
I'm having the same problem on my Ubuntu 15.10 and release Beta 0.57.0 (also tried with 0.50.0 just to be sure and it was raising the same error). Trying to build from source didn't work out as following the steps on README, but either way the main issue stays: 

```
asilva@KNM-210036-L:~/projects/private/terminix$ terminix 
2016-04-15T11:20:34.744:terminal.d:spawnTerminalProcess:1284 Unexpected error occurred: Failed to execute child process "" (No such file or directory)
```

**Comment by curaloucura** [comment]
One interesting info is that when running the uninstaller I get the following error:

```
asilva:~/projects/private/terminix$ sudo ./uninstall.sh 
Uninstalling from prefix /usr
rm: cannot remove ‘/usr/share/appdata/com.gexperts.Terminix.appdata.xml’: No such file or directory
```

**Comment by gnunn1** [comment]
@curaloucura The last message about appdata.xml is no big deal, the next release adds a new file.

Do you have time to help me debug this? What I can do is compile a version with some extra tracing enabled to track down where the problem is occurring. I can do that later today.

**Comment by curaloucura** [comment]
sure thing, I have Ubuntu only on my work machine, so latest on Monday I will check the debug version

**Comment by gnunn1** [comment]
@curaloucura Try the newest release first on Monday, I added some additional error messages so hopefully that will be enough to shed light on the issue. If not, I'll compile a debug version for you to try out.

**Comment by curaloucura** [comment]
After downloading the latest and running, this is what I've got:
```
asilva@:~/Downloads$ sudo unzip terminix.zip -d /
...
asilva@:~/Downloads$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
...
asilva@:~/Downloads$ terminix
2016-04-18T11:34:22.095:terminal.d:outputError:1246 Unexpected error occurred: Failed to execute child process "" (No such file or directory)
2016-04-18T11:34:22.096:terminal.d:outputError:1247 Working Directory=/home/asilva/Downloads
2016-04-18T11:34:22.096:terminal.d:outputError:1248 Arguments used to execute process:
2016-04-18T11:34:22.096:app.d:main:66 Unexpected exception occurred
2016-04-18T11:34:22.096:app.d:main:67 Error: integral
```

**Comment by gnunn1** [comment]
Thanks, that's really interesting. If I had to guess, I'd say that Terminix isn't finding your shell for some reason, it does this using the VTE method here:

https://developer.gnome.org/vte/0.40/VteTerminal.html#vte-get-user-shell

I suspect my issue is that I'm not reacting to the NULL by using the system default. I'll investigate this tonite after work.

Also, can you confirm for the profile you are using that you do not have setting "Run a custom command instead of my shell" enabled?

**Comment by gnunn1** [comment]
Can you try this and report what you get back:

```echo $SHELL```

**Comment by gnunn1** [comment]
Just as an FYI, looking at gnome-terminal code for this it is obvious that it is using a much more sophisticated approach then I am to determining the shell. I'll work on emulating it, see here for g-t approach:

https://github.com/GNOME/gnome-terminal/blob/master/src/eggshell.c

**Comment by gnunn1** [comment]
Can you download the version from here and confirm that it is working for you:

http://gexperts.com/files/terminix.zip

**Comment by curaloucura** [comment]
yep, that did the trick! thanks a lot for looking at it, gonna use Terminix today to see how it performs  :)

**Comment by Kabouik** [comment]
I'm sorry to hijack this old closed issue, but I am having the same error when trying to run a npm executable in a new Tilix window using `tilix -e vtop`, while `vtop` in an existing Tilix session would work. Should I open a new issue?

**Comment by quaintdev** [comment]
I have this exact same issue which @Kabouik mentioned only with different command.

**Comment by vnckppl** [comment]
Similar issue here: `tilix -e htop` works, but `tilix -e 'echo abc'` does not.
