### ISSUE TITLE
Fedora RPM for 0.35.0 (based on aur)

### ISSUE THREAD

**Issue by fastrizwaan** [gnunn1/terminix#21]
Here's fedora 23 rpm spec file
[terminix.spec.txt](https://github.com/gnunn1/terminix/files/90219/terminix.spec.txt)

or download for fedora 20, 21, 22, 23
https://build.opensuse.org/package/show/home:fastrizwaan/terminix

**Comment by gnunn1** [comment]
Thanks for this, I really appreciate it. I was looking at doing this with OBS myself at some point when I get time. I'll update the main in the next day or two pointing to this.

**Comment by gnunn1** [comment]
Can you remove the  i586 targets as I'm only doing 64 bit builds. If you can do that and update to 0.36 I'll update the readme to include a pointer to this page.

**Comment by gnunn1** [comment]
Sorry, I should also ask the captain obvious question. Are you willing to keep this up to date or is it more just helping me out with a useable spec file? I'm fine either way, just realized I was jumping the gun a bit about volunteering you :)

**Comment by fastrizwaan** [comment]
I can't keep up with the updates, I really wanted to help you with the spec file, so that with each update obs could be used for terminix release. Please create terminix project at obs. Thanks.

I've disabled the i686 packages. Also updated to 0.36.1.

**Comment by gnunn1** [comment]
No worries but thanks for your effort on this. I've moved the .spec file and the _services file to my own home in OBS and setup builds for Fedora 23 and CentOS 7. One question, is there a way to have the _service file use the version number from the spec file instead of having to update both the spec and _service file?

**Comment by fastrizwaan** [comment]
I have not tried, And not sure about whether it is possible; but these might help:
https://en.opensuse.org/openSUSE:Build_Service_private_instance_software_live_cycle#Integrating_with_Git

example _service
https://build.opensuse.org/package/show/home:Kenzy:packages/finalterm
https://build.opensuse.org/package/show/home:Kenzy:packages/Mailpile

**Comment by gnunn1** [comment]
Thanks for the info, I will check it out.
