### ISSUE TITLE
Hide terminal title, not clear how to close/maximize a session

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#210]
I love the new change to completely hide the terminal title bar, and the moving of those options into the right click popover. There is one usability concern however, which is that it is not clear how to close or maximize a session when the terminal title bar is hidden, as those options are not carried over to the popover.

Thus, while I would love to hide the bar and use the right click popover for all of those options, I can't yet do the fact that I can't close any of my sessions unless I briefly show the top bar again :-/

The only other thought that I could think of is that it is commonplace in windows and various linux software apps (electron based apps mostly) to show a previously hidden menubar when the "alt" key is pressed, and have it disappear again when the alt key is released. Perhaps that could be a middle ground when people chose to hide the terminal titlebar, but still would like to have fast access to options that just won't fit in the right-click popover.

**Comment by gnunn1** [comment]
The maximize option is already in the context menu however I did indeed miss the close item. I'll fix it for the next release, however in the interim you can use the shortcut to close a terminal. The context menu in general could use some optimization and design though so if someone has some thoughts on how best to organize it I'm more then happy to take it into consideration.

The idea about showing the title on a modifier key is interesting, it might interfere with shortcuts though. I'll keep it in mind.

**Comment by gnunn1** [comment]
So I fiddled a bit with the context menu, here's a screen shot showing how it looks with the title active and the next one with the title hidden. Any thoughts/opinions from folks?

![screenshot from 2016-04-06 19-17-29](https://cloud.githubusercontent.com/assets/9358238/14337570/66ecb492-fc2c-11e5-9517-4af7e48edde4.png)

![screenshot from 2016-04-06 19-17-41](https://cloud.githubusercontent.com/assets/9358238/14337573/6c8d088e-fc2c-11e5-83a4-ea43608c5f05.png)

**Comment by brittyazel** [comment]
Looks great to me! Cut/copy/paste aren't terribly clear from the icons though unfortunately

**Comment by arshavindn** [comment]
how about Synchronize Input in the menu? I think we need to turn it on/off sometimes when the title's hidden

**Comment by gnunn1** [comment]
@arshavindn I forgot about that button for toggling the terminal synchronize input state, thanks for reminding me

**Comment by gnunn1** [comment]
@brittyazel That's a function of the icon theme you have configured for your desktop, the one I'm using (Moka) isn't very distinctive for these specific icons. The other issue is that the buttons on the popover don't have tooltips and I'm not seeing any way to enable them.

**Comment by dsboger** [comment]
@gnunn1 by seeing the popover appearance, I'm guessing you are using a menu model to generate it? If that is the case, I think if you define a custom popover (i.e. add widgets to it manually) you can add tooltips like anywhere else.

**Comment by gnunn1** [comment]
@dsboger Yes I'm using a menu model to generate it, you have a good idea but I'd really prefer not building the popover from scratch just to get the tooltip going.

**Comment by dsboger** [comment]
It could also be nice to have the terminal title in the context menu. Maybe it could start with a line very similar to the hidden titlebar:

```
1: large ... ellipsized title [SyncBtn] [MaxBtn] [CloseBtn]
-----------------------------------------------------------
Splitting
[SplitV] [SplitH]
...
```

**Comment by gnunn1** [comment]
@dsboger To add the title that way I'd definitely be looking at building the popover manually instead of a menu model and style it in a different manner so it's obviously non-interactive. I'd like to see someone come up with a mock-up though before I start going down this route.

**Comment by gnunn1** [comment]
The last commit added support for replacing the sync input button from the titlebar, so from my perspective this enhancement is complete.
