### ISSUE TITLE
Feature Request : Add Link handler

### ISSUE THREAD

**Issue by showcheap** [gnunn1/terminix#211]
On gnome-terminal have menu 'Open Link' and 'Copy Link Address' maybe it can be added on terminix.

**Comment by gnunn1** [comment]
It already has this feature, see screenshot below, is there some aspect of it that isn't working for you?

![screenshot from 2016-04-05 11-03-41](https://cloud.githubusercontent.com/assets/9358238/14290900/2b84f518-fb1e-11e5-9713-acbb5ef47a4e.png)

**Comment by showcheap** [comment]
@gnunn1 Sorry, I was install from OpenSUSE build service repo, so i get 0.54.0 version. Thanks for your reply, i'll update my terminix.
