### ISSUE TITLE
Improve Find shortcut behavior

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#212]
Is it possible to make the find shortcut (Ctrl+Shift+F, by default) work in a slightly different way: if the search entry is visible, but not focused, pressing the shortcut gives it focus instead of hiding it (like e.g. Firefox's Ctrl+F)? Thanks!

**Comment by gnunn1** [comment]
I'll have a look at it, the behavior in gnome apps is a bit inconsistent in this regard. In Nautilus Ctrl+F acts as a toggle whereas in gedit it does not.
