### ISSUE TITLE
Relax dependency on gtk-d version a bit

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#213]
Is it possible to change `dub.json` so that `terminix` will depend on `"gtk-d" : "~>3.3.0"` or `"gtk-d" : ">=3.3.0"`? That will make easier to build `terminix-git` with latest `gtkd` from git master. Thanks!

**Comment by gnunn1** [comment]
I'll do that, but I'm not sure it will have any practical effect since up to now I've been pretty aggressive about upgrading to the latest version of gtk-d, either to fix critical bugs or to leverage new GTK features.  But who knows, maybe things will settle down a bit now :)

**Comment by dsboger** [comment]
In my case, the problem is when I'm trying to build terminix with gtkd newer then what is accepted. Dub ends up fetching the older version unless I "fool" it by setting the exact version from `dub.json` to the newer gtkd.

**Comment by gnunn1** [comment]
Oh ok, that makes sense. I was thinking in the context of dynamic linking and not having to rebuild the gtkd shared libraries for every change.
