### ISSUE TITLE
Double click behaviors

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#215]
1. When the left menu button on title bar is checked, double click on it causes maximize the pane and vice versa.
2. When find box is active (Ctrl + Shift + F), double click on search text field or next, previous button equalizes panes

bonus: Need to correct the tooltip of synchonize input button on title bar, if button is unchecked, set it to "Enable input..."

**Comment by gnunn1** [comment]
1. Can't reproduce

2. I can reproduce this one and I'll take care of it

bonus: Not planning on changing as it seems kind of pointless to me, the associated checkbox shows the state. Other Gnome apps don't have this behavior either as far as I can tell.

**Comment by gnunn1** [comment]
As for the bonus, me bad, I had in my brain the session synchronize input menu option, forgot about the toggle on the titlebar. I'll have a look at it, my apologies for the confusion.

**Comment by arshavindn** [comment]
@gnunn1 sorrry, do you mean you can reproduce the first issue?

**Comment by gnunn1** [comment]
@arshavindn Yes, I can reproduce the first issue as well. I'm really starting to dislike GTK's mouse handling event model.

**Comment by arshavindn** [comment]
@gnunn1 many thanks for your hard working and great app :D
