### ISSUE TITLE
Popover section title text looks odd on Ubuntu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#217]
Just compiled the latest master branch on Ubuntu 16.04 and the section title text in the popover looks a bit odd:

![selection_001](https://cloud.githubusercontent.com/assets/422013/14360448/5d2d210e-fcee-11e5-9295-450eb1e530e8.png)

**Comment by gnunn1** [comment]
To parody Sheldon from Big Bang Theory "Oh, Ubuntu, you are my least favorite Linux-based operating system!"

I don't think this is a bug with Terminix but rather Ubuntu's Ambiance theme. I'll see if I can workaround it with some CSS though.
