### ISSUE TITLE
To be able to deactivate the _open in the browser_ behavior

### ISSUE THREAD

**Issue by GuillaumeAmat** [gnunn1/terminix#218]
When Terminix displays a _sort of_ link, a click on it opens launch the url in the browser.
It is so annoying to me!... I read a lot of logs everyday and copy and paste a lot of things. That behavior always redirect me on my browser and it turns me mad ;)

Is it possible to:
* Be able to deactivate it?
* Or be able to replace the _click_ by a _ctrl+click_?

Thanks for the good work anyway!

**Comment by gnunn1** [comment]
I just tried this out in gnome terminal, never realized that it worked off of ctrl-click and not just click. I'll modify terminix to use the ctrl+click combo.

**Comment by GuillaumeAmat** [comment]
Great, thanks!
