### ISSUE TITLE
Issue setting some shorcuts

### ISSUE THREAD

**Issue by gnumdk** [gnunn1/terminix#219]
Here, setting "Shift+Left" and "Shift+Right" as next/prev terminal shorcut doesn't work.

**Comment by gnunn1** [comment]
I tried here and it's working OK for me on git master, I assume it has not been assigned to another shortcut in your case? If you close and re-open terminix does it make any difference?

**Comment by gnumdk** [comment]
Restarting make difference. And using next/prev session and not terminal... What's the difference?

**Comment by gnumdk** [comment]
Terminix adopted ;)

**Comment by gnumdk** [comment]
Ok, I know the diff ;)

**Comment by gnunn1** [comment]
So what was the issue?
