### ISSUE TITLE
Enabling login shell not working

### ISSUE THREAD

**Issue by gnumdk** [gnunn1/terminix#221]
On archlinux, I follow this page:
https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue

But here the result
![capture du 2016-04-09 16-39-42](https://cloud.githubusercontent.com/assets/3918824/14404270/fa310f40-fe71-11e5-8549-48d7a2260f43.png)

**Comment by gnunn1** [comment]
Can you confirm you have the following packages installed:

```
vte-notification-common 0.42.3-1
vte3-notification 0.42.3-1
gnome-terminal-fedora 3.18.2-1
```

**Comment by gnumdk** [comment]
Ah ok, no, archlinux with default vte...

**Comment by gnunn1** [comment]
It works fine with the regular VTE as well, but it looks like you have the /etc/profile.d/vte.sh from the fedora patched VTE that emits notifications?

**Comment by gnumdk** [comment]
You are right, just the common package... Thanks ;)
