### ISSUE TITLE
issues if DBusActivatable is enabled

### ISSUE THREAD

**Issue by lucazade** [gnunn1/terminix#228]
open new instance with V/HSplit and maximize option are not working if DBusActivatable=true in .desktop launcher. 

Also 'open in terminix' contextual entry in Nautilus doesn't open with the correct path but only with default one.

These issues are present with latest commit from git usign gnome 3.20 and archlinux

**Comment by gnunn1** [comment]
The desktop file has DBusActivatable=true by default in terminix and it is working fine for me in the sense that the command line option to maximize works.

As to the V/HSpit, I just changed the action names to terminal-split-right and terminal-split-down so try those instead, I have updated the Command Line Actions of the wiki to reflect that.

Finally, the Nautilus Open in Terminix is also working fine for me, are you trying to open a normal folder or something different like a network share or mtp based folder?

**Comment by lucazade** [comment]
ok.. I try to be more clear :)
The option "On new istance" is not working for me.. it always open a new window instead of a new session or splitting the existing window.

attached there is a screencast of the issue
[Screencast_12-04-2016_08:28:27.webm.zip](https://github.com/gnunn1/terminix/files/214452/Screencast_12-04-2016_08.28.27.webm.zip)

**Comment by gnunn1** [comment]
Now I understand, I'll take care of it. Thanks for reporting this.

**Comment by lucazade** [comment]
thanks.. now it is working correctly!
