### ISSUE TITLE
Move Fedora builds to Copr

### ISSUE THREAD

**Issue by nexfwall** [gnunn1/terminix#234]
OBS is useful only when building for openSUSE, but then it comes to Fedora, it should not be used.

And there is only one big reason: OBS does not [include Fedora "updates" repo in their Fedora chroots](https://build.opensuse.org/project/repositories/Fedora:23).

So, your package is always built using release repo, which is (almost) always outdated.

Also, using Copr you can provide Fedora 24 builds, so folks like me, updating Fedora on Alpha release, can install your application using rpm packages.

// I have experience in Fedora packaging, so if you need help, just ask. I'm just wanted to try your application, but found out, what there is no F24 builds. 🙁

**Comment by gnunn1** [comment]
See #25, I'm not interested in maintaining packages and am looking for volunteers to do so. A few people have created COPR packages for Terminix but they don't keep them up to date so I don't include a link to them. If you are willing to do so, reply in #25.
