### ISSUE TITLE
Command-line switch `--switch-to-existing-window`

### ISSUE THREAD

**Issue by almson** [gnunn1/terminix#236]
This switch would be used in launchers, keyboard shortcuts, and any other places in the desktop environment that take a command as an argument. User would use this switch if he doesn't want to clutter his desktop with multiple terminal windows. It would be used to implement global hotkey functionality.

**Comment by almson** [comment]
Note that the switch's name is a placeholder. Consider that xfce4-terminal provides the following command-line switches:

    Window or Tab Separators
        --tab
           Open a new tab in the last-specified window; more than one of these options can be provided.

           If you use this as the first option, without --window separators, the last window will be re-used.

        --window
           Open a new window containing one tab; more than one of these options can be provided.

**Comment by gnunn1** [comment]
Terminix has a preference for what to do when opening a new instance (New Window, New Session, Split Right, Split Down). I think it would make sense to add this as an option there as well as adding a new command line switch

**Comment by gnunn1** [comment]
Added a preference called "Focus Window" to the new instance option and added a command line parameter called ```--focus-window```

**Comment by almson** [comment]
Thank you. I didn't notice the option in preferences. Could you add the option to merely switch focus there as well? Since I'd like it to be the default, it would make it even easier for me to configure.
