### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by giray** [gnunn1/terminix#237]
It would be nice to be able to assign keyboard shortcuts for actions such as

1) Show session sidebar
1.a) select session (1,2,3,4,...)
2) Jump to session [Alt - 1, Alt - 2]
3) Start new Session

also would be nice if these shortcuts are customizable.

**Comment by phw** [comment]
All those are available and configurable, see the keyboard shortcuts in settings. E.g. showing session sidebar is currently `F12` by default, switching session is `Ctrl + Alt + 1` to `Ctrl + Alt + 0`

**Comment by gnunn1** [comment]
I think @phw answered this satisfactorily, closing issue.

**Comment by giray** [comment]
is settings the same as "Profile", have not been able to find a settings section...

**Comment by gnunn1** [comment]
It's the preferences dialog, see the screen shot below:

![screenshot from 2016-04-12 08-07-54](https://cloud.githubusercontent.com/assets/9358238/14462763/ccc96a96-0085-11e6-88a5-37151667edf2.png)

**Comment by giray** [comment]
I'm using Beta 0.57.0 I cannot find "Preferences"

I have "Save, Find ..., Layout Options..., Read Only,  Profiles, Encoding" on the drop down for the session ...

And "Open.., Save, Save As, etc" on the right hand corner

**Comment by phw** [comment]
What desktop environment are you using? On Gnome you should see the Preferences in the Gnome app menu (click on the application name in the upper left corner of the screen), on other DEs you should have a fallback menu placed in the header bar of Terminix (I think it is on the left, but I am not sure).

**Comment by giray** [comment]
Using Ubuntu 16.04 with default unity

This is the "alt-space" menu
![image](https://cloud.githubusercontent.com/assets/316284/14485784/80555452-0159-11e6-9c84-465a5070254b.png)

This is the sessions options menu

![image](https://cloud.githubusercontent.com/assets/316284/14485791/8bf53124-0159-11e6-99a5-c3d4fed92c6e.png)

This is what I think of as the options menu

![image](https://cloud.githubusercontent.com/assets/316284/14485800/96a8ee8a-0159-11e6-9c73-77f228cf042b.png)

And this is how it overall looks

![image](https://cloud.githubusercontent.com/assets/316284/14485848/ea7e073e-0159-11e6-8294-377c9b5ecc16.png)


I don't really see a hook to open the "Preferences" menu that you refer to

**Comment by phw** [comment]
Unity places the preferences in the app menu. Unity places the menu in the top bar and hides it unless you move you mouse there, see this screen:

![terminix](https://cloud.githubusercontent.com/assets/29852/14486200/f797252a-015b-11e6-8440-57848c51f1f6.png)

Actually this behaves the same for all other applications in Unity ;)

**Comment by giray** [comment]
Not if you have changed to menu behavior to move the menu's back to the windows title bar
"Settings -> Appearance -> Behavior"
![image](https://cloud.githubusercontent.com/assets/316284/14486405/e037c370-015c-11e6-8495-c53da7b50b03.png)

**Comment by phw** [comment]
Yep, I can confirm this, see https://github.com/gnunn1/terminix/issues/241

**Comment by gnunn1** [comment]
Just out of curiousity, if you enable the terminix disable-csd option in dconf-editor does the menu then appear?

**Comment by abitrolly** [comment]
@jitka for that Gnome HID guidelines should be updated https://github.com/gnunn1/tilix/issues/1559
