### ISSUE TITLE
Configuring Unity with menus in app titlebar makes app menu unavailable

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#241]
If one configures Unity to place menus in the apps titlebar, the app menu is no longer available. See https://github.com/gnunn1/terminix/issues/237#issuecomment-209287425 . I assume Ubuntu does some special patching to the apps they ship to deal with this.

This makes some functionality unreachable, most notably the preferences dialog. One way to handle this would be to place the relevant menu options in the session menu in this case. We just need to know how to detect it.

**Comment by giray** [comment]
+1

**Comment by gnunn1** [comment]
Thanks @phw for your efforts in tracking this down, I'll have a look.

**Comment by gnunn1** [comment]
Actually I just tried this in 16.04, if you hold the mouse over the ```Terminix: Default``` title for a second it changes to ```Terminix``` in the titlebar and is a clickable menu which has all of the Gnome appmenu options including Preferences. Holding down the left Alt key also triggers this behavior, does this work for you guys?

**Comment by phw** [comment]
No, I can't get this to work. Using a Ubuntu 15.10 VM here. But @giray also is on Ubuntu 16.04, so his feedback is probably more interesting.

**Comment by giray** [comment]
I can't get anything to trigger via the title menu ... but if I press `Alt` I get the unity "search menu items" option, where I can get to `Preferences`, though its not really intuitive :)

![image](https://cloud.githubusercontent.com/assets/316284/14495869/901d14fa-0191-11e6-87dc-43c93511383f.png)

**Comment by phw** [comment]
I get the same behavior as @giray regarding the alt key. If I set the terminix option `disable-csd` with dconf-editor clicking the title in the terminix titlebar shows the menu, similar to how @gnunn1 described it.

**Comment by gnunn1** [comment]
@phw, I didn't realize it but I had the CSD disabled as well from when I was testing it last. I'm not sure what the best solution is here, I'll need to think about it a bit.

**Comment by gnunn1** [comment]
So I checked a few apps that use CSDs when this option is turned on and here is what I found:

* Nautilus - No way to access the app menu as far as I can tell
* Gedit - Same as Nautilus
* Lollypop - Disables the CSD on Unity, menu accessible the same way Terminix menu is accessible when CSD is disabled

Unless I'm missing something here, I'm inclined to mark this as a Won't Fix as IMHO it's really up to Unity to handle the appmenu appropriately when this option is enabled. Do you guys know of any other CSD apps that handle this option differently or better then these examples? As well, if I am missing something with regards to Nautilus or GEdit in terms of accessing the app menu let me know, my experience with unity is pretty low.

**Comment by gnunn1** [comment]
OK, I'm closing this and marking it as Won't Fix.

**Comment by phw** [comment]
This was fixed by #538 :)
