### ISSUE TITLE
Terminix needs its own icon

### ISSUE THREAD

**Issue by matthiasclasen** [gnunn1/terminix#245]
Sharing the same icon with gnome-terminal is confusing at best, and terminix really deserves a nice icon of its own. Asking for help in #gnome-design is likely to yield results.

**Comment by jimmac** [comment]
I'll give it a shot.

**Comment by jimmac** [comment]
How about http://jimmac.musichall.cz/stuff/terminix.zip ?

**Comment by gnunn1** [comment]
Impressive, thanks for taking care of this!

I'm flying tonite so I'll incorporate it tomorrow.

**Comment by edubxb** [comment]
Awesome, thanks @jimmac!

**Comment by dsboger** [comment]
The icon shown for the in-window AppMenu button (i.e. when the AppMenu is disabled/unsupported) is still the old icon.

**Comment by dsboger** [comment]
A small issue is that the smaller icons (48x48 and smaller) are not vertically centered.

**Comment by jimmac** [comment]
We don't vertically center app icons, we baseline align them.

**Comment by dsboger** [comment]
I'm definitely out of my AoE, so I said bs. Even though, I feel the alignment is a bit high when the icon is put in the headerbar:
![terminix_icon_headerbar](https://cloud.githubusercontent.com/assets/2356842/14623419/6e2a7b88-05a8-11e6-8cfd-18664b816f6a.png)

**Comment by jimmac** [comment]
I thought we were talking about the highres. Should have looked at the low res as well. You are indeed right, everything was shifted a few pixels upwards, the smaller ones being even clipped. My apologies. I re-uploaded the icon to the same URL -- http://jimmac.musichall.cz/stuff/terminix.zip It should have the small sizes corrected now.
