### ISSUE TITLE
OpenSUSE Build Service not work

### ISSUE THREAD

**Issue by dotws** [gnunn1/terminix#251]
No information home: gunun / terminix

**Comment by gnunn1** [comment]
I'm not sure what is going on with OBS, however you can find the RPMs here:

http://download.opensuse.org/repositories/home:/gnunn/Fedora_23/x86_64/

http://download.opensuse.org/repositories/home:/gnunn/CentOS_7/x86_64/

**Comment by gnunn1** [comment]
Deprecated OBS in favor of COPR, see new links on front page.
