### ISSUE TITLE
Not remembering window last location on Gnome3.20 with X server

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#256]
Since 3.20 hit stable, under an X environment none of the gtk3 windows would remember their last locations and instead open up in the upper left hand corner of the screen. This was mostly fixed with 3.20.1 as far as I can tell from other gtk3 windows (nautilus, calendar, etc), but Terminix still opens in the upper left hand corner.

From my testing, under Wayland Terminix does remember the last location, and seems isolated under X. 

Now, i'm not sure if/what you can do about this issue, but Terminix is one of the last remaining gtk3 apps not remembering window locations, so I thought I would bring it to your attention.

**Comment by gnunn1** [comment]
As you surmise, I don't think there is anything I can do as I'm not set the window position explicitly anywhere. Do you have a link to the gnome bug for this?

**Comment by brittyazel** [comment]
Nope I don't. I just remember it was extremely annoying with Gnome 3.20.0, most notably with Nautilus. However, with 3.20.1 nautilus and a slew of other gtk3 apps now retain their last opened position. There are still some that don't though, and Terminix is not the only one by any means. Gnome-software also doesn't remember. And other like Gnome-Calculator still open in the upper right, but that could be do to Arch repos still having 3.20.0 for its version.

Did you compile Terminix against an older version of gtk3+, perhaps 3.20.2 or 3.20.1? I'm wondering if compiling against the latest gtk3+ libs might implicitly fix this. But I have no idea what I'm talking about ;-)

**Comment by gnunn1** [comment]
It shouldn't matter what version I compile against as the window position logic should be in the window manager not the application AFAIK, plus GTK is a shared library and I'm not statically linking to it, only the D interface (GtkD) is statically linked. 

As an FYI though, I run Arch so my version is usually pretty up to date, currently that is 3.20.3-1.
