### ISSUE TITLE
appdata problem

### ISSUE THREAD

**Issue by Kami-no** [gnunn1/terminix#259]
/usr/share/appdata -> /usr/share/appdata/terminix.appdata.xml

It might be a Gentoo-specific problem.

**Comment by dsboger** [comment]
There was an issue with install.sh that was fixed (https://github.com/gnunn1/terminix/commit/e1115fee734c7af26ee92adf3654abd94b41fec7), but the official binary package was created before the fix.

**Comment by Kami-no** [comment]
May be release 0.58.1 required? =)

**Comment by dsboger** [comment]
For Arch, I solved that with a simple hack [1]. I guess the same could be done for gentoo?
[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=terminix

**Comment by gnunn1** [comment]
My plane just landed, I'll push a fix when I get to my hotel in a couple of hours.

**Comment by Kami-no** [comment]
Gentoo is also [flexible](https://github.com/Kami-no/overlay/blob/master/x11-terms/terminix-bin/terminix-bin-0.58.0.ebuild#L20) enough.

**Comment by gnunn1** [comment]
Pushed new release, any issues let me know.
