### ISSUE TITLE
Opening a new tab should not prompt option

### ISSUE THREAD

**Issue by Vinibo** [gnunn1/terminix#26]
It might be just me but I wasn't expecting a prompt when clicking "New Tab".

I think it should just create a new tab with default values instead of asking for a profile.

**Comment by gnunn1** [comment]
In Preferences on the first page turn off the "Prompt when creating new session" option and you will no longer be prompted as Terminix will just use defaults.

Now whether this option should be on or off by default is an interesting question.

**Comment by Vinibo** [comment]
It's great that the option is there!
But it doesn't seem to have any effect if I check it or not.
I always have a prompt, even after a reboot of the app.

For the default behavior, maybe some more users could give their feedback.
