### ISSUE TITLE
Feature request: option to close session directly from session sidebar

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#261]
Hi, a simple request that would improve my workflow with terminix is if directly from the Session Sidebar we had an option to close the sessions. Perhaps this could be done with a "X" in the upper right hand corner of each mini-window, or an option to right click on a mini-window and select close.

**Comment by gnunn1** [comment]
Makes sense, I'll see what I can come up with.

**Comment by brittyazel** [comment]
Awesome thanks! Love the work you do

**Comment by gnunn1** [comment]
Added feature with referenced commit
