### ISSUE TITLE
Disable sound when switching sessions in sidebar (sessions preview)

### ISSUE THREAD

**Issue by doubleloop** [gnunn1/terminix#262]
When I go to sessions preview and switch session with arrows, there is sound when I press up(down) arrow while on first(last) session.
I think good idea would be to disable this sound or make cycle (from last session you go to first) or make those configurable.

**Comment by gnunn1** [comment]
That's standard GTK Listbox behavior and I'm not sure I can change it, I'll do some research though.

**Comment by gnunn1** [comment]
Just to confirm, that's standard GTK behavior and I'm not going to override it. Marking it as Won't Fix.
