### ISSUE TITLE
Change the terminal that is focused after closing terminal

### ISSUE THREAD

**Issue by doubleloop** [gnunn1/terminix#266]
IMO it would be more intuitive when after you close the terminal, the terminal that is focused is the last used.

Fore example when you have 2 terminals (1, 2), and being in terminal 1 you open new one and then close it, you end up in terminal 2 not in terminal 1.

**Comment by doubleloop** [comment]
Also for example in situation of split:

1 | 2
--- | ---
  **1**  | **3**

(1's are one terminal) when you are in terminal 3 and do alt+left (goto terminal 1) then alt+right you end up in terminal 2 not in 3 as could be expected.

**Comment by dsboger** [comment]
Would it be desirable to have a full most-recently-used terminal list per session? I would like to exercise some D coding for the first time and that seems a good opportunity, if there is interest. This list could be useful beyond this issue, like opening way for a possible MRU order ctrl+tab feature (similar to alt+tab in window managers).

**Comment by gnunn1** [comment]
@dsboger Absolutely, before @alexwhitman did this work I was thinking about using an ordered linked list to track the focus order of terminals as a chain. So if you want to enhance the work that Alex did please feel free.
