### ISSUE TITLE
Feature request: clear terminal shortcut

### ISSUE THREAD

**Issue by alcir** [gnunn1/terminix#270]
There is a shortcut to clear the current window?

**Comment by gnunn1** [comment]
I don't think so, however if you can define a bit more what you mean by clear I could consider it as a feature request. For example, do you mean a shortcut for the equivalent of the Linux ```clear``` command, the ```reset``` or ```reset and clear``` feature in gnome-terminal, etc?

**Comment by alcir** [comment]
Yes, sorry. I mean reset.

**Comment by edubxb** [comment]
There's no reason for that, IMHO, Control+L does this, is a shell shorcut.

From Bash man:

**clear-screen (C-l)**
    Clear the screen leaving the current line at the top of the screen. With an argument, refresh the current line without clearing the screen.

**Comment by gnunn1** [comment]
@edubxb Thanks for that, however I think the VTE reset is a bit different then clear, from the VTE [documentation](https://developer.gnome.org/vte/0.40/VteTerminal.html#vte-terminal-reset):

_Resets as much of the terminal's internal state as possible, discarding any unprocessed input data, resetting character attributes, cursor state, national character set state, status line, terminal modes (insert/delete), selection state, and encoding.
_

Gnome Terminal has two actions, ```reset``` and ```reset and clear``` based on this VTE method.

**Comment by edubxb** [comment]
Mmm, the VTE reset does the same that the [reset](http://linux.die.net/man/1/reset) command?

**Comment by gnunn1** [comment]
@edubxb I didn't even know there was a reset command. I just tried it, looks pretty much the same at first glance.

@alcir What do you think, do still need this as I'm not sure it's worthwhile adding a shortcut for this?

**Comment by gnunn1** [comment]
No response from OP, I'm fine relying on clear/reset commands

**Comment by grigio** [comment]
+1 It's one of the most useful features in Gnome Terminal.

- `CTRL+L` is *clear* (it isn't very useful, because just the cursor is moved, the buffer still has the old data)
- `CTRL+K` is *clear and reset* (in my terminal) it means the buffer is empty again

**Comment by gnunn1** [comment]
It's been added in the newest release thanks to a PR from @Boiethios
