### ISSUE TITLE
Option to disable highlighting of pasted text

### ISSUE THREAD

**Issue by doubleloop** [gnunn1/terminix#271]
When you paste some text to terminix it is highlighted (which for example works bad when you have some coloring enabled like https://github.com/zsh-users/zsh-syntax-highlighting). Could it be optional?

**Comment by gnunn1** [comment]
I'm not adverse to adding an option for this, would you mind posting a screenshot to illustrate the issue?

**Comment by doubleloop** [comment]
the simplest example (using https://github.com/zsh-users/zsh-syntax-highlighting):
after I paste:
![screenshot from 2016-04-22 19-25-03](https://cloud.githubusercontent.com/assets/2602750/14749520/2753e238-08c0-11e6-84a0-dcecf082205c.png)

then after I press right arrow:
![screenshot from 2016-04-22 19-25-20](https://cloud.githubusercontent.com/assets/2602750/14749519/2751383a-08c0-11e6-8ece-6c4a7ddd4c21.png)

Even without this coloring plugin, I did not find many terminals to highlight pasted text by default

**Comment by gnunn1** [comment]
OK this is weird, I just tried on my local instance of terminix and this isn't happening for me, the behavior is the same as g-t which is the pasted text is not highlighted. How does gnome-terminal behave on your system?

**Comment by gnunn1** [comment]
Also, any chance to this could be related to your shell (zsh)?

**Comment by doubleloop** [comment]
In bash there is no highlighting. It is in zsh even without any configuration (`zsh --no-rcs`).
On gnome-terminal there is no highlighting in both bash and zsh

**Comment by phw** [comment]
Yes, that is default behavior for zsh, see http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html
