### ISSUE TITLE
Max width/height

### ISSUE THREAD

**Issue by Tadly** [gnunn1/terminix#272]
**For reference**
Resolution 1920x1080
Version: 0.58.1

I prefer my terminals to open on the very top stretching from the very left to the very right (fill the screens width)

So, the problem than.
Terminix allows 256 as max columns and 256 max rows.
Even if I set the columns to 256 it doesn't fill the whole screen.
I tried fine-tuning the columns which had no effect
![terminix_1](https://cloud.githubusercontent.com/assets/503647/14744634/d77c3e26-08a7-11e6-8d90-f54afa8bcb8c.png)

**Comment by gnunn1** [comment]
Absolutely, I went with what gnome-terminal was using and I noticed they've changed this as well.

https://bugzilla.gnome.org/show_bug.cgi?id=761395

I'll bump the maximum for both to 512.

**Comment by Tadly** [comment]
As another side-note, on gnome-terminal I set the columns to 220 which is enough for it to reach all the way.
Same font, same font-size

So I'm not sure if bumping the maximum to 512 will be enough, but we'll see I guess :)

Oh and thanks btw. :)

**Comment by gnunn1** [comment]
@Tadly I'm not sure what's going on with that, on my system setting the columns and rows to the same values (180x40) for both terminix and gnome-terminal results in the same size.
