### ISSUE TITLE
New instance positioning (pos_x, pos_y)

### ISSUE THREAD

**Issue by Tadly** [gnunn1/terminix#273]
Very simple to explain...

It'd be nice if new instances could be opened at a specific position.
Having a *Position X* and *Position Y* within each profile would be super nice :)

Currently it feels kinda random (to me at least) and depends on other windows on the same workspace (I think).

Not sure if that's a limitation of GTK as gnome-terminal removed the geometry argument with 3.20 (however they like to remove stuff even though it worked just fine)

**Comment by gnunn1** [comment]
I have mixed feelings about this as I generally think it should be the window manager's job to position the window. I'd be interested in hearing what other folks think about this.

**Comment by Tadly** [comment]
Fair point (and might be the reason for gnome removing it from gnome-terminal, who knows)
Interestingly enough, gnome-terminal ALWAYS opens on the very top for me while terminix doesn't.

So the might still be doing *something*

**Comment by egmontkob** [comment]
gnome-terminal did not intentionally remove geometry support. Gtk+ changed something internally, and adjusting g-t is in progress: https://bugzilla.gnome.org/show_bug.cgi?id=760944

**Comment by Boiethios** [comment]
A command line argument to do this may be a good solution, is not it ?

**Comment by gnunn1** [comment]
@Boiethios For me it's not so much where it's done but whether it should be done at all. As I mentioned previously, I tend to think that window positioning is the responsibility of the window manager and not the application.

Are there any other well known Gnome applications that have this feature?

**Comment by Tadly** [comment]
Sorry, been super busy lately.

@gnunn1 Apart from gnome-terminal I can't think of any other app that can (or well.. could) do that.

So even though I really would like such a feature I do understand that within the application itself it's not the right place to implement it.

**Comment by Boiethios** [comment]
http://linux.die.net/man/1/wmctrl can do the job. No need to implement it in the application.

**Comment by Tadly** [comment]
yeah I know about wmctrl.
Would have liked to not use a separat tool for positioning but that's fine.

This issue was more for discussion anyway which has been done :)

So I'm fine if we close that issue unless there are objections.

**Comment by gnunn1** [comment]
I've implemented the command line --geometry switch to support this. This initial version seems to work pretty well, but be aware that the parsing of the geometry string is custom (via regex) and thus doesn't support things like just setting the width or just the height. Right now it only supports two strings:

a. (width)x(height)
b. (width)x(height)+(x)+(y)

So rarer use cases like setting just the width are not supported at this time.
