### ISSUE TITLE
How to rebuild to have the languages changes ?

### ISSUE THREAD

**Issue by Boiethios** [gnunn1/terminix#277]
There is not an issue about the terminix features : there are some new changes in my language (French) and I would have them in terminix. I did :

```
$ git pull
$ dub build --build=release --force
$ ./terminix
```

But there are no changes in the application, while the changes are in the `po/fr.po`. Why ?

**Comment by phw** [comment]
dub build just compiles the source code and builds the binary. You need to run install.sh to compile the po files to mo files and install them to the appropriate system folder.

**Comment by Boiethios** [comment]
I never installed the application using `install.sh`. The depo is in my `/opt` and I lauch terminix using `cd /opt/terminix_depo && ./terminix`, and I have still the old translation. How is it possible ?

**Comment by phw** [comment]
AFAIK Terminix does not try to load the locale files from any other location then the system wide default. So when you run Terminix from an arbitrary directory it will usually just display the English default strings. Is it possible you had Terminix installed before (either via install.sh or via some package?) and had older translation files in `/usr/share/locale/fr/LC_MESSAGES/terminix.mo`?

It would be nice if Terminix could support compiling and loading the language files locally, especially for testing the translations quickly without a full install.

**Comment by Boiethios** [comment]
Thanks for your complete answer : perhaps I ran `install.sh` and forgot it.

And thank you for terminix, it is a really good job. I waited for this since long time.

**Comment by phw** [comment]
@Boiethios: All thanks goes to @gnunn1 , I am completely unaffiliated and just trying to answer your question :D

**Comment by Boiethios** [comment]
https://github.com/gnunn1/terminix/graphs/contributors : phw : 50 commits. You contributed too. But yes, I am grateful to @gnunn1 primarily :)

**Comment by gnunn1** [comment]
@phw is too modest, the localization in Terminix wouldn't exist without the work he put in, much appreciated,
