### ISSUE TITLE
Nautilus extension does not work

### ISSUE THREAD

**Issue by Boiethios** [gnunn1/terminix#283]
```
$ nautilus --version
GNOME nautilus 3.18.5
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux testing-updates (sid)
Release:	testing-updates
Codename:	sid
$ ls /usr/share/nautilus-python/extensions/open-terminix.py
/usr/share/nautilus-python/extensions/open-terminix.py
```

All seems ok, but there is no "Open Terminix here..." in my nautilus.

**Comment by dsboger** [comment]
Please, can you verify if you have the `python-nautilus` package installed?

**Comment by Boiethios** [comment]
Ok, I did not know. Can I propose a pull to the wiki, to add this info ?

**Comment by dsboger** [comment]
Maybe also add an item to the dependencies section in the readme.

**Comment by gnunn1** [comment]
I've included it as a dependency in readme, thanks for the suggestion @dsboger.

**Comment by akyag** [comment]
I am on gnome 3.22.2 and this extension didn't work for me. I do have nautilus-python so that isn't the problem.
