### ISSUE TITLE
Session sidebar not highlighting session when switching via keyboard shortcut

### ISSUE THREAD

**Issue by Tadly** [gnunn1/terminix#284]
Most of the time I use sessions (instead of tiles) and mapped all "switch to session *n*" to alt+*n* in old gnome-terminal fashion.

I noticed, when switching to a different session with alt+*n* **while** the session sidebar is open, the new session does not get highlighted.
After closing/reopening the session sidebar the new session is highlighted properly.

This is (obviously) just a minor bug :)

Tested and reproduced with:
* 0.58.1
* master branch from today

OS: archlinux
DE: gnome 3.20

**Comment by gnunn1** [comment]
Just a note to say I'm fixing this in parallel with #261
