### ISSUE TITLE
Unable to display icon with Ubuntu 16.04

### ISSUE THREAD

**Issue by githano** [gnunn1/terminix#286]
Hello,
I've manually installed terminix using the zip with the two following commands:
sudo unzip terminix.zip -d /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
The application is working, anyway I'm unable to load the icons for the launcher.
What am I doing wrong?
Thanks for the support.

**Comment by gnunn1** [comment]
You probably need to re-build your icon cache:

```
sudo gtk-update-icon-cache -f /usr/share/icons/hicolor/
```
You may also need to stop nautilus, from a command line:

```
nautilus -q
```

**Comment by gnunn1** [comment]
No response from OP, closing.

**Comment by agustibr** [comment]
I had the same issue, re-buiding the icon cache solved the issue. Thanks! :smiley:

**Comment by vipseixas** [comment]
Had the same problem and rebuilding solved it. 
You should document this on the "Manual installation" steps.

**Comment by mfleon** [comment]
In Debian stretch I installed manually version 1.8.9 and I also had this issue, rebuiling icon solved it.
Thanks!
