### ISSUE TITLE
Elementary port

### ISSUE THREAD

**Issue by jak645** [gnunn1/terminix#287]
I try to install it on elementary os Freya and is not very well done
is do sudo ./install.sh

resulte:
mederic@mederic-oldlaptop:~/Téléchargements/terminix-master$ sudo ./install.sh 
Installing to prefix /usr
Copying and compiling schema...
Building and copy resources...
Copying color schemes...
Copying and installing localization files
Processing po/de.po
Processing po/en.po
Processing po/es.po
Processing po/fr.po
Processing po/id.po
Processing po/ko.po
Processing po/pl.po
Processing po/pt_BR.po
Processing po/ru.po
Processing po/zh_CN.po
Processing po/zh_TW.po
msgfmt: unrecognized option '--desktop'
Try 'msgfmt --help' for more information.
msgfmt: unrecognized option '--xml'
Try 'msgfmt --help' for more information.
Note that localizating appdata requires xgettext 0.19.7 or later
Copying Nautilus extension
cp: cannot stat ‘terminix’: No such file or directory
cp: cannot stat ‘data/pkg/desktop/com.gexperts.Terminix.desktop’: No such file or directory
cp: cannot stat ‘data/appdata/com.gexperts.Terminix.appdata.xml’: No such file or directory
/usr/share/applications/com.gexperts.Terminix.desktop: file does not exist
Updating icon cache
gtk-update-icon-cache: Cache file created successfully.

**Comment by gnunn1** [comment]
I think the issue is the version of xgettext on Freya is too old, can you confirm what version you have by running:

```
xgettext --version
```

It might be possible to adjust the script to simply skip localizing the desktop and appdata file when xgettext is too old and copy it directly instead.

**Comment by gnunn1** [comment]
BTW, if you download the binary release instead it should hopefully work fine on Freya.

**Comment by phw** [comment]
>     cp: cannot stat ‘terminix’: No such file or directory

In addition to the gettext isdue this is a sign that you did not run dub build before running install.sh.

**Comment by gnunn1** [comment]
@phw Missed that, thanks. I'll update the install.sh to check if the terminix executable is present and emit an error if it is not, there have been a few people who missed running dub build first.
