### ISSUE TITLE
Can't upgrade to 0.59

### ISSUE THREAD

**Issue by almson** [gnunn1/terminix#289]
trying to start from command line, receive error:

```
2016-05-02T17:32:16.080:resource.d:getResource:102 Unexpected error loading resource /com/gexperts/Terminix/css/terminix.Numix.css
2016-05-02T17:32:16.080:resource.d:getResource:103 Error: The resource at '/com/gexperts/Terminix/css/terminix.Numix.css' does not exist

(terminix:3747): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Keybindings' does not contain a key named 'terminal-reset'
Trace/breakpoint trap (core dumped)
```

**Comment by gnunn1** [comment]
Are using Antergos?

**Comment by almson** [comment]
Sorry, forgot to mention I'm on Xubuntu 16.04

**Comment by gnunn1** [comment]
After you upgrade, you need to recompile the settings schema:

```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by almson** [comment]
Thank you, that worked

**Comment by almson** [comment]
Quick question, where did the application menu (ie, the place to access settings), go?

**Comment by gnunn1** [comment]
I haven't changed anything with the application menu as far as I can recall, unfortunately I'm not very familiar with Xfce. In Gnome, the Preferences (along with New Window, New Session, About and others) are accessed via the Gnome application menu. This menu either appears in the top bar at the top of the screen or there is a gnome option to add it to the application itself.

Do you know what Xfce does with this application menu? Do you have other Gnome apps like GEdit or Nautilus and if so how do you access their preferences as it should be the same for Terminix.

**Comment by almson** [comment]
Looks like the app menu disappeared from Gnome Disks as well. Ugh... Thank you for your help! I'll try to figure this out on my own.

**Comment by almson** [comment]
Got it. In `Window Manager` settings, the Menu button needs to be added to the title bar.
