### ISSUE TITLE
Support Localization

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#29]
Currently D does not have an official i18n package. Terminix uses a _() localization function as per GNU gettext but it doesn't actually do anything at the moment. At some point localization needs to be implemented, current localization options are:

* Write a D version of gettext using standard po/mo files
* Use the GLib wrapper of gettext
* Use a non-official D localization package such as i18n-d (https://github.com/JakobOvrum/i18n-d)
* Create a custom localization system

Of the four options, we will probably go with the second. While writing an official D version of gettext would be nice, it would be resource intensive. If Option #2 works and is supported by GtkD it would be the best.

**Comment by gnunn1** [comment]
I've added localization capabilities to Terminix and am using it successfully to localize the shortcut categories and names from their programatic names to proper english names. I'd appreciate it if someone would be willing to localize Terminix in their language and test the localization next release.

I only need one volunteer at this time, so if you are going to it just post in here claiming this task. While others are welcome to localize, I just want to be sure everything works as expected before going full bore into it.

**Comment by frnogueira** [comment]
I can do this.. But, in my OpenSuse I can't install the Terminix to test... :(

**Comment by gnunn1** [comment]
frnogueira, if the language you localize it in is relatively common it should be fine as others can test it. I just want to include at least one localization in the next release to vet it. With respect to OpenSUSE, assuming you meet the dependency requirements listed on the home page, feel free to open an issue for it and I'll help work with it.

**Comment by frnogueira** [comment]
Brazilian portuguese translations 100%

**Comment by gnunn1** [comment]
Thanks Fabio, really appreciate it. I'll be doing a new release in the next day or two that includes this.

**Comment by gnunn1** [comment]
Closing this issue, localization support added in 0.45
