### ISSUE TITLE
Inconsistent capitalization in pref labels

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#291]
It's inconsistent whether labels in the preference dialogs start the second and further words with upper- or lowercase. E.g.:

Terminal **t**itle **s**tyle
Theme **V**ariant
Dim **u**nfocused **t**erminals

Rewrap **o**n **r**esize
Custom **F**ont

Unfocused **D**im

etc.

**Comment by phw** [comment]
One way to fix this would be by fixing the English "translation" at https://hosted.weblate.org/projects/terminix/translations/en/ instead of changing the actual source strings.

Having somebody look over this and making sure the wording is consistent and inline with GNOME standards would be great.

**Comment by gnunn1** [comment]
@phw Since you are more familiar with localization then I am, if I change the case of the source strings in the application I assume that creates it as a new string triggering a re-localization requirement?

Gnome standards on capitalization are here:

https://developer.gnome.org/hig/stable/writing-style.html.en

I'll fix up the obvious candidates that @egmontkob pointed out.

**Comment by egmontkob** [comment]
> One way to fix this would be by fixing the English "translation"

This doesn't sound like a good idea to me. Instead of a one-off fix it has a fixed amount of burden to carry, the English translations need to be maintained, it becomes harder to grep for a UI string in the source (as there's one more non-trivial indirection), and also translators to other languages are misguided wrt. how to capitalize.

I think the strings should be fixed in the source, and yes, that'll result in fuzzy translations, which might be the right thing (forcing translators to review their upper/lowercases).

With a bit of patience you might easily fix all the translations at least with Latin scripts (to release the burden from translators), or just do a search-replace on the original strings in all the translations to avoid any fuzzyness and leave the translations as-is (even if they are inconsistent).

**Comment by egmontkob** [comment]
> I'll fix up the obvious candidates that @egmontkob pointed out.

Please go through all the prefs tabs, I just highlighted a small random selection :)

**Comment by phw** [comment]
> @phw Since you are more familiar with localization then I am, if I change the case of the source strings in the application I assume that creates it as a new string triggering a re-localization requirement?

It will require a re-localization, but it shouldn't be too much trouble for the translators. Gettext is clever enough to keep the existing translations and just marks them as fuzzy (so they are still in the PO files, but won't be compiled into the mo). In Weblate this will cause the "needs review" checkbox to be active and a translator should check it.

> This doesn't sound like a good idea to me. Instead of a one-off fix it has a fixed amount of burden to carry, the English translations need to be maintained, it becomes harder to grep for a UI string in the source (as there's one more non-trivial indirection), and also translators to other languages are misguided wrt. how to capitalize.

I agree here (except the last part, English capitalization rules don't easily apply to other languages), I just wanted to point out the possibility. Some projects do this, so they have the strings by the developers and have somebody dedicated to just fix the wording and keep things consistent.
