### ISSUE TITLE
Release Stable Version 1.0

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#293]
This is more of a request for input then an issue. I'm thinking of pushing out a stable 1.0 version in the next couple of weeks.  Looking at the issue list, once #290, #288 and #285 are fixed I'm thinking the app would be in pretty good shape at that point for a stable non-beta release.

Once 1.0 is out, I would probably slow down the releases and look at tackling some of the features that require a longer time frame to complete. Some of the things I would like to look at implementing include dbus support and patching VTE to pass escape codes to support iterm2 level features.

I'm interested ito hear if others feel that Terminix is ready for a stable 1.0 release or if there is some show stopping issue/feature that needs to be addressed that I'm not aware of.

**Comment by phw** [comment]
Just one wish from my side: It would be great if you could update the UI strings some time before doing the release and so translators have a chance to update the translations :)

**Comment by gnunn1** [comment]
Absolutely

**Comment by whitebyte** [comment]
Huge + for 1.0

**Comment by frnogueira** [comment]
Nice!
I will finish the pt_BR translations.

**Comment by gnunn1** [comment]
I think everything is good shape for a 1.0 release, as per the comment in the last release I'm targeting a date of around May 23rd for a 1.0 release. I checked in some fixes last night to address remaining transparency issues and other then hopefully fixing #15 I don't have anything in my queue until the release. All the other bugs identified in the first post of this issue have been addressed.

**Comment by phw** [comment]
I just ran `pacman -Rns terminator` :) It's really amazing how fast Terminix became such a feature rich and mature product.

**Comment by gnunn1** [comment]
Thanks @phw!

**Comment by frnogueira** [comment]
Me too, @phw ! :) :+1:

**Comment by agur4ik** [comment]
I'm using Terminix as my only terminal emulator since 0.58 and have not noticed any instabilities so far. It would be nice to release it as stable already.

**Comment by gnunn1** [comment]
I'm planning on moving the date up to the 21st of May since everything is looking good, if anyone is planning on updating translations now is the time to do it.

**Comment by edubxb** [comment]
I'm updating the Spanish translation in Weblate, hope I can finish it before the deadline.

**Comment by edubxb** [comment]
I completed the Spanish translation in Weblate, but any revision will be welcome :stuck_out_tongue_winking_eye:

**Comment by gnunn1** [comment]
Closing this issue as I've pushed out the 1.0 release and added a Roadmap section to the wiki.

https://github.com/gnunn1/terminix/wiki/Roadmap

Thanks again everyone for your help and support, it's been greatly appreciated.
