### ISSUE TITLE
Feature Request: Profile configuration for a default directory when opening the terminal

### ISSUE THREAD

**Issue by mehcode** [gnunn1/terminix#295]

**Comment by gnunn1** [comment]
So I'm struggling a bit with whether this is worth the effort of implementing and supporting it. As far as I can see, the only time this setting would get used is when launching a terminal from the command line with the --profile switch. If you switch profiles for an existing terminal I wouldn't expect it to switch directories.

So if it's only used when launching the terminal with --profile, is it really adding much over just specifying the --working-directory at the same time? I can see it as being somewhat convenient in terms of not having to type the directory for a given profile, but I'm not sure it's so convenient as to be worth implementing.

**Comment by mehcode** [comment]
@gnunn1 I wanted a way to overcome https://github.com/gnunn1/terminix/issues/25#issuecomment-218013837 -- and thought this might be a neat thing to do regardless.

**Comment by gnunn1** [comment]
OK thanks, I'm going to mark this as Won't Fix, I think using the --working-directory is an acceptable solution for this/
