### ISSUE TITLE
Shortcut label ugliness

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#297]
Prefs -> Shortcuts:

"reset" and "reset-and-clear" look like internal technical representations that forgot to have nice UI strings.

"Resize Terminal left" is lowercase "L" whereas the other directions are uppercase.

**Comment by phw** [comment]
reset and reset-and-clear are indeed internal representations. Those labels for keyboard shortcuts are special and need to be translated in the PO file (best done using Weblate).

**Comment by gnunn1** [comment]
As @phw pointed out, it's just updating the localization file. I'll take care of it tomorrow unless someone beats me to it.
