### ISSUE TITLE
Forgets my custom font size profile

### ISSUE THREAD

**Issue by sasann** [gnunn1/terminix#30]
Hi there.
I change my profile font size to something bigger. It'll change. But next time I open terminix it shows default font size. On edit profile section it shows the bigger font as being selected but the actual font size is small.
I'm running Archlinux and my default shell is fish.

**Comment by gnunn1** [comment]
Thanks, I haven't done any testing with fish so I'll have a look and see if it's something there. I assume this is working fine for you on gnome-terminal?

**Comment by sasann** [comment]
Yup gnome-terminal is fine.
