### ISSUE TITLE
Expanded terminal (dual-monitor)

### ISSUE THREAD

**Issue by seniorihor** [gnunn1/terminix#300]
I try to adjust terminal configuration to my needs.
Due to I perform most of my job within terminal (`tmux`, `neovim`, etc.) and I've got dual-monitor configuration, there's curiosity to expand `terminix` for the whole dual-monitor workspace.

Is there an option which would help me to achieve such a result?
Otherwise, IMO it might be decent feature request, huh? :smile:

**Comment by gnunn1** [comment]
It sounds like what you are asking for is to treat two monitors as one, so that Terminix spans across both monitors, is that correct? I might be missing something but I don't see how it's the applications job to worry about this, isn't this the job of whatever DE you are using?

**Comment by seniorihor** [comment]
Yes, it's correct.
Anyway, from my point of view, if there's an option --monitor which
supposed to set specific monitor to be launch on, it might be fine to allow
pass option "dual" to spans terminal across both monitors.
It would be super useful for people who use terminix as drop-down terminal,
like myself.

czw., 5 maj 2016, 18:34 użytkownik Gerald Nunn <notifications@github.com>
napisał:

> It sounds like what you are asking for is to treat two monitors as one, so
> that Terminix spans across both monitors, is that correct? I might be
> missing something but I don't see how it's the applications job to worry
> about this, isn't this the job of whatever DE you are using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnunn1/terminix/issues/300#issuecomment-217203311>
>
-- 
Sincerely yours,
Ihor Breza

**Comment by gnunn1** [comment]
I think the feature you want has already been added, albeit indirectly. I just added support for the geometry switch, you could use that to control which screen(s) terminix appears on and what the dimensions of it are (albeit in chars, not pixels). See this stackoverflow answer for a more detailed description. 

http://stackoverflow.com/questions/18360569/how-do-you-run-an-application-in-bash-and-select-which-monitor-it-runs-on

Do you think this will do the job for you?

**Comment by seniorihor** [comment]
Thanks! I think, that's the answer I was looking for.
I'll check out this solution tomorrow and let you know whether it fit my
needs.

czw., 5 maj 2016, 18:51 użytkownik Gerald Nunn <notifications@github.com>
napisał:

> I think the feature you want has already been added, albeit indirectly. I
> just added support for the geometry switch, you could use that to control
> which screen(s) terminix appears on and what the dimensions of it are
> (albeit in chars, not pixels). See this stackoverflow answer for a more
> detailed description.
>
>
> http://stackoverflow.com/questions/18360569/how-do-you-run-an-application-in-bash-and-select-which-monitor-it-runs-on
>
> Do you think this will do the job for you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/gnunn1/terminix/issues/300#issuecomment-217208383>
>
-- 
Sincerely yours,
Ihor Breza

**Comment by gnunn1** [comment]
Sounds good, just keep in mind that this new geometry switch is only available in git, it will be included in the next release.

**Comment by seniorihor** [comment]
I just pulled latest `master` from git and reinstalled `terminix`, but can't find out how to use the new geometry switch:
```
$ terminix --geometry
Unknown option --geometry
```
Could you provide some example of usage, please?

**Comment by gnunn1** [comment]
If you use the help command it should give you an example, i.e.

```
terminix --help

Usage:
  terminix [OPTION...]

Help Options:
  -h, --help                            Show help options
  --help-all                            Show all help options
  --help-gapplication                   Show GApplication options
  --help-gtk                            Show GTK+ Options

Application Options:
  -w, --working-directory=DIRECTORY     Set the working directory of the terminal
  -p, --profile=PROFILE_NAME            Set the starting profile
  -s, --session=SESSION_NAME            Open the specified session
  -a, --action=ACTION_NAME              Send an action to current Terminix instance
  -x, --execute=EXECUTE                 Execute the passed command
  --maximize                            Maximize the terminal window
  --full-screen                         Full-screen the terminal window
  --focus-window                        Focus the existing window
  --geometry=GEOMETRY                   Set the window size; for example: 80x24, or 80x24+200+200 (COLSxROWS+X+Y)
  --display=DISPLAY                     X display to use
```

**Comment by seniorihor** [comment]
```
terminix master % git pull
Already up-to-date.
terminix master % sudo ./install.sh
Installing to prefix /usr
Copying and compiling schema...
Building and copy resources...
Copying color schemes...
Copying and installing localization files
Processing po/bg.po
Processing po/de.po
Processing po/en.po
Processing po/es.po
Processing po/fr.po
Processing po/id.po
Processing po/it.po
Processing po/ko.po
Processing po/pl.po
Processing po/pt_BR.po
Processing po/ru.po
Processing po/zh_CN.po
Processing po/zh_TW.po
Copying Nautilus extension
Updating icon cache
gtk-update-icon-cache: Cache file created successfully.
terminix master % terminix --geometry 80x24
Unknown option --geometry
terminix master % terminix --help          
Usage:
  terminix [OPTION...]

Help Options:
  -h, --help                            Show help options
  --help-all                            Show all help options
  --help-gapplication                   Show GApplication options
  --help-gtk                            Show GTK+ Options

Application Options:
  -w, --working-directory=DIRECTORY     Set the working directory of the terminal
  -p, --profile=PROFILE_NAME            Set the starting profile
  -s, --session=SESSION_NAME            Open the specified session
  -a, --action=ACTION_NAME              Send an action to current Terminix instance
  -x, --execute=EXECUTE                 Execute the passed command
  --maximize                            Maximize the terminal window
  --full-screen                         Full-screen the terminal window
  --focus-window                        Focus the existing window
  --display=DISPLAY                     X display to use
```

**Comment by phw** [comment]
You have to rebuild it using `dub build --build=release` before running install.sh

**Comment by seniorihor** [comment]
Alright! Now I got `--geometry` option, but unfortunately I can't expand `terminix` for width bigger than width of one monitor.
It means, both commands create equal windows:
```
$ terminix --geometry 1920x24
$ terminix --geometry 3840x24
```

**Comment by gnunn1** [comment]
I don't have access to dual monitors during the week, only weekends when I'm home from work so I couldn't actually try this earlier. Let me play it around with it this weekend and I'll see what I can do.

**Comment by seniorihor** [comment]
Sure, thank you! :smile: 
Looking forward for news from you.

**Comment by gnunn1** [comment]
So I can confirm, it seems like the maximum size it lets me set in geometry is the size of the largest monitor, I can get it to still span the two monitors by setting the x and y coordinates but the actual size won't go any bigger. For example:

```
./terminix --geometry=2000x24+800+200
```

I don't think this is a VTE limitation, I suspect the window manager itself is preventing it but I need to look into it more.

**Comment by gnunn1** [comment]
I'm going to close this, I think this is an issue with the window manager constraining the maximum size.
