### ISSUE TITLE
Gettext used fundamentally incorrectly for shortcuts

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#301]
At certain places, Terminix uses internal technical identifiers as the string to be translated (msgid), and translates it even to English. E.g. en.po contains:

msgid "switch-to-terminal-1"
msgstr "Switch To Terminal 1"

This approach is wrong for a couple of reasons.

Sure there are some internationalization frameworks out in the wild that work this way, but gettext is not one. It expects the source string to be the American English UI label. (In case the English word is ambiguous and the same word appears at multiple places which should be translated differently, the solution is pgettext()).

Gettext falls back to the source string (msgid) and displays that on the UI if the catalog(s) according to the LANG, LANGUAGE, LC_* variables do not contain the translation.

Just start up Terminix with a locale that it is not translated to. E.g. `LC_ALL=hu_HU.UTF-8 LANGUAGE= terminix`. The UI literally presents `switch-to-terminal-1`. Not good.

Also, translators are not being helped enough. E.g. they see `switch-to-terminal-1`, it's hard to come up with a consistent way of capitalizing the letters – how should they know, without seeing the English translation, whether it's preferably translated with fully lowercase, or uppercase initial, or uppercase initial at each word? Sure a language might decide to deviate from English, but at least there should be a reference. Even flavors of English, let's say Canadian, might easily get "translated" differently from the American one for no good reason.

Sometimes the ID is even less intuitive, e.g. `switch-to-terminal-0` becomes `Switch To Terminal 10`, a translator shouldn't have to figure out that 0 stands for 10.

`app` is translated to `Application`, `win` is translated as `Window` (a translator might believe it's the opposite of `lose`) etc.

Please stick to the convention and how gettext was designed: msgid should always be the American English UI string. en.po probably shouldn't exist since the American strings are hardcoded; if other spellings are available then they go to en_GB.po, en_CA.po etc.

**Comment by gnunn1** [comment]
Well I am Canadian...

Seriously though, I'm not adverse to a better way of doing it but I'm not seeing an obvious solution that wouldn't have its own set of problems. For example, I could create a source file that has a static hash map that maps shortcuts to English names and localize that. On the downside though it's yet another file that needs to be updated and maintained when shortcuts are added or changed. I already have gsettings and shortcuts.UI to maintain, I'd prefer not to add a third file.

The cleanest option would be to have a standalone definition file and generate the gsettings file, shortcuts.ui file and anything else that's needed but that's a fair amount of work for not a huge benefit IMHO.

Just being pragmatic, I'm not so hugely bothered by this that I'd be willing to spend the time fixing it. Im happy to take a PR if soneone wants to tackke thus, maybe this is your opportunity @egmontkob :).

**Comment by gnunn1** [comment]
@phw Thoughts?

**Comment by phw** [comment]
No good idea right now. In general I completely agree with @egmontkob's argumentation. The current technical strings are problematic not only for unknown locales, but also for the translators. I myself was confused on how to translate them and had to dig into the code to find out, and I have seen in other translations people tried to keep the structure with the hyphens in the translations themselves (see e.g. https://github.com/gnunn1/terminix/blob/master/po/ru.po#L69). Also the translations often duplicate the texts in the help overlay, but for different source strings. That duplicates the translation effort and makes it harder to rely on translation memory.

But the easy solution of having a separate mappings code file doesn't sound too sexy :( Maybe at least that mapping file could be created and updated automatically (but one still would need to manually set the proper English string in the file). Do you see any way of reusing the strings in this file in the help overlay without duplicating the English text there?

**Comment by egmontkob** [comment]
I don't think it needs a new source file, nor needs to be overengineered and automatically generated. I think a manually maintained hashmap is good enough.

I don't know anything about D, so just some Java-ish pseudo code that could go to an already existing file:

hashmap foo = new hashmap();
foo.add("switch-to-0", _("Switch to 10"));
foo.add("switch-to-1", _("Switch to 1"));
foo.add("switch-to-2", _("Switch to 2"));
etc...

**Comment by phw** [comment]
Well, yes. I think that is the solution that was meant with "new source file" (the code has to go somewhere ;) ). The main concern is that in order to add a new keyboard shortcut aside from actually using the shortcut somehwere it has to be added to:

* The gsettings schema file
* The help overlay UI template
* The new mapping hashmap
* The strings between the hashmap and the UI template need to be kept in sync

**Comment by egmontkob** [comment]
I still haven't checked terminix's source, but generally the UI template should allow a text to be marked for translation, so there's no need for the hashmap. The msg* utilities take care of extracting from there into the .pot/.po files, and the UI template engine (e.g. glade) takes care of translating it runtime.

See e.g. https://bugzilla.gnome.org/show_bug.cgi?id=763911

**Comment by phw** [comment]
> I still haven't checked terminix's source, but generally the UI template should allow a text to be marked for translation, so there's no need for the hashmap. The msg* utilities take care of extracting from there into the .pot/.po files, and the UI template engine (e.g. glade) takes care of translating it runtime.

I think you should look at the source ;) The [UI template](https://github.com/gnunn1/terminix/blob/master/data/resources/ui/shortcuts.ui) is for the help overlay. That one gets translated as you described. The other part is the settings dialog for the shortcuts. This is [automatically constructed](https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/prefwindow.d#L209) from the [keys in the GSettings schema](https://github.com/gnunn1/terminix/blob/master/data/gsettings/com.gexperts.Terminix.gschema.xml#L511), and that part needs the hashmap (to translate the identifiers from the template to proper human readable strings, just as you described above, see [`_(id)` in prefwindow.d](https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/prefwindow.d#L314).

Which brings me to the ideas that we could probably create the hashmap automatically by parsing the help overlay UI template :) All the info we need, the IDs and the UI strings, are there.

**Comment by gnunn1** [comment]
@phw Reading the text from the UI file is a good idea. The easiest solution would just be to use GTKBuilder, load the UI and get the text from Shortcut widgets unfortunately that would only work in GTK 3.20. The most compatible option would be to load the UI file as an XML document and parse it. I'll look at doing that, one wrinkle is D's XML support is pretty weak but it should be good enough for this simple task. There's actually a GSOC project this summer to write the D XML parser.

**Comment by phw** [comment]
> The most compatible option would be to load the UI file as an XML document and parse it.

Or do that in the build phase, e.g. using a Python script or something alike.

**Comment by gnunn1** [comment]
Now reads localization from shortcuts.ui

**Comment by egmontkob** [comment]
Thanks for the fix...

Note, however, that a few strings still show up the old-fashioned way, using a lowercase identifier. This happens both with English locale settings as well as with a locale that Terminix is not translated to.

Application > new-window
Session > close, name, synchronize-input
Terminal > split-right (whereas "Split down" is correct)

**Comment by egmontkob** [comment]
I can't find any place in the source where split-right and split-down are handled differently.

In data/resources/ui/shortcuts.ui, theshortcuts are divided into sections which are further divided into groups, the latter is not reflected on the UI, so I don't know what its purpose is.

If I swap the two 6-line blocks of split-right and split-down, it's "Split right" that gets shown correctly and "split-down" becomes invalid. Seems like the first of these two children is not translated within the group.

If I move both to the beginning of the next group ("Find"), both strings are translated.

I have no clue what the heck is going on.

**Comment by gnunn1** [comment]
No worries, I'll look into it tomorrow, should have tested it more.

**Comment by gnunn1** [comment]
Problem was my parsing, removed the code that was trying to parse out prefix names. I don't think getting the prefix localization from shortcuts.ui was a great idea anyway, I had to work around the missing Window prefix plus where the prefix names are located isn't intuitive.

I also updated the shortcuts.ui to add two missing shortcuts.

**Comment by egmontkob** [comment]
Awesome, thanks! :)
