### ISSUE TITLE
Copy paste shortcut does not work until the copy button is clicked

### ISSUE THREAD

**Issue by stoatally** [gnunn1/terminix#305]
When I first launch Terminix the copy shortcut (I have it bound to `Shift+Ctrl+C`) does not work until I right click and then click on the copy button under 'Clipboard'. After doing that it works fine.

**Comment by gnunn1** [comment]
I cannot reproduce, it's working fine for me. What distro and GTK version are you using?

**Comment by gnunn1** [comment]
Anyone else having this issue?

**Comment by stoatally** [comment]
Sorry, forgot about this, using Arch Linux and Gtk 3.20.3.

**Comment by gnunn1** [comment]
@stoatally I'm on the same environment (Arch, Gtk 3.20.3) and it works fine for me. What package are you using in Arch, terminix or terminix-git?

**Comment by phw** [comment]
I can't reproduce it either, again same environment. Tested both with the release 0.59.0 and latest master.

**Comment by stoatally** [comment]
```
↪ pacman -Qi terminix-git 
Name            : terminix-git
Version         : 0.59.0.r14.2f75f7d-1
Description     : A tiling terminal emulator based on GTK+ 3 (git master)
Architecture    : x86_64
URL             : http://github.com/gnunn1/terminix
Licenses        : MPL
Groups          : None
Provides        : terminix
Depends On      : gtk3  dconf  gsettings-desktop-schemas  vte3  hicolor-icon-theme
Optional Deps   : python2-nautilus: for "Open Terminix Here" support in nautilus [installed]
Required By     : None
Optional For    : None
Conflicts With  : terminix
Replaces        : None
Installed Size  : 9.65 MiB
Packager        : Unknown Packager
Build Date      : Wed 04 May 2016 07:42:13 CEST
Install Date    : Wed 04 May 2016 07:42:38 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by sainf** [comment]
I have the same problem in:
Arch - GTK 3.20.3 and terminix 0.59.0-1

**Comment by phw** [comment]
Maybe a) some misunderstanding on what is happening or b) related to something else. Regarding a) that is what I tried to reproduce it:

1. Make sure terminix is not running
2. Launch terminix
3. Select some text in the terminal
4. Hit Ctrl-Shift-C
5. Verify the content is in the clipboard by pasting it again with Ctrl-Shift-V

Regarding b): Can you give some more details about your environment, e.g. which desktop are you using?

**Comment by gnunn1** [comment]
I used the same steps as @phw to attempt to replicate. The only other thing I'm thinking of is maybe the copy action is not getting enabled on text selection in VTE for some reason.

**Comment by stoatally** [comment]
I cannot seem to replicate it at the moment either, I think there's an additional variable I'm unaware of. However here's what happens:

1. Make sure terminix is not running
2. Launch terminix
3. Launch a program that responds to Ctrl-C (`pacman -Syu` for example)
3. Select some text in the terminal
4. Hit Ctrl-Shift-C
5. Watch the running program exit after receiving Ctrl-C

This usually happens to me right after a reboot, within 10 minutes of logging in as the first thing I do is launch Terminix to start jack.

**Comment by gnunn1** [comment]
Had a quick look at the code and I see the problem. When the context menu is displayed, the copy and paste actions may be disabled and I never re-enable them. Steps to reproduce:

a. Launch Terminix
b. Right click without text selected to open context menu, copy action disabled
c. Close context menu
d. Select some text in the terminal
e. Hit Ctrl-Shift-C, behaves a Ctrl-C instead of selecting text.

I was thinking a fix would be to add a handler to the VTE selection changed signal to enable/disable the copy action, however because when it is disabled the shortcut gets interpreted by VTE I'm thinking it needs to be enabled all the time. I'll add some close to re-enable any disabled actions on the close of the context menu.

**Comment by gnunn1** [comment]
I'm kind of surprised this bug made it this far without anyone noticing so thanks @stoatally for reporting it!

**Comment by stoatally** [comment]
Awesome, glad I'm not going crazy. Keep up the good work, Terminix is already the best terminal for Gnome and it's not even been half a year.

**Comment by gnunn1** [comment]
Just a note to my future self, there may be an opportunity here to introduce the "smart copy/paste" feature that Pantheon terminal has where the copy shortcut is only used when text is activated. This allows the user to use Ctrl-C both to select text and stop processes at the same time.

This would basically involve enabling/disabling the saCopy and saPaste actions based on selection changes in VTE and clipboard text availability.
