### ISSUE TITLE
Splitter size

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#307]
A question and a feature request:

What is the "Use a wide handle for splitters" actually meant to do?  In both the enabled and disabled states on Ubuntu 16.04 the splitters visually look the same and I can't find any functional difference.

This is a personal preference, it would be nice if we could customise the width of the splitters to be thinner than they currently are.

**Comment by egmontkob** [comment]
I think the Ambiance theme doesn't define a wide width for separators, other themes might do. (It's a property of GtkPaned: https://developer.gnome.org/gtk3/stable/GtkPaned.html#gtk-paned-set-wide-handle)

**Comment by egmontkob** [comment]
Terminator allows you to set a custom width; it does so by overriding the theme's CSS. For a starting pointer you might want to look at the patch at https://bugs.launchpad.net/terminator/+bug/1522575.

**Comment by gnunn1** [comment]
As @egmontkob points out, more modern themes like Adwaita allow an application to set the width of the paned handle. I added this option in response to #127 originally.

Now that I'm supporting theme specific CSS, there might be an opportunity to patch in support for this on Ambiance.

**Comment by egmontkob** [comment]
Filed upstream bug for Ambiance: https://bugs.launchpad.net/ubuntu-themes/+bug/1579342
