### ISSUE TITLE
dub build fail

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#314]
```
$ dub build --build=release
Performing "release" build using dmd for x86_64.
gtk-d:gtkd 3.3.1: target for configuration "library" is up to date.
gtk-d:gstreamer 3.3.1: target for configuration "library" is up to date.
gtk-d:gtkdgl 3.3.1: target for configuration "library" is up to date.
gtk-d:sv 3.3.1: target for configuration "library" is up to date.
gtk-d:vte 3.3.1: target for configuration "library" is up to date.
terminix ~master: building configuration "default"...
source/gx/terminix/prefwindow.d(311,15): Error: no property 'clear' for type 'string[string]'
dmd failed with exit code 1.
```

On Ubuntu Gnome 16.04, gtk 3.18, from lastest version pull from git

**Comment by phw** [comment]
Have you looked at #310 ?

**Comment by arshavindn** [comment]
@phw I've just tried what #310 done but still have this issue

**Comment by gnunn1** [comment]
It's kind of weird to me how people are having an issue with this clear method, I don't think it's actually needed since this method is just called once but I put in for defensive programming. I'm curious now if the clear method is a recent addition to dmd/phobos, I'll look into it.

**Comment by golimpio** [comment]
@arshavindn have you installed the latest one from dlang.org ? (as per #310)

I had this same issue and it was because I had an old compiler installed (I'm also running Ubuntu 16.04 / gtk 3.18)

**Comment by arshavindn** [comment]
@golimpio thank you, latest dmd from dlang.org solves the problem.

**Comment by alex285** [comment]
To confirm from #322, updating from `DMD64 D Compiler v2.070.0` to `DMD64 D Compiler v2.071.0` solved it. Thanks!
