### ISSUE TITLE
Paths configured in session JSON not used

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#316]
When you save a session to disk the working directory is saved to the JSON (the directory key). When loading such a session file with the `--session` command line parameter the directories are only set if Terminix is not running. If there is already a Terminix instance the session is opened in a new window, but all terminals in that session open in `$HOME`.

When loading the session via the "Open ..." menu it works as expected.

**Comment by gnunn1** [comment]
Thanks, there are also issues if the _New Instance_ option is set to something other then New Window, I'll look into both issues tonite.
