### ISSUE TITLE
warn when you paste sudo is not showing any text

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#32]
I'm using the latest version from AUR repo
![capture du 2016-01-17 22-07-29](https://cloud.githubusercontent.com/assets/7660997/12379978/ecff91e4-bd66-11e5-9aaa-ada54f7fb962.png)

**Comment by gnunn1** [comment]
Thanks, it looks like this happens because I'm showing the command as part of the text. When you are pasting a command that includes some markup characters (i.e. <> etc) as Pango tries to interpret and fails. I simply forgot to escape it, I'll make that fix.

**Comment by bil-elmoussaoui** [comment]
Thanks for the quick fix :+1:
