### ISSUE TITLE
Questions about translations

### ISSUE THREAD

**Issue by Boiethios** [gnunn1/terminix#321]
I have a little questions about translations : why some strings are marked as translatable (like "DIRECTORY", "PROFILE_NAME", or the hidden parameters) since there are just used internally and never displayed in the UI ?

And another question about weblate.org : I do the French translations, and some strings are marked with failing checks because "source and translated strings are same". For example : "Terminal", "Terminix", "Application" are the same in English and French. What is the way to say : "that's ok, I am sure this is the good translation" ? I know this is not a question about Terminix, but perhaps someone knows that answer I could not find on the Internet.

**Comment by phw** [comment]
DIRECTORY and PROFILE_NAME are actually translatable strings, they are part of the output of `terinix --help`. See this:

```
Application Options:
  -w, --working-directory=DIRECTORY     Set the working directory of the terminal
  -p, --profile=PROFILE_NAME            Set the starting profile
  -s, --session=SESSION_NAME            Open the specified session
  -a, --action=ACTION_NAME              Send an action to current Terminix instance
  -x, --execute=EXECUTE                 Execute the passed command
  --maximize                            Maximize the terminal window
  --full-screen                         Full-screen the terminal window
  --focus-window                        Focus the existing window
  --geometry=GEOMETRY                   Set the window size; for example: 80x24, or 80x24+200+200 (COLSxROWS+X+Y)
  --display=DISPLAY                     X display to use
```

And the German translation:

```
Anwendungsoptionen:
  -w, --working-directory=ORDNER     Arbeitsordner des Terminals wählen
  -p, --profile=PROFIL_NAME          Als Startprofil festlegen
  -s, --session=SITZUNGS_NAME        Die angegebene Sitzung öffnen
  -a, --action=AKTIONS_NAME          Eine Aktion an die aktuelle Terminix-Instanz senden
  -x, --execute=BEFEHL               Übergebenen Befehl ausführen
  --maximize                         Terminalfenster maximieren
  --full-screen                      Terminalfenster im Vollbildmodus anzeigen
  --focus-window                     Vorhandenes Fenster fokussieren
  --geometry=GEOMETRIE               Fenstergröße setzen, z.B. 80x24 oder 80x24+200+200 (SPALTENxZEILEN+X+Y)
  --display=ANZEIGE                  X-Anzeige, die verwendet werden soll
```

For the Weblate checks there are two ways. One is for you as a translator you should be able to remove that check by clicking on the small cross at the left side of the check warning. But Weblate will redo the check and add the warning again if the strings get changed.

The second option would be to disable certain tests for the source string. That requires more privileges. @gnunn1: Is it possible you give me additional permissions on Weblate or does that require a support request? If so I could go through the source strings and tweak the configuration. Beside disabling some tests fine tuning the priority of some strings can help a lot in getting usable translations quickly.

**Comment by Boiethios** [comment]
Oh thank you, I did not know that there were displayed ! And about the string "Hidden argument to pass terminal UUID" ? Is it actually displayed ?

And thank you for the help about the warning, I did not see the small cross in it. Now I solved the issue.

**Comment by phw** [comment]
> And about the string "Hidden argument to pass terminal UUID" ? Is it actually displayed ?

It is the help text for the command line argument, just like the others, but. But since that argument is marked as hidden it is not displayed in `--help`. But it is the help text for that argument nevertheless, so it is marked as translatable. I wouldn't change that for now.

**Comment by gnunn1** [comment]
@phw I have added you as an owner in weblate, if you need anything else just let me know.

**Comment by gnunn1** [comment]
@Boiethios Can this be closed now?

**Comment by Boiethios** [comment]
@gnunn1 sorry, I supposed you still talked about this.
