### ISSUE TITLE
BUILD: Error: no property 'clear' for type 'string[string]'

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#322]
dub build --build=release --force
Performing "release" build using dmd for x86_64.
gtk-d:gtkd 3.3.1: building configuration "library"...
gtk-d:gstreamer 3.3.1: building configuration "library"...
gtk-d:gtkdgl 3.3.1: building configuration "library"...
gtk-d:sv 3.3.1: building configuration "library"...
gtk-d:vte 3.3.1: building configuration "library"...
terminix ~master: building configuration "default"...
source/gx/terminix/prefwindow.d(311,15): Error: no property 'clear' for type 'string[string]'
dmd failed with exit code 1.

-----
DMD64 D Compiler v2.070.0
DUB version 0.9.24, built on Oct 27 2015

**Comment by phw** [comment]
See #310 and #314

**Comment by alex285** [comment]
Oops! I missed 310. I will update DMD and try again. Thanks!

**Comment by alex285** [comment]
Updating from `DMD64 D Compiler v2.070.0` to `DMD64 D Compiler v2.071.0` solved it. Thanks!
