### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by mnowaksuse** [gnunn1/terminix#325]
```
Traceback (most recent call last):
File "/usr/share/nautilus-python/extensions/open-terminix.py", line 44, in get_file_items
tip=_(u'Open Terminix In %s') % file.get_name())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```
While entering folder `Kubík` in Nautilus. Terminix v 0.60.0 from Fedora's copr repo.

**Comment by phw** [comment]
I wonder whether it is the file name or the translation strings that causes the issue. What is the full path of the affected folder could help, maybe there is some special character in there. What file system is it?

In case it is translation related, what is your language setting? Can you give the output of the `locale` command?

**Comment by phw** [comment]
From what I can tell it must be in the filename. The full path and the encoding of the underlying file system would help.

**Comment by mnowaksuse** [comment]
Full path: `/home/newman/Pictures/Kubík`
`locale`:
```
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_GB.UTF-8
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```
FS: `ext4`

**Comment by phw** [comment]
Ah, I missed the `í`, the font here renders that not very pretty and it looked like an ASCII `i` :)

I can't yet reproduce this here, which Nautilus version is that?

**Comment by mnowaksuse** [comment]
It's `nautilus-3.18.5-1.fc23.x86_64` from Fedora 23. This is the terminix repo: `https://copr-be.cloud.fedoraproject.org/results/heikoada/terminix/`.

**Comment by gnunn1** [comment]
Working on it, looks to be the same as this question:

http://askubuntu.com/questions/117731/fix-nautilus-uris-in-a-python-script

**Comment by bil-elmoussaoui** [comment]
@gnunn1 I think replacing the line 22 with this one `filename = urllib.unquote(gfile.get_path());` should fix that
