### ISSUE TITLE
Multipages shorctuts window

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#327]
Hello,
In small screens(13,3") it's impossible to see all the shortcuts 
![capture d ecran de 2016-05-13 12-41-57](https://cloud.githubusercontent.com/assets/7660997/15245648/281e239c-1908-11e6-9c51-e3e62855bd9c.png)
Using Builder
![capture d ecran de 2016-05-13 12-43-05](https://cloud.githubusercontent.com/assets/7660997/15245673/41d19b0c-1908-11e6-8664-c9729f0bee46.png)
Also, the shorctuts window is not "linked" to the main window (don't know how to explain that correctly :P) 
Thanks!

**Comment by gnunn1** [comment]
The problem here for Terminix is the large blocks of 10 shortcuts for switching terminals/sessions. I could maybe break them into 2 blocks of 5 each, might look a bit odd though. I'll give it some thought.

**Comment by bil-elmoussaoui** [comment]
The best way to have this, is you can move the "Resize" shortcuts to the second block, and devide the other one on the first & second block. As the "resize.." and "file" shortcuts are equal :)

**Comment by gnunn1** [comment]
Yeah I had the same thought, I'm just waiting to change it (and introduce a new localization) until after 1.0.
