### ISSUE TITLE
New session while session sidebar is open

### ISSUE THREAD

**Issue by Tadly** [gnunn1/terminix#329]
Another super minor issue I came across.

When creating a new session while the session sidebar is open (via keyboard shortcuts) the new session doesn't appear within the sidebar.
It will after closing and reopening the sidebar.

**Comment by gnunn1** [comment]
Thanks, I'm probably not going to fix this for 1.0 as this is a bit tricky in terms of getting a preview image for it. I'll probably look at doing some re-architecting of the sidebar as one of my longer term activities after 1.0.

**Comment by Tadly** [comment]
No problem.
Not like its annoying or anything :) (using shortcuts to switch sessions is 10x faster than using the mouse anyway :D)
