### ISSUE TITLE
Switch keyboard focus to most recetly used terminal when closing a terminal

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#33]
Hi, when I close a terminal using keyboard (e.g. Ctrl+D), the focus is not automatically passed to any of the remaining terminals. I must either press Ctrl+Tab or click some of the remaining terminals.

**Comment by gnunn1** [comment]
Fixed for next release

**Comment by dsboger** [comment]
Amazing! Great work!

**Comment by dsboger** [comment]
It seems this problem is back.

**Comment by gnunn1** [comment]
Confirmed
