### ISSUE TITLE
Conflicting shortcuts

### ISSUE THREAD

**Issue by stunningpotato** [gnunn1/terminix#330]
As terminix is an application with loads of shortcuts, some might get consumed by Terminix and not get forwarded into the app running. For example, this might be an issue with the nano editor. By default, you save a file by hitting `CTRL + O`. However, this shortcut is consumed by Terminix.

It would be super cool if Terminix had the ability to turn off conflicting shortcuts temporarily, according to the program running.

**Comment by gnunn1** [comment]
I don't think I can do any sort of automatic system, it would basically involve tracking all of the CLI programs out there and the shortcuts they use and then keep it up to date. I just don't see this as being very viable. Did you have an idea of how this would work that would be simpler to implement and maintain?

There is an enhancement request #223 already to allow shortcuts to be disabled temporarily but that would be via  manual interface.

**Comment by stunningpotato** [comment]
There could be like a list of the most common CLI programs such as cfdisk, Nano, midnight commander etc.

This list would'nt have to be comprehensive - but programs that are pretty much installed on every single Linux OS should work well by default, shouldn't they?

Another Option could be to have something like a "bypass Shortcut": this shortcut would deactivate all terminix shortcuts for, let's say, 3 seconds. In this time, the user can perform a keyboard shortcut that only the CLI application recieves.

**Comment by egmontkob** [comment]
I already had this in mind to report that Ctrl+O should be changed to Ctrl+Shift+O (it conflicts at least with nano and mc).

Ctrl+S is also troublesome, it is useful at least in mc (although Alt+S does there the same). Albeit here Ctrl+Shift+S is already taken, and Ctrl+S acts as scroll lock (a not really useful feature) most of the time.

However, I think there should be no Ctrl+letter shortcut defined by default..

**Comment by phw** [comment]
I agree with egmontkob, Ctrl+single letter is used quite commonly. Having shortcuts predefined which are likely not to conflict is IMHO the better solution than disabling shortcuts randomly according to some hard coded application list.

**Comment by gnunn1** [comment]
As per #187 if someone wants to go through and optimize the shortcuts I'm happy to accept a PR for it.

**Comment by apiraino** [comment]
Hello,

as an EMACS user I will never probably find a match with Gnome HIG shortcuts :-)
That's ok as long as I can easily custom tailor Terminix shortcuts and disable some of them.

In pull request #187 you mention ` /data/gsettings/com.gexperts.Terminix.gschema.xml` as the file to change the defaults.
On my Lubuntu 16.04 I only have this other file `/usr/share/glib-2.0/schemas/com.gexperts.Terminix.gschema.xml` but changes I apply to that file apparently don't have any effect.

Which is the recommended way to change Terminix shortcuts? Namely, how to effectively set a shortcut to `disabled`? Please excuse me if this is mentioned somewhere (that I could'nt find); shortcut settings from Terminix seems to not have an apparent way to set toi `disabled`.

Thanks,
Antonio

**Comment by gnunn1** [comment]
@apiraino There is a preferences dialog that allows you to customize shortcuts, just use that:

![screenshot from 2016-08-01 07-56-21](https://cloud.githubusercontent.com/assets/9358238/17293313/990af410-57bd-11e6-9b22-0d3d72706027.png)

**Comment by gnunn1** [comment]
@apiraino Also if you are using Unity and can't find the Preferences dialog, see issue #241 in case that is causing the issue.

**Comment by apiraino** [comment]
@gnunn1 that's exactly what I was referring to by `shortcut settings from Terminix seems to not have an apparent way to set to disabled`. From that very dialog, I tried to set a shortcut to `disabled` to no avail, most likely my mistake ;-)
I double-click an entry, I'm asked to set the new accelerator but can't set to `disabled`.

**Comment by gnunn1** [comment]
@apiraino  Click on the shortcut so it says ```New accelerator...``` and then hit backspace to set it to disabled.

**Comment by apiraino** [comment]
thanks @gnunn1 that did the trick.

**Comment by leoheck** [comment]
The default ``Ctrl-o`` should not be used by default. Please, use something different by default like ``Ctrl-Shift-o``

**Comment by gnunn1** [comment]
Save and Open have been changed to Shift+Ctrl+S and Shift+Ctrl+O respectively, Save As shortcut is disabled by default.
