### ISSUE TITLE
Overlay scrollbars

### ISSUE THREAD

**Issue by derekstavis** [gnunn1/terminix#331]
Since GTK 3.16 we've got overlay scrollbars for almost every core application.

I believe the issue with overlay scrollbars in terminal applications is vte, as gnome-terminal still haven't implemented it too, but I'm opening this issue to keep registered what probably more people would be interested in.

Thanks for this awesome terminal application!

**Comment by gnunn1** [comment]
This is covered in the FAQ (https://github.com/gnunn1/terminix/wiki/FAQ), if it's alright with you I'm going to close this as I prefer trying to keep the issue list smaller and contained to the items that are within my control.
