### ISSUE TITLE
Right click menu is unclickable

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#334]
In the latest version when I right click in the terminal, the popover shows, but I cannot click any of the option. The mouse cursor just stays as the "capitol I" shape, as if I were selecting text.

Trying to select any option immediately closes the menu without anything happening.

**Comment by brittyazel** [comment]
Actually, I rebooted and this issue went away. I have no idea what caused it :-/

**Comment by gnunn1** [comment]
I'm going to close this, sounds like just one of those things. If you can reproduce this, feel feee to re-open.

**Comment by brittyazel** [comment]
I just installed the 1.2 version today, and this issue is back. Right clicking and showing the popover results in the mouse cursor not changing from the "I" and to the traditional mouse, and clicking on any option in the popover does nothing.

**Comment by brittyazel** [comment]
And just like last time, rebooting solved the issue. I have no idea why I need to reboot after Terminix releases to get a working right-click popover

**Comment by gnunn1** [comment]
No idea what the issue could be, I haven't had anyone else report the issue.

**Comment by bassman7689** [comment]
I have this same issue. The right click menu will stop working. Not allowing me to click anything on it until I restart.

**Comment by mezaisrael** [comment]
The same thing just happen to me

**Comment by austinried** [comment]
This happens to me intermittently, very frustrating.  Restarting just tilix has no effect. Ubuntu 18.04 with gnome/x.

**Comment by mycroftmih** [comment]
Same issue, it's annoying.

**Comment by dhpowrhost** [comment]
This happens to me on my XPS 9300, preinstalled with Pop!_OS, running 20.04.
Happens mostly when resuming from suspend. I use my terminal at a daily basis as a sysadmin, and it is pretty anoying.
