### ISSUE TITLE
Missing Environment Variables

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#335]
Terminix doesn't seem to inherit the same environment variables as gnome-terminal and other terminals. In particular, I noticed when checking for the variable XDG_CURRENT_DESKTOP.

**Comment by dsboger** [comment]
Thats probably because gnome-terminal is not DBusActivatable, so its process is forked from a different parent.

**Comment by gnunn1** [comment]
@dsboger lol I just came here to post that after playing with it but you beat me to it.
