### ISSUE TITLE
commanline split to 4  sides

### ISSUE THREAD

**Issue by fastrizwaan** [gnunn1/terminix#338]
I want a four side split like in the screenshot (manually created)

[rizvan@localhost ~]$ terminix -a app-new-session -x "sudo dnf update"
[rizvan@localhost ~]$ terminix -a terminal-split-down -x "sudo dnf update"
[rizvan@localhost ~]$ terminix -a terminal-split-right -x "sudo dnf update"

1st create new session, 2nd create split down, 3rd split right, now how do I get the 4th one, like in this screenshot?

![screenshot from 2016-05-23 15-55-01](https://cloud.githubusercontent.com/assets/1161682/15467987/2138583c-20ff-11e6-8cb2-b213648657b6.png)

if I try 
[rizvan@localhost ~]$ terminix -a terminal-split-right -x "sudo dnf update"
I'm getting this :(
![screenshot from 2016-05-23 15-59-59](https://cloud.githubusercontent.com/assets/1161682/15468033/7535af20-20ff-11e6-96f8-0cdfdf847d1b.png)

**Comment by gnunn1** [comment]
Your best bet would be to save the layout you want and then load it when needed:

```terminix -s mylayout.json```

**Comment by gnunn1** [comment]
Note also that you can specify the startup command or each terminal in a session using the Layout Options menu option as well.
