### ISSUE TITLE
Error install terminix ubuntu 15.10

### ISSUE THREAD

**Issue by Carlos-Stgo** [gnunn1/terminix#339]
Error:

Performing "release" build using dmd for x86.
gtk-d:gtkd 3.3.1: target for configuration "library" is up to date.
gtk-d:gstreamer 3.3.1: target for configuration "library" is up to date.
gtk-d:gtkdgl 3.3.1: target for configuration "library" is up to date.
gtk-d:sv 3.3.1: target for configuration "library" is up to date.
gtk-d:vte 3.3.1: target for configuration "library" is up to date.
terminix ~master: building configuration "default"...
source/gx/terminix/application.d(157,49): Error: function glib.Variant.Variant.getString (out uint length) is not callable using argument types (ulong)
source/gx/terminix/application.d(155,23): Error: function gx.gtk.actions.registerAction (ActionMapIF actionMap, string prefix, string id, string[] accelerators = null, void delegate(Variant, SimpleAction) cbActivate = cast(void delegate(Variant, SimpleAction))null, VariantType parameterType = null, Variant state = null, void delegate(Variant, SimpleAction) cbStateChange = cast(void delegate(Variant, SimpleAction))null) is not callable using argument types (Terminix, string, string, typeof(null), void, VariantType)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(AppWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, AppWindow[], long) error instantiating
source/gx/terminix/application.d(572,29):        instantiated from here: remove!(AppWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(ProfileWindow[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, ProfileWindow[], long) error instantiating
source/gx/terminix/application.d(583,29):        instantiated from here: remove!(ProfileWindow)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, void delegate(string)[], long) error instantiating
source/gx/terminix/application.d(717,29):        instantiated from here: remove!(void delegate(string))
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(bool delegate(ActionType)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1699,19): Error: cannot implicitly convert expression (from) of type long to uint
source/gx/util/array.d(22,37): Error: template instance std.algorithm.mutation.remove!(cast(SwapStrategy)2, bool delegate(ActionType)[], long) error instantiating
source/gx/terminix/common.d(44,29):        instantiated from here: remove!(bool delegate(ActionType))
/usr/include/dmd/phobos/std/algorithm/mutation.d(1697,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
/usr/include/dmd/phobos/std/range/primitives.d(1798,6):        std.range.primitives.popFrontExactly(Range)(ref Range r, size_t n) if (isInputRange!Range)
/usr/include/dmd/phobos/std/algorithm/mutation.d(1698,32): Error: template std.range.primitives.popFrontExactly cannot deduce function from argument types !()(void delegate(string, string, string, string)[], long), candidates are:
dmd failed with exit code 1.

**Comment by gnunn1** [comment]
By x86 do you mean 32 bit, as per the FAQ only 64 bit is supported.
