### ISSUE TITLE
Scaled bg image is slow

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#340]
A background image in tiled/centered mode causes a tiny slowdown when cat'ing a giant file. A large background image in scaled mode causes a 2-3x slowdown and jerky scrolling. Even after simple events (such as pressing Enter at the prompt) redrawing lags noticably.

Is the image, by any chance, being cropped/scaled over and over again on each paint?

I think there would be no noticeable slowdown (or at least no difference between the various modes) if Terminix cropped/scaled the background image once only (and after each resize) and cached it in a pixbuf (or whatever the appropriate Gtk object is).

**Comment by gnunn1** [comment]
You are correct, the ImageSurface is being re-created on each paint. I didn't notice any performance issues but I didn't test it exhaustively and I have a discrete GPU. I'll look at caching it and invalidate it on resize, thanks for reporting this.

**Comment by egmontkob** [comment]
Sometimes it's beneficial to have a slow computer :D

**Comment by egmontkob** [comment]
Just for fun:

The current issue would be way more prominent if we hadn't addressed https://bugzilla.gnome.org/show_bug.cgi?id=730732 (comment 1 summarizes the root cause). Prior to that fix, combining with Terminix rescaling the image all the time, I think it would be pretty much unbearably slow :)

**Comment by gnunn1** [comment]
@egmontkob I checked in a change that caches the rendered image, on my laptop it drops the time to cat a large file from about 5.5 seconds to about 4 seconds which is in-line with the time for no image. When I interact with the terminal I'm not noticing a perceptible difference but then can again as I mentioned earlier I have a pretty beefy laptop.

Can you please test and see how it performs on your machine, if it is OK go ahead and close the issue.

**Comment by egmontkob** [comment]
Perfect, thanks! :)

**Comment by gnunn1** [comment]
Glad it worked, one thing to note is that this does consume somewhat more memory since I'm caching the image globally as before but now also each AppWindow now caches a rendered version of the image.

**Comment by egmontkob** [comment]
That's a fair price to pay I guess.

VTE's memory footprint is not that super low either. Each vte uses around 384kB for caching reads/writes of the scrollback buffer (https://bugzilla.gnome.org/show_bug.cgi?id=738601#c100), plus the input decoder is crappy and should be rewritten (https://bugzilla.gnome.org/show_bug.cgi?id=730226), and who knows what else...

**Comment by egmontkob** [comment]
If you're really concerned about footprint, you could free the original image, and re-read the file on each resize. I probably wouldn't do it though :)

**Comment by gnunn1** [comment]
I thought of that as well and discarded the idea for the same reason :)

**Comment by egmontkob** [comment]
Inspired by #352, you might still want to choose whether to:

- remember the original image as the jpeg file itself (and decode jpeg on each resize; resulting in a perhaps noticeably smaller memory footprint), or

- convert to a bitmap (decode from jpeg) once and store that bigger object.

Here I guess I cast a weak vote for the former.

Maybe you can simply just mmap() the actual file and keep it mmap()ed (and then go haywire if the file changes :P)

So many possibilities :)
