### ISSUE TITLE
Bg: scaled, keeping ratio

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#341]
Thanks for the background image support, it's really awesome!

Along with Scale/Tile/Center, I believe a great choice would be to crop along one axis only (centered) and scale keeping the aspect ratio.

(I guess this is what most phones/desktops do with background image.)

E.g. if the canvas is 500x300 and the picture is 1000x800 then it'd be scaled down to 500x400 and then the top and bottom 50+50px cropped.

**Comment by egmontkob** [comment]
Just wondering about the terminology to use... maybe Scale for this one, and rename the current Scale to Stretch?

**Comment by phw** [comment]
Or remove the existing scale completely? Is this really useful?

**Comment by gnunn1** [comment]
For the current Scale option, I'm vacillating between calling it Stretch or Fill.

@phw It's a fair point, some people though may like it from the point of view of having the terminal window completely filled.

**Comment by egmontkob** [comment]
FYI:

What I had in mind was to crop the image, so that whatever remains fills in the whole application window.

Displaying the entire picture, plus empty margins if necessary, is another viable option, but I like it less :)

Also, due to the (per-terminal) title bar, it _seems_ that the picture is not vertically centered. This is a bit distracting with margins, but probably far less noticeable if the image is cropped.

Thanks!

**Comment by gnunn1** [comment]
I missed the cropping part, I'l see what I can do.

**Comment by egmontkob** [comment]
It now crops from the left or from the top, rather than equally from both opposite sides (either from top and bottom, or from left and right). Probably a div by 2 missing. Just sayin :P

**Comment by gnunn1** [comment]
lol, with all the time spent on this background image feature I probably could have solved world hunger instead! Good thing it's been a fun feature to implement and it's been interesting learning more about Cairo.

Anyway, I'll have a look at this.

**Comment by egmontkob** [comment]
Not sure about you guys, but I like it a lot! Thanks! :)
