### ISSUE TITLE
open terminal from nemo to new session with running terminix

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#343]
Like, again, I have a terminix running in home directory and when open terminal on context menu of nemo, terminix create a new session in home directory too, not in directory from nemo. Sublime Text 3 has this issue too.
I'm using Ubuntu Gnome 16.04 gtk 3.18

**Comment by gnunn1** [comment]
Which version of Terminix are you using, the stable release or one built from Master?

**Comment by arshavindn** [comment]
@gnunn1 build from master

**Comment by gnunn1** [comment]
Thanks, I can reproduce.
