### ISSUE TITLE
where is the profile  stored in the filesystem?

### ISSUE THREAD

**Issue by bellcolt** [gnunn1/terminix#344]
Is it possible to use different profiles for each split window similar to gnome-terminal? Where can i find the profile in the system?

**Comment by gnunn1** [comment]
Yes it is, the drop-down button (the one with the menu and buttons to split the terminal) on each terminals title has a Profiles sub-menu that allows you to select the profile used for that terminal. 

Profiles are stored in dconf, you can create new profiles using the Preferences dialog accessible in the Application menu.

If this answers your question, please close the issue. If not, feel free to elaborate.

**Comment by bellcolt** [comment]
Running on Ubuntu 16.04.  Don't see the application menu.

**Comment by gnunn1** [comment]
See #241
