### ISSUE TITLE
Terminal size and custom fonts

### ISSUE THREAD

**Issue by Kami-no** [gnunn1/terminix#346]
Using custom font **Hack** new window does not exactly fit all rows (window a bit smaller than required to fit the last row or much bigger than last row requires)

**Comment by gnunn1** [comment]
I use Hack from time to time (font size 11) and haven't noticed any issue myself. What distribution and versions of GTK and VTE are you using?

**Comment by gnunn1** [comment]
A screenshot would be helpful too

**Comment by gnunn1** [comment]
@Kami-no Any update on the questions I asked?

**Comment by gnunn1** [comment]
No response from OP, closing.
