### ISSUE TITLE
error Terminix install

### ISSUE THREAD

**Issue by Carlos-Stgo** [gnunn1/terminix#348]
dub build
Building gtk-d:gtkd 3.3.1 configuration "library", build type debug.
Running dmd...
Building gtk-d:gtkdgl 3.3.1 configuration "library", build type debug.
Running dmd...
Building gtk-d:sv 3.3.1 configuration "library", build type debug.
Running dmd...
Building gtk-d:vte 3.3.1 configuration "library", build type debug.
Running dmd...
Building gtk-d:gstreamer 3.3.1 configuration "library", build type debug.
Running dmd...
Building terminix ~master configuration "default", build type debug.
Compiling using dmd...
source/app.d(7): Error: module logger is in file 'std/experimental/logger.d' which cannot be read
import path[0] = source/
import path[1] = ../.dub/packages/gtk-d-3.3.1/srcgl
import path[2] = ../.dub/packages/gtk-d-3.3.1/src
import path[3] = ../.dub/packages/gtk-d-3.3.1/srcsv
import path[4] = ../.dub/packages/gtk-d-3.3.1/srcvte
import path[5] = ../.dub/packages/gtk-d-3.3.1/srcgstreamer
import path[6] = /usr/include/dmd/phobos
import path[7] = /usr/include/dmd/druntime/import
FAIL .dub/build/default-debug-linux.posix-x86_64-dmd_2066-57246E6AC8154B898EDAD7F1D55A7806/ terminix executable
Error executing command build: dmd failed with exit code 1.

**Comment by gnunn1** [comment]
GDC is not supported for compiling terminix, you have to use DMD. See #229
