### ISSUE TITLE
Initialize application with NON_UNIQUE

### ISSUE THREAD

**Issue by Cybso** [gnunn1/terminix#349]
I suggest to initialize the GTK Application instance with ApplicationFlags.NON_UNIQUE:

```
--- a/source/gx/terminix/application.d
+++ b/source/gx/terminix/application.d
@@ -539,7 +539,7 @@ private:
 public:
 
     this() {
-        super(APPLICATION_ID, ApplicationFlags.HANDLES_COMMAND_LINE);
+        super(APPLICATION_ID, ApplicationFlags.HANDLES_COMMAND_LINE | ApplicationFlags.NON_UNIQUE);
         addOptions();
         
         this.addOnActivate(&onAppActivate);
```

This prevents GTK from starting all windows within the same process and allows:

- to test code changes on Terminix within Terminix
- to kill each process separatly

Additionally, if one process crashes other opened windows will keep alive.

The downside is that windows started in separate processes cannot be dragged into each other, so maybe this should become a command line switch. The problem is that onCommandLine() is called *after* initialization, so it would be required to pre-parse the command line within app.d to search for the switch.

**Comment by gnunn1** [comment]
It's a good idea as a command line parameter which is off my default, I'll add support for it.
