### ISSUE TITLE
Remove $ and # from the beginning of the code 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#35]
I would like to have a feature (can be enabled/disabled) to automatically remove the `$` and `#` from the beginning of the pasted code! :+1: 

Thanks

**Comment by gnunn1** [comment]
Can you elaborate on the use case for a bit, for example is this for when you have a file opened in one terminal with a bunch of commented out commands that you want to paste into another terminal one by one?

**Comment by bil-elmoussaoui** [comment]
Yeah, i use that a lot when i need to build a package and i just copy the code and pasted on the terminal,  a lot of websites uses `$` or `#` at the beginning of each line

**Comment by gnunn1** [comment]
Thanks, I'll add an option for this that is 'false' by default
