### ISSUE TITLE
"Synchronize Input" conflicts with input method

### ISSUE THREAD

**Issue by egmontkob** [gnunn1/terminix#351]
Enable "Synchronize Input" for several panes. Press Ctrl+Shift+U followed by a hex number and then a space. The given Unicode character appears only in the actual pane, not all the others. Other trickier input methods (e.g. "Japanese (Anthy) (IBus)") probably also have such issues.

Terminator suffers from the same bug: https://bugs.launchpad.net/terminator/+bug/1518089. The conclusion there was that we have no clue how to fix it :) It might need some work (and a new API) in VTE.

So I'm just keeping it here as a low-prio issue to ponder on.

**Comment by gnunn1** [comment]
i will have a look when I get a chance, I think that's a GTK feature, wonder if it emits an event for it.

**Comment by gnunn1** [comment]
Ignore that last commit, mis-typed the issue number, it's for #352

**Comment by gnunn1** [comment]
I've had a look at this in mire detail, it's definitely something the VTE would have to expose since it handles the input method itself internally. I've opened an issue for this against VTE:

https://bugzilla.gnome.org/show_bug.cgi?id=773034
