### ISSUE TITLE
Request Feature: Saving

### ISSUE THREAD

**Issue by irongomme** [gnunn1/terminix#353]
It could be great if we could : 
- Save all sessions in the same file
- Quick open recent saves, or auto-open on startup the chosen save

**Comment by gnunn1** [comment]
I doubt I'd add the auto-open on startup option, you can accomplish the same thing using the --session command line parameter.

While you can't save all sessions in the same file, you could accomplish the same thing by loading multiple sessions at once via the command line. Having said that, adding the ability to save and load sessions as a group wouldn't be hard to do. I'd likely just create a new file type for this that aggregates individual sessions into a single JSON file.

**Comment by irongomme** [comment]
Ok, i've just discovered the command line parameters and it let me open a default session on startup, wich is what i want to do.

And i could open several sessions on startup by the same way ... you're right !

Is there a way to call parameters on startup, because the command line needs a running terminal ... 

Thanks, this is a really great project !

**Comment by gnunn1** [comment]
You can always customize the terminix desktop file to add whatever startup parameters you want to it though you may need to set DBusActivatable to false in the desktop file to do so.

**Comment by dsboger** [comment]
Would it be possible to save and restore the full session, including the buffers and histories of every terminal? It would be nice to be able resume work exactly where I stopped. Just a random idea, though. Not sure it even makes sense.

**Comment by gnunn1** [comment]
@dsboger I'd love to be able to do it, but unfortunately I do not think this is at all possible. The VTE doesn't support any way to set the buffer, and the underlying shells all manage their histories differently with as far as I can tell no easy to set them in advance.

**Comment by gnunn1** [comment]
I'm going to close this, I just don't see the effort to create a single file with multiple sessions as being worthwhile with the existing ability to load multiple files simultaneously.

**Comment by martin-g** [comment]
See my solution at https://github.com/gnunn1/tilix/issues/99#issuecomment-318327720
