### ISSUE TITLE
[Typos] com.gexperts.Terminix.gschema.xml

### ISSUE THREAD

**Issue by glitsj16** [gnunn1/terminix#357]
Hi,

https://github.com/gnunn1/terminix/commit/14b642ffcaf5ce765b14dd84fc547234cf21f855 probably introduced incorrect wording in data/gsettings/com.gexperts.Terminix.gschema.xml, for the 'search-default-match-entire-word' key:
    \<summary>Whether to onwhenly match the entire word\</summary>

Assuming this should read:
    \<summary>Whether to match the entire word\</summary>

Going over the entire data/gsettings/com.gexperts.Terminix.gschema.xml file showed some additional typos/styling inconsistencies. The attached patch assumes all key descriptions end with a '.' while summaries do not. Just a FYI..

Attach trouble, here's a link: https://gist.github.com/glitsj16/a311a4014c617e2ede23bbade79393d1

**Comment by gnunn1** [comment]
Fixed, thanks.
