### ISSUE TITLE
Configure Weblate to update LINGUAS

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#359]
I've investigated a little and found this: https://docs.weblate.org/en/weblate-2.4/admin/config.html#post-add-scripts

Is it possible to configure Weblate so that new translations are automatically added to LINGUAS?

Thanks!

**Comment by gnunn1** [comment]
I had a quick look, because Terminix is using hosted weblate I don't think this capability is available, at least I can't see anywhere to configure it.

@phw any thoughts on this?

**Comment by phw** [comment]
Ii don't think we have that available in the board version. I use a script in a self hosted install of Weblate, and adding scripts requires you to add the script somewhere on the server and in the main weblate config.

**Comment by gnunn1** [comment]
@dsboger Would it be possible to update the extract-strings.sh to generate the LINGUAS file?

**Comment by dsboger** [comment]
@gnunn1 That's a good idea, only I think `extract-strings.sh` is not the best place for it. Maybe I can sneak that somewhere in the `make` or `make install`. I'll try to sketch that and do a PR.

**Comment by gnunn1** [comment]
Just keep in mind I don't use the autotools if you want me to be the one keeping this updated. :)

**Comment by dsboger** [comment]
I understand, but LINGUAS is currently only used by autotools anyway, so if autotools generates it by itself, then there is no need to keep it in the tree.

**Comment by dsboger** [comment]
Correcting what I stated above, `LINGUAS` is used by `msgfmt` in XML and desktop modes, like called in `install.sh`.

**Comment by gnunn1** [comment]
With the merged PR from #364 can this be closed?
