### ISSUE TITLE
drag'n drop x-color support to change terminal background

### ISSUE THREAD

**Issue by slaf66** [gnunn1/terminix#361]
Hi, it would be nice to add this behaviour to be in part with gnome-terminal :
the drop of a Gtk+ color swatch to change the background.

Informations for an implementation:

https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-screen.c#n356
https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-screen.c#n356

sorry not doing it myself but i really don't know much about the D language.
Thanks for your work.

**Comment by gnunn1** [comment]
Added, note the alpha component of the color is ignored. While I could adjust the opacity based on the alpha, in most cases this isn't desirable (i.e. dragging a solid color onto the terminal when you have transparency set where you like it).
