### ISSUE TITLE
Find issues

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#362]
It seems Find functionality has some issues. First, if there is more than one match of the search term in the same line, all except the first are skipped. Second, going to the previous match does not always work. 

I can reproduce the first issue consistently: just open Terminix, enter `$ ls -l`, look for "r" and click next. It only highlights one match per line.

Second issue is harder to reproduce. For now, what I could use to replicate the behavior is to open Terminix, `cd` to Terminix git working directory, enter `make distcheck`, look for "data", click next a few times, then click previous a few times. It does not always highlight the previous match getting "stuck" in some matches.

I checked and both official 1.0.0 (i.e. `terminix` AUR package) and latest git (i.e. `terminix-git` AUR package) have these same issues.

**Comment by gnunn1** [comment]
The first issue is because the underlying VTE widget doesn't support finding more then one match on a line, Gnome terminal has the same problem.

Can you try the second issue on Gnome terminal and see if it exhibits the same issue, make sure you are using the same search options as you would in Terminix.

**Comment by dsboger** [comment]
I just confirmed both issues are present in GNOME Terminal as well.

**Comment by gnunn1** [comment]
Thanks, I'll check if the second issue has been reported against g-t or vte and open a bug for it if not.

**Comment by dsboger** [comment]
You could add an "upstream" or "vte" tag. "wontfix" sounds strange in this case :).

**Comment by gnunn1** [comment]
Good point

**Comment by gnunn1** [comment]
Looks like a bug already exists for this upstream, closing issue:

https://bugzilla.gnome.org/show_bug.cgi?id=694128
