### ISSUE TITLE
different color for read only mode

### ISSUE THREAD

**Issue by onionjohn** [gnunn1/terminix#363]
would it be possible to implement possibility for changing colors for read only mode?

it would be great to change background color automatically when terminal switch to read only mode. i'm using terminix as a main terminal in my daily work and very often few sessions are in ro mode due to long term processes running. after a while it is hard to remember which one is protected.

**Comment by gnunn1** [comment]
Are you asking for this feature for when the read only flag is enabled or when you can't type something in because a process is running? I don't think I can do much about the latter.

**Comment by onionjohn** [comment]
i was thinking only about first case, when read only flag is enabled on terminal.

**Comment by egmontkob** [comment]
(Or maybe some icon on the title bar, similarly to the visual bell??)

**Comment by gnunn1** [comment]
Adds an icon to the titlebar when read-only is active as per the image below:

![screenshot from 2016-06-11 11-57-21](https://cloud.githubusercontent.com/assets/9358238/15986026/e5ee53ae-2fcb-11e6-8a21-9b1cb67f4631.png)
