### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by gleydson404** [gnunn1/terminix#366]
I've created some alias, and the alias that i've created, works fine in gnome-terminal, but its not working in terminix.

**Comment by gnunn1** [comment]
Where are you defining your aliases, .bashrc?

**Comment by gleydson404** [comment]
Yes @gnunn1.

**Comment by gnunn1** [comment]
I just tried it here by defining a simple alias in .bashrc and it worked fine for me. Is everything else defined in your .bashrc working?

What version of Terminix are you using and what distro and desktop environment (Gnome, Unity, etc)?

**Comment by gleydson404** [comment]
I'm on  gnome shell 3.20.2, under arch linux, and my terminix version is 1.0.0. 
my .bashrc file have just two lines with aliases. Somethig like:
alias foo='cd /home/foo'

**Comment by gnunn1** [comment]
I tried that alias, it worked fine for me. I was thinking maybe it's related to the login parameter so I tried enabling that and it's still working fine.

I'm stumped, anyone else having this issue?

**Comment by gleydson404** [comment]
I try in terminator and works fine too. The problem is just in terminix. :(

**Comment by gnunn1** [comment]
Can you try modifying the terminix desktop file and set DBusActivatable to false instead of true. That's one other major difference between terminix, g-t and terminator. You will need to restart gnome-shell after making this change or log out and in.

You can tell if you get it right by running ```ps -ef| grep terminix``` and checking that the switch ```--gapplication-service``` is not part of the process name.

**Comment by gleydson404** [comment]
Where could i finde terminix desktop file ? I've looking in /usr/share/applications/ but there is nothing like terminix.desktop.

**Comment by gnunn1** [comment]
It's there, try something like com.gexperts.Terminix.desktop

**Comment by gleydson404** [comment]
I find, and i did what you ask, set the DBusActivitable to false, and i reboot, and the problem still.

**Comment by egmontkob** [comment]
Probably stupid question, but still... are you sure Terminix is starting up a bash, rather than some other shell? Press Ctrl-X Ctrl-V to figure out.

**Comment by gleydson404** [comment]
@egmontkob 
GNU bash, version 4.3.42(1)-release (x86_64-unknown-linux-gnu)

**Comment by gnunn1** [comment]
I assume if you just create an alias manually in terminix it works fine after that? 

If I had to guess, It sounds like your .bashrc is not being sourced for some reason.  I assume the terminix process is owned by your user when you do a ```ps -ef```?

For the default profile in terminix, can you confirm that the option "Run command as a login shell" under the Command tab is NOT enabled.

**Comment by egmontkob** [comment]
Could it be that $HOME is not set properly?
    cat /proc/(terminix's pid)/environ | tr '\0' '\n' | grep HOME

**Comment by gleydson404** [comment]
if create a alias manually in terminix it works, but when i reboot the alias is gone.

**Comment by gleydson404** [comment]
@gnunn1  the option 'Run command as a login shell' is enabled.

**Comment by gleydson404** [comment]
And, when i run  'ps -ef| grep terminix'


gcs       2693     1  1 20:28 tty2     00:00:02 terminix
gcs       2741  2699  0 20:30 pts/0    00:00:00 grep terminix

**Comment by gleydson404** [comment]
'gcs' is my user.

**Comment by gleydson404** [comment]
@egmontkob i run cat /proc/(terminix's pid)/environ | tr '\0' '\n' | grep HOME and the home directory is correct.

**Comment by gnunn1** [comment]
Try disabling the login shell option and restart terminix, I don't believe .bashrc is sourced for login shells but works in many distros due to inclusion in profile.

Also, please confirm if you have this option set in gnome-terminal for the profile there.

**Comment by gleydson404** [comment]
I disable the login shell optioin and works. But when i open terminix there is message warning for enable login shell option.

**Comment by gleydson404** [comment]
And in gnome shell the login shell option is disable too.

**Comment by gnunn1** [comment]
The warning you can work around a different way then use a login shell. In my .bashrc, I have the following lines to fix the VTE configuration issue.

```
# Fix VTE Configuration Issue
. /etc/profile.d/vte.sh
```

**Comment by gleydson404** [comment]
Thanks @gnunn1  and @egmontkob. Closing the issue!

**Comment by egmontkob** [comment]
Note that on Ubuntu (and I guess Debian too) it's `/etc/profile.d/vte-2.91.sh`.

**Comment by gleydson404** [comment]
I'm under Arch linux.
