### ISSUE TITLE
tab bar transparent

### ISSUE THREAD

**Issue by giray** [gnunn1/terminix#367]
Hi ...

   Latest "master"  (version 1.1.0), the "tab bar" is now fully transparent.

![screenshot from 2016-06-03 08-56-36](https://cloud.githubusercontent.com/assets/316284/15771203/67d56fec-2969-11e6-943b-fed88596a56b.png)

**Comment by gnunn1** [comment]
Problem was some CSS that GTK 3.18 didn't like which worked fine in 3.20 and this was stopping the base CSS from being loaded. This CSS wasn't actually being used so I just commented it out.

**Comment by giray** [comment]
confirm fixed

**Comment by jonlandrum** [comment]
To chime in, if you're having this problem, try changing your desktop theme. I was using the xfce Raleigh theme, which had this transparency issue. After switching to a new theme, this is fixed.
