### ISSUE TITLE
ERROR: Missing key 'audible-bell'

### ISSUE THREAD

**Issue by seniorihor** [gnunn1/terminix#368]
I just upgraded `terminix` from master branch and got the following error after restart:

```
$ terminix

(terminix:2821): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Profile' does not contain a key named 'audible-bell'
zsh: trace trap (core dumped)  terminix
```

**Comment by gnunn1** [comment]
Did you rebuild the schema?

```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by seniorihor** [comment]
No.
Now I rebuilt the schema and I have the same error, when trying to launch terminal.

**Comment by gnunn1** [comment]
Sounds like you are running an old version of the binary, did you build the source using ```dub build --build=release``` with no errors? What happens if you run terminix from where it was built?

**Comment by seniorihor** [comment]
I guess, you're right about old binary version!
`dub build --build=release` was successful.
And if I run `./terminix` from my repository - it works.
Should I reboot then?

**Comment by gnunn1** [comment]
Up to you, closing issue

**Comment by seniorihor** [comment]
Anyway, after reboot I get the same error.

**Comment by gnunn1** [comment]
Did you run the install script as per the instructions, ```sudo ./install.sh```. Otherwise you have an old binary in your path somewhere

**Comment by seniorihor** [comment]
Yes, I did.
