### ISSUE TITLE
Do not add an icon to the dock Plank

### ISSUE THREAD

**Issue by gargullia** [gnunn1/terminix#369]

**Comment by gnunn1** [comment]
Can you elaborate on the issue, I'm not very familiar with plank.

**Comment by gargullia** [comment]
@gnunn1 The icon is displayed only when the application is running. Fixed a problem that `sudo chmod +x com.gexperts.Terminix.desktop`

**Comment by gargullia** [comment]
@gnunn1 this option also helped `Encoding=UTF-8+Version=1.0`
