### ISSUE TITLE
Create "Open in Terminix" plugin for Nautilus

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#37]
I'm a consistent user of the gnome-terminal nautilus plugin "Open in Terminal", need to create the equivalent feature for terminix somehow.

**Comment by bil-elmoussaoui** [comment]
This might be helpful : https://code.launchpad.net/~emilien-klein/nautilus-open-terminal/head

**Comment by alex285** [comment]
Also this can add a plugin on Gnome Software in Nautilus:
https://bugzilla.gnome.org/show_bug.cgi?id=760851

**Comment by gnunn1** [comment]
I have added an initial plugin, essentially a modified python plugin from the libnautilus-extension package. I'm sure it could use some improvement, if someone is a Python dev feel free to have at it but closing this for now.

**Comment by nunocastromartins** [comment]
I don't know if it is expected, but the "Open in Terminal" plugin would also create an entry to open with `gnome-terminal`, which I don't have installed. I'm now using [Nautilus-Actions](http://www.nautilus-actions.org/).

Example configuration (you can import it by creating a `.desktop` file):
```desktop
[Desktop Entry]
Type=Action
TargetToolbar=true
TargetLocation=true
Icon[en_GB]=terminix
Icon[en]=terminix
Icon[C]=terminix
Tooltip[en_GB]=Open in Terminix
Tooltip[en]=Open in Terminix
Tooltip[C]=Open in Terminix
ToolbarLabel[en_GB]=Open in Terminix
ToolbarLabel[en]=Open in Terminix
ToolbarLabel[C]=Open in Terminix
Name[en_GB]=Open in Terminix
Name[en]=Open in Terminix
Name[C]=Open in Terminix
Profiles=profile-zero;

[X-Action-Profile profile-zero]
Exec=terminix -w %f
Name[en_GB]=Default profile
Name[en]=Default profile
Name[C]=Default profile
```

**Comment by phw** [comment]
@nunocastromartins I am not sure I understand correctly. What exactly did you install? Terminix already comes with a Nautilus plugin, which will add a "Open in Terminix" action.

Gnome Terminal has its own Nautilus plugin.

**Comment by nunocastromartins** [comment]
You're right. My bad. Only needed `python2-nautilus` and not `nautilus-open-terminal`; ended up with two entries in the context menu because of that.
The Nautilus-Actions option is still viable, though - if one doesn't want to install `python2-nautilus`. In my case, since I'm already using Nautilus-Actions for something else, might as well not install an extra package. :-)

Again, my bad, I apologise for the noise.
