### ISSUE TITLE
Uncouple Nautilus extensions from the main program in Copr repo

### ISSUE THREAD

**Issue by mkalinski** [gnunn1/terminix#375]
I'm using Fedora and wanted to give this terminal emulator a try, but the fact that it tries to pull in Nautilus (and Nautilus's dependencies) is a deal breaker.

Would it be possible to provide desktop integration in a separate package? This would benefit people who want to use a GTK3 tiling terminal emulator, but not necessarily have GNOME desktop.

**Comment by gnunn1** [comment]
I don't do the packaging so it's not in my scope to fix. Your best bet is to get in touch with the package maintainer, for COPR there is a contact button on the COPR page.

**Comment by phw** [comment]
The package definitely should not depend on Nautilus and it could still provide the extension without depending on Nautilus.
