### ISSUE TITLE
Titlebar height

### ISSUE THREAD

**Issue by horosgrisa** [gnunn1/terminix#378]
Window titlebar height in [Terminix](https://github.com/gnunn1/terminix) is biggest than in other apps when I use [Numix](https://github.com/numixproject/numix-gtk-theme) theme
![2016-06-13 16-45-18](https://cloud.githubusercontent.com/assets/4980269/16009883/456869de-3187-11e6-9532-1cd3467af362.png)

**Comment by horosgrisa** [comment]
UPD: https://github.com/numixproject/numix-gtk-theme/issues/486

**Comment by gnunn1** [comment]
Might be a Numix bug since other themes such as Arc work fine, but I'll check it out when I get a chance.

**Comment by gnunn1** [comment]
This looks like a bug with Numix, both gedit and terminix have the same height headerbar on my system whereas Nautilus is narrower. Here's a screenshot I took with Terminix on the left, nautilus in the middle and gedit on the right.

![screenshot from 2016-06-13 19-43-28](https://cloud.githubusercontent.com/assets/9358238/16026849/5e62c62e-319f-11e6-9a8d-7b8a68b3cf1b.png)
