### ISSUE TITLE
Focus Follows Mouse

### ISSUE THREAD

**Issue by tobru** [gnunn1/terminix#38]
Is it possible to configure terminix to set focus on a terminal based on the mouse location? "Focus Follows Mouse" or in Terminator "Mouse focus: Follow mouse pointer"

**Comment by gnunn1** [comment]
This feature does not exist at the moment but it's a good idea, I'll see what I can do.

**Comment by tobru** [comment]
great! really looking forward to replace Terminator with Terminix =)

**Comment by tobru** [comment]
wohoo, that was faast! will test it as soon as a release is landed in AUR :+1:

**Comment by tobru** [comment]
Tested on Arch: It just works! Thanks a lot
