### ISSUE TITLE
Port Guake color themes

### ISSUE THREAD

**Issue by kurobeats** [gnunn1/terminix#380]
Request to port Guake color themes to Terminix. I tried scripting it up to convert all of the themes to json files, but I'm way out of my depth. Maybe someone else that sees this would be more capable.

Palettes:
https://raw.githubusercontent.com/Guake/guake/b2a27183d8285135ed178bdf098471c734e4e54d/src/guake/palettes.py

**Comment by storm119** [comment]
@kurobeats ...i'm almost done porting the colour scheme (120 +- themes ) but i need another day or two to publish. I'm also create 1 specific colour scheme for Terminix ..... ;)

**Comment by gnunn1** [comment]
@storm119 That's awesome but I'm not sure I want to include that many themes in terminix by default as it would be overwhelming to many users without significant UI changes. I wonder if it would be best to keep this in a separate repository that could be packaged as an extra feature or where people could pull the specific theme they are interested in. 

I would certainly be more then happy to include a link on the terminix front page to this repository.

Thoughts?

**Comment by storm119** [comment]
@gnunn1...well....yeah agreed...its really not necessary to include in terminix by default since its really huge....
 
Btw...I will setup another repo for anyone who interested they can just pick/download and manually apply the theme.

**Comment by storm119** [comment]
@gnunn1 ....small contribution for Terminix project here the link [Terminix-Themes](https://github.com/storm119/Terminix-Themes) tell me if i missed or need to add anything...?

@kurobeats  ....mate check the link

**Comment by gnunn1** [comment]
Thanks @storm119, I've updated the Terminix front page to include a link to your repo.
