### ISSUE TITLE
Feature Request: Copy on Select

### ISSUE THREAD

**Issue by mattwilmott** [gnunn1/terminix#381]
Similar to Terminator, is it possible to implement a copy to clipboard upon mouse selection?

Cheers
Matt

**Comment by gnunn1** [comment]
I'm kind of surprised I haven't done this yet, I'll look at adding an option for this over the next week or so.

**Comment by mattwilmott** [comment]
Thanks mate

Look forward to it and congrats on an awesome project 😀
