### ISSUE TITLE
prompt starts in home directory when split or create new session

### ISSUE THREAD

**Issue by arshavindn** [gnunn1/terminix#382]
Everything is fine before but with the latest pull from github, it doesn't. I also checkout back to origin/stable and built again, then it works.

**Comment by gnunn1** [comment]
I'm not seeing the issue here, I assume your VTE is configured correctly otherwise I wouldn't think stable would work but maybe double check it:

https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue

**Comment by arshavindn** [comment]
I checked vte configuration before I checkout back to origin/stable

**Comment by arshavindn** [comment]
still not work for me. Btw, I'm using Ubuntu Gnome 16.04 gnome-shell 3.20 and I have vte 2.91, it's `vte-2.91.sh` in `/etc/profile.d`

**Comment by gnunn1** [comment]
Ubuntu doesn't source the VTE script in profile.d unless you are using a login shell. You either need to enable a login shell for your profile or source it in .bashrc as per the VTE configuration page.

Can you confirm which of the above two methods you are using to get the VTE script sourced? I did test it under Ubuntu and fixed a number of bugs related to this issue and it was working for me however it's possible I missed something.

Thanks for your patience.

**Comment by arshavindn** [comment]
I did both of them but I sourced it in my .zshrc cause I use zsh. And how do I know that VTE script loaded or not?

**Comment by gnunn1** [comment]
```echo $PROMPT_COMMAND```

If the script is loaded, you should see something like:

```__vte_prompt_command```

If the echo just outputs a blank line then it is not loaded.

**Comment by gnunn1** [comment]
Sorry that's for bash, I'm not sure what zsh does but you can look at the vte script to see where it binds the prompt command function.

**Comment by arshavindn** [comment]
yes, I have just checked that bash prints that `_vte_prompt_command` and zsh does not

**Comment by gnunn1** [comment]
So I tested on Arch with ZSH and looks like the VTE script is not returning the hostname like BASH does which is causing terminix to treat the directory as if you had SSH'ed to a remote host. I've checked in a change which fixes it on my system, can you try it out please.

**Comment by arshavindn** [comment]
Thank you for your hard work. It totally solves the problem.
