### ISSUE TITLE
Add a symbolic application icon

### ISSUE THREAD

**Issue by sirblackheart** [gnunn1/terminix#384]
Terminix already deserves the name gnome-terminal rather then the outdated gnome-terminal. It feels much more like a part of the GNOME desktop environment. To strengthen this integration it would be nice if a `…-symbolic.png` application icon would be added so it could be used in gnome-shells app menu.

e.g. gnome terminals symbolic icon
![screenshot from 2016-07-05 23-28-31](https://cloud.githubusercontent.com/assets/1131371/16600629/52f32a70-4308-11e6-999a-e8a4bb3e73ab.png)

terminix currently used icon in gnome-shells app menu:
![screenshot from 2016-07-05 23-29-03](https://cloud.githubusercontent.com/assets/1131371/16600641/633771fc-4308-11e6-88aa-e4cff21cd9b6.png)

**Comment by gnunn1** [comment]
I'm not artistic so I can't do it, but if someone wants to create one I would be happy to incorporate it.

**Comment by sirblackheart** [comment]
Based on ther gnome-terminal symbolic icon, terminix application icon and terminix numix circle icon. Maybe a tad to detailed for this size?
![screenshot from 2016-07-09 13-30-30](https://cloud.githubusercontent.com/assets/1131371/16707735/7605b630-45d9-11e6-9a79-57f96efb5c61.png)

**Comment by gnunn1** [comment]
Ideally I think the symbolic icon should follow the main icon style, i.e. two terminals split down the middle.

**Comment by sirblackheart** [comment]
![screenshot from 2016-07-09 21-42-55](https://cloud.githubusercontent.com/assets/1131371/16709904/21b8bfba-461e-11e6-811b-d2f19d52b44a.png)

**Comment by sirblackheart** [comment]
slightly longer cursor
![screenshot from 2016-07-09 21-45-21](https://cloud.githubusercontent.com/assets/1131371/16709919/7d9da32c-461e-11e6-808c-fe6a735f9200.png)

**Comment by gnunn1** [comment]
That's fine by me, feel free to e-mail the icon to me at gerald dot b dot nunn at gmail dot com.
