### ISSUE TITLE
Zsh themes issue

### ISSUE THREAD

**Issue by mor0n** [gnunn1/terminix#385]
Arrows from zsh themes are noticeably moved related to other parts. It is visible e.g. on this screen:   https://camo.githubusercontent.com/6d5e88d80ccd7357a606d87727ada972b28cade4/687474703a2f2f7777772e67657870657274732e636f6d2f696d672f7465726d696e69782f7465726d696e6978322e706e67 (try in zoom). It's not zsh issue because in some other terminals these arrows are displayed correctly.

**Comment by gnunn1** [comment]
@mor0n Sorry I'm not understanding, what arrows are you referring to? That screenshot you posted is my screenshot, I don't see any obvious issues and that screenshot is using bash not zsh.

**Comment by dsboger** [comment]
Seems like a font rendering issue? Have you tried different fonts?

**Comment by Uzytkownik2** [comment]
After closer inspection I checked that it depends on the type of font. So fortunately it is not the fault of Terminix.

**Comment by mor0n** [comment]
After closer inspection I think it only depends on the type of font so fortunately it is rather not the fault of Terminix.

**Comment by gnunn1** [comment]
So can this be closed?

**Comment by mor0n** [comment]
Yes
