### ISSUE TITLE
Feature Request: Number of Matches using Find

### ISSUE THREAD

**Issue by mattwilmott** [gnunn1/terminix#388]
Can the number of matches and current match be displayed next to the find dialog?

Currently it is difficult to determine how many there are when the search continually circles back to the first match. This is particularly evident when searching output history in the 1000s of lines

Cheers
Matt

**Comment by gnunn1** [comment]
Unfortunately there's not much I can do about this as I'm just using the search APIs implemented by the underlying VTE Widget (https://developer.gnome.org/vte/0.40/VteTerminal.html). Changing this is dependent on the VTE developers addressing it, there are already a number of enhancements open in gnome bugzilla for this.

I'd have a look at doing this, but I'm already struggling with C code for the two simpler things I want to do.

**Comment by mattwilmott** [comment]
Understood thanks for the explanation 😀
