### ISSUE TITLE
Feature Request: Mouse Focus Mode

### ISSUE THREAD

**Issue by johannagnarsson** [gnunn1/terminix#397]
It would be awesome if Terminix would either follow Gnome's Mouse Focus Mode between terminals or would just have a dedicated setting (similar to Terminator) to enable Mouse Focus mode.

**Comment by gnunn1** [comment]
It does have this already, it's on the first tab of the Preferences dialog.

**Comment by johannagnarsson** [comment]
Wow, big fat nevermind... Thanks!
