### ISSUE TITLE
Custom hyperlinking

### ISSUE THREAD

**Issue by nafg** [gnunn1/terminix#398]
E.g. if my build tool outputs an error at `/home/user/dev/path/to/file.ext:333` I should be able to click it to open in my IDE. This could be configured as a set of pairs of regex + command. Any text that matches a regex could be hyperlinked and when you click it it would pass the text to the corresponding command.

**Comment by gnunn1** [comment]
@nafg I'm looking into this along with #404, could you elaborate what you mean by "a set of pairs of regex...". Wouldn't a single regex be sufficient for this?

**Comment by nafg** [comment]
Yeah but ideally I could have different kinds of links
For instance the current hyperlinking of URLs that start with a protocol
could become just one entry in this set, and you could change how it opens.
Maybe besides that and opening a file, there could regexes for stack
traces. IIRC if you look at the list of plugins for Terminator there are
some other custom types of handlers well. Another idea that just occurred
to me is that you could click a git hash and it would open it in gitk or
something. I'm sure the possibilities are endless.

Thanks for looking into it!

**Comment by gnunn1** [comment]
I have checked in a first version of this, note I have only done very basic testing and I'm sure there's still of things that need doing before it's ready for prime-time, however testing is welcomed.

Below is the UI that shows the regular expression and command I'm using to test your use case:

![screenshot from 2016-07-26 19-50-01](https://cloud.githubusercontent.com/assets/9358238/17159292/342f3404-536a-11e6-9741-a3f96192ae64.png)

The way it works, is that the variables $0, $1, $2, etc represent the regular expression match. $0 represents the whole match whereas $1 to $x represent sub-matches if you use groups. In the regex above, I have two groups, one for the filename and one for the line number.

Anyway, give it a go and let me know how it works for you.

**Comment by gnunn1** [comment]
Oh and just make copying and pasting easier, here's the regex from the screenshot:

```
(\/.*\.[\w]+):([0-9]*)
```

**Comment by gnunn1** [comment]
Anyone have a better name for this feature then Custom Links? Guake calls it Quick Open which I like better, I suck at coming up with the catchy names.

**Comment by gnunn1** [comment]
I added support for case insensitive regex, this is feature complete now from my perspective, closing issue.

**Comment by nafg** [comment]
Thanks! When will this be in a release?

**Comment by gnunn1** [comment]
It will be in the next one, probably in a month or two

**Comment by nafg** [comment]
Ok, built it locally. Works great, thanks!

P.S. The regex was too general so I changed to something like `(\S|\\ )+(:[0-9]+)?`
