### ISSUE TITLE
VTE Configuration Issue alert with ssh session

### ISSUE THREAD

**Issue by simonbcn** [gnunn1/terminix#400]
```
Arch Linux 64 bits
GNOME Shell 3.20.3
terminix-git (installed from AUR)
```

When I open a SSH session with Terminix (_no other Terminix instance open_), it shows the [_VTE Configuration Issue_](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue) alert.

**Comment by simonbcn** [comment]
I've compiled it now and it still shows the alert.

**Comment by gnunn1** [comment]
Might be the -x, I tested SSH after opening terminix to a local command prompt first. I'll have a look some more.

**Comment by gnunn1** [comment]
I cannot reproduce this using this command:

```terminix -x "ssh gnunn@sdf.org"```

I also tried it with a local Ubuntu VM and no warning. Is there any chance you are using zsh?

**Comment by simonbcn** [comment]
Yes, I forgot to say it. I use ZSH.

**Comment by gnunn1** [comment]
Fixed an issue with ZSH and modified the warning to only fire when running a shell and not a command. I tested with zsh and it worked fine for me, hopefully this fixes the issue for you.

**Comment by simonbcn** [comment]
It works now. Thanks.

**Comment by simonbcn** [comment]
Now the warning is showed when I open a normal terminal for first time.

**Comment by gnunn1** [comment]
I fixed a bug on zsh where it wasn't showing when it should, can you confirm that vte.sh is sourced on your system, either in .zshrc or via enabling a login shell in Terminix.

**Comment by simonbcn** [comment]
The default profile in Terminix is a login shell.

**Comment by gnunn1** [comment]
Thanks, unfortunately I cannot reproduce. When I switch my shell to zsh I get the VTE warning as expected. I then modify the default profile to enable the switch "Run command as a login shell", stop terminix, start again and no warning. I then disable "Run command as a login shell", re-start Terminix and I get the warning as expected.

Can you confirm the presence of the following file on your system:

```/etc/profile.d/vte.sh```

**Comment by simonbcn** [comment]
The warning is showed only when I open a terminix the first time in a Gnome session, the following times (_in the same session_) does not show the alert. Your test isn't valid if you have opened the 2 terminix instances in same Gnome session.

Yes, that file exists in my system. I'm going to test it adding `source /etc/profile.d/vte.sh` to my `.zshrc`.

**Comment by gnunn1** [comment]
When I tested it no other instances of Terminix were running. Just to be sure, i went through the same set of steps and it works as expected. I'm not sure what else I can try on my end to reproduce it.
