### ISSUE TITLE
Spurious notification when starting terminix

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#401]
Almost every time I start Terminix it will spawn a "Command completed" notification, although it just started and no command was executed. I've noticed that the notification is about the last command executed before I closed Terminix last time, even if that command did not spawn the notification when finished (i.e. because the terminal was visible at the time).

**Comment by gnunn1** [comment]
The way the notifications work is that they are tied to the PROMPT_COMMAND, so when you first open the terminal you will get an initial notification that is supposed to be ignored. In Terminix I tie it to a terminalInitialized state but I recently re-worked that code fairly heavily to handle automatic profile switching so it's possible something went sideways.

Having said that I'm not able to reproduce it here I'll do some digging to see if there is a better way to handle it.

**Comment by gnunn1** [comment]
@dsboger I've made a change to try to fix this, can you please test it when you get a chance.

**Comment by dsboger** [comment]
I've updated to latest commit and I'm yet to see the issue. Hopefully it's all good, so I'm closing this. Thanks again!
