### ISSUE TITLE
Support iterm2 style triggers

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#404]
Add support for iterm2 style triggers, of particular interest is the report host/user and directory to improve the automatic profile switching.

https://www.iterm2.com/documentation-triggers.html

**Comment by gnunn1** [comment]
Just a little more detail on this, the idea is to allow users to create regular expressions that are run against text outputted in the terminal. If the expression matches, then various actions can be triggered against it. 

Two that iterm2 supports that I'm particularly interested in is Report Directory and Report User/Host. Having this will add a lot of flexibility to the automatic profile switching and hopefully reduce the need to install the script on remote hosts which may not always be feasible.

I've checked in some initial test code that runs a regex against the terminal output to detect the user and host. In terms of performance, it doesn't seem to add significant overhead when cat'ing large files so that is promising. If it does causes issues in terms of performance, I would add a flag indicating how many lines back in the buffer should be tested.

Still very early days on this and it definitely won't make it into the next release.

**Comment by gnunn1** [comment]
This feature looks like it requires the scroll buffer to be set to unlimited in order to be completely reliable when cat'ing files or outputting blocks of text which is unfortunate. I tested with both a small terminix source file and a large file of 40,000 lines. Setting the buffer to something small like 512 means that by the time VTE reports a change via text-inserted or contents-changed the text is no longer available when calling getTextRange.

This is unfortunate but I don't think it necessarily eliminates implementing the feature, some explanation for users may be necessary though.

**Comment by gnunn1** [comment]
I've tested out the potential performance impact of this feature and it seems pretty reasonable on my machine. To test performance, I'm cat'ing a 2.5 MB test file with 40,000 lines of text. Scrollback in the VTE is set to unlimited so every line is analyzed. I'm testing with two regex, one that tries to parse the username/host out of a typical prompt and the other looks for the word 'importation' which occurs 17 times in the file.

When cat'ing this file with the trigger feature turned off, VTE finishes outputting the file in about 0.19 seconds on my machine. Turning the trigger feature on results in it needing 0.32 seconds on my machine. From a performance point of view there is obviously an impact, but it's not so egregious as to ruling out doing this feature.

With a default scrollback of 8192, cat'ing the file is about the same as the unlimited scrollback with the trigger feature turned off, about 0.18 to 0.19 seconds. With the trigger enabled, it takes about 0.28 seconds which is less then the unlimited scrollback since it has less text to find.

**Comment by gnunn1** [comment]
@egmontkob Before I start investing significant time in those feature, I wonder if I could get an opinion on whether there is anything I'm missing from a VTE point of view that makes this problematic.

**Comment by gnunn1** [comment]
Oh and I suppose I should give the tldr; version. In a nutshell the terminal scrollback needs to be set to infinite if you want completely accurate results when cat'ing large files but for normal usage where the text output by a command is smaller then the scrollback it seems to work fine enough. 

There is a performance impact, but it seems reasonable at least on my Macbook Pro laptop where cat'ing a large file with 40,000 lines normally takes 0.19 seconds but 0.32 seconds with the trigger in place, so about 70% slower which sounds like a lot but considering the size of the file and the default fast performance VTE provides not that bad.

**Comment by gnunn1** [comment]
I've checked in some more code for this and it's getting very close now but not ready for testing so please do not waste anytime doing so as I know I still have some things to work through.

**Comment by gnunn1** [comment]
OK I think this feature is ready to be tested as it seems to be working pretty well for me in my testing so far.

I've documented how this feature works in the wiki, please have a look at it first here to understand how this is properly configured:

https://github.com/gnunn1/terminix/wiki/Triggers

Note that automatic profile switching has been updated to leverage switching on username since with triggers the username can be extracted from the terminal, typically via the prompt. I have also updated it's wiki section to reflect this.

**Comment by gnunn1** [comment]
One potential localization issue I just thought of, some of the actions take variables in the parameters, i.e. username, hostname, etc. Should this be localized and if so how to make this discoverable because right now it's user entered so I never display the string anywhere. I could throw up a help dialog or something I guess, thoughts @phw?

**Comment by gnunn1** [comment]
One problem I just noticed is that when running a CLI like nano, VTE reports column/row positions for the program and then resets it when it exits. I've checked in a hack fix for this that resets the count if the row the VTE reports is less then the last row terminix recorded, however ideally terminix should detect this and stop running triggers in this scenario.

I'll need to give this more thought.

**Comment by gnunn1** [comment]
@egmontkob I assume I'm seeing this behaviour because apps like nano, top, etc use the alternate screen, is there any way to detect when alternate screen is engaged and dis-engaged from the app using VTE? I don't see anything obvious looking at the docs.

**Comment by egmontkob** [comment]
> is there any way to detect when alternate screen is engaged

Nope I don't think so. (I don't have too much time nowadays but I'm planning to get back to this issue and investigate more thoroughly.)

**Comment by gnunn1** [comment]
@egmontkob Thanks Egmont for the quick reply, I've opened the issue below in VTE to request a feature to enable the enclosing application to be able to detect when entering and existing alternate screen mode. 

https://bugzilla.gnome.org/show_bug.cgi?id=769926

So far, the only way I can see to make this work is to get the process name associated with the current PID and check it against a list of well-known programs that use alternate screen mode. Otherwise, I'm probably going to have to revert this feature by hiding it behind a build flag.

**Comment by gnunn1** [comment]
So I tested out the feasibility of creating a list of processes to exclude trigger processing for and it seems to work very well. Even when I su to root and then run nano I can easily get the pid and map it to a process name in /proc/{pid}/status.

In my current test code this is hard-code, however I'll create a configuration setting for it which will consist of an array of process names to ignore. For a default setting, I have the following process names which I know use the alternate buffer or should likely be excluded, I'd welcome suggestions to add to the list though. I'm a developer not an administrator so I'm not quite the command line junkie some folks are (ironic I know):

nano
top
v
emacs
mc

**Comment by egmontkob** [comment]
less
screen/tmux
htop - interestingly top doesn't switch to alternate screen
joe
mc/mcview/mcedit (but not when executing an external command)
pico/pine/alpine
mutt
lynx/links/elinks/w3m
irssi and friends
alsamixer
calcurse
ranger
moon-buggy and other games (e.g. tetris clones)
and sure a whole lot more...

Maybe (weird idea) you could run ldd against the binary and see if it's linked to ncurses.

Of course this is a terrible hack (and doesn't work across ssh), it shouldn't be necessary given a proper API which requires some VTE work.

**Comment by gnunn1** [comment]
Thanks @egmontkob, I wasn't thinking about SSH with regards to using the processes as a way to exclude apps and you are right that this won't work in that scenario.

I'm going to revert this feature, it's disappointing considering how well it works but it's my own fault for not doing enough testing before I embarked on it. The code will remain in Terminix, just hidden by a build flag, so if VTE gets updated at some point to include this screen change event or even for broader support of triggers I can leverage it.

**Comment by gnunn1** [comment]
I've checked in code to turn off trigger support since there doesn't seem to be a way to get working well without patching a new event into VTE. Note that if someone wants to play with it at some point it can be re-enabled via the ENABLE_TRIGGERS flag in constants.d.

**Comment by gnunn1** [comment]
So I've brought trigger support back again but it requires a patch to the VTE which I've placed in experimental/vte, without this it will appear disabled to users. Applying this patch to the VTE results in a new signal being available which enables terminix to detect the change from normal to alternate screen and back again. 

I've re-factored the terminix code a bit to support detectinc these optional features that require a customized VTE version since it likely will expand beyond just supporting the fedora notification patch. As a another example, I expect to use the same process when I get around to adding support for badges which will require a similar patch in the VTE to make work.

I've tested the patch with the Arch AUR vte3-notification package and it builds fine in parallel with the existing notification patches. Please note that this patch and feature is considered experimental, I  absolutely do not recommend that packagers include it in stable packages at this time, if ever. 

I'm going to actively test it over the next week or so to make sure it is stable before sending it upstream in the previously linked bug report. However based on the comments I suspect upstream may not be interested in adopting this patch as it is too low level, they would likely prefer an implementation of the matching feature in VTE rather then leaving it to the application. I completely agree with this position but don't have the time or skills to implement it myself at this time. 

Despite that, providing this patch is still a good first step as it provides a testing ground to find out where the gotchas and issues are likely to be. I already see some issues with the Send Text action that I'll need to think about how to handle.
