### ISSUE TITLE
[Autotools] Can't build without $DC set to a path

### ISSUE THREAD

**Issue by Tinche** [gnunn1/terminix#405]
While trying to build terminix using autotools (actually, playing around trying to fit it into a snap, this is one of the steps), I've found I can't actually get it to build unless I have the env var `DC` set to the exact path of dmd. Just having dmd in the path (like mentioned on the wiki page) isn't enough.

`make` fails because the Makefile contains this snippet:

```
CYGPATH_W = echo
DC = 
DCFLAGS = -O
```
(the DC isn't set.) 

There is a related error while running `configure`:

```
checking where the gettext function comes from... libc
basename: missing operand
Try 'basename --help' for more information.
checking for DEPS... yes
```
(again, because $DC doesn't get set.)

This is on Ubuntu 16.04. If I set $DC to "/usr/bin/dmd" the build works. If I set it to just "dmd" or erase it, no dice.

**Comment by dsboger** [comment]
Looks like I made a mistake in `configure.ac`. The line that reads: `AC_PATH_PROG([DC], [ldmd dmd gdmd])` should be `AC_PATH_PROGS([DC], [ldmd dmd gdmd])` (notice the missing `S` in `PROGS`). I'll make a quick PR, but until it is merged you can workaround the issue fixing `configure.ac` and restarting the build from `autogen.sh` onwards. Thanks for reporting!

**Comment by Tinche** [comment]
Thanks for looking into this so quickly. :)
