### ISSUE TITLE
Change the name of this software, maybe?

### ISSUE THREAD

**Issue by yookoala** [gnunn1/terminix#41]
If you [search Terminix on Google](https://www.google.com/search?q=terminix), you'd most certainly find a whole page of result about "Your Strongest Defense Against Pests & Termites" (I am not including a link here. Don't want to further push their SEO rank). It is hard to search discussion and resource. And it is not a common term like "[Terminator](http://gnometerminator.blogspot.hk/p/introduction.html)".

I think it is better to rename this project to either:

1. something less confusing (no collision); or
2. easier to remember (common term)?

What do you think?

**Comment by alex285** [comment]
+1 (just because I find it not good enough)

**Comment by gnunn1** [comment]
I'm OK with a name change but it would need to be something awesome to make it worth the effort and I don't have any better ideas myself, I used up all of my limited creativity on Terminix. So if folks have suggestions, post them here and we'll see if anything interesting pops up.

**Comment by mjjzf** [comment]
If it is indeed terminal, how about "Final"?

**Comment by gnunn1** [comment]
"Final" is a nice though but a variant of that was already used for [FinalTerm](https://github.com/p-e-w/finalterm) and there would be too much confusion between the two even though FinalTerm is no longer actively being developed.

**Comment by bmeznarsic** [comment]
Mosaic

**Comment by gnunn1** [comment]
I like Mosaic, what do others think?

**Comment by jpraczyk** [comment]
https://en.wikipedia.org/wiki/Mosaic_(web_browser)

**Comment by bmeznarsic** [comment]
Last release 	3.0 / 1997; 19 years ago
Deprecated/dead...

**Comment by Tribex** [comment]
Determined?
InTerm?

...

Termite? (Yeah, okay, maybe not.)

**Comment by alex285** [comment]
Why not something not that "nerd"?
Apricot? Cocoa? Snickers? Gimme? Crunchie? Light Term? All Star?
Okay from what I said (and I stopping say more), I only like Light Term :)

**Comment by mjjzf** [comment]
If it is CLI to the max, it would be climax. But I expect it to lose in Google discovery to... other similarly named sites.
You could go elsewhere with CLI, like CLIck or CLIent - Click Terminal would probably work.
Traditionally, the teletype work with columns, so maybe Colonnade? That would at least be unusual enough to actually get some SEO juice, but maybe they would think it was a reference to Pantheon...

**Comment by tengwar** [comment]
Tilapia? Therm? Ceramic? Terracotta? Porcelain? Rects? (Make a KDE version called REKT :P) A name alluding to tessellation, mosaics or rectangles?

**Comment by Tribex** [comment]
Terracotta sounds nice to me. But Tilapia?

**Comment by mjjzf** [comment]
Therm? The hot new version - the Therminal!

**Comment by gnunn1** [comment]
I was actually thinking Thermite at one point, but it's a bit too close to Termite which another terminal is using for it's name. It would be nice to have a name that is unique for SEO purposes where someone could just google the name alone and this is what comes up. I guess there's a reason why car companies pay big books for consultants to name new car models...

Sorry but I'm not a fan of TermBook Alex, sounds like a laptop :)

Of the ones suggested so far, Mosaic is still my favourite. I think we are safe from name collision on the Mosaic browser :)

**Comment by phw** [comment]
For Mosaic this one comes in mind: http://mozaik.rocks/

But it has a distinct spelling and is a completely different product, so probably save to use Mosaic anyway

**Comment by mjjzf** [comment]
Maybe overly traditionalist: Uplink?

**Comment by topcatzero** [comment]
Dome-terminal? Like gnome-terminal, written in D.

**Comment by gnunn1** [comment]
Not really feeling Dome-terminal, but it got me thinking about DTerm or dTerm maybe, similar to iTerm in concept. Unfortunately that name is taken: http://decimus.net/dterm

Feel the same way about UpLink, interesting idea but not grabbing me. Mosaic is still my fave.

**Comment by Tribex** [comment]
I think perhaps too many people still are familiar with what Mosaic is/was. It would be hard to take over a name that has such a legacy behind it.

**Comment by archusr** [comment]
* wellplaid
* [tessellate](https://en.wiktionary.org/wiki/tessellate)

**Comment by edubxb** [comment]
My 5 cents...

How about DeltaTerm/ Δterm?

Delta for the Greek letter (https://en.wikipedia.org/wiki/Delta_%28letter%29)

**Comment by jpraczyk** [comment]
@edubxb I like that idea.

**Comment by bmeznarsic** [comment]
Ditto, maybe?

**Comment by dsboger** [comment]
What about "Splitterm"?

**Comment by m110s** [comment]
TerminD
"term in D" and also "ter mind", so we can spell /ˈtermaɪnd/ .

**Comment by eldelacajita** [comment]
**Terminatrix**? Keeps something from the current name, gets the badass part from Terminator.

But I like better the ones playing with the "tile" concept: **Tessellate** or **Mosaic** which is the best so far for me.

Also "dividing" could work as a concept. **Divide** could be a name itself, or you could call it **Thiessen** or **Voronoi** in honour of the scientists who studied a particular (and very cool-looking) way of dividing euclidean space.

**Comment by yookoala** [comment]
I think the major consideration of the naming are:

1. Easy to remember. Nouns of real world objects (e.g. apple, fox, bird) are easier to visualize and memorize. They are also better for emotional attachments.

2. Highlight some of major features / quality of the software.

Some of the name I thought of:

**Determinal** - It is written in D (De-) and one of the killer feature is it can **de**tach and re-attach terminal windows. Hence the De + terminal. Also this word has not been used at all.

**Ninjaterm** - The split, detach, re-attach thing just sounds like ninja things to me :-)

Besides, I like **Mosaic** very much. It is both visualize and easier to remember. It's also naturally highlighting the window tiling.

**Comment by frnogueira** [comment]
- DarkScreen

- DarkSide

- TermSide

- BlackWorld

- Blackout

;)

**Comment by davidosomething** [comment]
"invited", since it is an "**In**stance of **VTE**  in **D**" or however you want to mix the anagram around

**Comment by gnunn1** [comment]
I've opened a poll on Google+, feel free to note and let's see if we can get a consensus:

https://plus.google.com/+GeraldNunn/posts/D9snacQ8wjs

**Comment by bil-elmoussaoui** [comment]
What about Terminus?  :+1:

**Comment by gnunn1** [comment]
Terminus is a good name, but too late to add a new option too the poll. At this point it looks like I'll be sticking with Terminix and closing this issue. At some point, you just have to move on :)

**Comment by gnunn1** [comment]
Poll seems to be pretty much in favour of sticking with Terminix, so status quo for now and I'm closing this issue. Thanks everyone for the suggestions.
