### ISSUE TITLE
Synchronize input doesn't work with middle-click paste

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#410]
Need to look at handling the addOnPasteClipboard in the VTE and move the synchronization code from the paste action handler to this event. Note this event doesn't pass the string that was pasted, so will need to read it off the clipboard.

**Comment by gnunn1** [comment]
Ended up just extending @alexwhitman patch to override the middle button and do the paste directly. This enables the unsafe paste warning to work as expected as well.

**Comment by alexwhitman** [comment]
This doesn't quite fix it as it pastes from the wrong clipboard.  Now both Ctrl+Shift+V and middle click paste the same thing.

**Comment by gnunn1** [comment]
My bad, I'll revert the commit when I get back from lunch and look into this some more.

**Comment by gnunn1** [comment]
I've reverted the commit

**Comment by gnunn1** [comment]
@alexwhitman Hopefully this does the trick, try it out and let me know.

**Comment by alexwhitman** [comment]
That's working for me. :+1:

**Comment by gnunn1** [comment]
Thanks!
