### ISSUE TITLE
Remove border around search bar

### ISSUE THREAD

**Issue by brunelli** [gnunn1/terminix#414]
I was annoyed by that border around the search bar and opened GtkInspector to try to remove it:

![captura de tela de 2016-07-13 13-25-15](https://cloud.githubusercontent.com/assets/5755892/17074214/700faad0-504f-11e6-955f-83ee3006f850.png)

IMO it looks better without it, but just a suggestion.

Also, maybe add a close button at the end of the search bar?

**Comment by gnunn1** [comment]
The problem is when the title bar is active it looks like a big wall of grey without the border. I'll have a look though at toggling it depending on whether the title bar is active.

No plans for a close button on the search bar, again it looks ugly when the title bar is active to have the two close buttons stacked IMHO.

**Comment by brunelli** [comment]
Maybe setting only a 1px top border?

![captura de tela de 2016-07-26 15-09-32](https://cloud.githubusercontent.com/assets/5755892/17150111/909f5a0a-5344-11e6-8848-94fb030d319a.png)
![captura de tela de 2016-07-26 15-16-34](https://cloud.githubusercontent.com/assets/5755892/17150112/90bafd46-5344-11e6-97ca-021a187b168c.png)

**Comment by gnunn1** [comment]
@brunelli Have a look at it now and see what you think.

**Comment by storm119** [comment]
@gnunn1 ...the new commit (css) as below introduce another glitch imo (see screenshot attached before vs after commit). The white horizontal line....

`.terminix-search-frame { 
    border-top: 1px solid @unfocused_borders;
}`

Before the commit
![terminix-old](https://cloud.githubusercontent.com/assets/10151062/17181685/8a00b90e-5453-11e6-8770-2c4a98b54aa0.png)

After the commit...ugly white horizontal line 
![terminix-new](https://cloud.githubusercontent.com/assets/10151062/17181692/91ac44a2-5453-11e6-91a3-8069a1c366e6.png)

Ps- hmmm....after close inspection its something to do with my current system theme. Other themes look just fine with "border-top"....oh well i need to adjust the css and define the colour myself

**Comment by gnunn1** [comment]
@storm119 It's hard to tell from the screenshot because it is so dark, but is your theme not styling the GTKPane separator for some reason? What GTK theme are you using?

**Comment by storm119** [comment]
I'm using [diehard4](https://cinnamon-spices.linuxmint.com/themes/view/540) but slightly modified by me....i think you're correct about the GTKPane separator but never got chance to look at the theme yet...will do some other time.
 
for the time being....this suit me very well (tested with arc, vertex, mintdark etc)...

`.terminix-search-frame {
    border-top: 1px solid rgba(32, 32, 32, 1);
}
`
Thank you....
