### ISSUE TITLE
No "open terminix here"

### ISSUE THREAD

**Issue by cortopy** [gnunn1/terminix#416]
Despite having installed python-nautilus I don't see the "open terminix here". I'm not sure if it's a bug or something I'm missing

GNOME version: 3.20.3
DIstro: Fedora 24

**Comment by gnunn1** [comment]
Is there any output when you load nautilus from the command line, i.e.

```
nautilus -q
nautilus
```

Note the -q shuts down the current instance of nautilus and might take a few seconds.

**Comment by cortopy** [comment]
`nautilus -q` returns the following 

```bash
(nautilus:5773): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:5773): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
```

**Comment by gnunn1** [comment]
I'm not too worried about the ```nautilus -q``` output, I'm more interested in what was shown after running ```nautilus```?

**Comment by gnunn1** [comment]
Also, a couple more things:

* How did you install Terminix, from COPR?

* What is the output of this command:

```
 ls /usr/share/nautilus-python/extensions/
```
Do you see the file open-terminix.py?

**Comment by cortopy** [comment]
@gnunn1 thanks for answering so quickly!

Yes, I installed Terminix using COPR repo. I installed `nautilus-python` from the main fedora repo.

`/usr/share/nautilus-python/extensions/` is empty

`nautilus` output:

```bash
(nautilus:8720): Gtk-WARNING **: Theme parsing error: <broken file>:1:0: Failed to import: The resource at '/org/gnome/libgd/tagged-entry/default.css' does not exist
```

**Comment by cortopy** [comment]
Just seeing the `nautilus-python` is empty of plugins made me try removing Terminix and installing again in case I installed them in the wrong order. The plugins folder is still empty

**Comment by gnunn1** [comment]
I'd suggest dropping a line to the COPR maintainer, I remember there was a complaint about bundling the nautilus plugin in with terminix because it dragged in nautilus via dependencies. I'm assuming he is still installing the plugin but maybe it's been dropped completely?

You could also try copying the plugin file from here into ```/usr/share/nautilus-python/extensions/``` manually to see if that gets it coding. The plugin file is available here:

https://github.com/gnunn1/terminix/tree/master/data/nautilus

**Comment by gnunn1** [comment]
Have you managed to resolve this, may I close this issue?

**Comment by cortopy** [comment]
Yes, the plugin you posted is now working beautifully. Thank you for that @gnunn1 !

Obviously the issue is with the Copr repo package, not with terminix. Do you know whether the maintainers are on github so that I can tag them here?

**Comment by gnunn1** [comment]
See issue #375 for more information on the removal of the Nautilus extension from the COPR package.

@HeikoAdams is the COPR maintainer.

**Comment by HeikoAdams** [comment]
The nautilus extension has been moved to a seperate package called terminix-nautilus.

**Comment by cortopy** [comment]
Thanks @HeikoAdams !!!
