### ISSUE TITLE
Commandline option for using existing terminix windows

### ISSUE THREAD

**Issue by mherwig** [gnunn1/terminix#419]
I'm working on a oh-my-zsh plugin for loading terminix sessions automatically when the session's json file is found in the current dir. My idea was to to call terminix -s mysesssionfile.json but this actually opens a new window. Is there any way to use the existing terminix window for this command?

**Comment by gnunn1** [comment]
If you go to the Preferences dialog in terminix, there is an option called "On new instance". Change this from "New Window" to "New Session", then when you call ```terminix -s mysession.json``` it will be loaded into the current window as a new session.

Let me know if that meets your requirements, if not I'm happy to discuss other options.

**Comment by mherwig** [comment]
Thank you. This is exactly what I needed. Obviously I missed that option, sorry!
