### ISSUE TITLE
terminix maximize option

### ISSUE THREAD

**Issue by Cherkah** [gnunn1/terminix#420]
more a question than an issue,

can we get an option so as to open terminx in maximiz mod?
 if not, what is the command should i've use to setup terminix in maximize mod?

thx and great job

**Comment by gnunn1** [comment]
There is no option for this in the GUI preferencens, however if you run ```terminix --help``` there are command line options to do this:

```
...
  --maximize                            Maximize the terminal window
  --full-screen                         Full-screen the terminal window
```

**Comment by Cherkah** [comment]
ok thanks

when i appends --maximize command in desktop's shortcut (/usr/share/applications/com.gexperts.Terminix.desktop)
the window opens in normal mod! whats wrong?

**Comment by gnunn1** [comment]
I think it's because it uses DBus to launch the application from the desktop file, in the desktop file change DBusActivatable=true to DBusActivatable=false and see if it starts working as expected.

**Comment by Cherkah** [comment]
> change DBusActivatable=true to DBusActivatable=false

nothing change...

**Comment by gnunn1** [comment]
If this in gnome, you need to restart gnome-shell or logout/login after making that change. For other DE I would also suggest logging out and in again as most will cache the desktop files.

**Comment by gnunn1** [comment]
I just tested it locally, works fine for me.

**Comment by gnunn1** [comment]
Has this been answered, can I close this issue?

**Comment by Cherkah** [comment]
sorry, was focus on other things...

ok, you was right.
thank.
