### ISSUE TITLE
Feature Request : Insert terminal number

### ISSUE THREAD

**Issue by davromaniak** [gnunn1/terminix#421]
Hi.

I just discovered this project, and I find it quite interesting.

By the way, I use terminator, and there a grouping feature called "Insert terminal number", which the action is quite obvious.

Do you think it can be added in terminix ?

Thanks.

**Comment by gnunn1** [comment]
Can you elaborate on the use case, I'm not seeing how it would be useful considering the terminal number isn't constant, for example terminals get re-numbered when you delete one.

**Comment by gnunn1** [comment]
Ok I googled and see the use case, essentially to insert the terminal number when using synchronised input. So if you have four hosts to SSH to, test01, test02, etc you can have the last digit inserted.

I'll look into adding it, should be relatively straightforward.

**Comment by gnunn1** [comment]
I've added a new action for this, Insert Number, that does this. No shortcut is assigned to it by default so you'll need to assign one in Preferences | Shortcuts to use it.
