### ISSUE TITLE
VTE configuration issue -- permission denied vte.sh

### ISSUE THREAD

**Issue by dressedfez** [gnunn1/terminix#424]
On Fedora 24 I get the following error, when I follow the [guide](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue):
![terminix-1-2-0-fedora-24](https://cloud.githubusercontent.com/assets/5203474/17303464/1d16dedc-5821-11e6-9853-778d64a1294d.png)

vte.sh has the following permissions rw-r--r--.

.I get terminix from: heikoada-terminix --  Copr repo for terminix owned by heikoada 

Does the guide need some update here? The terminal seems to work without problems.

**Comment by gnunn1** [comment]
I'm not at my PC to double check, but shouldn't vte.sh have execute permissions?

**Comment by dressedfez** [comment]
I agree that this makes a lot of sense. I haven't changed the distribution settings, hence I assume that this is a bug in F24. I will cross-check this with folks there.

**Comment by gnunn1** [comment]
So on my machine vte.sh does not have execute permissions either. If I run it with the following, as per the instructions, it works fine:

```
. /etc/profile.d/vte.sh
```

However if I run it without the preceding [dot][space] I get the same permission issue.

**Comment by gnunn1** [comment]
Note this is expected behavior, as the [dot][space] simply runs the commands in vte.sh within the current shell hence why only read permissions are needed.

**Comment by egmontkob** [comment]
You definitely do need that [dot][space], without that you just launch a new shell, make some settings there and then quit that shell, that is, you've effectively changed nothing. As such, there's absolutely no point in adding exec permissons.

**Comment by dressedfez** [comment]
I would suggest to update the guide to using

source /etc/profile.d/vte.sh

The whole problem was apparently just caused by me not seeing the dot in front of the path. I have done so in my .zshrc.

**Comment by gnunn1** [comment]
I've updated the page to use source.

**Comment by egmontkob** [comment]
Note: "." is the old-fashioned sh-compatible version. "source" is a bash/zsh extension.

**Comment by dressedfez** [comment]
**Note:** I have exchanged an email with Matthias Clasen and he says that in principle all files in that directory should not be executable and are meant to be "sourced". In Fedora some still are executable, but this is  not correct.
