### ISSUE TITLE
VTE warning triggered when loading session from file

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#425]
When I open terminix with a saved session the VTE configuration issue is shown even though the profile used is set to act as a login shell. This seems to only happen if I have more than one terminal configured in the session file.

See the files at https://gist.github.com/phw/4b4975281555ed6b7d62703a0a7373e9

Opening the `file-terminix-test-vte-warning.json` file with `terminix -s file-terminix-test-vte-warning.json` will show the VTE warning, doing the same for `terminix-test-ok.json` will work. Both use the same profile, and the profile is set to act as a login shell.

Tested against stable 1.2.0 and latest git master.

**Comment by gnunn1** [comment]
This actually happened with any command line parameter, not sure why bit it triggers the VTE contents-changed signal twice even though the contents haven't changed.

**Comment by phw** [comment]
@gnunn1 That's not solved for me even with this commit, still same behavior.

**Comment by gnunn1** [comment]
@phw at line 764 in terminal.d you will see the following code commented out:

```
            /*
            trace("Contents changed:");
            trace("\tdirectory.length=" ~ to!string(gst.currentLocalDirectory.length));
            trace("\toverrideCommand.length=" ~ to!string(overrideCommand.length));
            trace("\tterminalInitialized " ~ to!string(terminalInitialized));
            trace("\ttestVTEConfig " ~ to!string(terminix.testVTEConfig()));
            */
```

Can you remove the /* and */ at the start and end of the block respectively to make the code active and re-compile terminix. Run terminix loading the session so you get the warning and then paste the output here.

Also, can you paste the .json file for the saved session here as well in case it's related to that for some reason.

**Comment by phw** [comment]
I will try to tun it with trace output as soon as I find the time, but might be after the weekend.

But I have already posted the session files , see the gist link above. Loading the session with multiple terminals triggers the VTE warning, the one with only one terminal works as expected.

**Comment by gnunn1** [comment]
@phw Thanks I missed that, too much going on today. Don't worry about running with tracing right now, I suspect I will be able to reproduce it from your session file and if not will then ask you to trace.

**Comment by gnunn1** [comment]
I've tied your file on my machine and it doesn't generate the warning. The bug I fixed was that the VTE warning came up anytime you used a command line parameter, even something like --maximize.

When you get a chance, try un-commenting those lines and post the results but no rush.

**Comment by klingtnet** [comment]
I get the same warning, so I can confirm the issue.

**Comment by gnunn1** [comment]
@klingtnet If you are building from master, please uncomment the lines I posted above, rebuild, and paste the output here after duplicating the issue.

**Comment by klingtnet** [comment]
I've installed `dmd` and `dub` but I can't build the package because `build/build` requires `xdg-app` and `xdg-app-builder` which were provided by the `xdg-app` package that was replaced with `flatpak` in AUR.

**Comment by gnunn1** [comment]
@klingtnet Ignore the build folder, it's only for building a flatpak and can be ignored. If you follow the instructions on the front page under Building all you need to do is run:

```
dub build
sudo ./install.sh
```

**Comment by klingtnet** [comment]
@gnunn1 This fixed the warning dialog.
To be sure I've double checked against `1.2.0` by reinstalling it from AUR.

**PS**: Thank you for developing such a great tool, I :heart: terminix and installed it on all my machines!

**Comment by phw** [comment]
I am not entirely sure, but the issue was still happening, so I did the `git pull && dub build && sudo ./install` dance again and now the warning is gone. Problem is I'm pretty sure that I did this previously with your fix already in master.

Anyway, I close this until this happens again :)
