### ISSUE TITLE
"New terminal" desktop action does nothing on Gnome

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#427]
If you right click on the Terminix icon in Gnome 3 dash you see the entry for "New terminal" as defined in the .desktop file. Clicking it does nothing. There is also a "New window" entry, which works as expected (and which Gnome adds because Terminix responds to the `new-window` action).

I have two issues with this:
1. "New terminal" does not work, at least not on Gnome 3
2. The entry looks redundant to the "New window" action

Not sure whether this works in other desktop environments.

**Comment by phw** [comment]
Ok, looked into it a bit more. The action name is actually send by dbus to the existing terminix instance, so it should be set to something terminix understands. So for example you could do something like this in the desktop file:

```
[Desktop Entry]
...
Actions=new-window;

[Desktop Action new-window]
Name=New Terminal
Exec=terminix
```

The `Exec=` is still required as a fallback if dbus is not used. See also https://developer.gnome.org/desktop-entry-spec/#extra-actions

I am still not quite sure how the "New terminal" action should be different from the existing "New window" action. But if it gets implemented it maybe should be different and there should both be a `new-terminal` action the app responds to and a way to trigger that same behavior from the command line (e.g. `terminix --new-terminal`).

If this is the only way to show such an action for other desktop environments maybe we need separate desktop files for Gnome and non-Gnome to avoid the duplication of the same action in Gnome.

**Comment by gnunn1** [comment]
Thanks, I should have paid more attention to this when the PR was submitted. I'm thinking we should change New Terminal to New Session if that makes sense to you, New Terminal is not very meaningful in a tiling terminal emulator context.

Also, it should be possible to make the Exec in these sections work the same as the actions simply by add the -a switch to the Exec but I'll need to test it, i.e:

```
Exec=terminix -a app-new-window
```

**Comment by phw** [comment]
I agree on having "new-session" here. That is also the second important action currently placed in the app menu.

Also `Exec=terminix -a app-new-session` seems to work as it should :)

**Comment by phw** [comment]
What's bad about the "new-session" action is that it works via command line even if no instance is running yet, but when called via DBUS it looks like it only works if there is an open window already. If not the action will do nothing.

I tested with this desktop.in file:
```
[Desktop Entry]
Version=1.0
Name=Terminix
Comment=A tiling terminal for Gnome
Exec=terminix
Terminal=false
Type=Application
StartupNotify=true
Categories=System;TerminalEmulator;X-GNOME-Utilities;
Icon=com.gexperts.Terminix
DBusActivatable=true
Actions=new-session;

[Desktop Action new-session]
Name=New Session
Exec=terminix --action=app-new-session
```

**Comment by gnunn1** [comment]
Thanks for looking into this, I'll have a look at fixing the Dbus issue with new-session tonite if it's not too complicated then update the desktop file accordingly.
