### ISSUE TITLE
Big icons on title bar.

### ISSUE THREAD

**Issue by ovovchuk** [gnunn1/terminix#428]
Hello,

I have strange issue with header icons on OpenSuse Leap 42.1, they are a little bit larger than should be.
Could you please advise how this issue can be fixed.

Thank you,
Oleksandr

![terminix_osuse_icons_bug](https://cloud.githubusercontent.com/assets/5849382/17380552/5c880734-59d0-11e6-8149-861eb5206cf9.png)

**Comment by gnunn1** [comment]
What theme are you using and do you have the same issue with Adwaita?

**Comment by ovovchuk** [comment]
It is Arc theme, with Adwaita they are big too.

![terminix_suse_issue_2](https://cloud.githubusercontent.com/assets/5849382/17380765/603159de-59d1-11e6-95e1-3ccaa0f62b9a.png)

**Comment by feskyde** [comment]
What icon theme are you using?

**Comment by ovovchuk** [comment]
I am using Arc icon theme as well, tried Adwaita, Moka and others but header icons still the same.

**Comment by gnunn1** [comment]
I'm not sure what the issue is, the big icons are custom ones included with Terminix. What version of GTK are you using?

**Comment by ovovchuk** [comment]
3.16.7

**Comment by gnunn1** [comment]
Unfortunately I don't have a VM handy with 3.16 to check what the issue is, it'll take me a day or two before I have time to do so. Any chance you are using the window scaling feature in the tweak tool, i.e. for a HIDPI display?

**Comment by ovovchuk** [comment]
Nope, window scaling is 1. I have checked OpenSUSE Tumbleweed which is using GTK 3.20.6 and Ubuntu 16.04 with  GTK 3.18.9 and icons have normal size there.

Also in GTK 3.16 with older version of Terminix(1.0.0) icons in popup menu are bigger too.

![terminix_issue_2](https://cloud.githubusercontent.com/assets/5849382/17395329/8d7631e8-5a36-11e6-8201-726677adf8de.png)

**Comment by gnunn1** [comment]
Personally I suspect this is a bug in GTK 3.16, I'd suggest trying a different app that uses custom SVG icons but off the top of my head nothing comes to mind.

**Comment by gnunn1** [comment]
I asked about this on the gtk+ IRC channel, the corebird author had the same issue and pointed me to this:

https://github.com/baedert/corebird/issues/451

The fix Corebird went with is represented by this commit:

https://github.com/baedert/corebird/commit/84a11623e24ac3bd58a86847b7262d373005eb53
