### ISSUE TITLE
Cinnamon Desktop - unable to resize window

### ISSUE THREAD

**Issue by khandpur-ualberta** [gnunn1/terminix#429]
Howdy.
Great project, now my default terminal.

One strange behaviour though. Upgraded to Fedora 24 and I use Cinnamon desktop (don't have any other DEs on any of my machines). Not sure if it's the same with Gnome, but WinKey+Left (or Right) Arrow moves the open window to take up half of the screen. With Terminix only, when I do this, I can't then resize (i.e. half the screen plus a little more). Used to work properly with Fed 23/Terminix 0.9 release..

Not having the same issue with any other GUI application, seems to be Terminix only that's showing this kind of behaviour.

Little more mouse clicky-clicky on my part thus not the end of the world, but don't know if that's something you could look into.

Still, awesome project, bravo!

Cheers,
vk

**Comment by gnunn1** [comment]
Hopefully I'm understanding this correctly, on Gnome once you click Win+Left/Right Arrow and it's bound to the side of the screen you cannot resize it with the mouse, I see the same behavior with Gedit on my system which uses Gnome DE.

**Comment by gnunn1** [comment]
You can see this question as well, looks like the answer is you can't:

https://www.reddit.com/r/gnome/comments/3vhjy9/how_do_i_resize_window_after_snapping_it_to_the/

There's also an open bug for this on Gnome:

https://bugzilla.gnome.org/show_bug.cgi?id=645153

What are the other applications you are testing with, anything that is gnome native (i.e. not patched/maintained by Cinnamon)?

**Comment by khandpur-ualberta** [comment]
Oh yeah? Huh. Would you look at that...
I'm not using pure Gnome apps (Firefox, virt-manager .. yaddah yaddah, all work the way I explained before), but yup, look at that, gedit, same thing. 

[er .. now that I think of it, I may have been using a competing shell tool ... hasta la vista, baby]

My mistake, go ahead and close. Thanks for getting back to me so quickly!

**Comment by gnunn1** [comment]
Anytime, glad you are enjoying Terminix.
