### ISSUE TITLE
Installer errors

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#430]
Since 417dc23fbaa8eedb146d6cafea8b4f808a6bb5a2 has been merged I'm now getting installer errors.

Firstly it was
```
Creating PNG symbolic resource icons
./install.sh: 37: ./install.sh: gtk-encode-symbolic-svg: not found
./install.sh: 38: ./install.sh: gtk-encode-symbolic-svg: not found
./install.sh: 39: ./install.sh: gtk-encode-symbolic-svg: not found
./install.sh: 40: ./install.sh: gtk-encode-symbolic-svg: not found
Building and copy resources...
terminix.gresource.xml: Failed to locate 'icons/16x16/actions/terminix-add-horizontal-symbolic.symbolic.png' in current directory.
```
which was solved by installing `gtk-3-examples` on Ubuntu.
After that the error I'm getting now is
```
Creating PNG symbolic resource icons
Can't save file icons/16x16/actions/terminix-add-horizontal-symbolic.symbolic.png: Error opening file '/home/alex/projects/github/terminix/data/resources/icons/16x16/actions/terminix-add-horizontal-symbolic.symbolic.png': No such file or directory
Can't save file icons/16x16/actions/terminix-add-vertical-symbolic.symbolic.png: Error opening file '/home/alex/projects/github/terminix/data/resources/icons/16x16/actions/terminix-add-vertical-symbolic.symbolic.png': No such file or directory
Can't save file icons/32x32/actions/terminix-add-horizontal-symbolic.symbolic.png: Error opening file '/home/alex/projects/github/terminix/data/resources/icons/32x32/actions/terminix-add-horizontal-symbolic.symbolic.png': No such file or directory
Can't save file icons/32x32/actions/terminix-add-vertical-symbolic.symbolic.png: Error opening file '/home/alex/projects/github/terminix/data/resources/icons/32x32/actions/terminix-add-vertical-symbolic.symbolic.png': No such file or directory
Building and copy resources...
terminix.gresource.xml: Failed to locate 'icons/16x16/actions/terminix-add-horizontal-symbolic.symbolic.png' in current directory.
```

**Comment by gnunn1** [comment]
I'm not a big fan of having generated artifacts in source control but in this case I think I'll make an exception and simply checkin the symbolic png icons. Forcing people to install the examples package to build terminix doesn't seem like a good idea?

Thoughts from @alexwhitman and @phw?

**Comment by gnunn1** [comment]
It's interesting that in arch, gtk-encode-symbolic-svg is included in the GTK package, seems weird that Ubuntu/Debian puts it in gtk-3-examples...

```
/usr/bin/gtk-encode-symbolic-svg is owned by gtk3 3.20.8-1
```

**Comment by gnunn1** [comment]
I've checked in the icons plus added a new script in data/resources that generates the symbolic icons if needed, hopefully this corrects the issue.

**Comment by phw** [comment]
Yes, better solution in this case if gtk-encode-symbolic-svg is not easily available. I am not surprised that it is not in the standard package on Debian/Ubuntu but on Arch. Arch in general just packages the software as is (including all headers and development tools), while Debian / Ubuntu prefers to only install what is necessary for normal usage and split everything else out into separate packages. But I am a bit surprised it is in the gtk-3-examples package and not some kind of -dev package.

**Comment by gnunn1** [comment]
Thanks @phw, I too was also surprised it was not in a dev package of some sort.
