### ISSUE TITLE
Inconsistent working directory in new windows / splits

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#432]
I think there is a bug or a strange behaviour how terminix handles working directory.

When I open a new terminix window, cd to /foo, I expect a new split to have the same working directory. That fails to work if I open another window and do `cd /bar`, then go back to the previous window and open a new split, which opens with `/bar` as a working dir.

Working directory should be local to a window or a session. Ideally, I would like an option to preserve working directory when a new tab/session/window is created.

**Comment by gnunn1** [comment]
Thanks for reporting this, I can reproduce and that's definitely a bug as it should be using the directory of the currently focused window. I'll have a look at fixing this tonite after work.

**Comment by belozer** [comment]
But it's not working :(

![image](https://cloud.githubusercontent.com/assets/1655916/24750208/bb72442a-1ace-11e7-81bf-c1bc38d9ea48.png)

tilix 1.5.4

**Comment by phw** [comment]
@belozer Have you configured https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue ?

**Comment by belozer** [comment]
@phw Thanks! After add in .zshrc
```
if [[ $TILIX_ID ]]; then
        source /etc/profile.d/vte.sh
fi
```
this is works! :)
