### ISSUE TITLE
to-pixbuf warning with installer on Ubuntu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#434]
Running the installer shows
```
terminix.gresource.xml: to-pixbuf preprocessing requested but GDK_PIXBUF_PIXDATA not set and gdk-pixbuf-pixdata not found in path.
```
`libgdk-pixbuf2.0-dev` installs `gdk-pixbuf-pixdata`.  Not sure if you want to add that as a dependency on Debian/Ubuntu.  Nothing seems obviously broken when running terminix after that warning is shown.

**Comment by gnunn1** [comment]
I agree that if packagers are building from source this needs to be reflected in the dependencies. I'll update the package thread about this and include it in the Readme file.

**Comment by gnunn1** [comment]
Added to build dependencies on front page.
