### ISSUE TITLE
VTE Configuration Missing on Ubuntu

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#435]
Hi, I would like to use Terminix on Ubuntu, I read this [wiki](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue) but the ``/etc/profile.d/vte.sh`` is missing on Ubuntu. How I solve that?

**Comment by gnunn1** [comment]
On Ubuntu it is ```vte-2.91.sh```

**Comment by leoheck** [comment]
Oh, thank you. Why not to improve the wiki with that?

**Comment by gnunn1** [comment]
Go right ahead, anyone should be able to edit the wiki

**Comment by leoheck** [comment]
Good, thank you.
