### ISSUE TITLE
Issue on pasting a command

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#439]
When I paste a command with ``sudo``, terminix shows a dialog window saying: 

``This command is asking for Administrative access to your computer``. 

If I click ``Paste Anyway``, **it should paste the already copied the command**. Instead, it is doing nothing and cleaning the paste buffer. So I have to copy the command again.

**Comment by gnunn1** [comment]
Seems to be working OK for me so it might be something to do with the specific command. Can you post a screenshot of the paste dialog so I can see what it is showing for the command?

**Comment by leoheck** [comment]
Also, with this ``Paste dialog window opened`` I can open a new terminal, but I can't use it. It remains blocked!

**Comment by leoheck** [comment]
Sure, it happens with any command with ``sudo``: 

```
sudo my_unknown_command
sudo apt get update
```

![selection_005](https://cloud.githubusercontent.com/assets/1277920/17518054/a6af24fa-5e1c-11e6-82fc-3f441619c7cf.png)


![selection_006](https://cloud.githubusercontent.com/assets/1277920/17518047/9c13f76e-5e1c-11e6-9ce4-869da3db42b9.png)

**Comment by leoheck** [comment]
Using 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by leoheck** [comment]
It annoys the fact that it clean my copy buffer. So I have to copy again.

**Comment by leoheck** [comment]
I think I did solve the problem. As you can see, the ``Paste Anyway`` is red indicating the default action. If I click ``Enter`` it uses the ``Don't Paste`` instead. The default action is different than the one marked red. 

Also, If I hit ``Esc``, the dialog is dismissed and the command is pasted. ``Esc`` should escape this action... meaning: please, do nothing.

**Comment by gnunn1** [comment]
Thanks, good catch. I'll take care of this in the next day or two, just trying to finish up a first iteration of trigger support first.

**Comment by leoheck** [comment]
Good, take your time! :)

**Comment by sdouche** [comment]
Hi,
I've the same issue on Ubuntu 16.04. The `Paste anyway` doesn't work and clean the buffer. I need to do the same action twice to paste my commamd.
![selection_099](https://cloud.githubusercontent.com/assets/170176/19278213/bce24f94-8fdc-11e6-91ca-fcc8af60e047.png)
