### ISSUE TITLE
Add an option to maximize terminal

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#44]
Sometimes when you are focused on a single terminal it would be nice to maximize it for more space and then when finished that particular task return it to normal. Note that the notifications system would need to take into account this new start so that notifications get shown for the hidden "minimized" terminals.

**Comment by luisdavim** [comment]
That would be awesome +1.

**Comment by edubxb** [comment]
:+1: for it!

**Comment by alex285** [comment]
+1

**Comment by gnunn1** [comment]
Almost there, just have to iron out DND with a maximized terminal. Note that splitting a maximized terminal is disabled and will remain that way.
