### ISSUE TITLE
JSON-based configuration next to dconf

### ISSUE THREAD

**Issue by arcticicestudio** [gnunn1/terminix#440]
It would be awesome if there would be a way to set all preferences/configurations via a `.json` file (e.g. `$HOME/.terminixrc` or `$HOME/.terminix/config`) to make it trackable via git for a `dotfiles` repository. I think `dconf` is just terrible when it comes to reusability of user settings.
The only way is to write a non-dynamical script with "hardcoded" values or to export the scheme.

The themes are handled via JSON too (which is a major advantage [compared to the GNOME terminal](https://github.com/chriskempson/base16-gnome-terminal/blob/master/base16-tomorrow.dark.sh)), so I don't think there should be a limitation for all other preferences.

This feature should be implemented with priority in mind:
  - Check if a JSON-based configuration exists (e.g. `$HOME/.terminixrc` or `$HOME/.terminix/config`)
  - If no JSON-based configuration is available either create one with default value AND/OR load the dconf preferences

**Comment by gnunn1** [comment]
Thanks for the suggestion but unfortunately I don't this is very feasible. Terminix is using GSettings all over the place and it provides a lot of features that I'm not interested in coding myself. While technically GSettings supports alternative back-ends, such as a key file, in practice I don't see it being used very often and I'm not interested in dealing with any issues that arise from that for what to me is a pretty minor improvement.
