### ISSUE TITLE
Add support for password manager

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#443]
Extracting this feature from #86 and closing that one to split these out into individual feature requests.

When considering this, I would strongly prefer using the system password manager if at all possible, i.e. gnome-keyring (https://wiki.gnome.org/action/show/Projects/GnomeKeyring?action=show&redirect=GnomeKeyring). However I don't want to couple terminix with a specific implementation if at all possible, need to do some research to figure out if there is a common abstraction layer for this, i.e. what do apps like Chrome and Firefox do?

Also, if I can get this going, look at creating a support trigger for it similar what iTerm2 does.

**Comment by gnunn1** [comment]
Doesn't look like a common abstraction layer exists at the moment, so likely will just go with gnome keyring for now:

https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/

**Comment by edubxb** [comment]
Gnome Keyring seems a good choose.

**Comment by freongrr** [comment]
Isn't the SSH key store good enough for most use cases?

Maybe you could have a 2-step wizard that invokes `ssh-keygen` and `ssh-copy-id` (like seahorse, the gnome-keyring UI, does).

**Comment by gnunn1** [comment]
@freongrr I'm might be missing something here, but this is intended for passwords not ssh keys. For example, if you ssh to a box and have to supply a password, this comes into play. It would work the same for other scenarios like command line ftp. 

SSH keys would continue to be handled via the normal ssh mechanisms and would be out of scope for this functionality.

If this doesn't make sense let me know, I'm not an ardent ssh'er so it is very possible I'm missing something.

**Comment by gnunn1** [comment]
So I'm getting close to having this working, hopefully will have a functional version ready tomorrow night. However one question, besides the name are there any useful attributes to describe the password I should include?

AFAIK iterm2 is just a simple Name field to describe the password and I'll probably just do the same unless there is a compelling reason not to.

**Comment by gnunn1** [comment]
I've checked in a first iteration of this feature, to access it use the new insert-password shortcut. The password manager interfaces with gnome-keyring via libsecret, if libsecret is not available an error message should display when activating the feature so I would consider libsecret an optional dependency at this point.

Note that implementing this code involved more interfacing with C then I usually do so I wouldn't be surprised if I have a few crash bugs/memory leaks here and there. If anyone notices anything while testing just open new bug reports and I'll address them as they come in.
