### ISSUE TITLE
Terminal IDs

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#446]
I saw terminal has IDs which are displayed in window title. I would like to ask if it is possible to have IDs for splits too and if I can use it like environment variables (e.g. TERM_ID). This will be nice to have when we have multiples synchronized splits. In this way, we can make a single command-line that has different behavior depending on terminal-split we are.

**Comment by gnunn1** [comment]
I don't think it is possible for me to inject environment variables. However, when you have synchronized input turned on you can generate an environment yourself like:

```
export TERM_ID={Hit shortcut for insert terminal ID action}
```

Each terminal will then insert the ID assigned to it. Note that terminal IDs can change as terminals are deleted so you may need to re-execute this in those cases. 

If this answers the question, please close the issue but if not just let me know and we can discuss further.

**Comment by leoheck** [comment]
No, this doesn't answer my question.

Suppose you have a script (bash for example) like:

```bash
case TERM_ID in
  1)
    # do_something_in_term_1 
    HOST=x.x.x.x
    ;;
  2)
    # do_something_in_term_2
    HOST=z.z.z.z
     ;;
esac

ssh user@$HOST
```

I can have a script to execute different commands in each tile (a terminal split). So it would be easy to run a single command in multiples synchronized tiles. In this way, the user could have an opportunity to customize the execution in each tile from a single command.

**Comment by gnunn1** [comment]
I must not be seeing it, if you follow the instructions I gave each terminal will get a unique TERM_ID, so terminal 1 will be TERM_ID=1, terminal 2 will be TERM_ID=2, etc. You can then run your script and it will handle the case statement accordingly. 

Note the shortcut "Insert terminal number" is relatively new and doesn't have a shortcut assigned to it by default. You can do that in Preferences | Shortcuts to make it useable.

If this doesn't do the trick I'm not sure what I'm missing?

**Comment by leoheck** [comment]
Ah, ok! I understand it now. Yeah, this can work I am expecting.
