### ISSUE TITLE
Reduce logging noise

### ISSUE THREAD

**Issue by vpavic** [gnunn1/terminix#447]
First and foremost - thanks for this great terminal app, keep up the good work! :+1:

I'm using Terminix on Ubuntu Xenial via WebUpd8 PPA.

By default, logging is too noisy and ends up polluting the `syslog` quite a bit. I haven't found an option to configure this.

Here's a sample:

```
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.772:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focus4bec3635-17bf-4967-820c-d9b4668016f9
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.775:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus 4bec3635-17bf-4967-820c-d9b4668016f9
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.949:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focus4bec3635-17bf-4967-820c-d9b4668016f9
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.950:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus 4bec3635-17bf-4967-820c-d9b4668016f9
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.956:session.d:focusDirection:1176 Focusing down
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.957:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focus4bec3635-17bf-4967-820c-d9b4668016f9
Aug 17 10:05:55 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:55.957:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus 3cc9d3e6-6b77-466d-8f7a-bed216a48f25
Aug 17 10:05:56 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:56.324:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focus3cc9d3e6-6b77-466d-8f7a-bed216a48f25
Aug 17 10:05:56 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:56.326:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus 3cc9d3e6-6b77-466d-8f7a-bed216a48f25
Aug 17 10:05:56 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:56.336:session.d:focusDirection:1176 Focusing left
Aug 17 10:05:56 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:56.337:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focus3cc9d3e6-6b77-466d-8f7a-bed216a48f25
Aug 17 10:05:56 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:05:56.337:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus e1faf51c-711c-4cb4-b76d-0a5f40f2d501
Aug 17 10:06:05 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:06:05.196:terminal.d:onTerminalWidgetFocusOut:1241 Terminal lost focuse1faf51c-711c-4cb4-b76d-0a5f40f2d501
Aug 17 10:06:05 vpavic-nb com.gexperts.Terminix[5527]: 2016-08-17T10:06:05.196:terminal.d:onTerminalWidgetFocusIn:1225 Terminal gained focus 4bec3635-17bf-4967-820c-d9b4668016f9
```

This feels like a trace log which I'd expect in development/debugging use but certainly not enabled by default.

**Comment by phw** [comment]
Looks like the PPA packag is not build in release but in debug mode. @hotice is maintaining the package and should be able to fix this easily by adding `DCFLAGS='-release'` to the make command.

**Comment by hotice** [comment]
It means the Debian package does the same, since I used the official packaging. I'm on it, I'll update the PPA soon.

**Comment by hotice** [comment]
I just built it in a test PPA and the syslog pollution doesn't stop. Any ideas?

**Comment by phw** [comment]
Strange. I have so far only built terminix with dub, where `dub build --build=release` ill do a proper release build which indeed disables the trace messages. I just saw the `-release' switch for ldmd2 and thought it should do the same.

Are you sure you are running the updated PPA build? If you had an existing terminix instance open it would not load the new code, so make sure all terminix instances are closed before opening a new terminal after updating.

**Comment by hotice** [comment]
I looked `configure.ac` and found `-version=StdLoggerDisableTrace`. Using both `-release` and `-version=StdLoggerDisableTrace` solves this.

**Comment by hotice** [comment]
Done, PPA updated.

**Comment by vpavic** [comment]
Updated - I can confirm that excessive logging is now gone. Thanks for the quick fix @hotice!
