### ISSUE TITLE
Scroll session by mouse wheel

### ISSUE THREAD

**Issue by AlexWayfer** [gnunn1/terminix#448]
Hello!
Can you enable scrolling sessions by mouse-wheel scroll on "View session sidebar" button?

**Comment by gnunn1** [comment]
So to be clear, you mean holding the mouse over the session button in the headerbar and using the mouse wheel to scroll through sessions? If I've gotten that right I'm not in favour of this, seems pointless versus just using keyboard shortcuts or am I missing something?

**Comment by AlexWayfer** [comment]
> So to be clear, you mean holding the mouse over the session button in the headerbar and using the mouse wheel to scroll through sessions?

Yeah.

> seems pointless versus just using keyboard shortcuts or am I missing something?

Keyboard shortcuts are cool, but sometimes your hands only on mouse, and one scroll instead of click-move-click can be more convenient. For example, scroll on tab-bar in Chromium for tab-switch, or scroll on dash/desktop of Desktop Environments (GNOME, for example) for workspace-switch.

**Comment by gnunn1** [comment]
Closed via PR from @alexwhitman which implements this.
