### ISSUE TITLE
App-Menu icon for CSD

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#45]
Some desktops don't use appMenu, (including Gnome Shell classic, or disable from Tweak) so an app-menu icon should be visible on top-left on the application

**Comment by gnunn1** [comment]
It seems to be working fine for me, what am I missing here?

![screenshot from 2016-01-21 20-37-48](https://cloud.githubusercontent.com/assets/9358238/12500187/e09d227a-c07e-11e5-98ed-c5a04a5eaf16.png)

**Comment by alex285** [comment]
@gnunn1 Please give me some time to build it and recheck. It wasn't working two days ago, and I realized Terminix had options later.

**Comment by alex285** [comment]
Right it works, but it brings the generic icon to me, with Adwaita icon set. 

![Uploading terminix-appicon.png…]()

**Comment by gnunn1** [comment]
Weird, for me it uses the application icon which is defined as utilities-terminal in the terminix desktop file. Is the desktop file properly installed on your system, you may need it for this, as well notifications depend on it too due to the way GTK notifications work.

**Comment by alex285** [comment]
Yeah, thats it:

[Desktop Entry]
Name=Terminix
Comment=A tiling terminal for Gnome
Exec=terminix
Terminal=false
Type=Application
StartupNotify=true
Categories=Utilities
Icon=utilities-terminal

W8 I ll try this on Arch, because I have it on Rawhide now, although I cant see how this is related with Gnome 319.x

**Comment by alex285** [comment]
I dont get whats going on, it works everywhere than Rawhide. I close it, and may reopen it on Gnome 320 bugs if not fixed.
