### ISSUE TITLE
Automatic notifications after a task has finished

### ISSUE THREAD

**Issue by itoshkov** [gnunn1/terminix#450]
elementary OS terminal has a very nice feature: it automatically notifies you when a long-running task has finished, if the tab that started it (or the whole terminal) is not on focused at the moment. It would be very good addition to terminix IMO.

This is similar to manually adding `; alert` to the command but is cleverer, because it's not spamming notifications when you actually are watching the terminal. Plus, it is automatic.

Here is a video, which demonstrates the feature: https://www.youtube.com/watch?v=WLhTmnifAro

**Comment by phw** [comment]
I am not sure, but it sounds like this is exactly what Terminix' current notification implementation does, just that Terminix requires a patched VTE for this to work.

See the section on notifications in the [FAQ](https://github.com/gnunn1/terminix/wiki/FAQ) (at the very end)

**Comment by itoshkov** [comment]
Yes, it sounds pretty similar. But I was unable to make it work on Ubuntu 16.04. I created the symlink and I'm sourcing the file. (And I checked the "Run command as a login shell" box.) 

The script seems to have loaded correctly, because I can see the directories are correctly updated when I change them. Also I checked that `echo $PROMPT_COMMAND` prints `__vte_prompt_command`. But I still don't get a notification.

BTW, how long is "long running process"? I tried with up to 1 minute...

**Comment by gnunn1** [comment]
As @phw pointed out, you need a patched VTE to make this work which Ubuntu does not include and without the patched VTE notifications will not work. It would be nice if the Fedora patch would get upstreamed at some point unfortunately it seems stuck at the moment.

**Comment by itoshkov** [comment]
OK, thank you. I thought that I just need to add the things described in the FAQ page.
