### ISSUE TITLE
Quick session opener/switcher

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#454]
Incoming feature suggestion...

Sublime Text has a [quick open panel](http://docs.sublimetext.info/en/latest/file_management/file_management.html#goto-anything) which performs a fuzzy search on files.

I think something similar for Terminix which searches for saved session files could be useful so that I could hit a hotkey, type something like 'web prod' (which would be in the name of a previously saved session file) and have the session open.

**Comment by gnunn1** [comment]
Interesting but might be tricky to implement. For one, you'd likely one to have a preference of where to search for these files so you are not searching the entire home directory. The other issue wouldn't you'd have to actually read the file to determine if it's a terminix json file or some other json file?

**Comment by alexwhitman** [comment]
The way Sublime Text does it is to store a list of paths to project files that it knows about. This list could be updated when a session file is opened or saved. Essentially it would be like a recent files list, but one which is fuzzy searchable.

**Comment by alexwhitman** [comment]
This is something along the lines of how I think it could work:
```diff
diff --git a/source/gx/terminix/appwindow.d b/source/gx/terminix/appwindow.d
index 3952dcf..5a4cb33 100644
--- a/source/gx/terminix/appwindow.d
+++ b/source/gx/terminix/appwindow.d
@@ -141,6 +141,8 @@ private:
     // Track size changes, only invalidate if size really changed
     int lastWidth, lastHeight;
 
+    string[] recentSessionFiles;
+
     /**
      * Create the user interface
      */
@@ -839,6 +841,7 @@ private:
                 throw new SessionCreationException("Session could not be created due to error: " ~ e.msg, e);
             }
         }
+        addRecentSessionFile(filename);
         trace(format("Session dimensions: w=%d, h=%d", width, height));
         Session session = new Session(value, filename, width, height, nb.getNPages() == 0);
         addSession(session);
@@ -861,9 +864,11 @@ private:
         if (fcd.run() == ResponseType.OK) {
             try {
                 loadSession(fcd.getFilename());
+                addRecentSessionFile(fcd.getFilename());
             }
             catch (Exception e) {
                 fcd.hide();
+                removeRecentSessionFile(fcd.getFilename());
                 error(e);
                 showErrorDialog(this, _("Could not load session due to unexpected error.") ~ "\n" ~ e.msg, _("Error Loading Session"));
             }
@@ -900,6 +905,7 @@ private:
                 return;
             }
         }
+        addRecentSessionFile(filename);
         string json = session.serialize().toPrettyString();
         write(filename, json);
         session.filename = filename;
@@ -913,6 +919,24 @@ private:
         createNewSession(name, profileUUID, workingDir);
     }
 
+    void addRecentSessionFile(string path) {
+        removeRecentSessionFile(path);
+
+        recentSessionFiles = path ~ recentSessionFiles;
+    }
+
+    void removeRecentSessionFile(string path) {
+        string[] temp;
+
+        foreach (int i, string aPath; recentSessionFiles) {
+            if (aPath != path) {
+                temp ~= aPath;
+            }
+        }
+
+        recentSessionFiles = temp;
+    }
+
 public:
 
     this(Application application) {
```

Obviously this is missing saving to/loading from a setting, doing it in such a way that it would work across multiple windows.

**Comment by gnunn1** [comment]
Thanks @alexwhitman ,you are almost there so feel free to finish it off and submit a PR :)

**Comment by alexwhitman** [comment]
I can handle the behind the scenes bit but I've not really done anything with GTK.  Any suggestions on where to start with that?

**Comment by gnunn1** [comment]
Well the first step is deciding what UI you want to use for this, should it be a pop-up dialog or a drop down? If you think a drop-down is best like Sublime, then you probably need to use an Overlay with the searching controls. There is already an Overlay in the AppWindow to support the SideBar, while I haven't tried it hopefully you could add a second overlay widget but aligned to the top without interfering with the sidebar. To get the controller to animate, use a Revealer, have a look at sidebar.d for this.

For the searching part, GTK has a SearchEntry you can use where the user types into it and it fires an event when a search should be performed. At that point you could then populate either a Treeview or ListBox with the results.

Another thought, should we actually do this in Terminix or simply get the Gnome Shell search provider going and make this one of the searchable items?

**Comment by gnunn1** [comment]
I've done a merge your PR and done some initial UI changes to improve the aesthics of it (hopefully!). I'll sleep on it tonite and take a crack at some more changes tomorrow.

**Comment by alexwhitman** [comment]
Definitely looks better and I'm finding it works quite well when setting the default session name to `${title}`. :+1:

**Comment by freongrr** [comment]
I've started using it and I like it. However, clicking in the list of sessions does not seem to work (using the keys and return works).

**Comment by alexwhitman** [comment]
@freongrr Thanks.  #499 is up to fix it.

**Comment by gnunn1** [comment]
I'm closing this as feature is present and working. I might still do some UI adjustments if I get a great idea between now and release but no sense holding this issue open any longer.

**Comment by ricardovsilva** [comment]
Sorry to revive this thread, but I'm trying to use that functionality without success. Is there any docs about how to use that?

**Comment by gnunn1** [comment]
@ricardovsilva It's been removed in the later versions in order to support the addition of tabs.

**Comment by ricardovsilva** [comment]
@gnunn1 =/ ok, is there some simillar functionality or plugin?

**Comment by gnunn1** [comment]
Not at the moment, sorry.

**Comment by ricardovsilva** [comment]
@gnunn1 can you re-open this issue as enchancement? This is a really great feature and I believe that it can be a great differential for tilix over other terminals.
