### ISSUE TITLE
Middle click on terminal title to close

### ISSUE THREAD

**Issue by lucascosti** [gnunn1/terminix#455]
One enhancement that I would love to have is to be able to middle-click on the terminal title bar to close.

IMO, this is a fairly common use case, and is much easier than remembering the shortcut or finding my way to the close button.

Is it possible to get this added, at least as an option?

**Comment by gnunn1** [comment]
Sure, this should be pretty easy to do and it's somewhat consistent with the browsers that typically let you close tabs by middle clicking them.

**Comment by edubxb** [comment]
I personally dislike this behavior (Firefox has it), so I prefer to have an option to disable it.
