### ISSUE TITLE
Title bar not updated after closing sessions

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#459]
On the latest master branch the title bar isn't updated when sessions are closed:

- Open 4 sessions, session button says 4/4, title says Terminix 4
- Open sidebar and close sessions 2 and 3 by clicking on the X button
- Close sidebar
- Session button still says 4/4, title still says Terminix 4
- Switch to session 1, title bar updates.

**Comment by alexwhitman** [comment]
This isn't quite fixed.  The n/n button which opens the sidebar doesn't update until there are no more sessions under the mouse cursor.  Kind of hard to explain, so here's a video http://sendvid.com/61pyxgh1

**Comment by gnunn1** [comment]
Good catch @alexwhitman, hopefully this commit does the trick.
