### ISSUE TITLE
Terminix theme variant doesn't respect global settings

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#46]
On Terminix Global Preferences on "Appearance" section there are 3 options:
Default
Light
Dark

Default variant always defaults on light theme, even if I've selected Global Dark Theme "ON" from Tweak Tool. Thats happening on GTK 3.19.7. Should be the same on 3.18 too though.

**Comment by dpnova** [comment]
Was there a solution to this? I'm seeing this on packages from the webupd8 ppa on 16.10

**Comment by gnunn1** [comment]
@dpnova It's working fine for me on GTK 3.24, might be an issue with the older GTK version in 16.10?

**Comment by dpnova** [comment]
Ah, could be.. I'm not in a position to bump my dist right now. Thanks for the reply though!
