### ISSUE TITLE
Feature Request: New Window if none on same workspace

### ISSUE THREAD

**Issue by Tadly** [gnunn1/terminix#460]
So, Terminix has this great feature **On new instance** which currently allows to be set to:
 * New window
 * New Session
 * Split Right|Down
 * Focus Window

Not knowing whether this is possible or not, I think it would be awesome to focus an active instances on the same workspace (if there is one) or create a new instance if there isn't.

Just an idea that popped to mind as I often end up with 3 or more instances on the same workspace because I forgot I already had one.

**Comment by dsboger** [comment]
For GNOME Shell, there is an [extension](https://extensions.gnome.org/extension/887/workspace-isolated-dash/) that does that irrespective of the application.

**Comment by Tadly** [comment]
@dsboger now that you've mentioned it. I think I've seen that somewhere before :)

This kinda solves the issue...
...On the other hand I'd prefer this to be handled by terminix itself if possible as not every DE supports GNOME Shell extensions.

**Comment by gnunn1** [comment]
While a nice idea I don't believe it is very feasible. At this time, the only library I'm aware of for handling workspaces cross platform is libwnck and I think it's pretty tied to X11 and likely won't work under Wayland. I also don't want to add it as a dependency, while I can work around that by checking if it was optionally available the effort to do so is just not worth the payback IMHO.
