### ISSUE TITLE
Feature request: --execute short option compatibility -e

### ISSUE THREAD

**Issue by Calrama** [gnunn1/terminix#462]
The conventional (AFAIK) short command line option in terminal emulators for `--execute` is `-e`;
at least it is provided as such by (non-exhaustive)

- (u)rxvt
- xterm
- gnome-terminal
- qterminal
- termit
- terminator
- st

This may seem trivial, but there are programs (such as [i3](https://i3wm.org/)'s i3-nagbar) that assume the user's terminal emulator can be used to execute a command by calling it with `-e`.
I'm not aware of any other terminal emulator using `-x` as the short option and would be grateful for `-e` being available for that purpose (either replacing `-x` or in addition to it).

**Comment by gnunn1** [comment]
Agreed, I must have had a brain-fart when I picked x as the shortcut.

**Comment by gnunn1** [comment]
Looking into this more, it appears I didn't have as much of a brain fart as I thought. Gnome Terminal supports both -e and -x with the difference being -x executes everything that follows it as the command whereas -e only executes the parameter string. Terminix should be compatible where possible with gnome terminal so I'll attempt to adjust this.

http://manpages.ubuntu.com/manpages/wily/man1/gnome-terminal.1.html

**Comment by Calrama** [comment]
Thank you for the quick fix.
