### ISSUE TITLE
Add new terminal down/right working directory

### ISSUE THREAD

**Issue by zatan** [gnunn1/terminix#465]
By adding new terminal down/right from the current window should set new terminal current working directory path to the original working path where it got called from.

**Comment by arcticicestudio** [comment]
This is a known issue related to VTE.  
There's a information popup for this which links to the [related wiki entry](https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue).

**Comment by zatan** [comment]
@arcticicestudio  thanks, this solved my problem!
