### ISSUE TITLE
Request: Pass profile and command to Terminix when launching new Terminix

### ISSUE THREAD

**Issue by sengelbert** [gnunn1/terminix#47]
With the recent updates to #40 I would like to be able to include the terminal profile and commands to the launching command. This is incredibly useful for launching new sessions, aliases, ssh sessions, etc.

Example:
terminix -c app-new-window -p dev
terminix -c app-new-window -p dev -x bash -c "ssh <server>"

Examples from Gnome terminal:
gnome-terminal --window-with-profile=dev
gnome-terminal --window-with-profile=dev -x bash -c "ssh <server>"

**Comment by gnunn1** [comment]
It's already completed and will be available in the next release which will hopefully be out tonite, see the wiki entry here:

https://github.com/gnunn1/terminix/wiki/Command-Line-Actions

**Comment by sengelbert** [comment]
OK. I did not see how to specify a profile that is not the default profile in #40 or the wiki you mentioned. How is that accomplished?  Example would be default profile is called "Solarized" other profile is called "Tango". User wants to open new terminal with "Tango" profile rather than default "Solarized" profile.

**Comment by gnunn1** [comment]
You can select the profile using -p or --profile. Running terminix with
--help shows all the command line options. Running terminix with the -a
will cause it to pass any command line options to the new terminal if one
is created via the action switch.

**Comment by sengelbert** [comment]
Great! Thanks!
