### ISSUE TITLE
Open remote shell on SFTP connections 

### ISSUE THREAD

**Issue by Gert-dev** [gnunn1/terminix#473]
Hello

Recently whilst trying out Terminix, it felt pretty much like an improved version of gnome-terminal (perhaps it would even be interesting if it became the default GNOME terminal). A minor feature I'm missing is opening a terminal on a remote location whilst automatically signing into the SSH session. 

GNOME terminal supports this via Nautilus by right-clicking; two options will show up in remote locations: one to "open a terminal here" (which is what Terminix already supports) and one to "open a remote terminal". It could be that this support is limited to SFTP protocols, however.

An example:
* I connect to `sftp://me@some-server.com/` via Nautilus.
* I ensure the folder is active.
* I right-click and open a remote terminal.
* A Terminix window shows up that in the background basically does something like `ssh me@some-server.com -p 22`. If a password needs to be entered, it will simply request it (in case of an SSH key, it will sign in automatically).

I noticed you mentioned something related to this in #100 as well `but I'll wait for a bug report on that first.`. Consider this the official bug report ;-).

Thanks for your awesome work!

**Comment by gnunn1** [comment]
Might take me some time to get to this, the Nautilus integration is in Python which I'm not that great at. If someone wants to take a crack at this feel free, the python code is a single file and can be found here:

https://github.com/gnunn1/terminix/blob/master/data/nautilus/open-terminix.py

**Comment by gnunn1** [comment]
I've checked in an initial attempt at this, please test it out and let me know how it goes.

You can test it by getting the nautilus extension here https://github.com/gnunn1/terminix/blob/master/data/nautilus/open-terminix.py and replacing the version in /usr/share/nautilus-python/extensions/

**Comment by Gert-dev** [comment]
I had a chance to test this today. Thanks for adding this, it works mostly as expected; two minor things I noticed:
* When you right-click inside the empty part of a directory, the option doesn't show up. Only `Open Terminix here` shows up. It does show up when you right-click a folder or file, however.
* When you right-click a file or folder and open a remote Terminix instance, the instance starts at the root of the server instead of at the folder or the the file is in respectively. [1] may be of help here.

[1] https://stackoverflow.com/questions/626533/how-can-i-ssh-directly-to-a-particular-directory

**Comment by gnunn1** [comment]
Thanks for testing this. I can reproduce the first point and will look into it, however for the second one this is working fine for me. You can see the code I'm using for this here (which was actually based on that  same stackoverflow article):

https://github.com/gnunn1/terminix/blob/master/data/nautilus/open-terminix.py#L43

Note it does require that you right click a folder in order to do this. Also, maybe check that in the remote session the $SHELL environment variable is set?

**Comment by Gert-dev** [comment]
Thanks for your response. That it's working for you is very well possible; I'm using the fish shell (`/bin/fish`) as shell command in my Terminix profile, which may be interfering with it somehow. I had similar problems getting it to work with gnome-terminal's "Open terminal here" functionality but got it to work somehow (though I can't for the life of me remember how).
