### ISSUE TITLE
Cannot select text with mouse near splitter

### ISSUE THREAD

**Issue by zeten30** [gnunn1/terminix#476]
Hello, 

mouse cursor is changing to 'resize' when close to splitter. First character on left side cannot be selected via mouse (workaround, select from  right to left). Image [https://goo.gl/photos/EmsoYXSNNJQbaF6T9](https://goo.gl/photos/EmsoYXSNNJQbaF6T9). This happens in all terminals added to right.

**Comment by gnunn1** [comment]
This is an issue with GTK and thin splitters, gedit has the same issue when you enable it's sidebar. The easiest way to work-around this is to enable wide handle in Preferences | Appearance.

See #307 for more information.
