### ISSUE TITLE
Feature request: Insert/paste terminal number/id function

### ISSUE THREAD

**Issue by zeten30** [gnunn1/terminix#477]
Insert/paste terminal number/id function (menu/button/shortcut) will be very useful when doing ssh server-${NUM} from tiled terminals for example.

**Comment by gnunn1** [comment]
It's already there in the git version, if you look in the shortcuts tab in the preferences dialog under the Terminal section there should be a shortcut for" Insert terminal number".

**Comment by zeten30** [comment]
Great. I was looking in latest commits, but didn't find it.
