### ISSUE TITLE
Release Version 1.30

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#479]
I think things are at the point where I should I look at releasing a stable 1.30 version in a couple of weeks towards the end of September, there are enough new features and bugs squashed to warrant it. 

Some of the remaining items left on my plate that I would want to do before this include:

* Fix any remaining quake issues that are in my purview to fix (I suspect #471 is not fixable by me and is an upstream issue)
* Take a pass through the Preference and Profile dialogs and try to make things look a little cleaner and prettier, some of the tabs have gotten a bit ugly and could use some tweaking.
* Incorporate @alexwhitman quick session switcher

Anyone disagree or have other items they feel are must-do for a 1.30 stable release?

**Comment by alexwhitman** [comment]
I wouldn't necessarily mark the switcher as a blocker to release unless anyone wants to volunteer to take a look at the visual side of it.  I'm probably not going to have time to add the fuzzy string search but I do want to make the simple string search case insensitive which I should be able to do tomorrow.

**Comment by gnunn1** [comment]
This was intended more as a list of things I'd like to do brfore release rather then a list of blockers, I should have been clearer.

Once the switcher is fully functional just let me know and I'll merge it in, I'm happy to work on cleaning up the UI to make it purdy :)

**Comment by vaijab** [comment]
I cannot wait. :-)

**Comment by gnunn1** [comment]
I'll be pushing out the new version tomorrow unless anyone has any show-stoppers to report?

**Comment by gnunn1** [comment]
Pushed out release.
