### ISSUE TITLE
Quake mode resizing strangeness

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#484]
I was testing the new Quake mode size scales in the preferences and noticed that the window width wasn't changing when the scale was changed.  That was because of a missing "watch" on `SETTINGS_QUAKE_WIDTH_PERCENT_KEY` which I was going to fix with:
```diff
diff --git a/source/gx/terminix/appwindow.d b/source/gx/terminix/appwindow.d
index 7c26482..fda56e0 100644
--- a/source/gx/terminix/appwindow.d
+++ b/source/gx/terminix/appwindow.d
@@ -823,7 +823,7 @@ private:
 
     void applyPreference(string key) {
         switch(key) {
-            case SETTINGS_QUAKE_HEIGHT_PERCENT_KEY, SETTINGS_QUAKE_PRIMARY_MONITOR, SETTINGS_QUAKE_SPECIFIC_MONITOR:
+            case SETTINGS_QUAKE_HEIGHT_PERCENT_KEY, SETTINGS_QUAKE_WIDTH_PERCENT_KEY, SETTINGS_QUAKE_PRIMARY_MONITOR, SETTINGS_QUAKE_SPECIFIC_MONITOR:
                 if (isQuake) {
                     GdkRectangle rect;
                     getQuakePosition(rect);
```
This fixed the problem of the scale changes not modifying the window, but I don't think the scales are quite working as intended, best expressed in a video: http://sendvid.com/yz4b8r2p

**Comment by gnunn1** [comment]
Thanks, should be fixed now.

**Comment by alexwhitman** [comment]
The resizing is now fixed, thanks.  There is also another small related issue in the video where the window position jumps down slightly which still occurs.  It looks like, but I'm not entirely sure, that the window drops down so that it's below the shadow of the top Unity bar.  Reopening the quake window repositions it correctly so it's only a minor bug.

**Comment by gnunn1** [comment]
@alexwhitman I'm not sure what is causing that drop down in position, the position is determined by the getQuakePosition method in appwindow.d which simply fetches the screen rect from the monitor and adjusts it based on the size settings. It doesn't actually touch the rect.y position at all. 

The method does output the coordinates it's using in a trace, can you test it again when you get a chance and see if the y coordinate is ever changing?

**Comment by alexwhitman** [comment]
Ran a debug build, the y co-ordinate does stay as 0.

**Comment by gnunn1** [comment]
Thanks, let's chalk this up to Ubuntu weirdness :)

**Comment by alexwhitman** [comment]
That's fine, it sorts itself out when reopening the window so someone would only see it when they change the preference which I can't imagine would happen often.
