### ISSUE TITLE
Shortcut to change font size

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#486]
Please, add ``ctrl+(scroll)`` to change font size.

**Comment by gnunn1** [comment]
I'm not keen on this, there are shortcuts already for zoom-in/zoom-out which is intended to be the mechanism to make things temporarily bigger/smaller. I'm not sure I want to add additional increases for the same purpose.

Thoughts?

**Comment by leoheck** [comment]
What are shortcuts for zoom-in/out? I have asked for ``Ctrl+(scrol)`` because many applications behave like that.

**Comment by gnunn1** [comment]
ctrl+ and ctrl-, see the Preferences dialog and the Shortcuts tab.

**Comment by leoheck** [comment]
Ok, ``crtl+`` should be used with shift in my keyboard, thanks.

**Comment by gnunn1** [comment]
Keep in mind you can change the shortcuts if you want to.

**Comment by leoheck** [comment]
Yeah, sure this is definitely a good behavior. I keep one thing in my mind: it's always better to not change because we always have to use computers from others AND if the application mimics other applications we can be productive in any system. But thanks, @gnunn1  :)

**Comment by EmTee70** [comment]
I have just detected the behavior, that the +- keys beside the cursor and number block on my notebook (Ubuntu17.04, Lenovo ideapad 110)  are not detected, despite they produce the correct chars.
(Same with an USB Cherry Keyboard)

**Comment by saltgen** [comment]
> I'm not keen on this, there are shortcuts already for zoom-in/zoom-out which is intended to be the mechanism to make things temporarily bigger/smaller. I'm not sure I want to add additional increases for the same purpose.
> 
> Thoughts?

Is it possible to persist a certain zoom level, thanks.
