### ISSUE TITLE
Make fade-in/out animation of Quake mode optional

### ISSUE THREAD

**Issue by danielkza** [gnunn1/terminix#488]
It would be really nice if I could disable the Quake animations, as I find them a bit annoying and they slow me down from getting quickly to a terminal then closing it.

**Comment by alexwhitman** [comment]
The fade in/out of the whole window is controlled by you desktop environment.  If you're running Ubuntu/Unity you can install `compizconfig-settings-manager` and use the Animations settings to stop the animations for Terminix.

To do this, add `!(class=Terminix) & ` to the start of the the Window Match for the "Glide 2" Close Effect for both the Open Animation and Close Animation.
![selection_001](https://cloud.githubusercontent.com/assets/422013/18607399/10d93dec-7cc3-11e6-8b71-6ef340916ebd.png)
Note that this will also remove the animations from the normal Terminix windows, not just the Quake mode window.

**Comment by gnunn1** [comment]
@danielkza Unfortunately I don't think there is anything I can do about this since as @alexwhitman points out it's really the window manager that manages this.

**Comment by danielkza** [comment]
The WM does manage it, but it's possible to tell it to prefer not to:

```diff
diff --git a/source/gx/terminix/appwindow.d b/source/gx/terminix/appwindow.d
index 60671e4..6cece48 100644
--- a/source/gx/terminix/appwindow.d
+++ b/source/gx/terminix/appwindow.d
@@ -1113,7 +1113,7 @@ public:
             setDecorated(false);
             setGravity(GdkGravity.STATIC);
             setKeepAbove(true);
-            setTypeHint(GdkWindowTypeHint.NORMAL);
+            setTypeHint(GdkWindowTypeHint.UTILITY);
             setSkipTaskbarHint(true);
             setSkipPagerHint(true);
             applyPreference(SETTINGS_QUAKE_HEIGHT_PERCENT_KEY);
```

**Comment by gnunn1** [comment]
Thanks for the tip, I'll test it out and add an option for it.

**Comment by kam3k** [comment]
Could this ticket be re-opened since the feature was removed?
