### ISSUE TITLE
Create a Gitter/IRC/etc channel (suggestion)

### ISSUE THREAD

**Issue by danielkza** [gnunn1/terminix#489]
I think it would be nice to have a chat channel of some kind that could be used to talk about Terminix, either for questions or development, to avoid needing to create issues. I'm working on updating translations, and it would be much easier to be able to ask the feature creators about what each string should mean, specially if I cannot test the feature myself (e.g. the new triggers feature).

Many projects seem to be using [Gitter](http://gitter.im) nowadays, but an IRC channel is always a good option that doesn't depend on a single external service.

**Comment by gnunn1** [comment]
I'd prefer IRC since I'm on IRC fairly regularly. On freenode my nick is gnunn though sometimes it changes to gnunn_ when I don't bother identifying with nickserv. On Gnome IRC channels I also go my gnunn.

If someone wants to start a #terminix channel I'm happy to add it to my IRC client.

**Comment by danielkza** [comment]
I created #terminix @ Freenode an +op'd you.

**Comment by gnunn1** [comment]
Thanks, I've added it to my room list for freenode.

I'll add a note about this on the front page.
