### ISSUE TITLE
Save/Load layout not working on Ubuntu Gnome 15.10 

### ISSUE THREAD

**Issue by johnnydvc** [gnunn1/terminix#49]
Hey. 
I'm having trouble saving and loading the terminal layouts.
First I split the terminal window no matter how and then
I save the file. When I reopen terminix and try
to load that layout I get the following error message
`Could not load session due to unexpected error.
Found '5' when expecting '"'. (Line 18:23)`
Thanks

**Comment by gnunn1** [comment]
Thanks, I'll have a look over the weekend.

**Comment by gnunn1** [comment]
Can you post your json file, I gave reproducing it a quick try with some different layouts and it was working OK for me, I'm probably missing something simple which will be immediately obvious with your file.

**Comment by johnnydvc** [comment]
Ok, here's the file.

2016-01-22 23:12 GMT+01:00 Gerald Nunn <notifications@github.com>:

**Comment by gnunn1** [comment]
Thanks, it looks the problem is with this line:

```
        "position": 0,5,
```
Are you in a locale that uses a comma as the decimal separator?

**Comment by johnnydvc** [comment]
I guess so. locale is
`LANG=de_DE.UTF-8`
Numbers are written as
`123.456.789,000`
Do I have to change the json file on my own?

**Comment by gnunn1** [comment]
If you want to keep those sessions you saved, then yes you will need to hand edit them. The next release will fix this issue in the sense that it will write out the correct value from then on but I can't do anything about already existing files, sorry about that.

**Comment by johnnydvc** [comment]
I want to thank you a lot for planing to fix/enhance this.
The sessions are no problem, they were just for testing the feature.
Terminix has a good chance of replacing terminator for me now.
Have you found someone to package vgrep for other distros yet? Looks interesting to.
Greetings

**Comment by vabada** [comment]
This same thing just happened to me, with:

```
Versions
	Terminix version: 1.4.2
	VTE version: 0.42
	GTK Version: 3.18.9

Terminix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

under Ubuntu 16.04

In line:
```
"ratio": 0.5,
```
```
Could not load session due to unexpected error.
Found '5' when expecting '"'. (Line 33:24)
```
