### ISSUE TITLE
Create a Terminix website

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#490]
I'd like to get a simple one-page website for Terminix setup in order to be a little more pro-active with the marketing. The idea would be to simply host the website in a seperate repository in github so it could be worked on collaboratively. A good example of this is what Lollypop has done in this regard where the website (https://gnumdk.github.io/lollypop-web) is simply served from a repository (https://github.com/gnumdk/lollypop-web/).

Unfortunately my web design skills are pretty weak so I was wondering if anyone would be interested in taking this on?

**Comment by bil-elmoussaoui** [comment]
Would love to help! Worked on both lollypop & FeedReader website, if any designer could do the design part on photoshop or any other software and i can do the HTML/CSS part :+1:

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui, that would be great! Hopefully we can attract some design help.

**Comment by ayoisaiah** [comment]
I'd like to work on this @gnunn1. I'm no designer but I can make pretty decent wireframes with Balsamiq. I'm also down for coding help if needed.

We can work on this together if you wish @bil-elmoussaoui.

**Comment by deriherdianto** [comment]
Count me too

**Comment by ayoisaiah** [comment]
@gnunn1 I see nothing much has happened here. I have created a wireframe for how the website could be laid out. You can view it here https://www.dropbox.com/s/ug4n470ehml1193/terminix.pdf?dl=0

I suggest you create the repo right away so myself and others can start contributing our ideas and code to the project.

**Comment by gnunn1** [comment]
I've created a repo here:

https://github.com/gnunn1/terminix-web

I've never worked with github pages before so if I've done something wrong just let me know.

**Comment by ayoisaiah** [comment]
Looks good @gnunn1 I'll complete the setup and send a pull request before the end of today (Friday)

**Comment by gnunn1** [comment]
So is anyone interested in picking this up? I think it's just a matter of selecting a jeckyll theme and start moving forward?

**Comment by ayoisaiah** [comment]
I've been a little busy recently but I'm free to work on it some more this weekend. I reckon it would be finished within the next week.

**Comment by bil-elmoussaoui** [comment]
I'm free to work on this, do you have any idea of a jekyll theme?

**Comment by bil-elmoussaoui** [comment]
Btw, the branch should be gh-pages and not Terminix

**Comment by gnunn1** [comment]
I've created the gh-pages branch. As to the jekyll theme, I don't really have much preference here. I'd suggest a relatively simple theme though.

**Comment by bil-elmoussaoui** [comment]
I can start working on a simple layout using http://semantic-ui.com instead of Bootstrap! It's used to create jekyll website. I will pull a first PR by this evening if everything goes as expected :+1:

**Comment by gnunn1** [comment]
Thanks @bil-elmoussaoui, that sounds great

**Comment by gnunn1** [comment]
I've updated the repo with a simple website for now.

https://gnunn1.github.io/terminix-web/

**Comment by bil-elmoussaoui** [comment]
Shame on me. I totally forgot about this. I will try to get some free time this week and push a PR with a better design ;)

**Comment by bil-elmoussaoui** [comment]
![capture d ecran de 2016-12-16 06-12-05](https://cloud.githubusercontent.com/assets/7660997/21252394/b38bcd0a-c356-11e6-8bc6-083b7efe5262.png)
![capture d ecran de 2016-12-16 06-12-11](https://cloud.githubusercontent.com/assets/7660997/21252395/b39dbaba-c356-11e6-80be-0626892b53a3.png)
![capture d ecran de 2016-12-16 06-12-16](https://cloud.githubusercontent.com/assets/7660997/21252396/b3a76650-c356-11e6-8259-20e0800d51df.png)
![capture d ecran de 2016-12-16 06-12-22](https://cloud.githubusercontent.com/assets/7660997/21252397/b3a92e68-c356-11e6-97a2-2345e613bece.png)
![capture d ecran de 2016-12-16 06-12-27](https://cloud.githubusercontent.com/assets/7660997/21252399/b3aa055e-c356-11e6-9007-c7ee62aaa488.png)
![capture d ecran de 2016-12-16 06-12-32](https://cloud.githubusercontent.com/assets/7660997/21252400/b3aa77be-c356-11e6-94f9-1186b7c6d9b8.png)
![capture d ecran de 2016-12-16 06-12-35](https://cloud.githubusercontent.com/assets/7660997/21252398/b3a992c2-c356-11e6-8e8f-d3bbcbb11b72.png)

@gnunn1 Here's a small prototype i built those last two hours (insomnia :P), here's a lot of small details to fix, i just wanted your feedback before i finish the work. Should be ready tonight(it's 6am here), at worst this weekend!  
Website is built using Jekyll, and Skeleton(small and fast compared to complicated stuff like Foundation 6 or Bootstrap). Works perfectly with gh-pages, uses CSS (sadly, not sass). and jQuery & jQuery UI.
If you have any suggestions, modifications, feel free. I will modify anything you wish! and open a PR once it's seems to be okey. 

PS: The colors of the buttons will be changed, don't worry about that :)

**Comment by bil-elmoussaoui** [comment]
Alpha 1 of the website 
![capture d ecran de 2016-12-16 10-39-10](https://cloud.githubusercontent.com/assets/7660997/21258141/f51c0260-c37b-11e6-9e6b-b39d94363b39.png)
![capture d ecran de 2016-12-16 10-39-14](https://cloud.githubusercontent.com/assets/7660997/21258142/f51c0b8e-c37b-11e6-91b1-89682ab6bf95.png)
![capture d ecran de 2016-12-16 10-39-21](https://cloud.githubusercontent.com/assets/7660997/21258143/f51c3744-c37b-11e6-8618-31179ae9b5ab.png)
![capture d ecran de 2016-12-16 10-39-23](https://cloud.githubusercontent.com/assets/7660997/21258144/f51c3bea-c37b-11e6-8547-07bad81aff12.png)

**Comment by gnunn1** [comment]
That looks awesome, very nice work @bil-elmoussaoui! Once you do the PR I'm happy to help with content.

**Comment by bil-elmoussaoui** [comment]
I'm going to send a PR this evening if things are going as expectede,j ust adding mobile and tablet support.

**Comment by edubxb** [comment]
cool! great job!

**Comment by gnunn1** [comment]
Closing, thanks again @bil-elmoussaoui for your hard work on this.

**Comment by bil-elmoussaoui** [comment]
You're welcome! it's all i can do to help improving this project :) i will try to keep it up to date!
