### ISSUE TITLE
New install script doesn't work correctly on Ubuntu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#491]
The new installer script added in #487 doesn't work correctly on Ubuntu.

Ubuntu uses `dash` for `sh`.  `dash` doesn't support `pushd` and `popd` so the script should either use a POSIX compatible method or use `bash` explicitly.

The script leaves a bunch of `.mo` files in the root of the repository directory which are marked as untracked by git.  They should either be cleaned up at the end of the script or added to `.gitignore`.

After the script runs (when changed to use `bash`), the root menu item in the top menu bar/panel says "Unknown Application Name" rather than "Terminix".
![workspace 1_002](https://cloud.githubusercontent.com/assets/422013/18613481/cf91f9bc-7d73-11e6-9039-1744e11eb8a9.png)

Ping @danielkza

**Comment by danielkza** [comment]
My bad for not testing properly on Ubuntu, I'll fix it up tomorrow.

Em dom, 18 de set de 2016 03:46, Alex Whitman <notifications@github.com>
escreveu:

**Comment by danielkza** [comment]
@alexwhitman Can you please try e7f3f042b6b?

I noticed that Terminix won't run unless I have `libsecret-1-dev` installed, due to the executable linking to `libsecret-1.so` instead of the fully versioned library, but I don't believe this is caused by the installation script. Do you notice the same issue?

**Comment by gnunn1** [comment]
Btw libsecret should be an optional dependency, if terminix is not running without it being present open an issue for it and I'll have a look at it. Also if Ubuntu is using a different name then arch that would be good to fix as well.

**Comment by danielkza** [comment]
This is what I get after compiling and installing (with the new script) in Ubuntu 16.04:

```bash
$ terminix
object.Exception@../.dub/packages/gtk-d-3.3.1/src/gtkc/Loader.d(123): Library load failed: libsecret-1.so
```

I just checked and Fedora does the same thing as Ubuntu: the devel package is the one that provides `libsecret-1.so`. The regular package only provides `libsecret-1.so.0` and `libsecret-1.so.0.0` , so it seems to me GtkD is doing the wrong thing.

**Comment by gnunn1** [comment]
This is me not GtkD since I created the wrapper API for it. It's referenced
in one of the files in source/secretc.

**Comment by danielkza** [comment]
Should be easier to fix then :smile:

**Comment by gnunn1** [comment]
I've fixed the issues with libsecret so hopefully all is good now, if not add an issue and I'll look at it further.

**Comment by alexwhitman** [comment]
The installer script now works (i.e. doesn't error) but the root menu item still says "Unknown Application Name".
![workspace 1_002](https://cloud.githubusercontent.com/assets/422013/18625656/e550c9a2-7e47-11e6-9562-102a950b7358.png)

**Comment by danielkza** [comment]
That's weird, it doesn't do that for me on 16.04. The installer should be
placing the exact same files it was before. Do you have any error messages
in the session logs?

Em seg, 19 de set de 2016 05:03, Alex Whitman <notifications@github.com>
escreveu:
