### ISSUE TITLE
Feature Request: Highlight all search results

### ISSUE THREAD

**Issue by xhorak** [gnunn1/terminix#496]
Make possible to highlight all occurrences of search term. See: https://ibin.co/2vabhkule3ks.png for demonstration.

The Konsole has it for ages and it's really useful at least for me.

**Comment by gnunn1** [comment]
Unfortunately, this requires changes in the underlying GTK VTE widget to support this, see this upstream issue:

https://bugzilla.gnome.org/show_bug.cgi?id=627886
