### ISSUE TITLE
Synchronized Input does not work for "moving" keys

### ISSUE THREAD

**Issue by jonasbb** [gnunn1/terminix#50]
I am running 0.38.0 from OBS on Fedora.

While testing the synchronized input feature I found a bug. Keys for moving the cursor (arrow keys, home, end, page up/down) only work in the selected terminal, but not all other ones. Combination of those keys with modifier have the same result.

I would expect those keys to be working as you may multi-edit files or want to access the shell history.

**Comment by gnunn1** [comment]
Good catch, if you look at the code I have a comment in there saying the way I'm doing it is sub-optimal. I was originally trying to feed the original key event to the other terminals which would provide the most fidelity but was having some issues with it. This gives me the impetus to look at it again so thanks.
