### ISSUE TITLE
Feature Request: Confirmation when closing window with multiple terminals/sessions

### ISSUE THREAD

**Issue by lucascosti** [gnunn1/terminix#500]
It's sometimes hard to remember that I have multiple sessions open in a window, and I often hit the close window button and lose all my sessions, when I should have closed the session instead.

Is it possible to get an option, so that when closing a window that contains multiple terminals or sessions, the user gets prompted for confirmation?

e.g. similar to a browser's "You are about to close X tabs. Are you sure you want to continue?"

**Comment by gnunn1** [comment]
Sure make sense, I probably won't have an obvious option for it, maybe a dialog that pops up by default when there is more then one session to remind you and has a "Do not show this to me again" checkbox to turn it off.

**Comment by lucascosti** [comment]
Sounds great, thanks! :)
