### ISSUE TITLE
dconf update crashes Terminix on CentOS 7.2.1511

### ISSUE THREAD

**Issue by johannagnarsson** [gnunn1/terminix#508]
I apologize if this has been posted already but I could not find any report that matched it.

I'm running a fully updated CentOS 7.2 system as of 27 Sep 2016

if I change the system dconf configuration in /etc/dconf/db/site.d/ and run 'dconf update' while I have terminix running with at least 1 split (add down/right) terminix crashes.

Steps to reproduce:

1. create file /etc/dconf/db/site.d/01-test.conf with the following contents:

> 
> [org/gnome/desktop/interface]
> clock-show-seconds=true

2. Start Terminix and split the window at least once.
3. Run as root: `dconf update`
4. Watch terminix crash.

Here is the backtrace:

> 
> [jagnarsson@jagnarsson $] `G_SLICE=debug-blocks gdb terminix`
> 
> GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-redhat-linux-gnu".
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>...
> Reading symbols from /usr/bin/terminix...(no debugging symbols found)...done.
> (gdb) run
> Starting program: /usr/bin/terminix 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> [New Thread 0x7fffe73af700 (LWP 21431)]
> [New Thread 0x7fffe52e9700 (LWP 21432)]
> Detaching after fork from child process 21433.
> Detaching after fork from child process 21434.
> [New Thread 0x7fffdf7fa700 (LWP 21435)]
> Detaching after fork from child process 21591.
> object.Error@(0): The function you are calling is not pressent in your version of GTK+.
> ----------------
> ??:? extern (C) void gtkc.Loader.Linker.unsupportedSymbol() [0xadebfd]
> ??:? void gtk.Paned.Paned.setWideHandle(bool) [0x9d4304]
> ??:? void gx.terminix.session.Session.updateWideHandle(bool) [0x91bffa]
> ??:? _D2gx8terminix7session7Session11initSessionMFZ42__T12__dgliteral1TC3gio8Settings8SettingsZ12__dgliteral1MFAyaC3gio8Settings8SettingsZv [0x91bc85]
> ??:? extern (C) void gio.Settings.Settings.callBackChanged(gtkc.giotypes.GSettings*, char*, gio.Settings.Settings) [0x9727f9]
> ??:? g_cclosure_marshal_VOID__STRINGv [0xf379cb48]
> [Thread 0x7fffdf7fa700 (LWP 21435) exited]
> [Thread 0x7fffe52e9700 (LWP 21432) exited]
> [Thread 0x7fffe73af700 (LWP 21431) exited]
> [Inferior 1 (process 21427) exited with code 01]
> Missing separate debuginfos, use: debuginfo-install terminix-1.2.0-1.el7.centos.x86_64
> (gdb) run
> Starting program: /usr/bin/terminix 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> [New Thread 0x7fffe73af700 (LWP 24585)]
> [New Thread 0x7fffe54f6700 (LWP 24600)]
> [Thread 0x7fffe73af700 (LWP 24585) exited]
> [Thread 0x7ffff7fc65c0 (LWP 24584) exited]
> [Inferior 1 (process 24584) exited normally]

**Comment by gnunn1** [comment]
Thanks, there were a couple of spots where I wasn't checking to make sure the GTK version was greater then 3.16 when using the wide handle option for Paned.
