### ISSUE TITLE
Feature Request: Shortcut for showing/hiding terminal title

### ISSUE THREAD

**Issue by gabrielmagno** [gnunn1/terminix#509]
Currently, it is possible to set the "Terminal Tittle Style" choosing between 3 options: "Normal", "Small" and "None". Particularly, I prefer the "None" option, since it gives me more screen area.

The problem is that, by hiding the terminal title bar, I cannot move and de-attach the terminals. Maybe there's another solution for allowing that, but I thought that providing a shortcut for showing/hiding the terminal title bar could be a good and easy solution.

**Comment by gnunn1** [comment]
Note that in master and the forthcoming 1.30 version there is a new option that hides the titlebar if there is only one terminal in the session, would that be sufficient for your needs?

**Comment by gabrielmagno** [comment]
Thanks for the fast reply and the kindness. Didn't know about that new feature, it will be great.

Maybe I'm being too boring and strict, but the problem is that in smaller screens, even 25 pixels could make a difference. Having the ability to show and hide the title bar when desired would be awesome (be it through a menu option or through a shortcut).
