### ISSUE TITLE
Fatal Error from libphobos2

### ISSUE THREAD

**Issue by Vistaus** [gnunn1/terminix#510]
I'm using the latest master version from Git on Arch Linux and I'm getting this error when trying to start Terminix:

```
vistaus[at]vistaus-arch ~/Apps ฿ terminix
Fatal Error while loading '/usr/lib/libphobos2-ldc.so.70':
	The module 'std.regex.internal.parser' is already defined in 'terminix'.
vistaus[at]vistaus-arch ~/Apps ฿ 
```

I've read somewhere that I should use the Git version of libphobos2 so I installed that and re-compiled Terminix but the error's still there.

How to solve this?

**Comment by gnunn1** [comment]
Are you using the terminix-git package in Arch?

**Comment by gnunn1** [comment]
I see @dsboger was already looking at this here, looks like it could be worked around by including the flag 
-disable-linker-strip-dead

https://github.com/ldc-developers/ldc/issues/1534

**Comment by Vistaus** [comment]
I'm not using that package, I'm building it directly from Git after cloning the repo.

Regarding that flag: do you mean I need to include that while building ldc or Terminix?

**Comment by gnunn1** [comment]
When building terminix. Alternatively you could use dmd which is what I'm using and works fine however LDC should work, I'll have a look at it when I get home tonite.

**Comment by gnunn1** [comment]
Just to confirm, adding the line:

```"dflags": ["-disable-linker-strip-dead"],```

After the mainSourceFile fixes the problem for me with ldc.

**Comment by dsboger** [comment]
You could aso have a look at how the package terminix-git does. Using the supplied PKGBUILD with makepkg it is the same as you are doing, except it is automatic. If you do the same commands, the results should be similar.

**Comment by Vistaus** [comment]
@gnunn1 Where is that mainSourceFile located?

@dsboger Thanks, that package does apply the dflag fix. But I'd much rather build it from Git myself.

**Comment by gnunn1** [comment]
@Vistaus It's in dub.json:

https://github.com/gnunn1/terminix/blob/master/dub.json#L6
