### ISSUE TITLE
Add support for environment variables (proxy)

### ISSUE THREAD

**Issue by arrufat** [gnunn1/terminix#514]
I've just noticed that terminix does not follow the proxy server I've set in gnome-control-center, but gnome-terminal does.
Would it be possible to add support for this?

Thank you for this awesome terminal!

**Comment by gnunn1** [comment]
I think this is is because the Terminix desktop file is using dbusactivatable, try setting it to false and let me know if that fixes the problem.

So edit /usr/share/applications/com.gexperts.Terminix.desktop and change the line:

```
DBusActivatable=true
```
to:
```
DBusActivatable=false
```

**Comment by arrufat** [comment]
Thanks for the quick response, unfortunately, that did not work :(

**Comment by gnunn1** [comment]
You may need to restart gnome shell for it to take effect since the desktop files are cached.

**Comment by arrufat** [comment]
Yes, I had already restarted the shell. Does it work for you?

**Comment by gnunn1** [comment]
I'm in the middle of something right now, I'll test in an hour or so. Thanks for trying it out though.

**Comment by gnunn1** [comment]
So I had a look and setting the DbusActivatable to false as no effect. 

Looks like gnome-terminal has code that sets these environment variables explicitly, I'll need to do something similar:

https://github.com/GNOME/gnome-terminal/blob/bd9cb2797d15c8f19f2f24db90ec0d7d8c8ac03c/src/terminal-util.c#L648

**Comment by arrufat** [comment]
Ok, I'll add the http_proxy variables to my .bashrc as a workaround. Thanks for the detailed response :)

**Comment by egmontkob** [comment]
Haha, g-t received the opposite request once: https://bugzilla.gnome.org/show_bug.cgi?id=747800

**Comment by gnunn1** [comment]
@egmontkob damned if you do, damned if you don't :)

**Comment by arrufat** [comment]
Thanks you so much!
