### ISSUE TITLE
Focusing Quake window can also bring other windows to front

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#518]
Sometimes, but not always, opening a Quake mode window also brings other Terminix windows to the front, above any other windows (Chrome/Firefox/Sublime Text etc).

Currently running the latest master branch on Ubuntu 16.04.  This could have been happening for a while but I've not noticed due to usually having a single Terminix window on a dedicated monitor with no other applications.

Unfortunately I can't find a reliable way to reproduce but now that I've noticed it, it does happen quite often.

**Comment by gnunn1** [comment]
I haven't noticed this myself in Gnome Shell but I'll freely admit I'm not a big user of quake mode myself.  I'd love to hear if others are having this issue to know if it's confined to Ubuntu/Unity or is something that occurs in other environments as well. 

I'll review my code later this week to see if I can notice anything.

**Comment by alexwhitman** [comment]
I've found a way to consistently reproduce.  Simply opening a new window (I've tried with nautlius and gedit) and positioning it over existing terminal windows, then opening the Quake mode window exposes the issue.  Video for example: http://sendvid.com/ela6ak1n

**Comment by gnunn1** [comment]
So I've tried on my 16.04 VM and still cannot reproduce the issue locally unfortunately.

**Comment by alexwhitman** [comment]
After further testing, it only happens when the "Set hint for window manager to disable animation" setting is enabled.  If I disable that then windows no longer get moved to the front.

I don't particularly use that setting (must have left it enabled after testing it) so from my perspective I no longer have the issue.  Feel free to close unless you want to investigate it further.

**Comment by gnunn1** [comment]
So this only seems to happen when you create the quake window for the first time. If you edit, place the other window on top of the terminals again, and re-activate the quake window  things work as expected.

I also can not duplicate this in gnome-shell or ubuntu 16.10 so I think I'm just going to chalk it up as a quirk.
