### ISSUE TITLE
scrolling not working

### ISSUE THREAD

**Issue by lucazade** [gnunn1/terminix#519]
I'm using terminix 1.3.0 in Manjaro 16.08 with Plasma 5.7.0,
sometimes the mouse scrolling is not working, it comes back working
switching the focus to another window then back to termininx.

**Comment by gnunn1** [comment]
I don't officially support Plasma since I would expect most folks to use a Qt based console on KDE like konsole. Having said that, what GTK theme are you using with Plasma? Also, any chance you have gnome-terminal installed and could see if you could reproduce with that.

**Comment by gnunn1** [comment]
@lucazade Any update on this with regards to my questions?

**Comment by gnunn1** [comment]
No response from OP, closing.
