### ISSUE TITLE
Zoom In/Out to increase/decrease text size

### ISSUE THREAD

**Issue by alunux** [gnunn1/terminix#52]
In Gnome Terminal, I use use the following key combinations:
 - Zoom in: Ctrl++
 - Zoom out: Ctrl+-
 - Normal size: Ctr+0

Is there another shortcut like this in terminix? Thanks.

**Comment by gnunn1** [comment]
I'll add this in for the next release, it's literally 15 minutes worth of effort. Just missed it since I never use this feature personally

**Comment by coreybruce** [comment]
So I zoomed into this report and I'm wondering if the feature will be added
