### ISSUE TITLE
Search bar does not support Paste command (under Wayland?)

### ISSUE THREAD

**Issue by bagage** [gnunn1/terminix#520]
Using debian unstable, gnome-shell 3.22 and terminix master 1.3.0 (but also released version 1.2.0), I cannot paste anything in the search bar:

1. Open search bar with `<Ctrl>+F`
2. Paste clipboard content with `<Ctrl>+V`
3. Instead of being pasted in search bar, the content is pasted on the prompt.

However using right click menu copy/paste, it works as expected.

**Comment by gnunn1** [comment]
So Arch Linux just upgraded to 3.22.1 and I cannot reproduce this. Can you try on 322.1 and see if it is fixed for you?

**Comment by bagage** [comment]
OK, actually found the reason. I remapped paste to `Ctrl+V` instead of `Ctrl+Shift+V` but it seems that somehow my shortcut is getting overridden by someone else, pasting to the terminal instead of the search bar.
That's actually not specific to Wayland as it also happens on X11.

**Comment by bagage** [comment]
Thanks a lot @gnunn1, you rock!
