### ISSUE TITLE
Easy way to save/load JSON color theme

### ISSUE THREAD

**Issue by bestouff** [gnunn1/terminix#527]
I found no way to easily save or load a color theme. The proposed themes are to be installed manually in `/usr/share` ... not that good.
I would prefer if there was a way to load and save a JSON file for the color theme.

**Comment by gnunn1** [comment]
Note that themes are also loaded from ```~/.config/terminix/schemes```.

**Comment by bestouff** [comment]
OK fine, but:
- this is totally not discoverable (how could I guess, the `~/.config/terminix/` directory doesn't even exist)
- there's still no way to export a nice hand-made color theme to another machine

**Comment by arcticicestudio** [comment]
This is a default path based on the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html).
Anyway, for the second point there should be an *Export* button in the *Colors* and a field to set the theme description.
Maybe you can go ahead and try to do a PR for it.

**Comment by bestouff** [comment]
The problem with XDG dirs is that you don't know their name before they exist. Case in point, do an `ls ~/.config` and watch the variety of case, spaces or caret, etc. So you can't guess if it's `~/.config/terminix` or `~/.config/Terminix`.
As for the PR, sorry I won't learn D just for that. Otherwise of course I would.

**Comment by arcticicestudio** [comment]
Well, the naming is indedd a problem I noticed with JetBrain products e.g. `~/.local/share/JetBrains`.
This is definitely a improveable point in the spec.
For this project there should be a note in the README for paths the application checks.
Even better: A man page which includes a *Files* section

**Comment by gnunn1** [comment]
I've added a new Export button to the color page that allows you to save a custom theme to a file, otherwise the button is disabled. The file dialog opens to the ```~/.config/terminix/schemes``` directory making it more discoverable.

Note that the filename is used as the theme name.

**Comment by bestouff** [comment]
Sounds really good !
Thanks,
        Xav
