### ISSUE TITLE
STDOUT eye candy

### ISSUE THREAD

**Issue by iax7** [gnunn1/terminix#528]
Not sure if this is actually possible to achieve, but here it goes:

Currently when using my pc I have a wonderful program that analyzes the command stdout and colorizes it using regex. ([grc](https://github.com/garabik/grc)) The result is something like this:
![image](https://cloud.githubusercontent.com/assets/6983510/19450891/d611e4dc-9470-11e6-8bf1-eaf9070d775b.png)

The problem is when I'm connected to a remote box using ssh. The program is not installed remotely and installing it is often no possible.

The question here is if there's a way to capture the command that was used, and the stdout before it is shown in Terminix in order to emulate this functionality locally.

**Comment by gnunn1** [comment]
I don't see any way to do this, sorry.

**Comment by iax7** [comment]
Now that I'm using iTerm2, I saw this feature somewhat implemented.
![image](https://user-images.githubusercontent.com/6983510/45104153-0c070f00-b0f7-11e8-9921-2bf81fb81630.png)

**Comment by gnunn1** [comment]
There's no way for me to do this as VTE is responsible for rendering the output not tilix, sorry. While I could fee color escape codes into the stream, the way triggers work is on blocks of output so I cannot insert the escape code with the color at the right spot.
