### ISSUE TITLE
Custom Scripts

### ISSUE THREAD

**Issue by iax7** [gnunn1/terminix#529]
When having lots of customization scripts, aliases and common tasks, a feature to assign a **script** to a keyboard shortcut or event (like using ssh) to be executed through the stdin in the remote machine (pretty much like a paste) would be excellent when using a lot of remote hosts.

**Comment by gnunn1** [comment]
Isn't this essentially the same as #88?

**Comment by iax7** [comment]
Yes, I think it is. 
![image](https://cloud.githubusercontent.com/assets/6983510/19453642/bd189af6-947b-11e6-8156-e6c973f464f4.png)

I'm closing it.
