### ISSUE TITLE
VTE extends the parent window

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#53]
As it is seen on 1:13
https://www.youtube.com/watch?v=KLTvMt8noes&t=1m13s

**Comment by gnunn1** [comment]
Well I agree, cool bug. The video is titled on Fedora (Rawhide), can you confirm this is on Rawhide as I am not able to duplicate it on 3.18. If it is a Rawhide issue, please close this bug and add it to the list of issues in #16. If it's on Gnome 3.18, let me know what distro and theme you are using and I'll see if I can replicate it.

**Comment by alex285** [comment]
@gnunn1 yes it is on Rawhide and Gtk 3.19.7
I will test against 318 in a couple of hours and move it on #16 if.

**Comment by bil-elmoussaoui** [comment]
Can't confirm this on 3.18

**Comment by alex285** [comment]
Cant reproduce it either on Gnome 318. Should I change the title to 320?
I dont know how to test something similar with other program on 320, so to make sure it is a Gnome bug.

**Comment by gnunn1** [comment]
Does it happen with the Nautilus sidebar?

You can close this issue and reference it in the Gnome 319 issue, I'm using
that issue as a catch-all for problems against 3.19.

**Comment by gnunn1** [comment]
Gnome 319 issue, moved to their.

**Comment by alex285** [comment]
No it doesnt happen on Nautilus (it has min width there though), neither on Builder or any dual panes on Gtk 319
