### ISSUE TITLE
[Enhancement] Add option to hide on lost focus

### ISSUE THREAD

**Issue by lpinner** [gnunn1/terminix#530]
The new quake mode is great, thanks.  Would you consider enhancing and adding a preference to hide the quake mode Terminix window when it loses focus (ala guake and qterminal)?

**Comment by gnunn1** [comment]
I had a look at this, the issue is when you open a dialog or other window like Preferences the quake loses focus and disappears which is probably not desirable. It would need to be tweaked when the focus is switching to other terminix windows and not hide in those cases.

**Comment by egmontkob** [comment]
See also https://bugs.launchpad.net/gnome-settings-daemon/+bug/1244090.

**Comment by lpinner** [comment]
Guake also gets hidden when its preferences dialog is opened. It's never been an issue for me personally.   Nor has the GSD/USD global shortcut key focus issue caused me any problems with Guake (because when I'm using a global shortcut I'm doing something else so I want Guake hidden).  

If you think that's too much of an issue, even as a non-default preference, no problem, I'm sure I can cope :).  It's just one of those "works for me" things that I'm used to and saves a lot of F12 (default guake key) presses when switching away from the terminal. Even at the cost of having to hit F12 every now and again to bring the terminal back if it gets hidden when I open preferences (which is almost never once I get it set up to my liking) or use a media key to change volume, skip a track etc.

**Comment by gnunn1** [comment]
No worries, I will have a look at this but I really want at least dialog parented to the window to work at a minimum. I think it's doable anyway.

**Comment by alexwhitman** [comment]
So the way guake does it is by having variables recording whether dialogs/windows are being shown: https://github.com/Guake/guake/blob/master/src/guake/guake_app.py#L619

Possibly not as straight forward to do here as dialogs/menus etc are split across appwindow.d and application.d but doable.

**Comment by gnunn1** [comment]
Feature added and made it so that the window will not hide when a dialog is shown like Advanced Paste or Layout.
