### ISSUE TITLE
Assign keyboard shortcut to accept popup dialog

### ISSUE THREAD

**Issue by iax7** [gnunn1/terminix#531]
When pasting from clipboard or inserting a password I need to grab my mouse and click in the default button. 
![image](https://cloud.githubusercontent.com/assets/6983510/19453978/11f3ddb4-947d-11e6-9d1f-1d23e57ad183.png)
or
![image](https://cloud.githubusercontent.com/assets/6983510/19454029/41085ef4-947d-11e6-8d19-6f7e934d28f3.png)

a CTRL + ENTER would be fine to accept after a quick change/selection
.

**Comment by gnunn1** [comment]
Modified the dialog so that if the textview has focus you can use ctrl-enter to accept the default for the dialog.
