### ISSUE TITLE
terminix --quake windows height

### ISSUE THREAD

**Issue by tagplus5** [gnunn1/terminix#532]
How can i change window default height in quake mode?

**Comment by gnunn1** [comment]
Open a normal Terminix window and use the preferences dialog.

**Comment by tagplus5** [comment]
I set 40 rows but i get this
![screenshot from 2016-10-18 19-10-24](https://cloud.githubusercontent.com/assets/2699260/19486404/ee4938ba-9566-11e6-95bb-215b06db27ad.png)
Normal window show 40 rows normally
![screenshot from 2016-10-18 19-05-21](https://cloud.githubusercontent.com/assets/2699260/19486431/07996d30-9567-11e6-954a-3ca9f146423a.png)

**Comment by gnunn1** [comment]
That's the Profile dialog, use the Preferences dialog adn adjust the height in the quake tab. 

![screenshot from 2016-10-18 12-16-50](https://cloud.githubusercontent.com/assets/9358238/19486536/ca5f6c2e-952c-11e6-8b43-871ea5c9ed3b.png)

**Comment by tagplus5** [comment]
Thanks. Its about Unity. I see app menu only for maximize windows when i set "Show menus for a window" "In the window's title bar"

**Comment by qazip** [comment]
Is the maximum height for quake mode 90%? Why not 100%?

**Comment by gnunn1** [comment]
@qazip see #617 for an explanation and history
