### ISSUE TITLE
In quake mode, show terminix in the focused monitor 

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#535]
Could be nice to have an option to show terminix in quake mode in the focused monitor.

**Comment by gnunn1** [comment]
Feature added and made it so that the window will not hide when a dialog is shown like Advanced Paste or Layout.

**Comment by gnunn1** [comment]
Sorry, closed the wrong one, I haven't looked at this yet.

**Comment by gnunn1** [comment]
This isn't feasible in Wayland and I'm not sure this is feasible in X11, do any other applications have this functionality (Guake, Tilda, etc)?

**Comment by edubxb** [comment]
I've no idea if other apps has this functionality, sorry.

**Comment by mifas** [comment]
Guake and Tilda has. And working perfectly
