### ISSUE TITLE
App menu unavailable on ubuntu-mate desktop

### ISSUE THREAD

**Issue by blonchkman** [gnunn1/terminix#538]
Hello,

there is apparently no terminix app menu available on ubuntu-mate 16.04 using mate-desktop 1.14.1-1~xenial1.01. Sure, i can live with this ;)

Might someone be nice enough to confirm ?

Kindest regards

**Comment by gnunn1** [comment]
Geary has been doing some work on this lately, might be able to apply the same workaround once they get it fully sorted.

https://bugzilla.gnome.org/show_bug.cgi?id=770617

**Comment by blonchkman** [comment]
thank you for your hint, @gnunn1
i'll keep an eye on it.

**Comment by phw** [comment]
Does this also help with #241 ? Or if not could this be adapted to that use case?

**Comment by phw** [comment]
Just tested myself, the second part of the patch really fixes the Unity issue from #241 :D Great
