### ISSUE TITLE
"Unfocused dim" not working (from master)

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#541]
As can be seen in the screenshot below. The left tile should be darkened, but they are the same. I'm using Arch, terminix-git compiled from master with LDC. The Gtk theme is Arc. Thanks!

![unfocused_dim](https://cloud.githubusercontent.com/assets/2356842/19657978/f4bb541a-9a04-11e6-84a4-1e78693645ab.png)

**Comment by dsboger** [comment]
That was fast! Thanks!

**Comment by gnunn1** [comment]
It was a simple fix, I have to draw handlers on the VTE now that I added support for badges, looks like having the first handler use the Scoped context is causing issues.
