### ISSUE TITLE
Borders in quake mod

### ISSUE THREAD

**Issue by DeepDlueIV** [gnunn1/terminix#542]
Can you please remove 1px borders in quake mod? It looks awful ^)
Tested in ubuntu 16.10 and ubuntu-GNOME 16.04 with Arc and Adapta dark variant themes. 
Btw i track your git whole year and with quake update i have finally moved to terminix. 
bb guake and gnome-terminal ;) 
TX

**Comment by gnunn1** [comment]
No plans to do so as the other option of having it un-bordered when the width is less then 100% looks worse in my opinion. 

I'm open to adjusting the border color though, I'll have a look at how it looks with Arc.

**Comment by gnunn1** [comment]
I've changed this to shaded black which seems to work reasonably well across most themes, give it a try and let me know what you think.

**Comment by DeepDlueIV** [comment]
No updates in ppa. I have tried to build itself with dmd and phobos. Got an error. Switch terminix to bright theme variant and dont give a damn now :-)
