### ISSUE TITLE
Empty window with no terminal after closing last terminal

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#543]
To reproduce:
1) In the preferences, ensure "Close window when last session is closed" is unticked.
2) Open a new terminix instance
3) Hit Ctrl+D to close the terminal

Expected: A new terminal opens
Actual: No new terminal opens, just the application background colour is visible.  In Quake mode the window horizontally shrinks down to the minimum it can while still fitting in the title bar buttons.

**Comment by gnunn1** [comment]
If this is on master it might be caused by the refactoring I did on the session object where it is now a two step process of creating it and then initialising it. I'll have a look later tonite.

**Comment by alexwhitman** [comment]
Yes, sorry, this is on master.

**Comment by gnunn1** [comment]
Thanks for reporting this, it was actually a bigger issue as creating new sessions had issues as well.
