### ISSUE TITLE
(re)Name a whole window

### ISSUE THREAD

**Issue by dbrodie** [gnunn1/terminix#544]
Unless I missed something, it is currently possible to rename a session and a terminal/layout. I didn't see any way to rename a window.

My use case involves having multiple windows with very similar sessions between them. and I would like to name them something that would make it obvious in the gnome-shell overview on which window I am working on (for example, Production / Staging).

Another example, I open a new window when I am starting something new, I would like to name what I am doing in the window and then have as many sessions as I need in that "task".

**Comment by gnunn1** [comment]
Thinking how about this, currently the window name is based on the current session, i.e. ```Terminix: ${session_name}```. Maybe a solution is to simply support variables here like elsewhere and let users specify it however they wish in Preferences.

**Comment by gnunn1** [comment]
One other thought, clicking the title in the header bar should directly edit the session name.

**Comment by gnunn1** [comment]
I've completed this feature and checked it into master. There are really two parts to this feature as follows:

* You can set a new preference in the Appearance tab to determine what the default title for an application window is. This can use variables ```${appName}```, ```${sessionName}``` and ```${sessionNumber}``` and Terminix will substitute them accordingly.

* You can override the title for a specific window by clicking the title, an edit box will appear and you can create a new title as desired that will only apply to this window. The same variables above are supported. To use the default title, simply clear the custom title in the edit box.

Note that setting a per-window custom title when disable-csd is active is not currently supported. Also note that the wiki FAQ has been updated to include the variables above.

**Comment by dbrodie** [comment]
Very cool, thank you!
