### ISSUE TITLE
Grey screen displayed instead of a terminal for new sessions

### ISSUE THREAD

**Issue by loops** [gnunn1/terminix#548]
Not much more to say than the title.  This didn't seem worthy of a pull request,
but trying to paste a patch in this text box was horrendous.  Here's a gist instead:

https://gist.github.com/loops/8e95a133a07b729b1761016732b5fb3a

If you prefer a pull request, can do that.

**Comment by gnunn1** [comment]
I think I fixed this already in master but I'll double check later tonite.

**Comment by gnunn1** [comment]
Checked, this was fixed yesterday as part of #543 with this commit:

https://github.com/gnunn1/terminix/commit/80985d663b1d451c8d15b1299127bfdac218eaa3

If you are not finding this to be the case after getting the latest from master, re-open the bug and I'll have another look.
