### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by davidosomething** [gnunn1/terminix#55]
Just leaving some notes here on configuration:

## Shortcut keys

You can customize keyboard mappings via `dconf-editor`:

![dconf](https://cloud.githubusercontent.com/assets/609213/12541875/36041580-c2ea-11e5-86f7-ebe1f17bdee7.png)

## Custom schemes

Colorschemes can be installed by adding JSON files with hex color data to `/usr/share/terminix/schemes` (or wherever `$TERMINIX_SHARE` was set to on install).

**Comment by gnunn1** [comment]
You can customize shortcuts in the preferences dialogue, no need to go to dconf-editor for this unless it's what you prefer.

Feel free to add a wiki page on customisation, it would be greatly appreciated.

**Comment by davidosomething** [comment]
ah didn't see how to get to prefs, but found it right clicking app icon
