### ISSUE TITLE
Cannot put quotes in command field

### ISSUE THREAD

**Issue by sametmax** [gnunn1/terminix#552]
In the regex => command matching configuration windows, if you put quotes (") in the 'command' field, it will make terminix crash. It will also be unable to restart again:

```terminix
2016-11-03T16:23:54.187:app.d:main:113 Une exception inattendue est survenue
2016-11-03T16:23:54.187:app.d:main:114 Erreur : Quote located in unquoted token
```

I'm guessing the input is not escaped properly. Also, since I don't know where is terminix configuration stored, I can't manually fix my setup. Can you help me with this ?

**Comment by gnunn1** [comment]
Terminix configuration is in dconf so you can use dconf-editor to change it manually. The configuration is stored in com/gexperts./Terminix, this item would be in one of the profiles.

Thanks for reporting this, I'll have a look at the issue tonit

e.
