### ISSUE TITLE
[Appearance] Quick Access to Terminal Title Style

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#554]
On Appearance Preference, there is "Terminal title style" option with 3 items
1. Normal  
2. Small
3. None

This is something I want to regularly switch (and affects Terminix UI a lot!), so I want to ask if it is possible to add this option on title bar, on a separate 3-state button, or inside the "Three Lines" menu popover, because going on preferences window is really inconvenient. 

I know we can configure a shortcut for it, but there is not much room for shortcuts :)

**Comment by gnunn1** [comment]
No plans to add this as I think the shortcut is sufficient. I can't add everything to menus as it would make the UI unwieldy, I just don't feel this is used enough to warrant it being a menu item.
