### ISSUE TITLE
Get current directory in custom link commands

### ISSUE THREAD

**Issue by sametmax** [gnunn1/terminix#555]
I created a custom link to match those file paths:

```
src/ww/wrappers/strings.py: note: In member "to_bool" of class "StringWrapper":
src/ww/wrappers/strings.py:725: error: Unsupported left operand type for >> ("FStringWrapper")
```
The regex `((?:^|\s)([^¤]+?\.py(?:\:\d+)?))` extract `src/ww/wrappers/strings.py:725` and runs `subl '$1'`.

In that case it will run `subl src/ww/wrappers/strings.py:725`.

The problem is that `src/ww/wrappers/strings.py` is a relative path, and the command is executed in a new shell, which current directory is set to `$HOME`. Bottom line: this creates a new file in my home directory instead of opening the existing one.

I would need a way to get the directory the terminal is currently in so I can pass it to the command, like `${directory}` in tab names.

**Comment by gnunn1** [comment]
I'm confused, the only python in Terminix is the Nautilus extension. Is this what you are filing a bug against?

**Comment by gnunn1** [comment]
Oh now I get it, sorry. I'll have a look at that, I'm  thinking when it executes the custom program it should set the current working directory so that relative paths can be resolved.

**Comment by sametmax** [comment]
Yes. I think the related code is : https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/terminal/terminal.d#L1495

There is a workDir parameter do solve the problem: https://dlang.org/library/std/process/spawn_process.html

**Comment by hasparus** [comment]
firsly, I wanted to say Tilix is quite amazing.

I was wondering if this issue reappeared recently. When I echo $(pwd) to a file, I get my $HOME dir, what makes relative custom links impossible to handle.
