### ISSUE TITLE
"terminal-split-right" is ignored

### ISSUE THREAD

**Issue by sametmax** [gnunn1/terminix#557]
`terminix --action=terminal-split-right` does not bring the current instance windows on top, nor does it add a new terminal to the current session.

`terminix --action=app-new-session` work exactly as advertised, suggesting it's a bug in the first command, or I'm missusing it and documentation should be updated.

**Comment by gnunn1** [comment]
The actions got re-factored some time ago but I forgot to update the wiki. The correct action is ```session-add-right``` and I tested it to make sure it works. The wiki has been updated as well, thanks for reporting this.
