### ISSUE TITLE
Blinking shell when focused and fn keys are pressed

### ISSUE THREAD

**Issue by fb87** [gnunn1/terminix#558]
Is this a bug or a feature? This may be helpful at control commands, but should maybe not be done when pressing louder/quieter/brighter/darker/etc. Distinction of cases would be nice!

**Comment by gnunn1** [comment]
I think this is a bug(?) with VTE, I can replicate it with gnome-terminal. If you have gnome-terminal installed, can you try it out there as well to confirm.

**Comment by fb87** [comment]
In gnome-terminal, just the cursor is blinking – in Terminix the cursor, the background and the title of the current terminal-window.

**Comment by gnunn1** [comment]
OK that's really weird, I can't reproduce that. I was thinking you were talking about the cursor which blinks rapidly when use the FN key with something like darken/brighten the screen. On my system only the cursor blinks, nothing else does.

What distro and desktop environment are you using?

**Comment by fb87** [comment]
Fedora 24 with GTK 3.22.

![terminal](https://cloud.githubusercontent.com/assets/10520767/20042083/0c40d5aa-a474-11e6-9bac-9637ae6a8c3b.gif)
![terminix](https://cloud.githubusercontent.com/assets/10520767/20042084/0c467b86-a474-11e6-956e-cbb2a52769ba.gif)

**Comment by gnunn1** [comment]
Thanks, that is very helpful. I'm using Arch with GTK 3.22 and I don't get that behavior other then the cursor blinking rapidly just like in gnome-terminal. I don't see how anything I'm doing in Terminix would cause that behavior but you never know. 

Which version of Terminix are you using 1.3.0 or are you building it form git?

**Comment by fb87** [comment]
I'm using 1.3.0 from the heikoada repo. Maybe you can test this in a VM or we see what happens with F25 in 11 days?

**Comment by gnunn1** [comment]
Yeah, I'll try that but I'm not overly optimistic about replicating it in a VM.

BTW, if other users of Fedora 24 are seeing this same behavior I'd be interesting in knowing it.

**Comment by fb87** [comment]
I can test it on my TV this week.

**Comment by gnunn1** [comment]
Oh one last question, is this Wayland or X11?

**Comment by fb87** [comment]
X

**Comment by gnunn1** [comment]
I almost wonder if what is happening is the terminal is losing focus very briefly. Do you have the the option to dim the terminal when not focused enabled?

**Comment by gnunn1** [comment]
This is more just a note to me, I have a suspicion that the OSD is stealing focus very briefly which results in this behavior. Some related links to this:

https://bugs.launchpad.net/ubuntu/+source/notify-osd/+bug/694224
http://infra.in.zekjur.net/archives/i3-discuss/2011-November/000348.html

More investigation required.

**Comment by fb87** [comment]
When the window isn't focused and I press those keys, there is no blinking. But I don't know where more dim options should be available?

**Comment by gnunn1** [comment]
In the Profile dialog under Colors there is a slider to set the Dim percentage and in the Advanced pop-up you can select a Dim color. If the Dim slider is bigger then zero Terminix will dim the terminal when it is not focused.

I think the issue is that when terminix is focused and use those keys, an OSD (On Screen Display) appears for example showing the volume going up or down. I think every time you press a key it is very briefly stealing the focus so terminix flips from focused to unfocused and back to focused.

You notice this more in Terminix then gnome-terminal because Terminix reacts to focus changes in order to more clearly show the terminal that has focus when you have multiple split terminals.

When Terminix isn't focused it's not going through this cycle since it wasn't focused originally, it just stays unfocused.

**Comment by fb87** [comment]
Yes, when I place the slider on the left end, the backgrund blinking doesn't occur anymore, cursor and title still blink.

So this is a Gnome bug… would you open a bug report, since you know the details better than me?

**Comment by gnunn1** [comment]
Thanks, that pretty much confirms it's a focus issue with OSD and I think it's a bug in notify-osd, I'll do some further investigation and then report it accordingly.

**Comment by gnunn1** [comment]
I did some searching and there is a bug open for it here:

https://bugzilla.gnome.org/show_bug.cgi?id=687862
