### ISSUE TITLE
Badge color option should probably be separated from advanced colors

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#559]
Currently the badge color is configured in the advanced dialog in colors. I see different issues with this:

1. The advanced dialog is used to configure colors you want to have different from defaults, and it is only active when using theme colors is disabled
2. Once configured the badge color is applied whether use theme colors is enabled or not
3. There is also a checkbox beside the theme color, which seems to have not effect on the color actually used.

**Comment by gnunn1** [comment]
Thanks for testing this, quite pleased to get a bug report for this functionality.

Anyway, I've made some changes so it works the same as the other advanced colors. The intent is that the badge color would default to the foreground color unless it is specifically set (i.e. use theme colors and use badge color is checked).

Feel free to re-open if it is still problematic.

**Comment by phw** [comment]
Yes, the new behaviour makes sense. Just tested it, feels good and consistent.

> Thanks for testing this, quite pleased to get a bug report for this functionality.

Actually I have personally not much use for this, but since the VTE patches are now easily available on Arch I finally can give the advanced functionality a try :D Notifications and triggers are awesome to have.
