### ISSUE TITLE
Drag&Drop text into terminix

### ISSUE THREAD

**Issue by MetotoSakamoto** [gnunn1/terminix#56]
By draging text to terminix, get this.

$ terminix 
2016-01-25T13:44:41.978:terminal.d:getDragTerminal:1061 Oops, something went wrong not a terminal drag
Erreur de segmentation (core dumped)

Gnome 3.18
arch updated

**Comment by gnunn1** [comment]
I can reproduce, thanks for the report, I'll fix it for the next release.
