### ISSUE TITLE
Double icons after update

### ISSUE THREAD

**Issue by edivad7** [gnunn1/terminix#561]
After updating Terminix to new version I have faced this issue, there's a second fuzzy icon on the dock, even if I start it using the menu application, even if I start it using the shortcut.

![image](https://cloud.githubusercontent.com/assets/19225432/20055379/05d98e06-a4e1-11e6-89db-b1b73b0657dd.png)

**Comment by gnunn1** [comment]
How are you installing Terminix, from a package or manually? Is that the gnome-shell dock or something else?

**Comment by edivad7** [comment]
I installed terminix through Pacman (I'm actually using Antergos). That's Plank. It was ok until yesterday.

**Comment by gnunn1** [comment]
Please open an issue with Antergos as they do their own packaging of Terminix and this to me looks like a packaging issue.

**Comment by phw** [comment]
Could it be, that after the upgrade there was just another instance of Terminix running? Or does this behavior persist a restart?

I just tested with Plank on my Gnome 3 Arch installation, but this is not reproducable.

**Comment by dsboger** [comment]
The same happens to me with GNOME Shell if I update Terminix when Terminix is running. It fixes itself when I close Terminix and open it again, though. Maybe Plank is not refreshing the .desktop database after the installation? I think you could try updating other apps and see if the same happens?

**Comment by phw** [comment]
@dsboger Yes, that's exactly my suspicion on what probably happened, @dgavio can you test this again?

**Comment by dgavio** [comment]
I've tested it, for me closing terminix isn't enough, but rebooting the pc solved the problem. Now the icon is perfect.
