### ISSUE TITLE
Add position/alignment option

### ISSUE THREAD

**Issue by Anton-Latukha** [gnunn1/terminix#567]
As new quake drop-down feature appeared, I want to use Terminix.

I encountered a lack of a function.
I have configured Yakuake to take left half of screen and Guake - take right side. Terminix have _no such option_.
![preferences](https://cloud.githubusercontent.com/assets/20933385/20143060/13245102-a6a0-11e6-9989-60b066fab19e.png)

This option is crucial for my workflow. I can have terminal tabs on half of screen and any other browsing/messaging on the other.
That creates a synergy between looking for info/articles on the web, and applying them to servers/hosts.
And backwards. I can look-up how I done something/man and contribute to the web, or messaging.
![woking](https://cloud.githubusercontent.com/assets/20933385/20143072/2643f198-a6a0-11e6-943c-5cb68fa5b36c.png)
In Terminix, for now, this is not possible.
![not-really-cozy](https://cloud.githubusercontent.com/assets/20933385/20143075/28f3ee34-a6a0-11e6-95e7-8cc3820559a6.png)
It appears above all other windows and makes using other aplication with it not possible. Making it not usable for me right now.

Thank you all. I look forward to use it and contribute more.

I use latest stable Terminix 1.3.5 on ArchLinux with KDE Plasma.

**Comment by gnunn1** [comment]
That makes perfect sense and I'll add within the next few days. One question, is all that is needed is a simple Alignment option (Left, Center, Right) like in Guake or does this need to be more fine-grained like Yuake is doing in your screenshot. I would really prefer the simple option but would consider the more complicated one if absolutely necessary.

**Comment by Anton-Latukha** [comment]
For me Alignment option is everything I need, and also for what I can imagine.
+ it sort-of continue embracing Terminix tiling philosophy, aligning Term in regular DE.

**Comment by franzhuang** [comment]
Thanks for adding "Window position" feature in quake mode, however, I get used to have terminal window at other position other than up or down or center. I use alt+F7(under gnome) to change the position of  a window, but next time I call drop down window , it appears at default position.
Is there config file for change the x, y position for drop down window in quake mode ?
