### ISSUE TITLE
VTE Configuration Issue

### ISSUE THREAD

**Issue by MetotoSakamoto** [gnunn1/terminix#57]
Don't solve the issue.

Gnome 3.18
Arch updated

**Comment by gnunn1** [comment]
Not solve what issue, can you provide more details?

**Comment by MetotoSakamoto** [comment]
Yes, when I started Terminix for the first time, a dialogue box said me "you have a VTE Configuration Issue... but be cool, go to https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue to solve it.

After editing bashrc, and check on option in preferences,

Still no feature like I view in your screenshoot (https://camo.githubusercontent.com/6d5e88d80ccd7357a606d87727ada972b28cade4/687474703a2f2f7777772e67657870657274732e636f6d2f696d672f7465726d696e69782f7465726d696e6978322e706e67) are working (ex colored prompt, style prompt) and no suggestion completion see in this video.

I don't know if I'm clear, and if this a bug related to vte...

**Comment by gnunn1** [comment]
The nice prompt in my screenshots don't have anything to do with terminix, it's a feature of [powerline](https://github.com/powerline/powerline) and it works in most terminals.

Hopefully that clears things up, if that explains it satisfactorily please close this issue.

**Comment by MetotoSakamoto** [comment]
Ok thanks for the light.

**Comment by simonbcn** [comment]
This error/warning is showed when I open a SSH session with Terminix (without another Terminix instance).

**Comment by gnunn1** [comment]
Thanks, can you open a new issue for this.
