### ISSUE TITLE
Synchronised scolling with Ctrl + Page Up/Down

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#570]
When terminals are synchronised, scrolling up and down with Ctrl + Page Up/Down only scrolls the active terminal.  The actions are not propagated to the other terminals.

**Comment by gnunn1** [comment]
This is a result of changes for #351, I'm aware of this issue and it's been on my mind to correct so now I have an excuse not to put it off any longer.

**Comment by gnunn1** [comment]
This should hopefully fix it, however I would really appreciate it if you could test it out. In particular, can you test that these keys work both in normal terminal and when using alternate screen (i.e. nano, vi, emacs, etc) as @egmontkob indicated there may be some differences between these two modes in how VTE handles things. It seems OK in my testing but a second look would be greatly appreciated.

You can see which keys are considered hard-code VTE keys and synchronized separately in this code: https://github.com/gnunn1/terminix/blob/master/source/gx/gtk/vte.d#L21

**Comment by alexwhitman** [comment]
So I got the details wrong and it should have been Shift rather than Ctrl.  That said it looks like the code takes Shift into account too, but it doesn't appear to work for me and still only occurs in the active terminal.

**Comment by gnunn1** [comment]
@alexwhitman It's definitely working for me here and I tested it with Ubuntu 16.04 in a VM as well. To test it, I split the terminal and syncrhonized input. I then ran ```ls -l``` a few times to generate some buffer. Finally hitting Shift-PageUp and Shift-PageDown to scroll the window up and down.

I added a trace statement so you should see something like ```Synchronizing key xxx```, can you confirm that it is showing up?

**Comment by alexwhitman** [comment]
*Sigh*, I know why it wasn't working.  I updated the git remote and then built, completely forgetting to actually update the master branch.  Today is not my day.

I'm away from the computer now until Monday so I'll test it then.  Sorry for the noise. 😄

**Comment by alexwhitman** [comment]
I've now tested the changes and can confirm that they work. :+1:
