### ISSUE TITLE
[Feature Request] Backup and Restore Current configuration

### ISSUE THREAD

**Issue by arcadian09** [gnunn1/terminix#571]
At this moment, unable to find the location where terminix pulls the store data for my profiles and settings. For new setups, would like to avoid manually restore terminix and simply restore my settings and preferences.

Thanks,

**Comment by gnunn1** [comment]
Terminix stores it's configuration in dconf and you should be able to use the dconf tool to migrate settings. To dump the setting:

```
dconf dump /com/gexperts/Terminix/ > terminix.dconf
```

To load this file back into dconf on a different machine:

```
dconf load /com/gexperts/Terminix/ < terminix.dconf
```

**Comment by dreamer** [comment]
After rename to Tilix, proper backup/restore commands are now:

    dconf dump /com/gexperts/Tilix/ > tilix.dconf
    dconf load /com/gexperts/Tilix/ < tilix.dconf

**Comment by zero77** [comment]
@dreamer  @gnunn1 
Will this also backup profile settings.
Also, is this already documented in the wiki or FAQ, thanks.

**Comment by dreamer** [comment]
@zero77 Just tested to double-check, as far as I can tell the profiles are backed up as well.

I don't know if this is documented in FAQ.

**Comment by zero77** [comment]
@dreamer 
Thanks

**Comment by peterrus** [comment]
Small script to do this: https://gist.github.com/peterrus/f7a8f6ce09ba6506b780f6ca8bceb74f

**Comment by bestouff** [comment]
FWIW I'm using this when installing a new machine (run that from a machine where Tilix is already configured):
```sh
dconf dump /com/gexperts/Terminix/ | ssh my_new_machine dconf load /com/gexperts/Terminix/
```
