### ISSUE TITLE
hideable scrollbar

### ISSUE THREAD

**Issue by etm** [gnunn1/terminix#572]
Please add an option to hide the scrollbar as in gnome-terminal (profile > scrolling).

**Comment by gnunn1** [comment]
It's already there in the Profile preferences page under the Scrolling tab, just uncheck the "Show scrollbar" option.

![screenshot from 2016-11-11 13-06-23](https://cloud.githubusercontent.com/assets/9358238/20225138/c55aa446-a80f-11e6-8463-303cc12d16a1.png)

**Comment by etm** [comment]
Oh my. No idea how i missed it. Thanks. Terminix is great.
