### ISSUE TITLE
How to hide application menu in quake mode?

### ISSUE THREAD

**Issue by ermolaev** [gnunn1/terminix#574]
Ubuntu 16.10

![screenshot from 2016-11-12 21-41-12](https://cloud.githubusercontent.com/assets/938305/20240094/02452e8c-a921-11e6-864f-cf8be71d05d5.png)

**Comment by gnunn1** [comment]
I'm not able to reproduce in my Ubuntu 16.10 VM. Can you help me by answering the following questions:

- What version of terminix are you using?
- In the Ubuntu System Settings, under Appearances/Behavior, what do you have set for the option "Show the menus for a window"?
- Do you have the Disable CSD option in terminix enabled (requires using dconf-editor to modify this)?

**Comment by gnunn1** [comment]
Also, this might be caused by the forcing of the app menu in Unity that I added for 1.3.5 of terminix. I should probably exclude this when running in quake mode but I'd like to be able to reproduce it if possible.

**Comment by ermolaev** [comment]
version 1.3.5
Show the menus for a window = In the window's title bar, (if set In the menu bar application menu not showed)

if Disable CSD set to true application menu also not showed
![screenshot from 2016-11-13 04-02-16](https://cloud.githubusercontent.com/assets/938305/20243019/40337a52-a956-11e6-830d-f514049df17c.png)

also I using `numix-gtk-theme`

**Comment by gnunn1** [comment]
Thanks, I was able to reproduce and fix it in my local VM.

**Comment by ermolaev** [comment]
Thanks!
