### ISSUE TITLE
Issues with setting an environmental variable and executing a command right after it

### ISSUE THREAD

**Issue by pakro** [gnunn1/terminix#575]
using a script:

terminix -w "/some/directory/" -x "ENV_VAR=someValue mvn spring-boot:run" throws an error.
Am I doing something wrong or is this simply not possible?

**Comment by gnunn1** [comment]
When you execute a command, terminix doesn't run a shell but instead just executes the command. Thus you can't chain multiple commands directly, however you can try something like this:

```
terminix -x bash -c "ENV_VAR=someValue mvn spring-boot:run"
```
And see if that works. Most terminal emulators behave the same way. If you google ```gnome terminal execute multiple commands``` you'll find lot's of discussion about it.

**Comment by pakro** [comment]
Thank you very much!
