### ISSUE TITLE
Questions about background image

### ISSUE THREAD

**Issue by laconbass** [gnunn1/terminix#576]
First of all - and not regarding the topic presented here - let me congrat @gnunn1 , terminix is really awesome and It ended up within my everyday-use toolset.
- - -

**kind-of use case scenario**

Both questions I'm presenting here bumped my head while testing the "background image feature", wondering if I can use that feature to let me distingish between tty environments quickly, a kind of "visual reinforce" to a "color-scheme-by-host" aproach I'm currently ussing.

> I don't want to waste your reading time, please let me know if it's clear what I'm talking about above.

## Question 1

> It's possible to set-up a background image w/alpha (i.e, *.png), so I can see the "stuff going on" under the terminix window?

I've tried with a png image, but it seems alpha channel gets coerced to solid black. I researched a bit too, but I'm not sure if this has to do with VTE usage ([seems possible](http://stackoverflow.com/questions/11686510/how-to-enable-transparency-in-vte-terminal)) or regards the [cairo image widget at `source/gx/gtk/cairo.d`](https://github.com/gnunn1/terminix/blob/master/source/gx/gtk/cairo.d) I've seen after a reading #341. (Related? #411)

## Question 2

> Is there any plan involving a profile-based `background-image` setting?

- - -

Please note I've digged at the [terminix wiki](https://github.com/gnunn1/terminix/wiki) and [through the issue tracker](https://github.com/gnunn1/terminix/issues?utf8=%E2%9C%93&q=background%20image) (most obvious related issue was #298), but I couldn't find a word about. Also note I'm just being curious about the background image feature, this isn't a thing I actually need to work with terminix.

Have a nice day!

---

Let me mention @egmontkob because I've seen it's active about the background-image feature, sorry if this annoys you

**Comment by f2404** [comment]
For question 1 - it's possible, I've support for that in xfce4-terminal recently: https://git.xfce.org/apps/xfce4-terminal/commit/?id=f784f668abe9dc8a35fa53a2032eddb52ac526a9

**Comment by egmontkob** [comment]
For question 2 - in Terminix you can have multiple panes (splits), and a single background image spans across them. This was a design decision made by gnunn1. As such, the concept wouldn't quite make sense - what should the background image be if there are multiple splits with different profiles?

In order to allow a per-profile background, we'd need to either redesign so that each split has its own background (IMO would look ugly), or force all splits to share the same profile (a way too strong restriction), or pick the background based on let's say the top-left or the oldest pane (totally arbitrary). In my opinion the current approach (the background is a global pref and not a per-profile one) is the best of these.

**Comment by gnunn1** [comment]
@egmontkob summarized point 2 well and is in alignment with my own thoughts. The other issue with per profile images is that managing performance and memory may be challenging if we apply the current method of caching the scaled image to each terminal rather then just st the window level.

If you are asking about this in the context of triggers, note that I just added the ability for a trigger to set a badge and that could be another option for visually differentiating terminals based on state. 

I'll apply the changes from @f2404 to Terminix to fix the alpha issue over the weekend.

**Comment by egmontkob** [comment]
> managing performance and memory may be challenging

I don't think there'd be a problem here. Sure you'd need to cache it for each terminal, but the overall size of these cached images would the same as the big one now.

From a technical point of view, I think this feature could be implemented without any problems. You _could_ even implement a global _and_ a per-terminal background applied at the same time, one being visible through the other if there's alpha/transparency involved, and let the users decide which one(s) they use. The main question is its usefulness compared to what we have currently and whether it's worth the required coding efforts.

**Comment by egmontkob** [comment]
> dragging of a splitter [...] could cause the UI to lag

That's a valid point!

> Personally I don't think the feature is worth the extra complexity it would bring.

Sure, it's your call :)

**Comment by egmontkob** [comment]
The history of this conversation is really messed up :D gnunn1 you accidentally _edited_ my comment and replied there, which makes it look like you said what I said and vice versa :D
