### ISSUE TITLE
CTRL + ↓ and CTRL + ↑ error

### ISSUE THREAD

**Issue by horosgrisa** [gnunn1/terminix#578]
CTRL + ↓ and CTRL + ↑ generate ^[[1;5B and ^[[1;5A, but tmux generate ^[OB and ^[OA. This breaks history-substring-search from oh-my-zsh.

**Comment by gnunn1** [comment]
This is probably an issue with the VTE rather then terminix, VTE is the underlying GTK widget that actually does the terminal emulation and is also used by gnome-terminal.

Can you try this in gnome-terminal and see if the issue is reproducible there?

**Comment by horosgrisa** [comment]
In Gnome Terminal also ^[[1;5B and ^[[1;5A.

**Comment by horosgrisa** [comment]
It's problem with vte

**Comment by gnunn1** [comment]
Thanks for the update.
