### ISSUE TITLE
Quake windows do not spawn on the right monitor

### ISSUE THREAD

**Issue by YerisAntonio** [gnunn1/terminix#579]
Currently using the quake mode in 3 monitors on my ubuntu gnome-shell 16.04, I tried the option to make terminix to always show terminal on an specific screen by declaring the number of the screen, but instead it shows up, wherever the mouse pointer is.

Kind regards

**Comment by gnunn1** [comment]
So I've tried duplicating this but it is working fine for me on Arch with Gnome 3.22. I run Ubuntu in Virtualbox to debug Ubuntu specific issues and I think Virtualbox supports multiple monitors so let me have a look at that tonite and see what I can find.

**Comment by YerisAntonio** [comment]
thank you, I use nvidia drivers too not sure if that may have something to do with it.

Regards, very nice app btw

**Comment by gnunn1** [comment]
I just tested in a 16.04 Unity VM with two monitors and it works fine there as well. I'm not really sure what to try next. Are you using the Ubuntu Gnome distribution?

**Comment by YerisAntonio** [comment]
Thats right! I am using the Ubuntu Gnome distribution, this happens at work and at home, same distro.

**Comment by gnunn1** [comment]
So I just tried Ubuntu Gnome 16.04 in a VM with the latest version from git and it is working fine as far as I can tell.

What version of terminix are you using?

**Comment by gnunn1** [comment]
@yerisantonio Are you still having this issue, if so could you let me know what version of terminix you are using?

**Comment by YerisAntonio** [comment]
yup, let me check my computer and be back to you

**Comment by gnunn1** [comment]
No response from OP, closing.
