### ISSUE TITLE
Merge Preferences and Profile Dialogs

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#581]
I was trolling through gnome-terminal bugs and noticed this nice mockup by Allan Day for merging the Preferences and Profile Preferences together. This would actually be pretty easy to do in Terminix given the current code style.

Mockup:
https://bugzilla.gnome.org/attachment.cgi?id=266172&action=edit

Bug Report:
https://bugzilla.gnome.org/show_bug.cgi?id=722114

**Comment by edubxb** [comment]
Looks great!

**Comment by gnunn1** [comment]
I've taken a first cut at this, seems to be working pretty well. There are a few things left to clean up as follows such as renaming a profile should rename it in the list and the title. Anyway, here's a screenshot showing what it looks like so far.

![screenshot from 2016-11-26 16-48-01](https://cloud.githubusercontent.com/assets/9358238/20644119/1fd51796-b3f8-11e6-8825-e138a9ac4622.png)

**Comment by edubxb** [comment]
How about changing the "Add Profile" button to look like NetworkManager dialog to add/remove networks?

![screenshot](https://cloud.githubusercontent.com/assets/1192339/20644417/e3c35fe2-b433-11e6-90c3-6cb5ac8bca68.png)

**Comment by gnunn1** [comment]
Yeah that makes sense from a consistency point of view...

...lol but you could have suggested it before I wrote the code! :)

**Comment by gnunn1** [comment]
An in case it's not clear, I'm just joking on that last post.

**Comment by gnunn1** [comment]
Done:

![screenshot from 2016-11-26 19-07-26](https://cloud.githubusercontent.com/assets/9358238/20644678/99b7408a-b40b-11e6-810c-c637fe2298d4.png)

**Comment by gnunn1** [comment]
OK I think this is basically done. If there are problems, and I'm sure there, just open new issues for them and I will deal with them.

**Comment by edubxb** [comment]
Amazing, good job!
