### ISSUE TITLE
Save remote connections

### ISSUE THREAD

**Issue by evfool** [gnunn1/terminix#583]
If possible, it would be great if layout saving would also store the remote location (and reconnect on reopen), e.g. in case of ssh into remotes.

**Comment by gnunn1** [comment]
I don't think this is really feasible. If you are using triggers, you can setup terminix so it knows the username and hostname that is being used. In theory, terminix could use that to automatically add an ```ssh username@hostname``` overrride command, however it wouldn't know about any other parameters passed to ssh such as exporting X.

I think the best course of action is just to do it manually. Before you save your layout, just set the override command in Layout Options for each terminal to the ssh command you want to use for that terminal.

Does that make sense?

**Comment by evfool** [comment]
Yes, it makes perfect sense, I didn't know about the session load command option, and if that gets saved with the layout options, then it indeed is a good workaround for my problem. Thanks for the pro tip.
