### ISSUE TITLE
Titlebar right-click menu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#584]
On Ubuntu in non-CSD windows, right clicking on a title bar will show a menu with options such as "Always On Top" and workspace related entries.
![title-right-click](https://cloud.githubusercontent.com/assets/422013/20630341/492b00ae-b328-11e6-9941-ac55f7756945.png)

Is there any way to make this menu appear when right clicking on the terminix title window?

**Comment by gnunn1** [comment]
I'm not sure I have any control of that menu, either the desktop environment or gtk is generating.

Having said that, wouldn't it be confusing on the terminal title because all of those options apply to the window not the terminal.

**Comment by alexwhitman** [comment]
Termin**ix** title, not termin**al** title. :smile:

It would be useful if it could be added, if only for the "Always On Top" option.

**Comment by gnunn1** [comment]
I really need to stop replying to issues on my phone :)

Anyway, this seems to be Ubuntu specific. In Gnome if set disable-csd to true I still get that  menu when I right click the titlebar. So it's something on the Ubuntu side, not sure how worthwhile it is to have a specific Terminix workaround for it?

**Comment by gnunn1** [comment]
@alexwhitman Since this is an Ubuntu specific issue and I don't have a nice way to easily work-around it, I'm going to close this. If you object or have an idea on how to fix it feel free to re-open and we can discuss.

**Comment by alexwhitman** [comment]
Turns out holding Alt and right clicking anywhere in the window will show the menu.  I don't know if it's possible to capture the right click on the title bar and then fake Alt being pressed before forwarding up the stack?  Appreciate that it's rather hacky and might not be something that you'd want to do even if it is possible.

**Comment by gnunn1** [comment]
Yeah, I don't think I want to program something like that it in though I do have a few workarounds for Ubuntu in place for other things. 

Maybe it's just me, but I'm hoping at some point Ubuntu works out a way to support GTK applications properly without forcing third party authors to work around their issues. None of these issues are major on their own, it's just as a collection they get irritating to deal with. Unfortunately I suspect with their planned transition from GTK to QT this isn't going to be a priority for them.
