### ISSUE TITLE
[VTE] Dim causes flickering with GNOME Shell OSD controls

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#585]
Reproduce. 
1. Open Terminix
2. Set Diming
3. Use Shell volume control

Output: 
VTE is losing focus and is flickering

Sorry for the dramatic video!
https://www.youtube.com/watch?v=q8sUdp32E6o

**Comment by gnunn1** [comment]
See #558, it's an upstream issue since OSD briefly steals focus.
