### ISSUE TITLE
Preference window lacks window controls on Ubuntu

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#587]
The new preference windows lacks window controls (close, minimize) and looks slightly odd with the gap between the pane titles ("Preferences" and "Global" in the image below).

![prefs](https://cloud.githubusercontent.com/assets/422013/20662278/b276ab3e-b54a-11e6-9840-5d9836a6b647.png)

**Comment by gnunn1** [comment]
Thanks, I'll have a look at the window controls. As for the gap, that's likely an issue with the Ubuntu theme, on Gnome the vertical line between the left and right panes looks like a seamless extension across the whole window.

![screenshot from 2016-11-26 19-18-39](https://cloud.githubusercontent.com/assets/9358238/20668984/9b70b1ec-b53f-11e6-8b18-fce819be4994.png)

**Comment by gnunn1** [comment]
@alexwhitman I've adjusted the colors of the headerbar split to look better, let me know what you think. If you aren't satisfied with them, you could try playing with the GTK Inspector to adjust them to see if you can achieve a better result. My CSS and color foo isn't the strongest :)
