### ISSUE TITLE
Mirroring behavior with every new terminal split

### ISSUE THREAD

**Issue by aastronaut** [gnunn1/terminix#588]
every split creates a mirrored terminal, instead of a new one - input becomes always synchronized (Synchronize Input is *un*checked).
was looking in all settings (Preferences and Profile) and couldn't find any option.
neither info on this behavior in the wiki nor in the filed issues.

...running zsh, installation from the Ubuntu PPA
```
~ terminix --version
Versions
        Terminix version: 1.3.5
        VTE version: 0.42
        GTK Version: 3.18.9

Terminix Special Features
        Notifications enabled=0
        Triggers enabled=0
        Badges enabled=0

~ lsb_release -d
Description:    Ubuntu 16.04.1 LTS
```

**Comment by gnunn1** [comment]
Hmmm, that's a weird one, I'm not sure what is happening here. Are the contents mirrored or is it actually a new terminal. i.e. if you do an ```ls``` on one terminal, split, do you see the results of ```ls``` on both the original and the new one?

**Comment by aastronaut** [comment]
`ls` in either one becomes `ls` in all splits. every input character is inserted into all splits as i type.
funny enough, with Synchronize Input checked, `ls` becomes even `llss` in two splits, `lllsss` in three splits etc.

**Comment by aastronaut** [comment]
problem solved - had byobu installed and installed it before terminix, this made my new split use the same tmux instance.

two solutions:
- the deinstallation of byobu fixed this behavior (obviously)
- a reinstallation of byobu now asks with a prompt on every new split what to do -> tileception

i feel a little stupid now
thanks for the help!

**Comment by gnunn1** [comment]
Glad you find the issue, thanks for letting me know what it was.
