### ISSUE TITLE
dub build --build=release error

### ISSUE THREAD

**Issue by kunamashina** [gnunn1/terminix#590]
When I run `dub build --build=release error` I get the following error at the end
```

terminix ~master: building configuration "default"...
Linking...
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
dmd failed with exit code 1.
```

Someone help please

**Comment by kunamashina** [comment]
you need to install libX11-devel library in order to solve this error

**Comment by kunamashina** [comment]
./install.sh succeeded but with graphical interface bug

http://imgur.com/Jmwptth

Title bar has missing background and icons for adding tiles right or bottom also have no icons

Please help to resolve this issue

**Comment by gnunn1** [comment]
What's the output of install.sh look like? I suspect the resource file isn't being compiled as it sometimes required the installation of s specific package on some distribution.

**Comment by gnunn1** [comment]
Closing, no reply from OP
