### ISSUE TITLE
Quit Terminix kills background window only

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#591]
To reproduce

1 Open two Terminix instances, A and B
2. On Terminix A run a long run task, for example "htop"
3. On Terminix B use quit menu

Output:
Terminix display the "There are processes still running, close anyway?" dialog, but for the Terminix A, when we are on Terminix B

If we select close, it will close Terminix A, but it will leave Terminix B open.

**Comment by alex285** [comment]
Are we sure we want "Quit" to close all instances? I know that is GNOME HIG but some applications get exceptions. For example GNOME Terminal and GNOME Calculator, that "Quit" only closes current window.

**Comment by egmontkob** [comment]
FYI: A bit of gnome-terminal discussion (with no conclusion as far as I recall): https://bugzilla.gnome.org/show_bug.cgi?id=766081

**Comment by f2404** [comment]
Another FYI: In xfce4-terminal, the menu entry is called "Close Window", and it closes current window only. There's no option to close all terminal windows.

**Comment by gnunn1** [comment]
Generally I'm the camp that yes it should close all windows. Having said that, the dialog could certainly be improved such as showing a list of all windows and processes running that makes it easier for the user to decide.

So not closing all windows is the bug IMHO.

**Comment by gnunn1** [comment]
I've done an initial iteration of my design. Essentially a new dialog gets shown when you attempt to close an application, window, session or terminal if that object has any running processes in the tree. The new dialog shows the processes that are still running and let's you cancel the close.

Note I'm not 100% happy with the look of the dialog yet, right now I'm showing the titles of the objects which can be confusing depending on how things are configured. Here's a screenshot of how it looks now, design input is welcome.

![screenshot from 2016-12-08 15-11-56](https://cloud.githubusercontent.com/assets/9358238/21026120/42da05ca-bd59-11e6-88ac-4d90fdb6a023.png)

**Comment by gnunn1** [comment]
I wrapped the titles in ```Window (..)``` and ```Session(..)``` and am reasonably satisfied with the result. I've closed this issue, however if someone has ideas on how to make this look better I'm happy to take the input.

**Comment by alex285** [comment]
Perfect!

**Comment by alex285** [comment]
@gnunn1 Is there any reason on the dialog to explicit need to choose what session to close? For example by default close all. But if we select 2/3, will quit only these 2

**Comment by gnunn1** [comment]
The selection is meaningless, it either closes everything or closes nothing. If it's not doing that then there's a bug, please open an issue.
