### ISSUE TITLE
Terminix doesn't start without trace

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#592]
Since https://github.com/gnunn1/terminix/commit/2e51f599cb76832c07ff8361c17311d5811e0d0f was merged, terminix no longer starts for me unless it was compiled with `--config=trace`.  I've tried both debug and release builds, both fail to start unless trace is enabled.

Reverting to the previous commit works as expected without trace.

**Comment by gnunn1** [comment]
It seems to be working fine for me here:

```
dub build --config=default
Non-selected package x11 is available with version 1.0.15.
Use "dub upgrade" to perform those changes.
Performing "debug" build using dmd for x86_64.
gtk-d:gtkd 3.3.1: target for configuration "library" is up to date.
gtk-d:gstreamer 3.3.1: target for configuration "library" is up to date.
gtk-d:gtkdgl 3.3.1: target for configuration "library" is up to date.
gtk-d:sv 3.3.1: target for configuration "library" is up to date.
gtk-d:vte 3.3.1: target for configuration "library" is up to date.
terminix ~master: building configuration "default"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
```

Can you post the errors you are getting?

**Comment by alexwhitman** [comment]
I've just reset to the latest HEAD and rebuilt and now it's working.  Slightly odd as I'd rebuilt a number of times previously where things weren't working.

There weren't any errors, everything built and installed fine but running `terminix` would just immediately exit.  Weird but working now so I'll close the issue.

**Comment by gnunn1** [comment]
That is weird, appreciate if you could keep an eye on things as a sanity check as I'm trying a few different things to address that memory leak issue.
