### ISSUE TITLE
Quake and Application Menu issue

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#594]
When you have the "Show Application Menu" toggled off in Tweak Tool, a little icon is added into the top left hand corner of your app with a popover effect showing those Application Menu options. This works great it 'normal' Terminix, but in Quake mode it leaves a transparent single line at the top of the window with a text button saying "Application" on the far left side.

![screenshot from 2016-12-02 14-29-31](https://cloud.githubusercontent.com/assets/3747347/20852657/c616bf68-b89b-11e6-99d7-7ebde758ee0e.png)

![screenshot from 2016-12-02 14-27-56](https://cloud.githubusercontent.com/assets/3747347/20852624/9a28603c-b89b-11e6-9e55-9de23bd9497e.png)

**Comment by gnunn1** [comment]
I'll have to look into this a bit more, the obvious solution of removing ```menu``` from gtk_decoration_layout isn't doing the trick.
