### ISSUE TITLE
Copy to paste buffer in colour

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/terminix#595]
It would be great if there was a way to preserve ansi colors when I copy and paste into something that supports it (e.g. libreoffice / google docs).

Use case is, when I'm copying something that has been logging errors / warnings, it's a lot easier to find what I need.

I guess this would need to construct html or rtf in the paste buffer for this to work.

**Comment by f2404** [comment]
To me, it rather looks like a feature request for vte, not for a terminal app. @egmontkob?

**Comment by gnunn1** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=365121

**Comment by egmontkob** [comment]
Yup, vte. Short summary: It's actually implemented, but enabled for unstable releases only. Grep vte's source for HTML_SELECTION.

**Comment by egmontkob** [comment]
I guess it should be controllable via an API, and in turn, apps could introduce a profile pref.

**Comment by gnunn1** [comment]
Sounds like a job for @egmontkob :)

**Comment by stuaxo** [comment]
That's awesome it's already in VTE, I rated the chance of this coming together fairly low when I opened the ticket if I'm honest !

**Comment by gnunn1** [comment]
Keep in mind that the last activity on that VTE bug report is April 2015, I'd say the chance of it happening anytime soon is pretty low.

I'm closing this issue since it requires upstream to make this available.
