### ISSUE TITLE
Option to hide headerbar for Quake mode

### ISSUE THREAD

**Issue by snaggen** [gnunn1/terminix#596]
it would be nice to have an option to use the quake mode with a minimum of window decorations (i.e. no headerbar) to have a clean non-intrusive experience.

**Comment by gnunn1** [comment]
I'll have to think about it, I'm not overly keen on it at first glance. How do others feel about this?

**Comment by PombaM** [comment]
I actually agree with @snaggen. Take a look for yourself:

Guake efficiently implements the spaces available to give user more screen -
![selection_001](https://cloud.githubusercontent.com/assets/11157420/20998370/6829701e-bd35-11e6-9b8d-69b9701c0e50.png)

Terminix has this unused space, wasting screen space -
![selection_002](https://cloud.githubusercontent.com/assets/11157420/20998376/6ca6b44e-bd35-11e6-9835-4d6809ee4d75.png)

**Comment by gnunn1** [comment]
@PombaM Doesn't guake though have the tab bar at the bottom which isn't being shown in your image which consumes the same amount of space as the headerbar? 

My concern here is without the headerbar is you lose a few things like seeing the number of sessions that are open, the number of pending notifications, terminal title (assuming you have terminal titles turned off), etc.

**Comment by PombaM** [comment]
Sorry if it feels like i am comparing Terminix to Guake but i feel like Guake is the only thing that comes close to Terminix!

To address you question, Guake does have  "tab bar" but it also has the option to hide it, so if we could have an option to hide the headerbar we could have the best of both world but i also see your concern so we could either have option to hide headerbar and/or reduce the size of the headerbar.

**Comment by gnunn1** [comment]
Ok thanks, I'll see what I can do.

**Comment by snaggen** [comment]
@gnunn1 You have valid points... 
My view comes from my use of quake style terminals I guess... I use it a temporary terminals, to open VPN:s, and do quick commands and things like that. I don't have long going sessions in there... for that I use regular terminals. So I have never had any use for session indicators and notification information, but I see your point. 
For a quake style terminal I suggest that info as some minimal overlay in the top right corner, and then add options for this in the popup menu (and of course as keyboard shortcuts). 

But for my kind of use case an hide option would do....

**Comment by gnunn1** [comment]
I'm going to see what's involved with adding an option to hide it when in quake mode.

**Comment by gnunn1** [comment]
As requested, I have added the feature. Any problems with it just open a new issue.
