### ISSUE TITLE
Quake mode is not always on top under Wayland

### ISSUE THREAD

**Issue by snaggen** [gnunn1/terminix#597]
My understanding is that the Quake mode would imply that the terminal is always on top. However, it seems that this doesn't work.

**Comment by gnunn1** [comment]
I'm setting the flag for this, might be a Wayland issue. I'll have a look into it.

**Comment by gnunn1** [comment]
I'm not able to reproduce, is there any application you notice in particular that it fails to stay on top for?

**Comment by snaggen** [comment]
The steps I have to reproduce: 
1. Open Terminix as a regular window and maximize the window (by draging it to the upper edge). 
2. In this terminal window, type "terminix -q"
   * A quake style terminix opens on top as expected.
3. Click in the full screen terminal window. 
   * The full screen terminal is now raised above the quake style terminal

In the scenario above, I expect the quake style window to remain on top.

**Comment by snaggen** [comment]
Looking at source/gx/terminix/appwindow.d it seems that the relevant code is commented out
            /*
            case SETTINGS_QUAKE_KEEP_ON_TOP_KEY:
                if (isQuake) {
                    bool keepOnTop = gsSettings.getBoolean(SETTINGS_QUAKE_KEEP_ON_TOP_KEY);
                    setKeepAbove(keepOnTop);
                    //setSkipTaskbarHint(keepOnTop);
                    //setSkipPagerHint(keepOnTop);
                }
                break;
            */

**Comment by snaggen** [comment]
I'm testing this on Fedora 25, Wayland session with 
terminix-1.3.5-1.fc25.x86_64
Just so you know the versions I'm using.

**Comment by gnunn1** [comment]
@snaggen Thanks for having a look, that code is commented out as I was thinking about making it a configurable option but decided against it. This line is where it is actually set, in the constructor:

https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/appwindow.d#L1340

I'll try using your steps to reproduce.

**Comment by gnunn1** [comment]
I can duplicate this issue using your steps so thanks for that, I suspect that's a gnome/mutter/wayland bug but I'll investigate more.

**Comment by gnunn1** [comment]
So I asked about the setKeepAbove on IRC and was told that "wayland doesn't allow clients to decide on neither the position nor stacking of their surfaces so this is no-op on wayland"

Looks like this is not fixable by me, sorry. If you are aware of a gnome application that is using keep above on Gnome/Wayland successfully, re-open this issue and I'll have a look at what technique they are using.

**Comment by gnunn1** [comment]
@debaetsr Extensions are different then applications because they are parented to the desktop window so they can use that as a reference whereas applications cannot.

**Comment by Queuecumber** [comment]
@gnunn1 Not sure if you found this but I can use the window menu (alt+space) and select always on top and it works until I close/hide the quake mode window. Probably there is a DE specific way to request this functionality that you'd have to implement for wayland

**Comment by gnunn1** [comment]
@Queuecumber I had not noticed that so thanks but unfortunately I'm not familiar with mutter. I had a quick look at the mutter reference but I don't see a way to get access to the Mutter metawindow from the actual GTK window.

**Comment by phw** [comment]
AFAIK this is only available through the UI Mutter provides, there's is no programmatic access to this.

**Comment by Queuecumber** [comment]
Since wayland is eventually going to replace X entirely, this should probably get worked out as I'm sure a lot of applications are going to want something like this. Do you guys have any idea where I should go to report this as a bug?

**Comment by Queuecumber** [comment]
@gnunn1 I think it's time to re-open this, I just tested Guake under wayland and it is able to stay "only-on-top", so there is some way to do it. I'm going to try to track down those code for it

**Comment by gnunn1** [comment]
It only works in Guake because Guake is using GTK2 and thus is not a native Wayland app since it runs under XWayland. If Guake ever updates to GTK3 they will have the same issue.

**Comment by Queuecumber** [comment]
So XWayland still supports always-on-top?

**Comment by gnunn1** [comment]
That's my understanding.

**Comment by flozz** [comment]
> So XWayland still supports always-on-top?

When I tested, it only worked between windows of X11 applications, not with native Wayland app's windows

**Comment by Queuecumber** [comment]
@flozz That makes sense based on what I've been reading about XWayland, it's possible that the quick test I had picked only X11 apps. I still don't fully understand if this is something we need to ask the Mutter guys to provide an API for or push Wayland itself to include though (I suspect it is going to be on the window-manager side to provide this functionality)

**Comment by gnunn1** [comment]
I would start with Mutter/GTK and let them determine if they want to support it or if it needs to go upstream to Wayland.

**Comment by basille** [comment]
A few months later, I was wondering whether there was any sort of progress on this issue (on Tilix or Wayland side). The fact that Tilix Quake doesn't stay on top is very annoying, and almost defeats the purpose of Quake…
