### ISSUE TITLE
Scrollbar jumps when there's new output

### ISSUE THREAD

**Issue by brunelli** [gnunn1/terminix#60]
When there's new output in the terminal, the scrollbar automatically jumps to the end. It should remember the position.

**Comment by bil-elmoussaoui** [comment]
Should be optional :+1:

**Comment by brunelli** [comment]
I fail to see why in heaven's name somebody would want that, but whatever :)

**Comment by gnunn1** [comment]
There is an option for this in the Profiles > Scrolling tab, "Scroll on output" I assume it's not working for you?

**Comment by brunelli** [comment]
I tried that before. It was disabled and still scrolling, then I enabled and it kept scrolling. Now I've disabled it again and it works...

Well, thank you for you time ^^

**Comment by gnunn1** [comment]
Can you confirm that when you re-start Terminix the setting stays disabled, just wondering if it's a bug where it doesn't set it on properly on start. It sounds the way based on your description and I've add it the issue with a couple of other settings.

**Comment by brunelli** [comment]
Yeap, it doesn't remains disabled.

**Comment by gnunn1** [comment]
Thanks, I'll have a look at it

**Comment by bil-elmoussaoui** [comment]
It remains in my case (using Arch)
