### ISSUE TITLE
disable input synchronization strange behaviour

### ISSUE THREAD

**Issue by nean-and-i** [gnunn1/terminix#604]
since 1.3.5, disabling input synchronization on a single splitted-window does not work properly.

steps to reproduce:
* split 4 windows into one window
* enable synchronize input
* disable input synchronization per icon on one splitted-window A

- if input on one (non-A) splitted-window eg.  B or C or D , input will be synchronized to B+C+D but NOT to A -> OK

- if input on splitted-window A, it will be synchronized to all A+B+C+D -> FAIL

I'd expect that input on disabled window A, will NOT be synchronized to any other window, because synchronization is disabled for this one.

**Comment by gnunn1** [comment]
Yeah, I noticed this a couple of weeks ago and fixed it. It will be included in the 1.4.0 release coming out later this week.
