### ISSUE TITLE
Segfaults since Beta 1.4.0

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#605]
I noticed a few segfaults.

`terminix[31091]: segfault at 0 ip 00000000009c2f3a sp 00007ffcfbbb40c0 error 4 in terminix[400000+a48000]`

Unfortunately that's all I have. I don't know how to reproduce it. My system:
```
~> uname -a
Linux sectoid.local 4.9.0-0.rc8.git2.2.fc26.x86_64 #1 SMP Wed Dec 7 23:36:03 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

~> cat /etc/os-release 
NAME=Fedora
VERSION="25 (Workstation Edition)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by gnunn1** [comment]
Thanks for the report, much appreciated. To debug this, you would need to run a debug build under gdb until it segfaults and then get a backtrace. If you are willing to do that I put together a build for you and some instructions later tonight.

Also, can you run ```terminix --version``` and post the output here please.

**Comment by vaijab** [comment]
That'd be useful. I use terminix everyday 24/7, so it's quite important this gets fix :-) Anything I can do to help let me know.

**Comment by shamil** [comment]
@gnunn1 I'm hitting this as well and quite often, on Fedora `23`. Please provide debug build for me as well.

**Comment by gnunn1** [comment]
You can download a debug here, this has debug information and tracing enabled.

http://gexperts.com/files/terminix.zip

To debug it, run terminix in gdb using the following command:

```gdb terminix```

And then type ```run``` to actually start the application. Once it crashes, run the the command ```bt``` which will give you a backtrace. Paste the backtrace here in this bug report.

**Comment by gnunn1** [comment]
Thanks, I'll have a look.

**Comment by gnunn1** [comment]
I think this is caused because I'm being aggressive about removing the VTE widget. Can you please try this updated version where I've added some additional checks on the VTE events to make sure it is not null.

http://gexperts.com/files/terminix2.zip

**Comment by gnunn1** [comment]
Can you let me know if the version above appears to correct the problem?

**Comment by shamil** [comment]
@gnunn1 will do.
I'm running the updated version, no segfaults yet. I'll update the ticket if I got any

**Comment by gnunn1** [comment]
I'm going to close this, if the problem happens again just re-open the issue.
