### ISSUE TITLE
How can I open Preferences in quake mode?

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#608]

**Comment by f2404** [comment]
I guess I could set up a shortcut; but a GUI element would also be nice to have.

**Comment by gnunn1** [comment]
Open a another terminal and do it from there, it's a limitation of Gnome and setting the hints to skip the pager and taskbar. I suppose I could add it to the hamburger menu but it wouldn't be consistent with running a normal terminal.

I'll give it some thought but suggestions always appreciated as well.

**Comment by f2404** [comment]
xfce4-terminal, when run in drop-down mode, adds a couple of icons to the tabbar; also, Preferences can be open from the right-click menu. I guess one of these options could work.

**Comment by f2404** [comment]
> Actually now that I'm remembering, part of the problem is that the preferences window isn't set to be
> keep above, so it would appear under the Quake window when running.
I was able to deal with this problem by setting GDK_WINDOW_TYPE_HINT_DIALOG to the preferences window.

**Comment by gnunn1** [comment]
I've added it to the hamburger menu when running in quake mode.
