### ISSUE TITLE
Preferences "circle" menu New Session action opens a new window instead

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#611]

**Comment by gnunn1** [comment]
I'm confused, which isn't unusual, what do you mean by the Circle menu? Do you mean the "On new instance" option in preferences?

**Comment by phw** [comment]
I think f2404 probably means the fallback app menu button shown on some desktops in the titlebar.

**Comment by f2404** [comment]
No, I mean the menu which is opened by the circle button in the top left corner of the preferences window. It has the same actions as the top-left corner menu of the main window.
