### ISSUE TITLE
Cannot open terminix from the ubuntu unity launcher.

### ISSUE THREAD

**Issue by kadaj** [gnunn1/terminix#612]
I had locked the terminix to the unity launcher and closed the app. On clicking the icon, nothing happens. Terminix can be launched only from the dashboard. I am on Ubuntu 16.04.

**Comment by gnunn1** [comment]
Did you install Terminix from a package or PPA, if so, which one?

Also, if you logout and in, does it start working?

**Comment by kadaj** [comment]
I have installed from `ppa:webupd8team/terminix`. I tried logging out, but it does not start from the launcher.

**Comment by gnunn1** [comment]
I don't think I will be able to help as I don't manage the packaging for individual Linux distros, you should open an issue with the ppa owner in Launchpad. You can open a bug here:

https://launchpad.net/~webupd8team/+archive/ubuntu/terminix
