### ISSUE TITLE
Split terminals do not keep their sizes ratio when resizing the window

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#613]
Open the terminal and split it vertically - both terminals will have the same width. Then resize the window to increase its width - the first terminal will become wider than the second one.
The same happens when splitting horizontally and increasing window height.

**Comment by gnunn1** [comment]
Hmm, interesting as I haven't noticed that before. I'm not sure there is much I can do about it, it's really up to GTK to manage the layouts but I'll have a look.

**Comment by gnunn1** [comment]
I've introduced a subclass of Paned that explictly maintains the ratio. In my testing this seems to work well, hopefully it hasn't introduced any new regressions.

**Comment by gnunn1** [comment]
This breaks loading sessions from files, I made need to defer a fix for this until after 1.4.0

**Comment by gnunn1** [comment]
I think this should be good to go now, however note that if you load an older session file terminix will use the old behavior and not automatically set the paned position based on the ratio. If you re-save the file, you will get the new behavior.

GTK really needs a Paned widget that can handle more then a single split. :)
