### ISSUE TITLE
Visual issues when opening terminals

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#614]
Appear when the terminix window is pretty small.
With one terminal, everything is fine. After adding 3 more terminals, the narrow ones start having issues with text:
![terminix_4terms](https://cloud.githubusercontent.com/assets/14939413/21140612/72fc1444-c152-11e6-9f7c-fdb418728ef6.png)
After closing the last terminal, the 3rd one has another text issue:
![terminix_3terms_1closed](https://cloud.githubusercontent.com/assets/14939413/21140620/880982fe-c152-11e6-969e-6de2194e1a38.png)

**Comment by f2404** [comment]
Though it could be a vte issue - I can reproduce it with xfce4-terminal and gnome-terminal if shrinking terminal window rapidly. If I decrease the width step-by-step (i.e. by 1 char), there are no visual issues.
@egmontkob, what do you think?

**Comment by gnunn1** [comment]
I'm pretty confident this is an upstream issue myself, it's not like I'm doing anything particularly weird with the VTE. I notice though that the command prompt is particularly sensitive to corruption in the VTE, I use powerline and it gets rendered particularly badly at small sizes.

![screenshot from 2016-12-14 08-01-01](https://cloud.githubusercontent.com/assets/9358238/21182974/c58fcf30-c1d3-11e6-95fc-c0a5acdda7d5.png)

**Comment by gnunn1** [comment]
Terminator (GTK3) version has the same issue as well, though it crashes once you size it too small.

![screenshot from 2016-12-14 08-08-03](https://cloud.githubusercontent.com/assets/9358238/21183125/7125511c-c1d4-11e6-8214-f0e2d4c6befe.png)

**Comment by gnunn1** [comment]
I've opened an upstream bug for this here:

https://bugzilla.gnome.org/show_bug.cgi?id=776097

**Comment by f2404** [comment]
Ok, thanks.

**Comment by egmontkob** [comment]
> Terminator (GTK3) version has the same issue as well, though it crashes once you size it too small.

Does it crash inside VTE (according to the stack trace)?

**Comment by gnunn1** [comment]
I don't get a stack trace when running terminator from the command line, it just disappears and the process ends.
