### ISSUE TITLE
Color emoji support 

### ISSUE THREAD

**Issue by rickmed** [gnunn1/terminix#616]
I've been able to render in black/white with emojione font. Is there a way to render in color?

**Comment by gnunn1** [comment]
Not as far as I know, sorry.

**Comment by bestouff** [comment]
`gnome-terminal` can do it, FWIW.

**Comment by bestouff** [comment]
Now that GTK3 can do it, could you reopen please ?

**Comment by edubxb** [comment]
Tilix already has color emoji support, there are some guides explaining how to get it working in GNOME.

https://community.ubuntu.com/t/try-color-emoji-in-18-04/1492

![Uploading Screenshot from 2017-11-30 23-30-36.png…]()

The screenshot shows Tilix 1.7.1 in Debian Testing, GNOME 3.26 and Google Noto Font.

**Comment by bestouff** [comment]
Ah OK, I'm using 1.6.4 that's probably why.

**Comment by alex285** [comment]
@bestouff  thats unrelated to Tilix. it is a GTK 3.22 and Cairo 1.5.8 feature. Arch has it, Ubuntu 17.10 doesn't, Ubuntu 18.04 does
