### ISSUE TITLE
Few issues with Quake mode

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#617]
Hello,
I just tried Quake mode on Arch, using the latest git version of terminix and on xorg  and gnome 3.22
When i set both width and height to max using the preferences dialog, the dimensions changes correctly but when i resize it, nothing happens :( Is that intended ?

Also, using the max width, there's a pixel on left and on right that are not covered by the terminal widget
![capture d ecran de 2016-12-15 03-46-27](https://cloud.githubusercontent.com/assets/7660997/21210151/1517ca8a-c279-11e6-8193-2d236f84c1d6.png)

One last issue, if i do set the height & width to max of quake window, close terminix and open terminix again on Quake mode; i can't change the height, and the height of the window override the gnome shell bar (i don't know what we call it exactly). i think that this issue is somehow related to the first one. 
![capture d ecran de 2016-12-15 03-50-25](https://cloud.githubusercontent.com/assets/7660997/21210232/a0166fc4-c279-11e6-9419-a11fcee2052d.png)

Thank you very much!

**Comment by gnunn1** [comment]
Thanks for the report, I'll have a look tomorrow night.

**Comment by gnunn1** [comment]
Just a note to myself, I wonder if I should be using getMonitorWorkarea instead of getMonitorGeometry.

**Comment by gnunn1** [comment]
The last issue, when you set the width and height to 100%, is because the window manager decides to switch the window to full-screen. I've tried a few things like using the monitor workarea coordinates instead of the geometry or preventing it by returning true when the window state changes to fullscreen but no luck.

Instead I'm going with the easy solution, only allowing the height to be set to 90% of the available height instead of maximum.

**Comment by gnunn1** [comment]
As for the 1 pixel border on the left and right, I can confirm this but also can confirm I'm setting the right coordinates. Again, I think this is a Window Manager thing and not something I can resolve.

I also tested xfce4-terminal with it's drop-down mode and it exhibits the same symptoms.

**Comment by bil-elmoussaoui** [comment]
Thank you! :+1:

**Comment by f2404** [comment]
@gnunn1 I think both of these issues are specific to a certain WM; they are not happening on Cinnamon or xfwm4. Maybe we should submit bugs against Gnome WM?

**Comment by gnunn1** [comment]
@f2404 I'm 50/50 on it because I can already see the answer being it's not a bug but a feature. I'll look into it some more over the weekend to get my ducks in order before opening a bug since I'll need some ammo to make it convincing that it is a bug.

**Comment by f2404** [comment]
I agree some ammo would be needed for the fullscreen issue.
But what about the pixels issue? It looks like a clear bug, and it's also not present under other WMs.

**Comment by asoete** [comment]
Hi

I actually like _quake mode_  occupying  my complete screen.
Would you consider adding an option `start fullscreen`, or something like that, to quake mode? This basically sets the height to 100% instead of 90%...

Thanks
Kr.

**Comment by gnunn1** [comment]
@asoete I think you can already do that, just add the full-screen option when you run it in quake mode:

```
terminix --quake --full-screen
```

**Comment by f2404** [comment]
> I think you can already do that, just add the full-screen option when you run it in quake mode:

Interestingly, it works, but also prints
`You cannot use the quake mode with maximize, minimize, fullscreen or geometry parameters`

**Comment by gnunn1** [comment]
Oops, that one slipped through the cracks. It used to be you couldn't do full-screen from quake mode but I relaxed that restriction and obviously missed removing that output. There was also a bug where terminix should terminate when command line parsing returns true for exit and that wasn't happening either.

I checked in a change to fix both of these.

**Comment by asoete** [comment]
@gnunn1 When I run `terminix --full-screen` I get:
![workspace 3_062](https://cloud.githubusercontent.com/assets/5277186/21851084/dd135942-d80d-11e6-95aa-5cca2b1173ab.png)
as desired.

If I however run `terminix --quake --full-screen` I get:
![workspace 3_065](https://cloud.githubusercontent.com/assets/5277186/21851099/e82decf2-d80d-11e6-9516-621368ef3ab1.png)
(notice the gap at the bottom + the top and bottom shell-bars are still visible...)

@f2404 do you get another result with these same commands?

**Comment by gnunn1** [comment]
It works fine for me, but also note I'm running the development version, it's possible I fixed something from 1.4.2.

With terminix closed, if you run ```terminal --quake``` in a command line from another terminal and then hit F11 for fullscreen mode, what happens?

**Comment by asoete** [comment]
Nothing happens:

- No full screen
- No errors (or any output) in the other terminal (or via journalctl) ...
