### ISSUE TITLE
Visual bug in quake mode

### ISSUE THREAD

**Issue by Limdel** [gnunn1/terminix#618]
I'm using terminix along with tiling WM, bspwm to be exact (for tilingception) and when I'm using it in quake mode, I have transparent 1 pixel size border between terminal and decorations. You can see it on screenshot.
http://i.imgur.com/QC8zuYW.png

**Comment by gnunn1** [comment]
I don't officially support tiling WM's, having said that try disabling transparency to see if that helps. To do this, use the dconf-editor and set the ```enable-transparency``` to false under com/gexperts/Terminix.

Note that disabling transparency with the slider in profiles isn't sufficient, you have to set the key above in order for Terminix not to create the Window transparent.

**Comment by Limdel** [comment]
It fixed it. Thank you.

**Comment by gnunn1** [comment]
Actually if that's a quake mode screenshot, using 1.4.0-rc2 to remove the application should fix this without having to disable transparency.

**Comment by Limdel** [comment]
Awesome. Sorry, I tested it before reading your response to my another issue and before trying RC2. Bug is gone even with enabled transparency.
