### ISSUE TITLE
Ability to set WM_CLASS, or have it different for quake and regular windows by default

### ISSUE THREAD

**Issue by Limdel** [gnunn1/terminix#619]
I want to use both quake and normal mode, but as a tiling WM user, I have to make a rule for terminix, so it would not be tiled like regular windows in quake mode, and here I have a problem. Because rules are set by WM_CLASS and it is same for all terminix windows, I can't tell my WM to not tile only quake mode windows.
If I try to set WM_CLASS running terminix with --class option, I can do that only if it is 1st terminix window, which doesn't solve my problem, because I want to use both modes in the same time.

**Comment by gnunn1** [comment]
According to the gtk documentation this is deprecated and should not be set:

https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass

Can you do something with the window role if I set that instead?

https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-role

**Comment by gnunn1** [comment]
I've gone ahead and set the window role for quake windows, if that is sufficient for your needs please close this issue.

**Comment by Limdel** [comment]
well. I'll try to make a workaround. thanks.
