### ISSUE TITLE
Add ability to get a default setting

### ISSUE THREAD

**Issue by MetotoSakamoto** [gnunn1/terminix#62]
Add ability to get a default setting to don't always have to do menu>load>MySetting.json when launching Terminix.

**Comment by gnunn1** [comment]
You mean load a session by default? You can do this with command line parameters:

```
terminix -s MySession.json
```
Does that meet your requirements?

**Comment by MetotoSakamoto** [comment]
Triple yes, I could probably do the tricks by editing my terminix.desktop. Thanks

**Comment by MetotoSakamoto** [comment]
I have no terminix.desktop in /usr/share/applications/ how can I do?

**Comment by gnunn1** [comment]
Thanks, let's leave this open until the next release as there were some problems with command line arguments that I have fixed but have haven't been released.

As for the desktop file, how did you install Terminix, from a package or from a release archive? If you run the following you don't get any matches shown?

```
ls /usr/share/applications/*Terminix*
```

**Comment by MetotoSakamoto** [comment]
He was installed via:
$yaourt -S terminix-git

$ls /usr/share/applications/*Terminix*
/usr/share/applications/com.gexperts.Terminix.desktop

hum ok... I espected to find a terminix.desktop not a com.gexperts.terminix.desktop. I need glasses. thanks

**Comment by gnunn1** [comment]
Please test the command line in 0.45 and if everything is OK close this issue.

**Comment by phw** [comment]
> Editing the .desktop file is painful because it get overridden every time there is an rpm update of Terminix

Instead of overwriting the system desktop file you can place a copy of it in `$HOME/.local/share/applications/` and modify that.
