### ISSUE TITLE
Application button in quake mode wasting space

### ISSUE THREAD

**Issue by Limdel** [gnunn1/terminix#620]
I don't know if it is supposed to look like that, or if it is caused by tiling WM, but that `Application` button is wasting a lot of vertical space and isn't needed really.
http://i.imgur.com/QC8zuYW.png

**Comment by gnunn1** [comment]
If this is in Quake mode it has already been fixed in #594, please try 1.4.0-rc2 in the releases.

**Comment by Limdel** [comment]
Sorry, installing 1.4.0-rc2 fixed it.
