### ISSUE TITLE
No difference between "Normal" and "Small" title styles

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#621]
Arch Linux, Cinnamon 3.2.1
terminix 1.4.0-rc2

**Comment by gnunn1** [comment]
All the small setting does is remove the extra padding in the Box that some themes like Adwaita use. If you are using a theme that is already compressed then there will be minimal to no difference between small and normal.

Can you post a screenshot when you get a chance.

**Comment by f2404** [comment]
This is how it looks for with Adwaita, no matter if Normal or Small setting.
![terminix](https://cloud.githubusercontent.com/assets/14939413/21286947/c3050f24-c47a-11e6-8d08-c466cc8470aa.png)

**Comment by gnunn1** [comment]
Weird, it's working fine on Gnome, not sure why using Cinnamon makes any difference.

**Comment by gnunn1** [comment]
Can you take another screenshot but hold the mouse over the title or close button so I can see how much spacing there is around the button. That is looking like it's already in small mode without the padding that Adwaita normally adds. 

Here's what it looks to me in Normal mode:

![screenshot from 2016-12-17 14-00-49](https://cloud.githubusercontent.com/assets/9358238/21289071/41590e58-c461-11e6-939f-aba9a6b3ad56.png)

And here it is in small mode:

![screenshot from 2016-12-17 14-00-33](https://cloud.githubusercontent.com/assets/9358238/21289074/48709224-c461-11e6-81ca-2d95e73f6a8c.png)

 If I use the GTK Inspector, you can see the button padding-top, padding-bottom, etc is reduced from the default:

![screenshot from 2016-12-17 14-03-42](https://cloud.githubusercontent.com/assets/9358238/21289087/b3aaf782-c461-11e6-849a-85d6f62fe85f.png)

To 0 when compact mode is enabled:

![screenshot from 2016-12-17 14-04-01](https://cloud.githubusercontent.com/assets/9358238/21289094/cc3fed70-c461-11e6-80c7-0df310ac0925.png)

**Comment by f2404** [comment]
Oh, I forgot about my custom GtkNotebook settings in ~/.config/gtk-3.0/gtk.css. Once I removed them, the Normal style became bigger than Small, as expected. Sorry for the noise.

**Comment by gnunn1** [comment]
No worries, thanks for figuring it out and letting me know what the issue was.
