### ISSUE TITLE
Move app menu items to terminix menu if desktop environment does not use an app menu

### ISSUE THREAD

**Issue by cra0zy** [gnunn1/terminix#625]
This is something Gedit does, and it makes it look nice on other desktop environments. Anyway to check this you simply need to call https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-prefers-app-menu

**Comment by gnunn1** [comment]
What version of Terminix are using? The current version of Terminix forces the app menu to appear in the Headerbar in cases where the environment doesn't support the application menu at the top like Gnome does. If you try one of the 1.4.0 release candidates this is the behavior you should see, I can't remember if I had this in 1.3.5 which is the last release version.

Note that generally speaking I only support Gnome and Unity explicitly, I don't test on other desktop environments nor am I willing to troubleshoot them in VMs. Having said that, I'm certainly willing to work with someone to make tweaks for other environments if that person is willing to do the testing.

**Comment by cra0zy** [comment]
> The current version of Terminix forces the app menu to appear in the Headerbar in cases where the environment doesn't support the application menu at the top like Gnome does.

It does do that, but what I am telling you is that you could actually move all the items into Teminix menu in case app menu does not exist instead of generating an app menu at the start of the HeaderBar, this is something Gedit does.

**Comment by gnunn1** [comment]
Understood, sorry but I don't think I'm interested in making that change as I'm not a fan of that approach. I think it makes the hamburger menu unwieldy and confusing. For example, the application quit menu item closes all windows of Terminix, but if it appears in the hamburger menu the implied context is to just close this window.

**Comment by cra0zy** [comment]
Quit item is the only item that you wouldn't be able to move... Anyway I am using GNOME so I don't really care about this, I just thought you might want to check out what Gedit does. Also I would recommend you do not do what System Monitor does when DE has no app menu, it looked so ugly... they actually added a menubar item for the global menu so it also loaded a titlebar, so you had a Titlebar + MenuBar + Headerbar... man that looked ugly.
