### ISSUE TITLE
32-bit package?

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#626]
What are the issues with 32-bit version?
I was able to build terminix-git package on a 32-bit Arch Linux system without any issue (leaving aside the issue with building gtkd which I was able to work around).

**Comment by gnunn1** [comment]
None at this point as far as I am aware of, there have been PRs to fix some issues. However I don't officially support it nor do I test in 32 bit environments. It's just not worth the time and effort considering how few people are still on 32 bit and that number is getting smaller all the time.

**Comment by f2404** [comment]
I think I was under impression that there were some issues preventing terminix from building or running on a 32-bit system. So I wanted to update you that I cannot see any.

**Comment by gnunn1** [comment]
There were many issues at one time but like I said it was addressed by some folks via PR. Right now it's more about spending time on it, it's the same reason I only officially support Gnome and Unity desktop environments. With a limited time budget there has to be prioritization.

Btw if Travis supported 32 bit builds I'd be willing to enable it but as far as I can tell it does not.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 it's possible to enable 32bit builds using Docker, here's a solution proposed on an issue ticket https://github.com/travis-ci/travis-ci/issues/5770#issuecomment-197771661
