### ISSUE TITLE
Same terminal title for all tabs

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#627]
I change tabs and but terminal shows the same title for all tabs, using 1.4.0-beta.
Even in the tabs list, ``Default`` is shown as label. Truncated form of the terminal title would be nice there too.

**Comment by gnunn1** [comment]
By tabs, do you mean the session title shown in the sidebar or the terminal title? You can change both of these Preferences. The session title can be changed in Appearances and the Terminal title can be changed in Profiles. 

You can use various variables in the titles, for example I use ```${title}``` to use the title of the currently active terminal. A complete list of variables is available in the wiki in the FAQ section though I should break this out into it's own section.

https://github.com/gnunn1/terminix/wiki/FAQ
