### ISSUE TITLE
Web site

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#629]
I think the web site looks awesome!
However, I feel that the Contribution section lacks links. For example, it's saying "Terminix is localized using Weblate, please visit the Weblate hosted Terminix transations site in order to assist with translations" - for me it would be natural to have a link to Weblate Terminix translation here. Same for the issues.

**Comment by bil-elmoussaoui** [comment]
Web site issue should be added here instead https://github.com/gnunn1/terminix-web

**Comment by gnunn1** [comment]
Just fixed it as well.
