### ISSUE TITLE
default session not being loaded

### ISSUE THREAD

**Issue by rickmed** [gnunn1/terminix#632]
launching with the -s flag and session name works. Not getting any errors on startup. Not sure how to proceed. Any ideas?

Versions
	Terminix version: 1.3.5
	VTE version: 0.42
	GTK Version: 3.18.9

**Comment by gnunn1** [comment]
Sorry, I'm not understanding what the issue is? The -s switch loads a session JSON file that you have previously saved, are you saying this isn't working for you? Please post the JSON file you are trying to load and I'll have a look.

**Comment by rickmed** [comment]
AFAIK, when I set in preferences a default session name it should be loaded when launching terminix without the s switch right? This is not happening in my case. 

```
{
    "child": {
        "child1": {
            "directory": "\/home\/rick\/Desktop",
            "height": 858,
            "profile": "54b0ab3a-7a04-4937-ac84-c7744399d8d7",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 652
        },
        "child2": {
            "child1": {
                "directory": "\/usr\/share\/sounds\/freedesktop\/stereo",
                "height": 399,
                "profile": "54b0ab3a-7a04-4937-ac84-c7744399d8d7",
                "readOnly": false,
                "synchronizedInput": true,
                "type": "Terminal",
                "width": 947
            },
            "child2": {
                "directory": "\/mnt\/storage-ntfs3g\/Gdrive\/Projects\/Programming\/shell_playground",
                "height": 458,
                "profile": "54b0ab3a-7a04-4937-ac84-c7744399d8d7",
                "readOnly": false,
                "synchronizedInput": true,
                "type": "Terminal",
                "width": 947
            },
            "orientation": 1,
            "position": 46,
            "type": "Paned"
        },
        "orientation": 0,
        "position": 40,
        "type": "Paned"
    },
    "height": 858,
    "name": "rm-sess.json",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 1600
}
```

**Comment by phw** [comment]
The default session **name** is just the default name for a new session (which you can rename later). AFAIK there is currently no preference to select a session file to be used by default, use the -s switch for that.

**Comment by rickmed** [comment]
so if I want to save a terminix state, close and continue working on the same state when reopening the idiomatic way is using the s flag?

**Comment by gnunn1** [comment]
What @phw says is correct, there is currently no way to load a session file by default. The idiomatic way is via the -s switch to load the file. Alternatively, you can just modify the terminix desktop file to add the -s switch and the session you want to load which accomplishes the same goal.

I do not have any plans to change this.

**Comment by syntaxseed** [comment]
If you find this issue while trying to get Tilix to launch a specific saved session by default when Tilix is launched, create a Desktop or Launcher icon with the following:

```
[Desktop Entry]
Encoding=UTF-8
Name=Tilix
Comment=Launch Tilix
Exec=tilix --session /path/to/tilix/session/default.json
Icon=com.gexperts.Tilix
Type=Application
```
