### ISSUE TITLE
Terminal focus requires click in latest version

### ISSUE THREAD

**Issue by eda2z** [gnunn1/terminix#634]
I just upgraded to version 1.4.0-1 in Arch Linux and "Focus a terminal when the mouse moves over it" no longer works.  Clicking is required whether the box is checked or not.  I checked on my other system which is running 1.3.5 and this does not happen.  What other info should I provide.

**Comment by gnunn1** [comment]
Thanks, I'll investigate.

**Comment by gnunn1** [comment]
This was caused by a typo, my apologies for that.
