### ISSUE TITLE
Terminix fails to launch

### ISSUE THREAD

**Issue by e-inquirer** [gnunn1/terminix#635]
I mistakenly set the preferences in Terminix to run the following command at start-up:

**`zsh %`**

Since I've done this, the application fails to load. I've tried to uninstall and reinstall the app (through dnf and Gnome Software Center) in an attempt to purge the configuration files, but the start-up setting seems to persist.

Is there an available remedy for this issue?

**Comment by gnunn1** [comment]
Use dconf-editor and go to /com/gexperts/terminix/profiles and then go through each profile one by one until you find the one that has this set in the command key. Just change the setting to an empty string and you should be good to go.

**Comment by gnunn1** [comment]
As a note to myself, Terminix should handle this better and I'll have a look at doing so.

**Comment by gnunn1** [comment]
I've added a new command line option, ```--preferences``` to allow the preferences to be shown directly to handle this situation in the future.
