### ISSUE TITLE
VteTerminal not filling app window on resize

### ISSUE THREAD

**Issue by jonian** [gnunn1/terminix#638]
Hi,

Thank you for this great application. I noticed an issue when maximizing the Terminix window or when going fullscreen. I'm using micro editor for demo purposes, but the issue occurs with any application.

Initial window on app launch. Everything is fine:

![screenshot from 2016-12-26 01-31-47](https://cloud.githubusercontent.com/assets/4119508/21473264/e16c77bc-cb0b-11e6-9fef-2166f9a8c2f6.png)

Maximized window. Extra space on right and bottom sides:

![screenshot from 2016-12-26 01-32-00](https://cloud.githubusercontent.com/assets/4119508/21473265/e170b192-cb0b-11e6-8dcd-bdd8422f33e0.png)

Full screen window. Extra space on right side:

![screenshot from 2016-12-26 01-32-11](https://cloud.githubusercontent.com/assets/4119508/21473263/e16a57a2-cb0b-11e6-8764-601c5a7c8efd.png)

I'm on Arch Linux using latest Gnome and Terminix (from AUR).

I tried changing some properties (expand, align fill) using GTK Inspector with no success.
I created a simple terminal app using VteTerminal and the issue was not present.

**Comment by gnunn1** [comment]
So looking at your image, I highlighted the extra space with red bars I think you are talking about, can you confirm?

![terminix-spacing-issue](https://cloud.githubusercontent.com/assets/9358238/21474418/d821221c-caec-11e6-84a9-2fcd8ceebc72.png)

For the one at the right, the color of the space is matching the scrollbar. It's either the scrollbar is extra wide for some reason or as you surmise that the VTE is not extending to the right for some reason. In the GTK Inspector, can you click on that space and see what it corresponds to please.

For the bottom, keep in mind that the VTE only shows full lines so there usually is some empty space at the bottom. Comparing terminix and gnome-terminal on my system I'm seeing anything different in behavior in this regard.

A couple of other thoughts:

a. What theme are you using?
b. Can you try the theme Adwaita and see if you have the same issues there?
c. Any chance you have some custom CSS in play in ```~/.config/gtk-3.0/gtk.css```

**Comment by gnunn1** [comment]
Hmm actually right after I post that I realize you are using Arc Dark. For full-screen I can reproduce the same behavior with the extra space on the right side when using full screen but not maximizing. However the behavior is exactly the same between gnome-terminal and terminix. The extra space does seem to be occupied by the VTE so it doesn't appear to be an obvious terminix bug as far as I can tell. I don't get that color difference on the right that you do.

What do you see with gnome-terminal, similar or different behavior?

**Comment by jonian** [comment]
Hi again,

I changed my theme to Adwaita and I see the same issue. I installed gnome-terminal and the same issue exists.

Custom CSS in ~/.config/gtk-3.0/gtk.css:

```
vte-terminal {
	padding: 0;
	margin: 0;
}
```

VteTerminal highlighted with GTK Inspector:

![screenshot from 2016-12-26 13-35-22](https://cloud.githubusercontent.com/assets/4119508/21481603/5b8dd37c-cb72-11e6-9f83-3ed37c52e9a0.png)

The widget seems to occupy all the available space, but not the contents.

Terminix window, if I remove expand from VTE Terminal:

![screenshot from 2016-12-26 13-35-53](https://cloud.githubusercontent.com/assets/4119508/21481636/ab0e5b38-cb72-11e6-9976-17f3469408cb.png)

VTE Terminal adapts to the content but the widget does not fill the available space.

Screenshot from Gnome Terminal having the same issue:

![screenshot from 2016-12-26 13-40-04](https://cloud.githubusercontent.com/assets/4119508/21481655/e934958a-cb72-11e6-8664-67062a78bda8.png)

I tested again with a test app using VTE Terminal and it has the same issue. It seems that I didn't test it properly the first time. I apologize.

![screenshot from 2016-12-26 14-16-00](https://cloud.githubusercontent.com/assets/4119508/21481937/27241ed0-cb76-11e6-8a83-d945b72301ef.png)

Maybe this is a VTE Terminal bug?

**Comment by gnunn1** [comment]
I think this is normal behavior for the.most part. On the right I suspect there is extra space because the VTE doesn't have enough room to render a character so leaves it blank. You should see this behavior if you slighty resize a gnome terminal or Terminix widget. This is how VTE deals with sizes that don't perfectly fit rows and columns.

The only part that is weird is the one screenshot you have that shows the extra buffer space being colored the same as the scrollbars background. You could try removing your custom CSS to see if that helps as I don't see the same behavior with Arc Dark myself.

**Comment by jonian** [comment]
> You should see this behavior if you slighty resize a gnome terminal or Terminix widget.

I tried it and the behaviour is as you describe. On some sizes it fills the window.

> The only part that is weird is the one screenshot you have that shows the extra buffer space being colored the same as the scrollbars background.

I have customized the color scheme to match Arc colors.

I'm closing this as it is normal and not a bug.
Thank you for your time and the detailed explanations.
