### ISSUE TITLE
Disable title edit on click

### ISSUE THREAD

**Issue by Salamandar** [gnunn1/terminix#639]
Well I move the window or double-click to maximize the window, so the title editing feature is more annoying than anything else for me :(

Would it be possible to add a preference toggle to disable it ?

Thanks !

**Comment by gnunn1** [comment]
Thanks for the report, actually this has been fixed in #630 very recently so it double clicking no longer activates it and neither does moving.

**Comment by Salamandar** [comment]
Got it, waiting for the next release !

**Comment by Salamandar** [comment]
Works well, thanks.
