### ISSUE TITLE
gtkd dependency

### ISSUE THREAD

**Issue by Limdel** [gnunn1/terminix#641]
I installed terminix-git from AUR and unlike previous versions, it depends on `gtkd` package, which I suppose is not very popular (considering that it's not in main arch repos) and which has to be compiled and uses more then 80 MBs of space. In my opinion, this is overkill for just a small terminal app. Yes, nowadays hard drive space isn't a problem, but I still prefer to have my system clean and optimized.

**Comment by f2404** [comment]
A good point but I think it's more for the AUR package.
I've asked the question on its site: https://aur.archlinux.org/packages/terminix-git/

**Comment by gnunn1** [comment]
Terminix requires GtkD, however there is an option to build Terminix statically or dynamically. With static builds only the GtkD parts used by Terminix are included, with dynamic builds it links to a GtkD shared library which includes all functionality.

Which way to build Terminix is up to the package maintainer, I try to stay out of packaging issues.
