### ISSUE TITLE
A manpage is missing

### ISSUE THREAD

**Issue by ximion** [gnunn1/terminix#643]
In Debian, having a manpage is a strong recommendation for all applications living in $PATH, especially when they have useful command-line flags which benefit from a more detailed explanation.

It would be awesome if we could get a manual page for Terminix (to silence our lint warnings, but also to have a better reference of the Terminix command-line options).

**Comment by ximion** [comment]
Okay, we need to get this into Automake or Meson too, but the manpage being available is great news! :)

**Comment by gnunn1** [comment]
@dsboger do you have any time to update the autotools to install the new man page?
