### ISSUE TITLE
Improving xterm compatibility

### ISSUE THREAD

**Issue by ximion** [gnunn1/terminix#644]
In Debian, it is now possible to use Terminix as x-terminal-emulator alternative, allowing it to be used as default terminal emulator (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842282 ).

This is currently done via a wrapper script: https://anonscm.debian.org/cgit/pkg-gnome/terminix.git/tree/debian/terminix.wrapper

As you can see, a lot of options are not supported. It would be awesome to support all or most of them, and maybe even to have Terminix support an xterm compatibility mode or provide a useful wrapper upstream.

**Comment by gnunn1** [comment]
Generally terminix emulates gnome-terminal for command line parameters, to be honest I haven't even considered xterm in this regard. What do other terminal emulators do under debian as I don't recall any of the ones I'm familiar with specifically emulating xterm's command line.

**Comment by ximion** [comment]
They either have a wrapper or use similar command-line flags. Having a wrapper is perfectly fine, but supporting a few more options would be nice.

**Comment by gnunn1** [comment]
Thanks, looking at the script I have the following questions:

* Should -fn (font), -fg (foreground) and -bg (background) all reference using the profile capability in Terminix like the -n option does? I have no plans to support these as command line since this is what profiles are intended to do.

* The -tn capability should be added to terminix, but again I'm thinking via the profile instead of a command line.

* I'm not sure what the -name option should do, if this is to change the GTK application name it may lead to weird issues. Do any non xterm emulators support this option?

**Comment by egmontkob** [comment]
Debian/Ubuntu ships a wrapper, written probably in python. I've never taken a closer look. Just as it's not shipped by mainstream gnome-terminal, I'm wondering if it's better if you ship such a wrapper or rather the distro should take care of it.

fn, fg, bg: I agree with you that they belong to the profile and I wouldn't bother with the possibility of overriding them (including the trouble of what should happen if you open the profile editor and even change these colors from such a terminal). No clue what tn is.

As for your last question, see https://bugzilla.gnome.org/show_bug.cgi?id=775383 (tldr: we don't care).

**Comment by gnunn1** [comment]
@egmontkob the tn parameter for xterm is defined as:

```
This option specifies the name of the terminal type to be set in the TERM environment variable. It corresponds to the termName resource. This terminal type must exist in the terminal database (termcap or terminfo, depending on how xterm is built) and should have li# and co# entries. If the terminal type is not found, xterm uses the built-in list "xterm", "vt102", etc.
```

I was thinking it could make sense to allow the user to override the TERM environment variable as perhaps a compatibility option. However after looking into it some more I'm not sure how useful this really is.

**Comment by egmontkob** [comment]
vte is designed to work with xterm / xterm-256color. No other value is supposed to work or tested by us. As such, I see no reason to diverge from vte's default "xterm-256color". If someone still wishes to diverge, they can modify TERM from .bashrc or use a custom command `env TERM=whatever cmd`.

**Comment by gnunn1** [comment]
Thanks @egmontkob, that explanation makes perfect sense.

@ximion So the -name option could map to --name, I just quickly tested it here and it doesn't have any ill effect.

Other then that, hopefully I answered the question for the other parameters. In general terminix and xterm have very different views of features despite both being terminal emulators so I don't think an xterm compatibility layer in upstream makes a lot of sense. If there are specific options you want me to look at that make sense within the context of Terminix feel free to open an issue and I'll have a look.
