### ISSUE TITLE
Misleading release information

### ISSUE THREAD

**Issue by ximion** [gnunn1/terminix#645]
There is a `1.20` tag and a release on Github which claims to be `1.30` while the current release is actually `1.4` - could you please delete or rename the tag and maybe also (for consistency) update the `1.30` release name?

At least the tags mess with our automatic new-version detection, and it would be better to fix this at the source rather than hack around it downstream.

**Comment by gnunn1** [comment]
I thought I did do that but I'll check again. I have limited internet access until tomorrow so I'll have a look then.

**Comment by ximion** [comment]
Deleting online tags is different - delete the tag locally, re-tag if you want, and then delete the remote tag (`git push origin :1.20`) and push the updated tags if there are any.

**Comment by gnunn1** [comment]
Hopefully I have fixed it this time, here's the list of tags I see:

```
0.10
0.20
0.21
0.30
0.31
0.31-1
0.31-1-1
0.31.1
0.32.0
0.35.0
0.36.0
0.36.1
0.37.0
0.38.0
0.40.0
0.45.0
0.46.0
0.50.0
0.50.1
0.50.2
0.51.0
0.52.0
0.52.1
0.53.0
0.54.0
0.55.0
0.56.0
0.57.0
0.58.0
0.58.1
0.59.0
0.60
0.60.1
0.60.2
1.0.0
1.1.0
1.1.1
1.2.0
1.3.0
1.3.5
1.4.0
1.4.0-beta
1.4.0-rc1
1.4.0-rc2
1.4.0-rc3
```

Do the -beta, -rcX tags cause any issues?

**Comment by bil-elmoussaoui** [comment]
@gnunn1 As I've already packaged some stuff on ArchLinux, in order to get the latest package release, you just get the tags and order it alphabetically. So for the automatic releases, it will get the 1.4.0-rc3 as the latest version and not 1.4.0. So for me, once the stable release is out, the beta/rc tags should be removed :+1:

**Comment by phw** [comment]
Removing the release tags sounds confusing, especially as the releases will not appear in Gihubs release list without tags. Wouldn't the better solution be to fix the sorting algorithm?

**Comment by bil-elmoussaoui** [comment]
Is it important to have alpha/beta release tags? i mean to keep them all along.

**Comment by gnunn1** [comment]
The other option would be to do something similar to what gnome does, 1.4.4-beta, 1.4.4-rc and then bump the version to 1.4.5 when released so it sorts correctly.

AFAIK, you can't control the way tags are sorted by git though you could do some things to get them sorted chronologically. Personally, I prefer to follow KISS so selecting a way that this happens naturally would be best.

**Comment by ximion** [comment]
@gnunn1 Looks like this is fixed now, thank you!
As far as I am concerned, this issue can be closed.

As for release-tags: One can append them with a `~` sign, because `1.0-beta` >> `1.0` >> `1.0~beta`
(we rewrite `-` to `~` at Debian when checking versions of Terminix).
But, do whatever you like best for this :-)

**Comment by gnunn1** [comment]
@ximion Thanks for the tip about the tilde, I suspect that would work fine for me.

**Comment by gnunn1** [comment]
Unfortunately github won't allow you to use a tilde in a tag.
