### ISSUE TITLE
Terminal contents search can only be performed once

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#651]
Make sure terminal output contains some word WORD once. Find it by entering WORD into search entry and pressing arrow down - the word WORD gets highlighted. Press arrow down another time - highlight is cleared. Press arrow up.
Expected result: WORD is highlighted.
Actual result: WORD is not highlighted, and it won't get highlighted no matter in which order and how many times buttons up and down are pressed.

**Comment by f2404** [comment]
This is only reproducible when Wrap Around is checked (by default). In fact, t's also reproducible in other vte-based terminal emulators under these conditions.

**Comment by bil-elmoussaoui** [comment]
Take a look here, @gnunn1 explained why it's not working as expected if i do remember.. #48

**Comment by gnunn1** [comment]
There are a number of open issues with search in VTE and this is one of them, you can see a couple of the more interesting bug reports here:

https://bugzilla.gnome.org/show_bug.cgi?id=694128
https://bugzilla.gnome.org/show_bug.cgi?id=627886

**Comment by f2404** [comment]
Indeed - thanks!
