### ISSUE TITLE
Improve discoverability of "click title to edit" feature

### ISSUE THREAD

**Issue by dsboger** [gnunn1/terminix#653]
I only found that feature because I saw a bug report mentioning it. Maybe the center of the header bar could be made into a .flat button, so hovering it would give a hint, and it could be reached through keyboard navigation?

**Comment by gnunn1** [comment]
I like keeping users in the dark, results in less bug reports :)

Seriously, I agree that it is not very discoverable. I'm not sure about the button though, it would look kind of odd doing normal window operations like dragging and double-clicking to maximize.

The feature as it stands mimics the way epiphany behaves, however epiphany has the advantage that when you launch it the edit is active so the user can enter a URL. This trains the user about how to edit the URL. Unfortunately I don't have a good idea to do the same.

**Comment by gnunn1** [comment]
Played around with this, unfortunately neither Label or EventBox implement support for the hover pseudo class so there's not much I can do about this. Implementing a button work work but because of the nature of the control I'd rather not.

**Comment by bil-elmoussaoui** [comment]
What about making the title as a button? or just an eventbox, once you click on it, it become a Gtk.Entry to rename it?

**Comment by gnunn1** [comment]
It is an EventBox and if you click it it does become editable, that's already implemented. There's just no way to make it discoverable. I'd prefer not making it a button, worry it would hinder some of the normal title interaction semantics.
