### ISSUE TITLE
[Quake mode security bug] sudo timestamp not reset when using hibernate

### ISSUE THREAD

**Issue by Mancooo** [gnunn1/terminix#660]
Hi,

I love Terminix, I use it exclusively.

Today I found a security related bug when running Terminix in Quake mode. When using sudo with Quake mode and hibernating just after you used sudo, the sudo timestamp never resets. 

When resuming from hibernation, you get unlimited time to perform sudo actions (unlimited lives, yess!). 

You have to exit Quake mode (by typing exit instead of the shortcut key) to reset the sudo timestamp.

This is a serious security issue imo.

Thanks for making this awesome terminal emulator!

edit: I use Terminix on Fedora 25 and Xorg (not Wayland)

**Comment by gnunn1** [comment]
What's the behavior of gnome-terminal in this situation?

**Comment by Mancooo** [comment]
I installed gnome-terminal and tested it. It does the same thing, so it's not a Terminix bug (yay!), but it is an odd bug.

Normally you would not notice it, unless you have an open terminal and you hibernate. Because of Quake mode you notice it more quickly.

I just tested out hibernation today on my laptop, I had never used it, always used suspend and resume, in case you were wondering.

**Comment by gnunn1** [comment]
Thanks for trying it out, I didn't think it was a terminix bug but good to know for sure. In general terminals have no clue as to what is actually running, it's up to the running program, in this case sudo, to react appropriately to these sort of situations. You might be able to work around it with a script tied into systemd or pm-utls.

**Comment by Mancooo** [comment]
Ok, thanks!
