### ISSUE TITLE
Terminx does not build 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#661]
I've tried to build the latest git version and i got this error 
```bash
source/gx/terminix/terminal/terminal.d(894): Error: no property 'setPropagateNaturalHeight' for type 'gtk.ScrolledWindow.ScrolledWindow'
source/gx/terminix/terminal/terminal.d(895): Error: no property 'setPropagateNaturalWidth' for type 'gtk.ScrolledWindow.ScrolledWindow'
make[1]: *** [Makefile:1084: terminix.o] Error 1
```
Using Archlinux 
Gtk version `gtk3 3.22.5-1`
Gnome version  `gnome-shell 3.23.2-1`

**Comment by gnunn1** [comment]
There is a new version of GTK required to build terminix, GtkD 3.4.1. If you are using terminix-git the gtkd-git (https://aur.archlinux.org/packages/gtkd-git/) package will need to be updated.

**Comment by bil-elmoussaoui** [comment]
Well, in this case terminix-git should use gtkd-git instead of gtkd. otherwise, this kind of issues will always happen...

**Comment by gnunn1** [comment]
Actually the gtkd package is fine, it's just in case the maintainer released a new version today and I jumped the gun as I had this commit lined up waiting for a fix from him. Normally this won't be an issue, my apologies.

**Comment by bil-elmoussaoui** [comment]
Perfect! just updated gtkd and everything works fine. Thank you again!
