### ISSUE TITLE
GLib-GObject-WARNING on start

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#665]
32-bit version:
`(terminix:8943): GLib-GObject-WARNING **: gsignal.c:2523: signal 'notification-received' is invalid for instance '0x861fdf0' of type 'VteTerminal'`

```
$ terminix -v
Versions
	Terminix version: 1.4.3-0.0.1
	VTE version: 0.46
	GTK Version: 3.22.5

Terminix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment]
I assume it didn't do this before? I might have been overly aggressive in copying and pasting my generated event code.

**Comment by gnunn1** [comment]
Yep, a little too aggressive on the copy and paste, restored some code that should fix this. Let me know if there are still any issues.

**Comment by f2404** [comment]
This issue seems to be fixed, thanks.
