### ISSUE TITLE
How is "warn about unsafe paste" supposed to work?

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#666]
I have this option checked in preferences but it doesn't seem to work with pastejacking examples from https://security.love/Pastejacking/ or http://thejh.net/misc/website-terminal-copy-paste

**Comment by gnunn1** [comment]
It's doesn't do anything for paste-jacking, it only looks for the the word ```sudo``` in paste text and warns about it.

If you want to prevent past jacking, use the option "Always use advanced paste dialog". This always displays the paste text to the user so they can see what will be fed to the terminal. This works fine for both of the examples you pointed to above.

With regards to the unsafe paste warning, I do think there are some enhancements that could be made to it as follows:

* Detect and warn about escape sequences in the paste text

* With my patch to the VTE that detects whether you are in normal or alternate screen, warn about multi-line pasting in the normal screen.

I'd be open to other suggestions along this line as well if you have any based on your experience with xfce4-terminal.

**Comment by f2404** [comment]
Ah, ok, thank you. I was confused by "unsafe paste" wording as paste jacking also falls into this category.

Also, advanced paste dialog does not pop when pasting primary selection with Ctrl+Ins - I think this may be improved.

**Comment by gnunn1** [comment]
I don't think there is anyway to detect pastejacking itself automatically since you don't have the context of what the user copied. If I'm wrong feel free to let me know, I think all you can look for are the signs like escape sequences, multi-lines, etc which I admittedly could do a better job of.

**Comment by f2404** [comment]
Apart from detecting pastejacking, currently neither unsafe paste warning nor advanced paste dialog work when pasting with Ctrl+Ins or middle mouse click. I think this may be improved.

**Comment by gnunn1** [comment]
Yep, I'll add that in, thanks for letting me know.

**Comment by gnunn1** [comment]
Should be fixed now for middle-click paste and shift+ctrl+insert

**Comment by f2404** [comment]
> Should be fixed now for middle-click paste and shift+ctrl+insert

This works fine, thanks. But what about Shift+Ins? It's still pasting primary buffer contents without any dialog pop-up.

**Comment by gnunn1** [comment]
Oops, missed Shift+Ins, I'll add that as well. Linux has way too many default shortcuts...

**Comment by gnunn1** [comment]
Added Shift+Insert as a new keyboard shortcut.

**Comment by f2404** [comment]
Right, need to always think for yourself and that guy :)

**Comment by gnunn1** [comment]
The default VTE paste shortcut keys are now always bound to the Terminix paste actions so changing the shortcut key will not allow the user to accidentally paste using VTE directly.

I debated about adding support to warn on multi-line paste but this really requires the alternate screen patch to do properly otherwise it becomes super annoying. I don't think enough people are using the patch to warrant the effort at this time.
