### ISSUE TITLE
[Question] How to set terminix as $TERM?

### ISSUE THREAD

**Issue by sirgallifrey** [gnunn1/terminix#668]
Hello guys, first let me say that that terminix is awesome and I love it very much!

I'm trying to set terminix as my default terminal so some applications open it instead of the gnome-terminal.
But when I try to set `export TERM=terminix` I get an error saying that the terminix terminal definition was not found. I tried to figure out how to add terminix to the terminfo but with no success... Is there some instructions somewhere on how I can accomplish it?

**Comment by gnunn1** [comment]
The TERM variable for terminix should be set to ```xterm-256color``` just like it is for all other VTE terminal emulators including gnome terminal. As far as I know, applications do not use this variable to determine which terminal to launch as that would be a bad practice IMHO.

Integrating terminix with your environment really depends on what desktop environment you are using. The only application I am aware of in GNOME that launches a terminal is nautilus (i.e. Files) and Terminix includes an extension to enable launching Terminix. 

If you provide some more info on what Desktop Environment you are using and what applications you are using that launches the terminal I can try to assist you with finding the best solution.

**Comment by sirgallifrey** [comment]
Hello @gnunn1 Thanks for your help! 

I left $TERM on it's default, and tried once more to set terminix as Gnome default, but with no success.... And as I only wanted terminix open with nautilus and sublime text 3 I was able to setup Nautilus Python as you said and have been able to find a config on a Sublime plugin to choose terminix.

Now everything is working fine! :D Thanks very much for your help!
