### ISSUE TITLE
RPM for Fedora 23 fails to install

### ISSUE THREAD

**Issue by fvzwieten** [gnunn1/terminix#67]
Hi,

rpm from suse buildservice for Fedora 23 fails to install:

dnf install terminix
Last metadata expiration check performed 0:04:40 ago on Thu Jan 28 09:24:18 2016.
Error: nothing provides libnautilus-extension needed by terminix-0.45.0-8.1.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)

I guess this is because the package is not called libnautilus-extension but nautilus-extenstion

Fred

**Comment by gnunn1** [comment]
Thanks, I've corrected that and kicked off a new build. Might be a bit though as OBS seems a bit slow today.

**Comment by fvzwieten** [comment]
The build is done (and wrong again). You have c-n-p-ed the package name from the text above...including the typo i made in there. The error now is:

Error: nothing provides nautilus-extenstion needed by terminix-0.45.0-11.1.x86_64

:-)

**Comment by gnunn1** [comment]
My apologies, there is a reason why I'm looking for package maintainers :)

Anyways, I corrected the issue and tested it on Fedora 23 and it works fine now. Thanks for your patience.
