### ISSUE TITLE
Application-colored prompt

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/terminix#670]
Hi and thanks for this wonderful terminal!
If I open [Julia](http://julialang.org) in Gnome-Terminal, my prompt gets colored green, if I type `?` it gets yellow and if I type `;` it gets red. Unfortunately this is not possible in Terminix. Would this be possible to implement? Would be really great! Thanks anyway!

**Comment by gnunn1** [comment]
It should work just fine in Terminix as Terminix uses the same back-end as gnome-terminal. How is this feature configured?

**Comment by fbruetting** [comment]
I have no idea, I just use it. :/

**Comment by gnunn1** [comment]
I just tried it here, works fine for me?

![screenshot from 2017-01-03 10-45-16](https://cloud.githubusercontent.com/assets/9358238/21613083/bae145b8-d1a1-11e6-9500-e1eb20cae498.png)

If you type this, and post what you get.

```
env | grep TERM
```
Here's what I see in Terminix:
```
COLORTERM=truecolor
TERMINIX_ID=6ccf7901-ed7f-493b-b3bf-cba2a61af237
TERM=xterm-256color
```

**Comment by fbruetting** [comment]
Same for me here, but prompt remains gray (v1.4.2):
![terminix standard_001](https://cloud.githubusercontent.com/assets/10520767/21613186/76f24b94-d1d4-11e6-9f43-e3d9bf87efa7.png)

**Comment by gnunn1** [comment]
What theme are you using, does it make any difference if you use Adwaita? Also maybe try a different Terminix text theme as well.

**Comment by fbruetting** [comment]
Ok, I found it that this is due to the solarized color scheme, sorry! But do you have an idea how I can modify it to adapt this hints? Foreground and background colours are set in this theme, while these are not settable(?) in all other themes.

**Comment by gnunn1** [comment]
There is a check box in the profiles color page labelled "Use system colors" or something similar. If you uncheck it the foreground and background colors will be editable.

**Comment by fbruetting** [comment]
Some themes have this checked, some don't have it – and all of them adapt these hints. Checking it with solarized sadly doesn't affect the prompt colour.

**Comment by gnunn1** [comment]
Change the color that I outlined in red in the screenshot below to something yellow and it will work fine. It just happens that the color is the same as the foreground so it doesn't appear to change colors.

![screenshot from 2017-01-03 12-02-41](https://cloud.githubusercontent.com/assets/9358238/21615825/2cd0364c-d1ad-11e6-86ad-6a5dea8254d8.png)

**Comment by fbruetting** [comment]
Both the green and the orange colour have to be modified. Thanks for pointing this behaviour out! I'll file a bug report for Solarized.

**Comment by gnunn1** [comment]
If you want to update the solarized color schemes they are simple JSON files under /usr/share/terminix/schemes, feel free to submit a PR. I did those files a long time ago and I may not have gotten the colors 100% correct.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 What do you think about adding some screenshots of all the supported color schemes to the website?

**Comment by gnunn1** [comment]
@bil-elmoussaoui It would look nice but we'd need to be careful that it doesn't come across as "these are the only themes that can be used". I did a themes page on the web site at https://gnunn1.github.io/terminix-web/manual/themes/ that could be enhanced with screenshots.

**Comment by bil-elmoussaoui** [comment]
I was thinking of a better idea :p we show all the themes possible in terminix-web, once you mouse over the screenshot there's an apply button that will open terminx://jsonpathoftheme and terminix will use xdg-mime in order to get the json file and apply the theme to the user? :P themes can be stored on local directory in order to avoid asking user for root permissions. 
This will need some work, but it will be a great feature to add ;)

**Comment by fbruetting** [comment]
I have the feeling that the Solarized colors are just wrongly ordered. On the left side there are the darker colors and right are the brighter ones – but in Solarized they seem disordered (maybe it's because of the brightness mathematics of Solarized, but I don't really understand console coloring). Could it be that they just need to be reordered? If you compare the colors of the Julia logo dots, you see that the colors of Solarized are different from every other theme.

**Comment by phw** [comment]
> I have the feeling that the Solarized colors are just wrongly ordered.

It doesn't look like it is wrong, that's just the way the colors are defined for the Solarized theme. It is exactly the same in Gnome terminal. And the theme is directly taken from https://github.com/altercation/solarized/blob/master/xresources/solarized, where it is defined with the same color ordering, so this can be considered official.

An interesting fact is that the colors on the official solarized theme linked above are slightly off. Maybe they tweaked the colors and this change was never updated in Gnome Terminal (from which the theme was taken for Terminix). For the fun I updated the dark theme locally to use the latest official colors, but I couldn't see a difference even when comparing side by side. If there is interest in having the latest official colors used I can also update the light theme and provide a pull request, but it is hardly worth the effort IMHO.

General rule: If a color theme is not to your liking use another one or adapt the colors ;)

**Comment by fbruetting** [comment]
Well, there certainly is something wrong, as colors named green and orange are obviously gray. But I don't know how to use them. Should I open a bug report at Solarized?

**Comment by phw** [comment]
If you want to know why colors are defined as they are here you definitely would need to ask upstream on Solarized, that's something that cannot be answered here.

It probably comes down to the fact that the Solarized color palette does not provide dark and light variants of the defined accent colors. An alternative to using gray for the light variants would probably have been to just reuse the exactly same color (as it is for example done in the Material or Monokai theme). But it is pointless to discuss this here. Of course Terminix could ship with a changed theme definition, but I wouldn't call it Solarized than.

**Comment by phw** [comment]
There is some discussion about this and an answer on https://github.com/altercation/solarized/issues/8#issuecomment-966693
