### ISSUE TITLE
Switch between advanced  paste and regular paste

### ISSUE THREAD

**Issue by laur1s** [gnunn1/terminix#671]
Hi, is it possible to quickly switch between regular paste and advanced paste or set different keyboard shortcut for them? I like using advanced paste for formatting the commands from the internet properly but confirming the paste every time even if its a shot one is too much hassle.

**Comment by gnunn1** [comment]
Yes, leave the "Always use advanced paste" turned off and  assign different shortcuts to each in the Shortcuts section of preferences.
