### ISSUE TITLE
Keyboard shortcut in Nautilus for Open in Terminix

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#672]
Just an idea and not sure if it is possible, but it would be nice to have a keyboard shortcut inside Nautilus to trigger the "Open in Terminix" action for the currently shown folder.

I found this Nautilus plugin which does add a keyboard shortcut to Nautilus:

https://github.com/riclc/nautilus_backspace/blob/master/BackspaceBack.py

In theory it should be even possible to read the configured shortcut from the gsettings Terminix settings, which would make the shortcut easily customizable in Terminix itself.

**Comment by gnunn1** [comment]
I'm not sure how feasible this is.  Looking at that code example it looks to me that it sets an accelerator for an existing action in nautilus, not for an extension created through Nautilus's extension point. 

If the extension API that is being used get's translated into an action in Nautilus under the hood it might be possible to do it that way. You would need to find out the detailed action name the extension gets placed against somehow.

**Comment by phw** [comment]
Another extension doing this:

https://github.com/vitaut/captain-nemo/blob/master/misc/shortcut-nautilus3.py

To be honest this all looks a little hackish, but I still like the idea of having this ability.
