### ISSUE TITLE
Display possible variables in Profile information > Terminal Title

### ISSUE THREAD

**Issue by Jiehong** [gnunn1/terminix#673]
Hi,

Today, when you edit your profile, you can set the title of the current terminal:
![terminix_profile](https://cloud.githubusercontent.com/assets/1061229/21676170/f8655656-d334-11e6-886e-8128b709b36a.png)

As you can see, by default, “${id}” and “${title}” are used. But there is no way to find out what else could be used!

Of course, the code already has this information:
https://github.com/gnunn1/terminix/blob/984a3af5e360d50daabb530c09756d1ac0d32510/source/gx/terminix/terminal/terminal.d#L172

Solution:
It would be great if the user could have the possibility to see a hint of what is usable.

We could have a folding area that would display something like what EasyTag does (the legend part):
![EasyTag song parsing](https://wiki.gnome.org/Apps/EasyTAG/Screenshots?action=AttachFile&do=get&target=screenshot_sw_mask_editor.png)

Having a preview could be pretty cool as well, as it isn't clear that “${title}” defaults to displaying the current directory for example.

**Comment by gnunn1** [comment]
It's covered in the [FAQ](https://gnunn1.github.io/terminix-web/faq) but I agree that it is something that needs to be more discoverable. Having said that, that EasyTag screen is pretty ugly IMHO. 

Perhaps a link to a dedicated online help page next to the combobox would be sufficient?

**Comment by phw** [comment]
I agree, it should be something nicer than what EasyTag does offer. What about a help link opening a popover?

**Comment by gnunn1** [comment]
@phw That's a possibility as well. One note to myself, there are four places where these titles work: Session Name, Application Title, Terminal Title and Badge.

**Comment by Jiehong** [comment]
EasyTag's window isn't a thing of beauty, indeed, but it was the only example that came up to my mind having a similar feature.

The pop-over could be pretty good!
I assume the use could copy/paste from it directly as well.

For the story, when trying to find information about what could be used, I checked:
1. `terminix --help`
2. `man terminix`
2.5 `Google`
3. Then the Wiki, but I couldn't figure out how to search in it.
4. Search in the code :D

Hopefully, people usually find it a bit more easily than me… haha

**Comment by phw** [comment]
Now that Terminus has a manpage this is definitely another good place for this info (in addition to the in app help).

**Comment by gnunn1** [comment]
So I've added some code to support this, here's what it looks like:

![screenshot from 2017-01-06 11-51-26](https://cloud.githubusercontent.com/assets/9358238/21725494/b485d122-d406-11e6-993c-10feeb931159.png)

**Comment by phw** [comment]
That looks great, I like it

**Comment by Jiehong** [comment]
Great job!

Just the "Help | Help" section feels funny.
