### ISSUE TITLE
Close window dialog closes all terminal window, even on cancel button

### ISSUE THREAD

**Issue by marco-prati** [gnunn1/terminix#674]
Hi, i'm on master (version number 1.4.3-0.0.1 in about dialog), default config. These are the steps to reproduce the bug:
1. open a terminal window
2. open another terminal window and ssh into an host or launch and interactive process (`htop` for example)
3. try to close the terminal with the ssh or htop session open
4. the close window dialog warning pops up 
5. When you hit close all terminal windows are closed, even if cancel button is clicked.

**Comment by gnunn1** [comment]
I cannot reproduce, here's the steps I tried based on what you posted:

1. open a terminal window
2. open a new terminal
3. run the ```top``` command
4. Press the close button of the window running the ```top``` command
5. Close Window dialog is displayed
6. Click Cancel
7. Dialog disappears, no other action is taken

**Comment by marco-prati** [comment]
I've tried and for me it fails even with only one window open (running `top`). Here's the output when I hit close or cancel:
```
λ [~] → terminix

(terminix:18554): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(terminix:18554): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(terminix:18554): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

(terminix:18554): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(terminix:18554): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(terminix:18554): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(terminix:18554): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
**
GLib-GObject:ERROR:gobject.c:2899:toggle_refs_notify: assertion failed: (tstack.n_toggle_refs == 1)
[1]    18554 abort (core dumped)  terminix
```

**Comment by gnunn1** [comment]
That last one is the problem, it's a bug in GtkD 3.4.0. please try building with GtkD 3.4.1 if you are not using it already.

**Comment by marco-prati** [comment]
Confirmed, GtkD 3.4.1 solves the problem. Thank You
