### ISSUE TITLE
Close terminal frame close the whole window

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#677]
While i was working on a python code, the code stopped and i had to close the terminal "frame". I clicked on the correct frame and hit the Close button. But it closed the whole terminal instead of closing the "frame".
How to reproduce that? Just open a new terminal, separate the terminal vertically or horizontally; type sleep 10 in on of them and try to close it. 

![capture du 2017-01-07 22-40-29](https://cloud.githubusercontent.com/assets/7660997/21745360/5c845208-d52a-11e6-9ff6-f51a439996aa.png)
![capture d ecran de 2017-01-07 22-40-47](https://cloud.githubusercontent.com/assets/7660997/21745362/622d45e8-d52a-11e6-9f3d-5b987d30f919.png)

This shouldn't close the whole application :( 
Hope its clear enough! And i'm using the latest git version

**Comment by gnunn1** [comment]
The problem is likely because you are using GtkD 3.4.0 instead of 3.4.1 or 3.5.0. There was a problem in that version where showing and close a dialog causes terminix to crash. Try building with a newer version of GtkD and the problem should be resolved.

@dsboger Would it be possible to update the Arch GtkD package to a newer version?

**Comment by bil-elmoussaoui** [comment]
It must be the case, the gtkd is outdated in AUR :(

**Comment by dsboger** [comment]
I'm working on that right now

**Comment by bil-elmoussaoui** [comment]
@dsboger it's still impossible to compile a new version of gtkd until i remove the old version :( which means that i have to uninstall terminix...Is there anything that we can do to fix this? Also, i couldn't neither install the latest gtkd version neither

**Comment by dsboger** [comment]
@bil-elmoussaoui The Makefile provided with GtkD 3.5.0 has a directory creation [bug](https://github.com/gtkd-developers/GtkD/issues/181) that prevents it to install correctly. The bug has been fixed and package `gtkd-git` should build and install properly. I've asked GtkD devs to do a point release with the fix and package `gtkd` is waiting for that, unless it takes too long, in which case I'll work around downstream. 

I've also removed the static libraries from both packages, which I suspect might be causing the linker errors. I've tested building/installing `gtkd-git` both in my production machine and in a blank-slate builder VM and it seems to be working. 

Finally, I've pushed a small fix for package `terminix-git` that allows it to use `gtkd-git` more easily. It builds, installs and works fine for me. Could you test using `terminix-git` + `gtkd-git` and report any issues in the AUR comments?

**Comment by bil-elmoussaoui** [comment]
I will do right now :) Thanks for your work!
