### ISSUE TITLE
Improvement in Japanese (possibility of occurrence in other languages)

### ISSUE THREAD

**Issue by fu-sen** [gnunn1/terminix#678]
I received a report from Twitter,
and confirmed that obviously funny translation was done on the added items.
Therefore, I improved Japanese with Hosted Weblate.
Please reflect this translation to the source.

This may be a problem in other languages,
and the translator needs to be notified and confirmed.

**Comment by gnunn1** [comment]
Changes in weblate are automatically propagated to the source in GitHub.

Can you shed some more light on the issue, is it a case of someone deliberately screwing up the translations (I.e. inappropriate words, completely unrelated content, etc) or just a case of someone doing a poor job?

If it's the former I have no clue on how to validate them, suggestions welcome.

**Comment by fu-sen** [comment]
It probably means that the translation has not been reset when the text changes are reflected in the Hosted Weblate.
If it keeps like this, the display may obviously go crazy in some languages!

**Comment by phw** [comment]
I am not sure I understand the issue. You say you got a notification on Twitter. Was that by some other user who reported it to you? Was it a specific string that was badly translated or was it about new/updated strings that needed translation? Maybe give us some example, currently I fail to see an issue here :)

There were some changes to the strings in Terminix, and that of course means the translation s need to be updated again. You can set up Weblate to send you notifications by e-mail when the source strings change.

**Comment by fu-sen** [comment]
https://github.com/gnunn1/terminix/blob/69e50b217e58628a114da8ed0e35c18e5e47d915/po/ja.po

#: source/app.d:133
#, fuzzy
msgid "Versions"
   -> "バージョン"
msgstr "ペルシア語"
   -> "Persian language"

#: source/app.d:134
#, fuzzy, c-format
msgid "Terminix version: %s"
    -> "Terminix バージョン: %s"
msgstr "%s を Terminix で開く"
    -> "Open %s on Terminix"

#: source/app.d:135
#, fuzzy, c-format
msgid "VTE version: %s"
    -> "VTE バージョン: %s"
msgstr "%s を Terminix で開く"
    -> "Open %s on Terminix"

It was a terrible translation.

**Comment by fu-sen** [comment]
It appears to be occurring in other languages as well. I used Google translation:
https://github.com/gnunn1/terminix/commit/69e50b217e58628a114da8ed0e35c18e5e47d915#diff-7c1fe251f091fb38df00894ab846c479

#: source/app.d:133
#, fuzzy
msgid "Versions"
msgstr "Сесия"
  -> "Session"

#: source/app.d:134
#, fuzzy, c-format
msgid "Terminix version: %s"
msgstr "Отваряне на настройки"
  -> "Open Settings"

#: source/app.d:135
#, fuzzy, c-format
msgid "VTE version: %s"
msgstr "Отваряне на настройки"
  -> "Opening Settings"

Even if you do not know the language, you will be able to see that there is a problem with the locale file, such as "%s" not attached.

**Comment by phw** [comment]
That's just how gettext works. For new strings it tries to find similar strings and will pull in translations for that. It marks the translations then as fuzzy, which marks them for review in Weblate.  Fuzzy strings are also not included in the compiled translation, so they will just fallback to the English source in the UI. It is the job of a translator to review those strings, do a proper translation and remove the fuzzy flag.

That behavior is intended as a help for translators and also helps in not loosing translations when a string is just slightly changed (e.g. a typo in the English language is fixed). As the whole process is just a similarity check of the source strings the results sometimes fit better, sometimes worse. But in any case they need to be reviewed.

**Comment by gnunn1** [comment]
Thanks for the detailed explanation @phw, much obliged. Closing issue.
