### ISSUE TITLE
Erroneous files in release 1.4.2 .zip

### ISSUE THREAD

**Issue by glitsj16** [gnunn1/terminix#679]
After installing terminix via AUR https://aur.archlinux.org/packages/terminix/ I'm seeing strange icon folders. As the AUR package simply copies content from the release zip offered here on GH it suggests something went wrong processing that file. Here's a rundown of the icon folder structure:

```
/usr/share/icons/hicolor
    16x16
    22x22
    24x24
    32x32
    48x48
    256x256
    512x512
    experimental <-- (1)
    files <-- (2)
    scalable

(1) usr/share/icons/hicolor/experimental
    flatpak2
        files
            usr/share/icons/hicolor/experimental/flatpak2/files/share/icons/hicolor
                16x16
                22x22
                24x24
                32x32
                48x48
                256x256
                512x512
                files
                    usr/share/icons/hicolor/experimental/flatpak2/files/share/icons/hicolor/files/share/icons/hicolor
                        16x16
                        22x22
                        24x24
                        32x32
                        48x48
                        256x256
                        512x512
                        scalable
                scalable

(2) usr/share/icons/hicolor/files
    share/icons/hicolor
        16x16
        22x22
        24x24
        32x32
        48x48
        256x256
        512x512
        scalable

```

Not sure whether the above accounts for the unusually large file size of the terminix binary in the .zip (about 10x larger):

https://aur.archlinux.org/packages/terminix-git/
```
$ stat -c %s /usr/bin/terminix
1848536

```
https://aur.archlinux.org/packages/terminix/
```
$ stat -c %s /usr/bin/terminix
1907080

```

**Comment by gnunn1** [comment]
I've updated the release archive, I was playing with getting things working in flatpak and some things snuck in that should not have. My apologies for that.

I don't track the file sizes, not sure why the binary is larger but I'll look into it. Worse case you can always run ```strip``` against it if you wish.

**Comment by gnunn1** [comment]
I checked the previous 1.3.5 release, the binary is the same size as 1.4.2 so I don't think anything has changed here. Are you sure you are not using the AUR terminix-git package, I believe that dynamically links to the GtkD shared library which will result in a much smaller binary then what I produce which uses static linking.

**Comment by glitsj16** [comment]
Confirming the fix for the icon issue, thanks. I tested both terminix AUR packages and your explanation regarding the file size difference is spot on. All the best for 2017, coding and otherwise.

**Comment by glitsj16** [comment]
Follow-up: I pinged the maintainer of the terminix AUR package about your fix.
