### ISSUE TITLE
Shadow does not appear on Gnome 3.16

### ISSUE THREAD

**Issue by jcarrz1** [gnunn1/terminix#68]
![screenshot from 2016-01-28 01-15-09](https://cloud.githubusercontent.com/assets/1952023/12640017/a990bca0-c55c-11e5-8e5d-97709ff86385.png)

A minor thing, but I really appreciate the work that has clearly gone into Terminix being GTK+ 3 style so I figured I'd mention it. (It's not just because it is currently the inactive window in the screenshot)

**Comment by gnunn1** [comment]
Working fine on 3.18, might be a side effect of supporting transparency. What theme are you using, if it's not Adwaita do you get the same behavior with Adwaita?

**Comment by krazyabouttechnology** [comment]
Yup, can confirm that shadow works fine on default Adwaita theme under Gnome 3.18 / Fedora 23.

**Comment by gnunn1** [comment]
No response from OP, closing issue.

**Comment by gnunn1** [comment]
Re-opening, problem looks like RGBA windows, which is required for transparency, are not compatible with drop shadows in GTK 3.16 or earlier. I'll add an option to disable transparency.

**Comment by gnunn1** [comment]
Added option to disable transparency which will restore drop shadows. This option is only visible when the GTK version is less then 3.18 though it can be set in dconf-editor directly.
