### ISSUE TITLE
Add support for Bookmarks

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#680]
I've debated about the need for this feature with myself a few times since the obvious alternative to bookmarks is to setup appropriate aliases. However for regular SSH users I think bookmarks can be a useful particularly where you might have limited permissions on the target system.

Bookmarks would be stored hierarchically similar to the way it is handled in a typical browser. This feature would add a bookmark manager to the preferences dialog to manage and organize the bookmarks. For accessing bookmarks, a searchable dialog similar to the existing password dialog would be used.

The following types of bookmarks would be supported:

* Path, represents a path and would translate it into a ```cd``` command
* SSH
* FTP
* Command, represents a one line command. Possibly support custom variables with substitutions via a GUI.

**Comment by gnunn1** [comment]
Just an update on this, I have a basic bookmark manager working now and bookmarks are saved/loaded in a JSON file to ~/.config/terminix/bookmarks.json. The bookmark manager allows a users to do the basics of add, edit and remove bookmarks but there is still a lot of work to do before I can turn things on for users.

At the moment the following bookmark types are supported:

a. Folder - Used to organize bookmarks heirarchacly
b. Path - A path location on the file system
c. Remote - A bookmark to a remote system using SSH, telnet, FTP, etc
d. Command - A bookmark representing a command

Things left to do include:

a. accessing bookmarks from terminal. This will be a searchable dialog similar to the existing password dialog

b. Creating bookmarks from the terminal and making it smart enough to guess the bookmark type.

c. Drag and drop in bookmark manager to re-organize bookmarks

Here's a couple of screenshots showing what it looks like so far:

![screenshot from 2017-01-29 16-27-27](https://cloud.githubusercontent.com/assets/9358238/22408090/c2890ba8-e640-11e6-8c7d-3ca5ab18bd5e.png)

![screenshot from 2017-01-29 16-27-59](https://cloud.githubusercontent.com/assets/9358238/22408092/c7dc4b24-e640-11e6-9023-99b2c89bd3de.png)

**Comment by gnunn1** [comment]
I've enabled bookmarks so feel free to give it a try and open bug reports as needed. Note that I would urge some caution in terms of backing up your bookmarks periodically in case you hit a bug. Bookmarks are stored in ```~/.config/terminix/bookmarks.json```.

Also, note the menu items in the terminal titlebar for bookmarks are not final, I'm planning on re-working that menu.

**Comment by shivakumargn** [comment]
Tried the bookmarks features with v1.7.7. The feature is very nice. The "Add bookmarks" and "Select bookmarks" kind of options are most useful when accessible with single keyboard shortcut or a 1/2 clicks.

**Comment by shivakumargn** [comment]
I wrote the comment within 5mins of trying tilix. Was a bit hasty. Came across https://github.com/gnunn1/tilix/issues/1053 and then checked out shortcuts(screen 2) options. Works well. Thanks.

**Comment by cgerada** [comment]
i know this is an old thread, but my bookmarks are not being saved 
and I do not have a ~/.config/terminix/bookmarks.json  file on my system  , (adding bookmarks does not create this file)  when I quit tilix all the bookmarks that I created dissapear,  any help regarding this greatly appreciated.  thanks
