### ISSUE TITLE
Library load failed

### ISSUE THREAD

**Issue by TheAifam5** [gnunn1/terminix#683]
OS: ArchLinux
Packages: gtkd-git | terminix-git

``
object.Exception@src/gtkc/Loader.d(123): Library load failed (libcairo.so.2): /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
``

Cairo & harfbuzz & harfbuzz-icu are installed cuz i'm using Gnome Desktop.

**Comment by arcticicestudio** [comment]
https://github.com/gnunn1/terminix/issues/682#issuecomment-271589615
