### ISSUE TITLE
broken dependencies from RPMs for Fedora 23 available via the OpenSUSE Build Service.

### ISSUE THREAD

**Issue by hhlp** [gnunn1/terminix#69]
Today there is an update of terminix, installed in fedora 23:

Last metadata expiration check performed 2:04:45 ago on Thu Jan 28 12:09:28 2016.
Dependencies resolved.
================================================================================
 Package          Arch           Version               Repository          Size
================================================================================
**Skipping packages with broken dependencies:**
 terminix         x86_64         0.45.0-8.1            home_gnunn         2.1 M

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Complete!

regards.,

**Comment by gnunn1** [comment]
Closing, dup of #67
