### ISSUE TITLE
Dark Variant and Xubuntu 16.04

### ISSUE THREAD

**Issue by mimf** [gnunn1/terminix#692]
Hello,

Dark Variant doesn't work on Xubuntu 16.04.

**Comment by phw** [comment]
AFAIJ that depends on the GTK theme used, if it doesn't support a dark variation the styling won't change. What Gtk theme do use?

**Comment by mimf** [comment]
The default one in Xubuntu 16.04, which is greybird. Yes, it seems to not support a dark variation. Oh well.
