### ISSUE TITLE
Quake hotkey

### ISSUE THREAD

**Issue by mimf** [gnunn1/terminix#693]
What's the quake hotkey/shortcut? In preferences, there are settings for Quake mode. However, I can't find any option, under shortcuts, for quake mode.

**Comment by alexwhitman** [comment]
There isn't an option within Terminix, the idea is to set a hot key within your desktop environment to run `terminix --quake`.

**Comment by gnunn1** [comment]
Following on @alexwhitman comment, see the documentation here:

https://gnunn1.github.io/terminix-web/manual/quake/

**Comment by humanamerican** [comment]
An update to @gnunn1 comment: the site is now https://gnunn1.github.io/tilix-web/manual/quake

**Comment by alexfornuto** [comment]
As a note to the documentation linked, while it says that quake mode won't work on Wayland without invoking X, I was able to do so just fine.

**Comment by mmrezaie** [comment]
I still do not have any idea what is the shortcut to open/hide tilix. As a long time terminator user I would like something that works on Wayland but how should I do it?

I am testing tilix on gnome 3.38 and the extensions are not working for some reason!?

**Comment by phw** [comment]
You can configure keyboard shortcuts for Gnome in Gnome's settings menu. There you can bind keyboard shortcuts to arbitrary commands. For the command to use see the Tilix documentation at

https://gnunn1.github.io/tilix-web/manual/quake/

**Comment by mmrezaie** [comment]
ooh I see. I was just reading the text and not paying attention to the image. thanks.
