### ISSUE TITLE
Open new terminal windows in the folder of the active terminal.

### ISSUE THREAD

**Issue by RealKindOne** [gnunn1/terminix#699]
Other terminal emulators such as ```gnome-terminal```, ```roxterm```, ```terminator```, and ```xfce4-terminal``` (and maybe others) open new terminal windows in the folder of the active terminal window.

Reasoning for this is if someone is working on multiple things in the same folder and does not want to enter ```cd /some/path/here``` into the terminal every time.

Could it be possible to do this by default or have an option for it? Thanks.

**Comment by bil-elmoussaoui** [comment]
Already available just enable this 
![screenshot from 2017-01-18 05-36-59](https://cloud.githubusercontent.com/assets/7660997/22051033/36661854-dd40-11e6-83d4-a0199698dcc5.png)

**Comment by RealKindOne** [comment]
@bil-elmoussaoui Oh. thanks.

**Comment by phw** [comment]
Also see https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue for a more in-depth explanation for this and alternative solutions.
