### ISSUE TITLE
Could not load libvte-2.91.so on RHEL 7.2

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#7]
Currently terminix tries to load the VTE library as libvte-2.91.so which exists on Arch, however on RHEL 7.2 it does not exist. The name should be changed to libvte-2.91.so.0 which exists on both systems.

**Comment by alex285** [comment]
It was trying to find libvte2_91.so instead of libvte-2.91.so (rawhide)

**Comment by gnunn1** [comment]
Thanks, I figured that out as well, I just haven't updated this bug yet. I opened issue #141 with GtkD for this so once they fix it I'll close this. In the meantime I patched GtkD locally to use libvte-2.9.1.so.0.

https://github.com/gtkd-developers/GtkD/issues/141

**Comment by gnunn1** [comment]
Fixed in GtkD, closing.

**Comment by alex285** [comment]
GtkD requires beta version of D?

**Comment by gnunn1** [comment]
I've been using a git version of GtkD to build because they patched a
critical memory issue but hadn't cut a new release. They just released the
new version last night, If you update the version to 3.2.2, without the
commit tag, in dub.json it should work.

I'll test and update it in github in a couple of hours.

**Comment by alex285** [comment]
yeah noticed the new version after comment. Thanks!
