### ISSUE TITLE
Using topbar shows a Menu on settings

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#700]
As i switched to dash-to-panel recently. I've had this small "bug" on the preferences window. It shows the application menu in there too! It shouldn't be the case...
![screenshot from 2017-01-18 05-37-17](https://cloud.githubusercontent.com/assets/7660997/22051058/683fcf46-dd40-11e6-864a-38e2ed42a159.png)

**Comment by bil-elmoussaoui** [comment]
By looking at the source code https://github.com/gnunn1/terminix/blob/master/source/gx/terminix/prefeditor/prefdialog.d#L94 you seem to be using an ApplicationWindow for the settings instead of a simple Window which will fix that ;)

**Comment by gnunn1** [comment]
The ApplicationWindow is required to make the ```-preferences``` option work. In master it should be setting ```showMenubar(false)```.

**Comment by gnunn1** [comment]
Yeah looks fixed to me in master, if it's not let me know.

**Comment by bil-elmoussaoui** [comment]
Perfect! I will update to master and reopen if i still have this issue ;) Thanks!
