### ISSUE TITLE
Huge image as a background

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#703]
Comparing to xfce4-terminal, terminix seems to be consuming much more memory for a background image. For example, [this image](https://commons.wikimedia.org/wiki/File:LRO_Tycho_Central_Peak.jpg) (21,467 × 9,860 pixels, file size: 42.3 MB) takes about 1 GB of RAM in terminix and only about 660 MB in xfce4-terminal.
An even bigger [image](https://commons.wikimedia.org/wiki/File:In_the_Conservatory.jpg) (30,000 × 22,943 pixels, file size: 172.7 MB) gets terminix killed by OOM guard on my machine with 8 GB of RAM, but xfce4-terminal can handle it taking about 2 GB of RAM.
I was measuring RAM usage by running htop and looking at RES column.

**Comment by gnunn1** [comment]
I have some suspicions about where the problem might be, thanks for bringing it to my attention.

**Comment by gnunn1** [comment]
OK so I'm not seeing the same results but I suspect what I know what is happening.  First a couple of points as follows:

a. Terminix enforces a maximum resolution (4K max) for the image, if you load an image past that size Terminix only caches a lower resolution version of that image.

b. D is a GC'ed language unlike xfce, so remember that temporary objects are kept around for awhile including

So when I use the conservatory image, the memory use between terminix and xfce seems to be about the same:

![screenshot from 2017-01-20 18-40-12](https://cloud.githubusercontent.com/assets/9358238/22169157/10deec4e-df40-11e6-9bde-82ba0bedea3c.png)

However once I invoke the GC (When running in debug mode there is a GC menu item in the hamburger menu to force a collection), the memory use plummets:

![screenshot from 2017-01-20 18-40-38](https://cloud.githubusercontent.com/assets/9358238/22169174/34570404-df40-11e6-947c-187438f8f053.png)

Based on this, I made a code change to destroy a temporary pixbuf I was using 
and on my system it seems to address the memory issue as GTK frees up the image data in memory immediately even though the pixbuf object lingers until the D GC gets around to it.

BTW, are you using 32 bit or 64 bit? I wonder if part of the issue you were having is that something in DMD or LDC is sub-optimal on 32 bit.

**Comment by f2404** [comment]
I was testing this on a 64 bit machine.

BTW, limiting image resolution to 4K looks like a good idea, I think I will do it in xfce4-terminal in order to limit memory consumption.

**Comment by gnunn1** [comment]
If you try that change I made does it fix the issue?

**Comment by f2404** [comment]
Your change helped in the way that is frees the memory after the image has been loaded.
However, the gigantic 30,000 × 22,943 image still kills terminix after it has eaten about 3 GB.

**Comment by gnunn1** [comment]
It's working fine for me here so I need to understand what is different. Are you compiling with LDC or DMD? Is any error message shown when it crashes?

I wonder too if the difference is simply I'm on a machine with 16 GB of RAM versus your 8.

**Comment by f2404** [comment]
Both the version that you compile and [terminix-git](https://aur.archlinux.org/packages/terminix-git) work the same for me. There's no error from terminix; OOM killer prints the following to the system journal:
```
kernel: Out of memory: Kill process 12881 (terminix) score 780 or sacrifice child
kernel: Killed process 12881 (terminix) total-vm:8663436kB, anon-rss:6257084kB, file-rss:76kB, shmem-rss:4692kB
kernel: oom_reaper: reaped process 12881 (terminix), now anon-rss:0kB, file-rss:0kB, shmem-rss:4692kB
```
Indeed, I think you're not observing it because your system has more RAM, and OOM killer threshold is probably higher.
Do you have any idea why terminix is using 1.5 times as much RAM as xfce4-terminal while loading a file to memory?

**Comment by gnunn1** [comment]
@f2404 I suspect it's simply because I downscale huge images to 4K. When this happens I'm holding both the original image and the 4K ImageSurface in memory at the same time. Once the downscaling is completed, the original image pixbuf is destroyed but there is that point in time where more memory is required. Additionally, GTK may be using additional memory to actually render the downscaled image.

Does that make sense to you?

**Comment by f2404** [comment]
xfce4-terminal was also loading the entire image to memory (with `gdk_pixbuf_new_from_file()`) but taking less RAM than terminix.

I have just pushed a change to check image resolution before actually loading, it and use `gdk_pixbuf_new_from_file_at_size()` instead of `gdk_pixbuf_new_from_file()` in case it's too high (higher than 8K). This allowed to reduce memory usage from 2G to 550M while loading our gigantic image.
Maybe you could use the same approach in terminix?

**Comment by gnunn1** [comment]
Thanks for the tip, it makes a huge amount of sense and I'll look into it.

**Comment by gnunn1** [comment]
I've made the same change as you with respect to checking the image size first and if it exceeds the max permitted size load it at that size. If you get a chance, try it out and see if it fixes the crash issue for you. Memory usage seems good here, not sure what else I can do.

BTW, appreciate the collaboration, thanks again for all the help.

**Comment by f2404** [comment]
Yes, your change seems to have fixed the issue for me.

And you are very welcome :)
