### ISSUE TITLE
Can you add pt_PT to language translation?

### ISSUE THREAD

**Issue by danielpinto8zz6** [gnunn1/terminix#705]
https://hosted.weblate.org/projects/terminix/#languages
I only see pt_BR

**Comment by gnunn1** [comment]
You should be able to add new languages in weblate, I have not been adding them in git.

**Comment by phw** [comment]
Adding a new language in Weblate is a bit hidden under Tools > Start new translation

Anyway, I have added Portuguese, see https://hosted.weblate.org/projects/terminix/translations/pt_PT/ . Happy translating :)

**Comment by gnunn1** [comment]
Thanks @phw!

**Comment by danielpinto8zz6** [comment]
Thank you guys, have a nice day
