### ISSUE TITLE
Detecting Wayland

### ISSUE THREAD

**Issue by gnunn1** [gnunn1/terminix#708]
Currently terminix uses an environment variable to detect if Wayland is the back-end. However when switching between Wayland and X11 via logout/login I found that the Wayland environment variables would hang around on the X11 sessions causing terminix to think it was running under Wayland when X11 was active. 

To avoid this, a full restart when switching between the two was required. I need to look at using the gdk_wayland_display_get_type which GtkD unfortunately does not link.

**Comment by f2404** [comment]
In xfce4-terminal, I'm using `GDK_IS_X11_WINDOW` macro: please see https://wiki.gnome.org/Initiatives/Wayland/Applications/Porting

**Comment by gnunn1** [comment]
Thanks, it looks like that macro maps to gdk_x11_window_get_type which GtkD does link to so that is a better alternative for me.
