### ISSUE TITLE
Terminix fails on load (parse) a previous saved session file (malformed JSON)

### ISSUE THREAD

**Issue by theUncanny** [gnunn1/terminix#709]
# Terminix fails on load (parse) a previous saved session file (malformed JSON)

## Example (real) of an automatic saved session file

The problem is in the value format for `ratio` field:

```json
{
    "child": {
        "child1": {
            "directory": "\/home\/theuncanny",
            "height": 494,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 1914
        },
        "child2": {
            "directory": "\/home\/theuncanny",
            "height": 490,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 1914
        },
        "orientation": 1,
        "position": 50,
        "ratio": 0,5,
        "type": "Paned"
    },
    "height": 988,
    "name": "Default",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 1914
}
```

**`"ratio"`** field value format:
* Original and **incorrect** (*comma* character): `0,5`
* Correct (*point* character): **`0.5`**

## Additional information

* Terminix version:

```bash
Versions
	Terminix version: 1.4.2
	VTE version: 0.42
	GTK Version: 3.18.9
```

> **Note**: Installed from `ppa:webupd8team/terminix`

* Ubuntu version:

```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

* Locale: `es_ES.UTF-8`

> Update: Added locale information. Thanks to @f2404 and @gnunn1.

**Comment by f2404** [comment]
Is my guess correct: your locale is not en_US?

**Comment by gnunn1** [comment]
Are you in a country that uses the comma character as a decimal separator? I think this is a bug in D's JASON library that I worked around elsewhere.

**Comment by f2404** [comment]
I've also had this problem with yajl :)

**Comment by theUncanny** [comment]
@f2404 @gnunn1 You both are right, my locale is `es_ES.UTF-8`.
