### ISSUE TITLE
Testing the translations

### ISSUE THREAD

**Issue by frnogueira** [gnunn1/terminix#71]
In my Arch Linux, I can't test the mo files. I did put in /usr/share/locale/pt_BR/LC_MESSAGES and nothing. Someone using Arch Linux here to help me?

**Comment by gnunn1** [comment]
I just tested French on my system and it works fine. Is the pt_BR locale installed on your computer, you check that with ```locale -a```? 

Also, to test Terminix, in gnome-terminal (or other terminal, make sure Terminix isn't running already) try forcing the locale by running it as follows:

```
LC_MESSAGES=pt_BR.utf8 terminix
```

Any locale related messages shown?

**Comment by frnogueira** [comment]
Nothing! 

My locale is pt_BR.utf8, but, terminix still in english. I will try in another machine

**Comment by frnogueira** [comment]
Something wrong with Arch. On CentOS, everything Ok.
By investigating.. ;)

**Comment by frnogueira** [comment]
[RESOLVED]

Solution: I did remove the terminix and install again with yaourt.... Bingo!
Before I had installed via makepkg ... :(
