### ISSUE TITLE
Force to close the session without the popup

### ISSUE THREAD

**Issue by zatan** [gnunn1/terminix#712]
Can this popup be removed or at least to have some option to force close without asking?

![screenshot from 2017-01-25 12-56-04](https://cloud.githubusercontent.com/assets/486313/22291342/bea2b840-e2fd-11e6-8ff9-0f7e4b4b2b65.png)

**Comment by gnunn1** [comment]
Absolutely, I'm kind of surprised I don't have an option for that already.
