### ISSUE TITLE
Man page localizations

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#713]
Why no man page localizations?

**Comment by gnunn1** [comment]
I haven't had time to look into how to best handle it, contributions welcome as always.

**Comment by phw** [comment]
Just a heads up that the manpage localization is now up on Weblate: https://hosted.weblate.org/projects/terminix/manpage/

**Comment by f2404** [comment]
I'm seeing only German, is it possible to add other translations?

**Comment by phw** [comment]
Sure, that's why we have it on Weblate so others can help translate. You can start a new language on Weblate over Tools > Start new translation

**Comment by f2404** [comment]
Ah, ok, thanks!

**Comment by frnogueira** [comment]
Great! 
pt_BR added!

**Comment by phw** [comment]
I noticed the German translation is not yet included in the current release zip, even though it was available.

@gnunn1 Do you have po4a installed?

**Comment by gnunn1** [comment]
@phw I do now!
