### ISSUE TITLE
Titlebar is transparent in 1.4.2 on Fedora 25 (Wayland)

### ISSUE THREAD

**Issue by carlbolduc** [gnunn1/terminix#714]
![screenshot from 2017-01-25 13-22-56](https://cloud.githubusercontent.com/assets/410440/22303504/90928576-e301-11e6-9273-2d71389c1431.png)

**Comment by gnunn1** [comment]
I suspect the resource file which contains the terminix CSS was not installed correctly. How did you install it, from the COPR package? 

Can you check if this file is present on your system:

```
/usr/share/terminix/resources/terminix.gresource
```
This is why your icons for adding terminals are not there either.

**Comment by carlbolduc** [comment]
The `/usr/share/terminix/resources/` folder exist but is empty.

I downloaded 1.4.2 sources and did this to install it:
- `dub build --build=release`
- `sudo ./install.sh`

**Comment by gnunn1** [comment]
That should do the trick, what was the output of install.sh, any complaints about building the resource file?

**Comment by carlbolduc** [comment]
Yes it's complaining:
```
Building and copy resources...
./install.sh: line 36: glib-compile-resources: command not found
install: cannot stat 'terminix.gresource': No such file or directory
```
After installing glib2-devel and gdk-pixbuf* pacakges, the install script stopped complaining.

Thank you, it's much better now:
![screenshot from 2017-01-25 14-24-57](https://cloud.githubusercontent.com/assets/410440/22305624/365ac556-e30a-11e6-9a17-aa0426dcadfa.png)

**Comment by gnunn1** [comment]
You are welcome, glad it worked out.

**Comment by f2404** [comment]
> Yes it's complaining:
> Building and copy resources...
> ./install.sh: line 36: glib-compile-resources: command not found
> install: cannot stat 'terminix.gresource': No such file or directory

@gnunn1 Shouldn't the install script fail in such case, to avoid broken installations?

**Comment by gnunn1** [comment]
@f2404 I don't disagree, but people should install from packages so I haven't spent much time on optimizing it.
