### ISSUE TITLE
env variables aren't adapted at program start

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/terminix#718]
After entering `LANG=en_US.UTF8 terminix` I get this output in the new terminal:
```
$ env | grep LANG
LANG=de_DE.UTF-8
GDM_LANG=de_DE.UTF-8
```

**Comment by f2404** [comment]
Is another instance of terminix with LANG=de_DE.UTF-8 already running?

**Comment by fbruetting** [comment]
No, but why should this be affected by other instances?

**Comment by f2404** [comment]
Well, it seems it is.
`LANG=ru_RU.UTF-8 terminix` works fine for me here - unless there's another instance of terminix run with default locale which is en_US.UTF-8.

**Comment by fbruetting** [comment]
I tested this again before confirming this to you. I expect this to work, even if other instances are running, seems strange to me.

**Comment by gnunn1** [comment]
Terminix is a single process, so multiple windows all run in the same process. Thus whatever language you us to start the original process persists for the others.

**Comment by fbruetting** [comment]
Ok, I misunderstood this – I can't start in a first Terminix window, but have to start in e.g. Gnome-Terminal and call Terminix with the env I want it to run. Then it works. But can't arguments be passed so the new instance runs like `LANG=XYZ` at start before showing the prompt? Doing this manually works!

**Comment by f2404** [comment]
You could create a launcher and run terminix with the desired locale.

**Comment by fbruetting** [comment]
I don't need this regularly, but I see this more as a general deviation from expected behaviour. Because every other program I know of accepts env variables passed this way. Maybe I'm wrong…?

**Comment by gnunn1** [comment]
Most GTK 3.0 applications are single instance and work the same way that terminix does, for example:

```
gedit
LANG=ru_RU.utf8  gedit --new-window
```

the new window is in english not russian.
