### ISSUE TITLE
Commands are executed, despite there's something wrong if sudo authentication is active

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/terminix#719]
Without having yet entered the sudo password, the command is stopped:
```
$ sudo find / -iname fei8lhn | pv
bash: pv: command not found...

[2]+  Stopped                 sudo find / -iname fei8lhn | pv
$ Install package 'pv' to provide command 'pv'? [N/y]
```

After having authenticated (by `$ sudo ls`), the first command gets executed:
```
$ sudo find / -iname fei8lhn | pv
bash: pv: command not found...
Install package 'pv' to provide command 'pv'? [N/y] find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
```

// Edit: The command even runs when not using sudo and Gnome-Terminal behaves the same. Guess it's not Terminix-related… so whom should I report this bug?

**Comment by gnunn1** [comment]
I'd say bash, I don't think this is a terminal emulator problem.
