### ISSUE TITLE
Unable to open new terminix windows with Gnome hotkey

### ISSUE THREAD

**Issue by larsks** [gnunn1/terminix#722]
I have a hotkey configured in my desktop environment that will open a new window, previously mapped to the command `gnome-terminal`.  If I replace this with `terminix`, then:

- If Terminix is not currently running, it will open a new Terminix window.
- If Terminix is already running, it does nothing.

I see the same behavior if I try to run Terminix via the Gnome "activities" interface.

I am extra puzzled because in both cases, simply running `terminix` from the command line results in a new window opening.

**Comment by bil-elmoussaoui** [comment]
@larsks You can use `terminix --new-process` instead of `terminix`

**Comment by f2404** [comment]
@bil-elmoussaoui `--new-process` isn't recommended for regular usage.
@larsks Assigning `terminix` to a shortcut does open multiple terminix windows here under Xfce. What is your DE?

**Comment by larsks** [comment]
I saw that about `--new-process`, which is why I wasn't using it.

@f2404 I'm using a stock Gnome 3 install on Fedora 25.  It's not *just* a hotkey issue...going to the Gnome "activities" menu and trying to start Terminix has the same behavior (if there is already a terminix window open, nothing happens).

**Comment by f2404** [comment]
@larsks Do I understand correctly that there's no such issue with gnome-terminal? Can you try xfce4-terminal - will it behave as expected?

**Comment by larsks** [comment]
@f2404 I am embarassed.  Doubly so because:

(a) It looks like it *was* a hotkey problem, and very likely something broken because I had upgraded some packages without restarting the desktop environment, and

(b) because I had erroneous memories of the behavior of the activities menu.

So...neeeeeeeever mind.

/me craws back under a rock.
