### ISSUE TITLE
The "-e" option does not work as documented

### ISSUE THREAD

**Issue by larsks** [gnunn1/terminix#723]
According to the man page:

       -e --command=COMMAND
              Executes all text after this parameter as a command,  thus  this
              parameter must be the last parameter.

But try something like this:

    $ terminix -e env PS1="test$ " bash --norc

I would expect that to run `env PS1="test$ " bash --norc` in a new Terminix window, but it doesn't.  Instead, you get:

    Unknown option --norc

You can *quote* the command:

    $ terminix -e 'env PS1="test$ " bash --norc'

And that will launch the expected command, but that is not the behavior described by the man page.  Requiring a quoted string can substantially complicate things if someone is trying to run a command that *already* contains quotes.  

For comparison, the `-e` option to XTerm behaves in the manner described by the Terminix man page:

    $ xterm -e env PS1="test$ " bash --norc

**Comment by larsks** [comment]
Requiring quoted strings *also* prevents a shell like `bash` from performing tab completion when typing in the command.

**Comment by gnunn1** [comment]
gnome-terminal seems to have the same issue. I think the solution here is for terminix to implicitly quote everything after the -e while escaping any inner quotes. So when you type:

```
terminix -e env PS1="test$ " bash --norc
```

Internally terminix will treat it as:

```
terminix -e "env PS1=\"test$ \" bash --norc"
```

**Comment by gnunn1** [comment]
Oh and just to clarify, by implicitly quote, I mean terminix would do this additional quoting internally before passing it onto the GTK application which handles the arguments.
