### ISSUE TITLE
gschema overrides do not seem to apply

### ISSUE THREAD

**Issue by highvoltage** [gnunn1/terminix#724]
Usually, you can override defaults in gschema xml files in /usr/share/glib-2.0/schemas by adding another file with a .gschema.override that contains the dconf settings to be applied as default.

So for example, when I add a file called 95_com.gexperts.Terminix.gschema.override to /usr/share/glib-2.0/schemas that contains the following:
```
[com.gexperts.Terminix]
theme-variant='dark'
warn-vte-config-issue=false
```

It should set the default theme to dark and disable the vte warning by default. Unfortunately this doesn't seem to take effect and I can't find out why. My other gschema overrides work fine though, so it seems that this is Terminix specific.

**Comment by phw** [comment]
Are you sure you haven't personal user settings for the keys in question already? After all this does just change the defaults, not the user settings. Maybe try resetting all the Terminix dconf configuration for your user.

**Comment by gnunn1** [comment]
The group ID you are using isn't correct, try this:

```
[com.gexperts.Terminix.Settings]
theme-variant='dark'
warn-vte-config-issue=false
```

This gets it working for the warn-vte-config-issue but the theme-variant still isn't working, not sure if it's something to do with enums?

**Comment by gnunn1** [comment]
Oh never mind, it does work for the enum, I wasn't using the default setting.
