### ISSUE TITLE
Open in Terminix nemo plugin

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#729]
The same as Nautilus plugin but for Nemo. The code shouldn't be too different. I've installed Nemo and i will give this a shout!

**Comment by gnunn1** [comment]
Nemo already as an open in terminal which unlike Nautilus is configurable with regards to which terminal is used so I'm not sure this is needed?

http://winaero.com/blog/how-to-set-the-default-terminal-app-in-nemo/

**Comment by bil-elmoussaoui** [comment]
Alright! i didn't knew that you can configure Nemo plugins. I was thinking of reusing the same shortcut key that we use in Nautilus for Nemo and rename the Nautilus string to File Manager or something like that. Terminix having it's own Nemo plugin will allow us to port the same functionalities to both plugins without having to wait for that to be implemented upstream;

 Anyway, It's up to you. I don't even use Nemo :P

**Comment by gnunn1** [comment]
I wouldn't bother personally, I know people are using Terminix with Nemo just fine as it is.
