### ISSUE TITLE
Please reduce the height of header bar if possible

### ISSUE THREAD

**Issue by krazyabouttechnology** [gnunn1/terminix#73]
In comparison to Gnome-Terminal, the header bar of Terminix looks huge and I feel takes a bit more space than necessary. There is no penalty functionality wise, but on my 1366x768 resolution LCD (which an awful lot of people have unfortunately), it doesn't feel right somehow....looks a bit giant. Gnome-Terminal's title bar although is not a header bar, is a bit more pleasant looking. 

I don't know whether it is possible under GTK+ or not, but if possible I would request to make the header bar a bit slimmer, height wise.

Thanks.

**Comment by KateAdams** [comment]
>I feel takes a bit more space than necessary.

FYI, you're wrong.  Less space is taken up using a `HeaderBar`; hiding tabs when only one open is something Gnome-Terminal does and Terminix doesn't, and may be why you see more space wasted—even though it's not.  Hiding the file menu in Gnome-Terminal does use less space (a whopping ~16px with tabs in both…), but it's also less functional (UI) from then on too.

**Comment by krazyabouttechnology** [comment]
Fair enough. I will give reducing headerbar width system wide a try. On second thought, I actually find it a bit big for almost all applications. Thanks for the tip. Closing this issue.

**Comment by krazyabouttechnology** [comment]
I tried to do what you suggested using gtk.css, however, its only affecting the Client Side decorations, i.e. the windows which do not have a real headerbar, just their traditional titlebar replaced with a headerbar like titlebar, in appearance. Here is what I used:

.header-bar.default-decoration {
    padding-top: 2px;
    padding-bottom: 2px;
}

.header-bar.default-decoration .button.titlebutton {
    padding-top: 2px;
    padding-bottom: 2px;
}

**Comment by KateAdams** [comment]
@krazyabouttechnology This works for me on Gedit and Nautilus:

```css
.header-bar
{
	padding-top: 2.5px;
	padding-bottom: 2px;
}

.header-bar .button
{
	padding: 5px;
}

.header-bar .button.titlebutton
{
	padding: 5px;
}
```

![](http://i.imgur.com/YSF4iTZ.png)

**Comment by edubxb** [comment]
If you need to have more space in your screen, hide the GNOME Shell top bar (there are a few extensions to do this, I'm currently using [Hide Top Bar](https://extensions.gnome.org/extension/545/hide-top-bar/)) or put the apps in full screen mode, I really like the GNOME HIG, and the apps that follow it, so IMHO, the current design is the right.

**Comment by gnunn1** [comment]
As others have noted, Terminix follows the Gnome HIG and I don't have any plans to deviate from that at this time. If it were the case that Terminix's HeaderBar was larger then other Gnome apps such as GEdit and Files then I would happily fix it but as far as I can it is not. So from point of view, this is a Wont Fix and I'm closing the issue.

**Comment by krazyabouttechnology** [comment]
Yes, that css given by KateAdams worked. Thanks a lot.

Yes I do understand that following HIG is the right thing to do, and as such I never intended this to be a bug, rather more of a special request for people like me.

**Comment by josvos** [comment]
Just as a note for everybody referring to the GNOME Shell, GNOME HIG etc: I am using Xfce and I stopped using GNOME after version 2 (and I regret I didn't do this much earlier).  For the rest I do understand the reasons to follow Gtk3 defaults (although I do not always like them ;-)).
