### ISSUE TITLE
terminix in official distribution Ubuntu/Fedora

### ISSUE THREAD

**Issue by Pajinek** [gnunn1/terminix#739]
I used terminator, but I started use terminix some months ago. I am really happy, this application is more better and more usable. But I would like to have installed from official repository.

Did you try to push project to official distribution?

**Comment by phw** [comment]
Debian and Ubuntu already have it, but it is a mater of a new distribution release:

http://packages.ubuntu.com/zesty/terminix
https://packages.debian.org/stretch/terminix
