### ISSUE TITLE
Load session error: Key not found: orientation

### ISSUE THREAD

**Issue by glitsj16** [gnunn1/terminix#74]
After configuring terminix to use a vertically split layout I can save the session without error. Yet, when loading the saved xxx.json file later I always receive a 'Key not found: orientation' error:

$ terminix

2016-02-07T21:39:15.396:appwindow.d:loadSession:576
gx.terminix.session.SessionCreationException@source/gx/terminix/session.d(63):
Session could not be created due to error: Key not found: orientation

??:? gx.terminix.session.Session gx.terminix.session.Session.__ctor(std.json.JSONValue, immutable(char)[], int, int, bool) [0x80bed0]
??:? void gx.terminix.appwindow.AppWindow.loadSession(immutable(char)[]) [0x7fd966]
??:? void gx.terminix.appwindow.AppWindow.loadSession() [0x7fda72]
??:? _D2gx8terminix9appwindow9AppWindow20createSessionActionsMFC3gio8Settings8SettingsZ75__T12__dgliteral7TC4glib7Variant7VariantTC3gio12SimpleAction12SimpleActionZ12__dgliteral7MFC4glib7Variant7VariantC3gio12SimpleAction12SimpleActionZv [0x7fbf13]
??:? extern (C) void gio.SimpleAction.SimpleAction.callBackActivate(gtkc.giotypes.GSimpleAction*, gtkc.glibtypes.GVariant*, gio.SimpleAction.SimpleAction) [0x8564b3]
??:? g_closure_invoke [0xb3d91014]

After inspecting the json file it looks like there's actually nothing saved that relates to a splitting layout. Is saving/loading a split layout not implemented yet?

$ cat xxx.json
{
    "child": {
        "type": "Other"
    },
    "height": 414,
    "name": "Default",
    "type": "Session",
    "version": "1.0",
    "width": 642
}

OS: Arch Linux
terminix 0.45.0.r9.g9ba39ad-1
gtk3 3.18.7-1
vte3-notification  0.4

**Comment by gnunn1** [comment]
This should work fine, I'll test on my end and see if I can reproduce.

**Comment by gnunn1** [comment]
I'm assuming you were on the git version, I broke this when I added the initial work for maximize. The last commit should fix this, however note that I do not consider git stable and commits will break things from time to time as I don't test commits as thoroughly as I do releases.
