### ISSUE TITLE
[Symbolic Icons] Some extra icons?

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#744]
That image pretty much describes the issue. There are 4 (2+2) identical icons almost on the same position

![terminix-titlebar](https://cloud.githubusercontent.com/assets/11244308/22649942/d0ff4648-ec85-11e6-90df-1f3f25e67974.png)

Could Terminix provide unique max/unmax and close icons?

**Comment by gnunn1** [comment]
No, I don't think that would be a good idea. It would be confusing trying to explain what the new icons are and wouldn't fit it in well with the various icon themes.
