### ISSUE TITLE
Segfault when combining the q and s parameters

### ISSUE THREAD

**Issue by Nevel** [gnunn1/terminix#748]
Both the q and the s parameter work fine, except when combined (resulting in a segfault).

[ 3062.004053] terminix[15686]: segfault at 0 ip 000000000057e66b sp 00007fff59bc4820 error 4 in terminix[400000+1e5000]

Terminix version: 1.4.2
VTE version: 0.42
GTK Version: 3.18.9

OS: Linux Mint 18.1 Serena x86_64 
Kernel: 4.9.1-040901-generic

Please let me know if you need any more info.

**Comment by gnunn1** [comment]
I can reproduce, thanks for reporting this.
