### ISSUE TITLE
Quake mode opening when new instance is set to focus window

### ISSUE THREAD

**Issue by alexwhitman** [gnunn1/terminix#749]
I've been seeing an issue lately with Quake mode but I'm not sure when it started.  Under Ubuntu 16.04 I've configured a key combination to open Terminix in Quake mode.

If Terminix isn't running and I open a standard terminal window, triggering a quake mode window just focuses the terminal window.  If instead I first run Terminix in Quake mode and then open a standard terminal window, Quake mode works as intended.

It looks to be related to the "On new instance" setting as I have it set to "Focus Window".  If I set it to "New Window" then Quake mode opens as intended no matter what order Terminix was started in.

**Comment by gnunn1** [comment]
Thanks, I can reproduce it and I'll sort it out, should be an easy fix in ```application.d```.
