### ISSUE TITLE
cp: cannot stat ‘terminix’: No such file or directory

### ISSUE THREAD

**Issue by udara-u3** [gnunn1/terminix#75]
![screenshot from 2016-02-08 07-45-27](https://cloud.githubusercontent.com/assets/12265797/12879727/40303894-ce49-11e5-972a-06f9f724bcc0.png)

Hello,
I have installed DMD, and followed the instruction. when i run the ./install.sh getting error.
Any idea how to fix this ? (Ubuntu Xenial | Gnome)
Thanks.

**Comment by gnunn1** [comment]
You need to build the application before running install.sh:

```
dub build --build=release
```

**Comment by udara-u3** [comment]
Thanks. I have installed it successfully and fixed VTE Configuration Issue.
**But why i can't see that style under the username same like below Image ?**

![issue](https://cloud.githubusercontent.com/assets/12265797/12909232/7232a15e-cf18-11e5-9c0b-6f67f86f9fac.jpg)

**Comment by gnunn1** [comment]
That's powerline, has nothing to do with Terminix. Most distros should have it available in a package.

**Comment by udara-u3** [comment]
Got it, Thanks :)
