### ISSUE TITLE
Terminix and GNU screen

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#750]
I am using screen to handle (usb) serial connection with the command.
``` 
screen /dev/ttyUSB0 9600
```

After exiting the screen program with `Ctrl-A, Ctrl-D` combo, terminix becomes little strange. For example,  the scroll wheel on mouse changes its behavior to navigate through the command history instead of scrolling the terminal screen. Also, I cannot open a new serial connection again. 

I don't know who is the culprit of the problem, I am also using `zsh` shell and `oh-my-zsh` plugin. 

Someone has any idea on what is going on? Thanks.

**Comment by gnunn1** [comment]
Do you have the same issues in gnome-terminal, for example not being able to open the serial connection again.

**Comment by leoheck** [comment]
Good question, sorry by not to verify it when I made the issue, my fault.

gnome-terminal, terminator and terminix with the same behavior. I found the problem. I was using ``Ctrl+A, Ctrl+C`` instead of ``Ctrl+A, Ctrl+D``.

**Comment by manosnoam** [comment]
I'm having the same weird issue on the new Tilix.

After using CTRL+D (to exit session, instead of entering "exit"), the mouse scroll is navigating shell history commands, instead of scrolling Tilix console window.

Versions:
	Tilix version: 1.6.4
	VTE version: 0.46
	GTK Version: 3.22.10

Tilix Special Features:
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
