### ISSUE TITLE
Switching height control on Quake mode can cause window to reopen at 100% height

### ISSUE THREAD

**Issue by OmanF** [gnunn1/terminix#752]
(**_Gnome 3.22, Fedora 25_**)

1. Via the Gnome settings, set a keyboard shortcut to activate Terminix Quake mode (`terminix --quake`)
2. Open a Terminix console (with the shortcut key)
3. Go to the Quake settings page again and set the "Height percentage" bar to be over 50% (gauge by eye, since there's no numbering given)
4. Close Terminix *completely* (i.e. not just the settings page, but the console itself, via the "x" on the upper-right corner of the console)
4. Reopen the main console using the shortcut button

For me, I get a console display that takes up 100% of the screen.
This continues to happen until, using the Quake settings, I slide the "Height percentage" to about quarter way.

P.S. As can be seen in the screenshot, after this issue happens (fixed or not, by the percentage bar) the session title is malformed, though it "snaps" back to itself when hovered over.

![takeswholescreen](https://cloud.githubusercontent.com/assets/7848797/22778161/a074d20a-eebe-11e6-8fe1-d144d803528f.png)

![malformedtitle](https://cloud.githubusercontent.com/assets/7848797/22778171/ab570044-eebe-11e6-8b68-9f8c93b7bce0.png)

**Comment by OmanF** [comment]
Maybe has something to do with #617 and #573? They seem close...

**Comment by gnunn1** [comment]
Are you using Wayland, if so if you login using X11 instead do you still see the same issue?

**Comment by OmanF** [comment]
Indeed, switching from Wayland to X11 resolves the issue.

I'll leave it up to you if you consider this a _"Close"_ for the issue or not. Personally I can live with X11 over Wayland so I'm good. Thanks.

**Comment by gnunn1** [comment]
Unfortunately while I wish I could fix it my hands are tied unless I start writing Wayland extensions for different compositors which I'm not willing to do.
