### ISSUE TITLE
always on top in quake mode

### ISSUE THREAD

**Issue by pedromellofh** [gnunn1/terminix#753]
it would be nice if quake-mode was "always on top"

**Comment by f2404** [comment]
It is always on top for me. Have you unchecked the setting "hide window when focus is lost"?

**Comment by pedromellofh** [comment]
yes, i have it unchecked. i'm on fedora 25 under wayland... could be it the cause

**Comment by f2404** [comment]
Yes, wayland could be the reason - it's not actually allowing app windows to fine tune their position.
Can you login using X11 and try it, just to make sure?

**Comment by pedromellofh** [comment]
yes, wayland is the bad guy... it worked flawlessly on x11

**Comment by pedromellofh** [comment]
on wayland, I'm able to set always on top via context menu (alt+space) but it resets each time the window shows up

**Comment by gnunn1** [comment]
There's not much I can about Wayland issues unfortunately, it was one of the major reasons why I wasn't initially going to even bother with a quake mode.
