### ISSUE TITLE
why My terminix 1.4.2 not showing badges?

### ISSUE THREAD

**Issue by toplinuxsir** [gnunn1/terminix#755]
why My terminix 1.4.2 not showing badges?

**Comment by phw** [comment]
Badges require a patched VTE, see https://github.com/gnunn1/terminix/wiki/Badges for details.

What is the ouput of `terminix --version`? It should show `Badges enabled=1` if the VTE patch is present.

**Comment by gnunn1** [comment]
@toplinuxsir Does that answer your question, can this be closed?

**Comment by toplinuxsir** [comment]
How to compile with badges in debian 9.0 ? Is there any tutorial ? 
Thanks !

**Comment by gnunn1** [comment]
All I have is what I wrote here:

https://github.com/gnunn1/terminix/tree/master/experimental/vte
