### ISSUE TITLE
Don't always show the searchentry on shortcuts settings

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#756]
I think it's better to hide the search entry, and show it only when the user uses CTRL +F or add a Gtk.ToggleButton to the headerbar as it's done on the new design of Gnome settings :)

**Comment by gnunn1** [comment]
I don't think the headerbar is going to work since this is the only page to support search, it would just be weird to have a disabled search button except for this one page. I'm also not a fan of making it shortcut driven as it renders it un-discoverable. Any other ideas?

**Comment by dsboger** [comment]
Maybe you could hide the search button on different pages, instead of disabling it.

**Comment by gnunn1** [comment]
@dsboger That's a good idea, thanks.
