### ISSUE TITLE
Font line spacing / line height

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#757]
Apologies for asking probably a dumb question. I realise that terminix uses vte widget for rendering terminal text. Does VTE expose any controls over font line spacing or character spacing? Are there any other options for configuring fonts per application?

**Comment by f2404** [comment]
No, everything you can do with vte is choose a font and allow/disable bold chars, that's it.

**Comment by gnunn1** [comment]
@f2404 Pretty much covered it, however note that the fonts are configured on a per-profile basis. You could have multiple profiles with different fonts configured in each and switch between them as desired.

**Comment by egmontkob** [comment]
This has just been implemented in VTE (forthcoming 0.52), using the new API method `vte_terminal_set_cell_height_scale()`.
