### ISSUE TITLE
Change ${title} in trigger

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#758]
I am experimenting with triggers, and I wonder if it would be possible to just change the ${title} variable with a trigger action. I know I can set the entire title string with the corresponding action. But I actually would like to only set the `${title}` variable, so I can leave it as is in most cases, but have some triggers that explicitly overwrite it.

Not sure how this `${title}` works, this comes from VTE, right? Would it be possible to overrule it from within Terminix?

**Comment by gnunn1** [comment]
No it is not and unfortunately I don't have any plans to support this. I feel this would be making things too complicated, particularly if I had to support it across all variables for consistency. I'm not seeing an issue with just using the same title as the default and making the change.
