### ISSUE TITLE
[Bookmarks] Use light icon on dark theme

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#764]
I Use the GTK Arc theme, and the dark bookmark icons look strange there, light icons would fit better.

![bildschirmfoto vom 2017-02-14 17-35-48](https://cloud.githubusercontent.com/assets/29852/22938437/0eb22c60-f2dc-11e6-989b-ea4cf4ed6f7a.png)

**Comment by bil-elmoussaoui** [comment]
It's due to this https://github.com/gnunn1/terminix/blob/445183dbb39849cd9f40d86d1981e284f531c26a/source/gx/terminix/bookmark/manager.d#L612

**Comment by phw** [comment]
Is it possible to explicitly set the color of the symbolic icons?

**Comment by gnunn1** [comment]
@phw the symbolic icons should adjust their color automatically, I'm probably doing something wrong. I'll have a look into it.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 As far as my knowledge on Gtk, Pixbuf is just the current image even if it's with a -symbolic suffix. The code i pointed should return an array of Gtk.Image instead of Pixbuf which will fix this issue :)

**Comment by gnunn1** [comment]
@bil-elmoussaoui Thanks for the tip, I'll have a look.

**Comment by bil-elmoussaoui** [comment]
@gnunn1 i took a closer look, and it seems that you can load symbolic icons as Pixbuf using http://api.gtkd.org/src/gtk/IconInfo.html loadSymbolicForContext. I tried to implement this, the context part wasn't hard, i just didn't figure out how to use the out bool wasSymbolic
Hope this will help!

**Comment by gnunn1** [comment]
You just need to declare a bool first and pass it, i.e.

```
bool wasSymbolic;
loadSymbolic(fg, success, warning, error, wasSymbolic);
```
Of course you need to get the theme colors for fg, success, warning and error. That can be done with StyleContext.lookupColor.
