### ISSUE TITLE
[Bookmarks] Path bookmark forgetting path

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#765]
If I add a new bookmark for a path, select a directory and save it, the path is actually empty when editing the bookmark again. Also when using the bookmark this just results in an empty `cd ` command without path being entered. Furthermore when I edit it and select a path again, the OK button stays disabled.

See the following animation

![peek 2017-02-14 17-39](https://cloud.githubusercontent.com/assets/29852/22938706/da199c12-f2dc-11e6-8037-1f70bc1962a6.gif)

**Comment by gnunn1** [comment]
Thanks for testing this, I'll have a look at it but probably not until the weekend as I have a hard deadline for Friday for something for work.

**Comment by phw** [comment]
No problem, just testing. Are you ok with me adding separate issues for separate things I find, or are you more happy with a "bookmarks bugs and improvements" issue?

**Comment by gnunn1** [comment]
I'm OK with separate issues, this way I can tie commits to issues. I really appreciate you spending some time testing this out as I was a bit worried about pushing out the next release with no one trying this functionality besides myself.
