### ISSUE TITLE
Cannot load a session json file when passing --session parameter inside a custom .desktop file

### ISSUE THREAD

**Issue by cfviotti** [gnunn1/terminix#768]
I'm on Ubuntu Gnome 16.10 and having issues while creating my own custom terminix desktop file for my own session layout.
If I run terminix directly in a command line using --session path/to/session/file.json it works just fine. But using the same command in the "Exec" field of a custom .desktop file it just loads the default session. Note that this wasn't an issue on 16.04, but not really sure if there is any correlation. Modifying the original com.gexperts.Terminix.desktop file also won't work. 
Any tips on why this may be happening?

**Comment by cfviotti** [comment]
Ok, just realized I can't use the tilde expansion (~) to look for my /home/user folder inside a .desktop file. You need to explicitly set the whole path.

**Comment by gnunn1** [comment]
Thanks for the update, glad you figured it out.
