### ISSUE TITLE
Escaping --command parameter

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#770]
In Terminix 1.4.2 the following works:

    terminix -e 'sh -c "ls; read"'

It will open a Terminix terminal and execute the command inside the shell context.

In current git master trying to open this nothing happens. Just calling `terminix -e sh` however still works.

**Comment by phw** [comment]
Just found out that swapping single and double quotes works:

    terminix -e "sh -c 'ls; read'"

In would also expect this to work, but it fails:

    terminix -e "sh -c \"ls; read\""

In terminix 1.4.2 all three variations work.

**Comment by f2404** [comment]
Probably broken by this commit: https://github.com/gnunn1/terminix/commit/223eb13c3a283a40cfc61423e9a0f4b3180007ef

**Comment by phw** [comment]
Probably, yes. And that gives us two more variations that should actually work now, but don't:

    terminix -e sh -c "ls; read"
    terminix -e sh -c 'ls; read'

**Comment by gnunn1** [comment]
That commit was to fix #723, I think I need to revisit this whole topic but look at it holistically. Up to now I've been dealing with the issues around this too piecemeal.

**Comment by gnunn1** [comment]
OK hopefully this commit does the trick. Essentially I have to check for two situations and deal with them a bit differently:

a. User has already quoted everything after ```-e```, in which case I can just pass it on as a single argument
b. User has not quoted or selectively quoted values after ```-e```, in which case I have to assemble it as a single argument

I've tested this against all of @phw examples plus the one in #723 and it seems to work fine. Have a look and let me know if you notice any issues.
