### ISSUE TITLE
1.4.9 beta coredump

### ISSUE THREAD

**Issue by netroby** [gnunn1/terminix#775]
```
huzhifeng@nac ~ $ terminix 

(terminix:18363): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Settings' does not contain a key named 'window-style'
[1]    18363 trace trap (core dumped)  terminix



```

[core.zip](https://github.com/gnunn1/terminix/files/778646/core.zip)

**Comment by gnunn1** [comment]
How are you installing the archive, did you just unzip it? If so, you need to compile the schema:

```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by netroby** [comment]
oh. i will have a try.

**Comment by netroby** [comment]
seems not working. 
```
huzhifeng@nac ~/soft/usr $ sudo glib-compile-schemas /usr/share/glib-2.0/schemas 
No such key 'Gtk/IMModule' in schema 'org.gnome.settings-daemon.plugins.xsettings' as specified in override file '/usr/share/glib-2.0/schemas/50_sogoupinyin.gschema.override'; ignoring override for this key.

```

I am using ubuntu mate 16.04. 
installed terminix from ppa , working well .but the 1.4.9 beta not working

**Comment by netroby** [comment]
Compiled the schema. and it works.

**Comment by netroby** [comment]
another isssue. I am using ubuntu 16.04 mate desktop. the terminix window can not resize. even i put mouse pointer at the border of the terminix window. 

Resize windows will be a very common action in daily using. so if possible. take a look ?

**Comment by gnunn1** [comment]
Is this the normal Terminix window or a quake window? I don't have any issues with a normal window on Gnome.

**Comment by gnunn1** [comment]
Also, try going into Terminix Preferences, Appearances and set the window style to "Disable CSD" to see if it helps.

**Comment by netroby** [comment]
Magic, after disable csd, it works.....
Excellent works.

**Comment by netroby** [comment]
Well . but i can not open perference now.... the top right button seems not list preference menu.

**Comment by gnunn1** [comment]
I'd suggest opening an issue with the Mate folks about the best way to get Terminix working in their DE. I don't use Mate so it's difficult for me to provide advice. If you post a URL to the issue here I will keep an eye on it.

**Comment by netroby** [comment]
thanks. i guess they will don't care about it .
