### ISSUE TITLE
Blurry window

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#777]
Hi, `iTerm2` (for mac) have a nice feature to make the window blur. Is is possible to add that on terminix?

Look the `Window Appearance` section

<img width="1038" alt="profiles_window" src="https://cloud.githubusercontent.com/assets/1277920/23019914/a7185ab0-f42b-11e6-9058-1aa921d8e069.png">

It should look like this:

![twowindowswithblur](https://cloud.githubusercontent.com/assets/1277920/23020013/217e0e44-f42c-11e6-87b2-d7220125d8d8.png)

**Comment by gnunn1** [comment]
Thanks for the suggestion, but I think this is just a little too much on the feature bloat side of the house for my taste. Additionally it wouldn't be very widely used anyway since it would require my patched VTE to make it happen.

**Comment by leoheck** [comment]
Oh I see, thanks anyway.
