### ISSUE TITLE
Ugly white 1px {top,left} borders under Ubuntu Ambiance and dark Color Scheme

### ISSUE THREAD

**Issue by ronjouch** [gnunn1/terminix#778]
Terminix shows two weird borders under Ubuntu, which are visible when using a dark profile Color Scheme (e.g. Monokai Dark):

![terminix-ubuntu-topleftwhiteborders](https://cloud.githubusercontent.com/assets/522085/23035484/45b663d0-f44d-11e6-9d82-ecb410412b8d.png)

Problem not reproducible on my Arch/GNOME Shell/Adwaita machine, maybe it's Ubuntu/Unity/Ambiance specific? Feel free to ask for more debug info, and sorry if this is a dupe, I did a few GitHub issue searches but didn't find anything.

## Configuration

* Ubuntu 16.04.2 LTS x64, up-to-date.
  * Ubuntu theme: unmodified default `Ambiance`
* Terminix source: Webupd8 PPA
* Terminix Versions
  * Terminix version: 1.4.2
  * VTE version: 0.42
  * GTK Version: 3.18.9
* Terminix Special Features
  * Notifications enabled=0
  * Triggers enabled=0
  * Badges enabled=0

**Comment by gnunn1** [comment]
I'm not seeing the issue on the version in Master, can you try with the beta and see if you still have the issue.

![screenshot from 2017-02-16 18-27-24](https://cloud.githubusercontent.com/assets/9358238/23046129/ca5f650a-f475-11e6-8d23-4e681c31f35e.png)

**Comment by gnunn1** [comment]
Also, confirm you don't have any custom CSS set in ```~/.config/gtk-3.0/gtk.css```

**Comment by ronjouch** [comment]
@gnunn1 thanks for the fast feedback!

> Confirm you don't have any custom CSS set in `~/.config/gtk-3.0/gtk.css`

I don't have a `~/.config/gtk-3.0/gtk.css`

> Can you try with the beta and see if you still have the issue.

Sure, one little question: I suppose you refer to the (currently 1.4.9) beta listed in [the Releases page](https://github.com/gnunn1/terminix/releases), which contains a zip indeed containing a binary release. Is there a way for me to *not* extract it to `/`? (which will pollute the tree and conflict with current/future deb installs, unless manual file-by-file cleanup is done). Because it looks like terminix looks for its resources at hardcoded places rather than relative to its bin location (which I would like to be for example `/opt/terminix-beta`):

```
~ /opt/terminix-beta/bin/terminix
2017-02-17T10:08:02.429:resource.d:findResource:53 Resource terminix/resources/terminix.gresource could not be found
(terminix:5328): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Keybindings' is not installed
[1]    5328 trace trap  /opt/terminix-beta/bin/terminix
```

→ Any trick to make the app looks for its resources at the right prefix?

**Comment by gnunn1** [comment]
You might be able to get it going in a local path using the environment variables here: 

https://developer.gnome.org/gtk3/stable/gtk-running.html

I haven't tried it myself though.

**Comment by ronjouch** [comment]
By some coincidence, I had to reinstall this machine today, and the problem is absent after a fresh Ubuntu 16.04.2 install. Closing, sorry for the noise 🙇  .
