### ISSUE TITLE
How to enable the command prompt style ?

### ISSUE THREAD

**Issue by toplinuxsir** [gnunn1/terminix#780]
How to enable the command prompt style ? like below picture .
<img width="226" alt="cmd_propmt" src="https://cloud.githubusercontent.com/assets/1111353/23100752/b83e753c-f6c3-11e6-9bf4-90be2c43b7e8.PNG">

**Comment by alex285** [comment]
@toplinuxsir this is a Linux shell theme and unrelated to Terminix. I reckon to check on PowerLevel9k for ZSH
https://github.com/bhilburn/powerlevel9k

**Comment by gnunn1** [comment]
I'm using powerline on bash for the prompt.

**Comment by toplinuxsir** [comment]
Thanks , I got it . It's very cool !

Gerald Nunn <notifications@github.com>于2017年2月19日周日 下午6:20写道：

I'm using powerline on bash for the prompt.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gnunn1/terminix/issues/780#issuecomment-280909406>, or mute
the thread
