### ISSUE TITLE
crash after clicking on preferences

### ISSUE THREAD

**Issue by BBasile** [gnunn1/terminix#784]
(or maybe settings in english, but as I cannot change the language I cant say)
- OpenSuse, KDE 4
- x86_64
- terminix master installed from script install.sh

> Gtk:ERROR:gtkstylecontext.c:798:style_values_lookup: assertion failed: (priv->widget != NULL || priv->widget_path != NULL)

**Comment by bil-elmoussaoui** [comment]
@BBasile  Can you rebuild the application using `dub build --build=debug --config=trace` and run the application again? This will give a better output about the issue :)

**Comment by gnunn1** [comment]
If you could do what @bil-elmoussaoui suggested that would be great. Note that I don't typically support KDE in terms of making terminix work perfect on it but I'd like to fix any crash issues that exist.

**Comment by BBasile** [comment]
trace file: https://gist.github.com/BBasile/e7c4fde93693caa8b22b2b15f2637e9c

**Comment by BBasile** [comment]
KDE _usually_ runs GTK apps fine. You shouldn't have to do anything to support it.

**Comment by gnunn1** [comment]
@BBasile Oh I agree, unfortunately there tends to be subtle differences between desktop environments that cause issues though typically not crash ones. Thanks for the trace, I'm investigating.

**Comment by ivoarch** [comment]
I have the same issue , and after clicking on preferences terminix crash :( 

CentOS - 7.3 - Gnome 3.14
Terminix 1.5.0 from Heikoada Fedora Corp repo .

**Comment by gnunn1** [comment]
So it looks like a GTK 3.14 issue, I've checked in a fix for it. Not sure how long I'm going to keep supporting this version considering how ancient it is getting and the hassle of dealing with it.
