### ISSUE TITLE
Profile setting for quake mode

### ISSUE THREAD

**Issue by phocean** [gnunn1/terminix#785]
Hello,

It would be nice if it were possible to select a specific default profile for the quake mode.

For instance, I usually use a solid and white background, but only for quake mode, I feel it would make sense to have transparency and a dark background.

I apologize if it has already been suggested, but I could not find an issue for that.

And I want to thank you so much for the amazing terminal you brought to the community. Huge, beautiful work.

**Comment by gnunn1** [comment]
Just pass the profile you want with the --quake switch, i.e.

```
terminix --quake -p MyProfile
```
