### ISSUE TITLE
Unable to build terminix v.1.5.0 on Centos 7 with the latest appdata file ?

### ISSUE THREAD

**Issue by ivoarch** [gnunn1/terminix#786]
The appdata from the latest terminix gives problems to build the package  with rpmbuild/mock on el7-CentOS - here is the error [build.log](https://gist.github.com/ivoarch/c2423d42bbfd53c23cda77e231a58971) . I removed the validation of appdata from the .spec file [patch](https://gist.github.com/ivoarch/c5923a656e8445d5cf89b54a0e5f502b) then the mock build sucess  .

Also here is the log from the [heikoada fedora corp epel-7 repo](https://copr-be.cloud.fedoraproject.org/results/heikoada/terminix/epel-7-x86_64/00514818-terminix/build.log.gz) .

Any idea that has changed in the new file, and now gives this error ??
Thanks!

**Comment by phw** [comment]
The error is during validation of the appdata file. There has been some additions to that file at https://github.com/gnunn1/terminix/commit/44a74787e901c0e4188b994e822a8eb8fe6945cb

According to the logs it does not like one of the new URLs added, but doesn't tell which (one ore more of help, faq, bugtracker or translate should be at fault). If I validate locally everything is fine:

    $ appstream-util validate-relax --nonet com.gexperts.Terminix.appdata.xml
    com.gexperts.Terminix.appdata.xml: OK

I have however likely a newer version of appstream-utils installed. Instead of patching out the entire validation you could also try to just patch out the newly added URLs  from the `data/appdata/com.gexperts.Terminix.appdata.xml.in` file

**Comment by gnunn1** [comment]
I went and tried commenting them out one by one on CentOS 7, it's the translate URL that is causing the issue. I'm wondering if that's a newer type?

**Comment by gnunn1** [comment]
I've commented out the ```translate``` URL for now until I can figure out if there is a better way to handle this.

**Comment by ivoarch** [comment]
It may be that the problem comes from the old version of libappstream-glib package .

```
$ appstream-util validate-relax --nonet com.gexperts.Terminix.appdata.xml
com.gexperts.Terminix.appdata.xml: FAILED:
• tag-invalid           : <url> type invalid [unknown]
Validation of files failed
```
Versions
CentOS 7.3
libappstream-glib - 0.3.6-1.el7.x86_64
Fedora 25
libappstream-glib - 0.6.8-2.fc25
***
Removing translate url is OK .

**Comment by phw** [comment]
This was added in appstream-glib 0.6.1 released last October, see https://github.com/hughsie/appstream-glib/blob/master/NEWS#L138

I think there is no good way to handle this, as some distributions will always validate against older versions. IMHO the right way to handle this to patch the unsupported parts out when packaging for such distributions.

**Comment by gnunn1** [comment]
@phw I tend to agree with you on this in terms of packagers removing the offending line before packaging. That's probably what I'll end up recommending, just want to close the loop to make sure there's not a better option.

**Comment by ivoarch** [comment]
You can specify it in the terminix dependencies section .

Minimum version (appstream-glib >=  0.6.1) .

Also packagers can fix it easily by one line with sed or patch that remove the problem line from appdata.xml.

**Comment by gnunn1** [comment]
I've reverted the commenting out of that URL as I don't see a way to avoid this on my side. @ivoarch you will need to open a bug with the package (i.e not here) to correct the issue with appdata by removing the invalid translate url for that version of appdata.
