### ISSUE TITLE
Terminix don't show in nautilus

### ISSUE THREAD

**Issue by PrzemekSkw** [gnunn1/terminix#787]
I upgrade terminix to ver. 1.5.0 in my Fedora 25 and now I doesn't have  option in nautilus to open terminix in folder. Is this a bug or I don't have some deps installed ?

**Comment by alex285** [comment]
it works on Arch. Do you have `python-nautilus` or `python2-nautilus` package installed?

**Comment by PrzemekSkw** [comment]
Hi, thx for fast reply. I have nautilus-python-1.1-10.fc24.x86_64 installed. But after I upgrade terminix and make autoremove command some python packages including that one removed. I install it again but terminix is still invisible in nautilus.

**Comment by gnunn1** [comment]
in a terminal, can you type the following and paste here what the output is:

```
nautilus -q
nautilus
```
This will tell us if nautilus is having an issue with loading the plugin for some reason.

**Comment by PrzemekSkw** [comment]
That's output:
`[przemek@przemek ~]$ nautilus -q

(nautilus:7620): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:7620): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
[przemek@przemek ~]$ nautilus
[przemek@przemek ~]$ `

**Comment by gnunn1** [comment]
I'm not sure what the issue, I'd guess you removed something that is required but I'm not familiar enough with Fedora to tell you what it is. I'd suggest asking on a Fedora forum.

**Comment by bil-elmoussaoui** [comment]
@PrzemekSkw It's an issue with the latest release of Nautilus, you will have to kill it again using `nautilus -q`

**Comment by PrzemekSkw** [comment]
Thanks for Your help. I install nautilus terminal and it works fine.
