### ISSUE TITLE
Session Title doesn't change

### ISSUE THREAD

**Issue by GeertGeurts** [gnunn1/terminix#789]
Hello, 
Somehow the session title doesn't change anymore...
When I open teminix the top toolbar shows Terminix: Default. I can change this when I mouseclick it.
This used to be the place where the session title was shown and would correspond to the the selected sessiontitle seen when pressing F12. Somehow this mouseclick editable feature, which I like a lot by the way, disabled this functioning.
Is this a confiuration issue?
If so, where to change?

Thanks!
Best regards,
Geert

**Comment by gnunn1** [comment]
What do you have set for the Default Session Name and Application Title in preferences, see screenshot below for what I use:

![screenshot from 2017-02-21 07-51-01](https://cloud.githubusercontent.com/assets/9358238/23165539/9dfb362c-f80a-11e6-8102-15e9cea1eb41.png)

**Comment by GeertGeurts** [comment]
Hello Gerard Nunn,
Thanks for your quick reply!
I do not have the Window style option...
Instead for me there is a checkbox for Enable transparency.

Best regards,
Geert

**Comment by gnunn1** [comment]
That's not important, I need to see what you have for ```Default session name``` and ```Application title```. Please post a screenshot like I did.

**Comment by GeertGeurts** [comment]
OK sorry...
Please see the attached screenshot!

Regards,
Geert

**Comment by gnunn1** [comment]
There's no screenshot, try editing the bug directly in github and attaching the screenshot there.

**Comment by GeertGeurts** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5459002/23181791/a2a23d6c-f876-11e6-890b-bc23a25c8a3a.png)

**Comment by gnunn1** [comment]
You can rename a session bu clicking the hamburger menu in the headerbar and selecting ```Name...```. When you click the title and edit it, that is changing the Application title not the Session name. 

Also, in the screenshot above you can use something other then ```Default``` if you want, for example if you use ```${title}``` it will use the title from the currently focused terminal in the session.

Does that answer the question?

**Comment by GeertGeurts** [comment]
Is it possible to configure terminix to show the session title there where currently the application title is?

**Comment by gnunn1** [comment]
It's already configured that way, that's what the ```${appName} : ${sessionName}``` is doing in the Application title setting. If you only want the session name showing just delete the app name variable.

**Comment by tonylambiris** [comment]
Thanks for the quick replies @gnunn1, would it be possible to have a checkbox that will inherit the Application Title from the current profile's Terminal title, or does that behavior already exist in a place I'm overlooking?

Thanks again, starting using the terminal today on Arch and loving it!

**Comment by gnunn1** [comment]
Yes it's already there, just set the Application title to ${title}

You can see a list of all variables here:

https://gnunn1.github.io/terminix-web/manual/title/

**Comment by tonylambiris** [comment]
@gnunn1 I get the following when setting the Application title to ${title}:

![screenshot from 2017-02-21 16-23-13](https://cloud.githubusercontent.com/assets/14058972/23185674/3763d3cc-f852-11e6-9c6c-6782e4730665.png)

FWIW I'm loading the recommended vte.sh:
```
16:24:45 c1-linuxdev ~ $ tail -3 ~/.bashrc_local 
[[ $TERMINIX_ID || $VTE_VERSION ]] && source /etc/profile.d/vte.sh

PROMPT_COMMAND=bash_prompt_cmd
```

**Comment by gnunn1** [comment]
Are you setting it in preferences or by clicking the title and editing it directly? If editing it directly try setting in preferences as ```Application title```. It should work the same though for either.

Worse case, use the settings in my previous screenshot.

**Comment by phw** [comment]
I can reproduce with ${title} and other terminal names in the application title.

What works for me is:
- Set the session title to `${title}`, it will reflect the title of the current active terminal
- Set the application title to `${sessionName}`, it will correctly show the session name (which is the terminal name)

But directly setting ${title} in the application name gets printed as is. Doesn't matter if I set it in the options or the headerbar directly.

To be honest I find the many titles most confusing :)

**Comment by gnunn1** [comment]
OK thanks @phw, that's a bug. I can understand the confusion, if you have any suggestions to simplify it or make it easier I'm happy to take them.

**Comment by phw** [comment]
two things I noticed:

- The variable helpers are great, but they should be available everywhere one can edit titles
- If the application title uses the default value and you edit it in the title bar, it is empty. But for me as a user it would be easier to see the default string there so I can tweak it.

Personally I would even question whether we need separate session and application title, but I can see why some people want to have that flexibility.

**Comment by gnunn1** [comment]
@phw The only place the variable isn't present is the Entry that appears when you click the title. I didn't do it there because it's a wider control and it causes the minimum size of the window to increase. I should probably revisit this though.

**Comment by tonylambiris** [comment]
@gnunn1 Editing the title through preferences:

![screenshot from 2017-02-21 16-38-30](https://cloud.githubusercontent.com/assets/14058972/23186247/6ce80af2-f854-11e6-9b0d-3aaceca0fe73.png)

Apparently my settings were already configured to mostly match yours. Just to be thorough, I built this today from the AUR without changing anything in the PKGBUILD itself:
```
16:40:31 c1-linuxdev ~ $ pacman -Qi terminix 
Name            : terminix
Version         : 1.5.0-1
```

**Comment by phw** [comment]
> The only place the variable isn't present is the Entry that appears when you click the title.

I also meant the "Name..." dialog in the session menu on the upper right and terminal layout options dialog.

**Comment by gnunn1** [comment]
Thanks, I'll take care of those as well.

**Comment by gnunn1** [comment]
Mostly fixed except for the session name input, I'll have a look at that tomorrow.

**Comment by GeertGeurts** [comment]
really??!
Brilliant! nice one!
I go check it out immediately!

**Comment by gnunn1** [comment]
So this should be all fixed up now, however note the title editor will only appear for the Session name dialog if you are using Wayland as there is not enough room for the popover to appear without getting clipped in X11.

**Comment by gnunn1** [comment]
Oh and I'd also appreciate it if someone could test the title editor when you click the window title. Getting it disappear when it loses focus but not disappear when interacting with the variable popover was a bit tricky.

**Comment by GeertGeurts** [comment]
Sorry for the late reply gnunn1, I got lost in dependency hell although the "dub" tool seems to be there to overcome dependency hell, not having it is... well.... HELL ;D
Anyways, I got things working! Thanks for the improvement of terminix!!
It's brilliant!
Thanks!

**Comment by tonylambiris** [comment]
Working for me too, thanks!
