### ISSUE TITLE
In quake mode, hamburger menu gets truncated

### ISSUE THREAD

**Issue by f2404** [gnunn1/terminix#790]
The menu gets truncated by the quake window height:

![quake_menu](https://cloud.githubusercontent.com/assets/14939413/23171960/dde315fa-f85c-11e6-968b-c7d8ab3867d3.png)

**Comment by gnunn1** [comment]
Is the menu longer then the window size, if so that's a known issue with popover menus in X11. The solution would be to make your window larger, otherwise there is nothing I can do about it.

**Comment by phw** [comment]
Dude, you should really check what files you upload to Github. Did not expect my Github issue mails to be NSFW and NSFF (not safe for family) ;)

**Comment by f2404** [comment]
@phw and all, I'm very sorry about that, don't know how it happened :-/
