### ISSUE TITLE
Visualize active pane

### ISSUE THREAD

**Issue by ronjouch** [gnunn1/terminix#791]
Using Terminix, it's not immediately clear which pane is active. From what I see here, the only difference I see between active/inactive panes is cursor blinking, which is subtle:

![terminix-no-visual-clue-active-pane](https://cloud.githubusercontent.com/assets/522085/23185257/d17b95be-f850-11e6-80d6-a9b17e9bdb54.gif)

It would be great to have a feature helping visualize this in an obvious/immediate way. I am using Terminix v1.4.9-2.0.0 (VTE: 0.42, GTK: 3.18.9, Notifications: 0, Triggers: 0, Badges: 0) from PPA package 1.5.0-1-webupd8-xenial3, under Ubuntu 16.04.2 / Unity / Ambiance.

---

* Tmux is more helpful, by coloring the borders of the active pane, equating "left" to "top" and "right" to "bottom" in the case of left/right and top/bottom splits. Obligatory animated GIF:  
![tmux-border-coloring-active-pane](https://cloud.githubusercontent.com/assets/522085/23184825/43c8c6e8-f84f-11e6-8133-d8a36ee613a6.gif)

* ... but it's only one solution, other ones (dimming? overlaying a clue?) might work too.

**Comment by egmontkob** [comment]
FYI: See profile preference Color -> Unfocused dim. It was added #263.

**Comment by ronjouch** [comment]
@egmontkob thanks! Missed it; I didn't search at this place. Closing.
