### ISSUE TITLE
Where is configuration saved?

### ISSUE THREAD

**Issue by pkkid** [gnunn1/terminix#792]
I often symlink my configuration files to Dropbox.  However,  I don't see the configuration file in any of the usual suspected places.

**Comment by gnunn1** [comment]
It's saved in dconf with the exception of the bookmarks which are saved in ~/.config/terminix

**Comment by pkkid** [comment]
Ahh, thanks. I guess it'll be hard to share config across computers. :-/

**Comment by gnunn1** [comment]
https://github.com/gnunn1/terminix/issues/571
