### ISSUE TITLE
Add graphical way to access preferences when CSD is disabled

### ISSUE THREAD

**Issue by ragnese** [gnunn1/terminix#793]
Thank you for working on Terminix- it's absolutely fantastic!

One thing that would be nice is to be able to access the preferences via the right-click menu, so I don't have to launch terminix --preferences when CSD is disabled.

**Comment by gnunn1** [comment]
I need to think about this a bit and how best to make it fit with the different window style options. Right now in Quake mode it adds Preferences to the hamburger menu.

**Comment by gnunn1** [comment]
@ragnese what DE are you using, as far as I can tell the preferences is always available in the AppMenu in both Gnome Shell and Unity with CSD Disabled?

**Comment by ragnese** [comment]
It doesn't show up with window managers that don't have appmenu type buttons in titlebars. In my case, it was Openbox.

**Comment by gnunn1** [comment]
I only actively support Gnome Shell and Unity, someone who is a developer and using Openbox would have to step up and make this happen.

**Comment by ragnese** [comment]
Ah, okay. That's fair. Sorry for the spam, then.
