### ISSUE TITLE
White border on dark theme

### ISSUE THREAD

**Issue by lapega** [gnunn1/terminix#799]
I just upgrade to 1.4.9-2.0.0, and now I got a white border below the menu:
![captura de pantalla de 2017-02-23 11-59-02](https://cloud.githubusercontent.com/assets/572502/23264258/81cac97a-f9bf-11e6-8dcb-e8d42b232502.png)

I'm using ubuntu 16.04.02, with Numix theme.

Thanks!!!

**Comment by bil-elmoussaoui** [comment]
This issue was reported on Numix theme repository too. Not sure if it's an upstream issue or it requires a patch on terminix side

**Comment by gnunn1** [comment]
I'm not seeing the issue here with Numix, I'll wait to see what the Numix folks have to say.

![screenshot from 2017-02-23 10-42-08](https://cloud.githubusercontent.com/assets/9358238/23266138/d74708e2-f9b4-11e6-8802-ad68425c8501.png)

**Comment by gnunn1** [comment]
I also tried it with CSD disabled and toolbar hidden which is what I think the OP has configured, I'm still not able to reproduce it.

**Comment by khurshid-alam** [comment]
I am not able to reproduce either. I will try on Gtk-3.22.

**Comment by leoheck** [comment]
@gnunn1 see https://github.com/numixproject/numix-gtk-theme/issues/655#issue-208975154 I have this problem with Ubuntu 16.04. Terminix+Numix is fine on Ubuntu 16.10.

**Comment by gnunn1** [comment]
I think the issue is because of this CSS in terminix:

```
.terminal-titlebar {
    border-bottom: 1px solid @borders;
}
```
Either Numix does not declare a ```borders``` color or it is declaring a white one. You can fix it my overriding the style in ```~/.config/gtk-3.0/gtk.css``` as follows:

```
.terminal-titlebar {
        border-color: black;
}
```
Change black to whatever color works best for you.
