### ISSUE TITLE
Fullscreen support

### ISSUE THREAD

**Issue by noirbizarre** [gnunn1/terminix#80]
It would be awesome if Terminix could go fullscreen on a keyboard shortcut !

**Comment by bil-elmoussaoui** [comment]
Yeah something like F11 by default

**Comment by gnunn1** [comment]
Just wondering how useful is this, from my point of view the only thing in Gnome that fullscreen buys you over maximizing is the small amount of vertical space taken up by the gnome shell top bar?

**Comment by noirbizarre** [comment]
It's like a "be focused" mode for me: no distractions.
I use often fullscreen for comfort and focusing when coding.
You're right, it's also a way to gain space on laptop, but it's not the main thing for me.
A lot of application can do it (from gnome or not): Gnome terminal, Atom, Chrome, Firefox, Gnome Web, Terminator...

It's not indispensable but very comfortable.

**Comment by gnunn1** [comment]
OK thanks, i was just wondering where to prioritize this, it doesn't sound difficult and thus should be pretty easy to add for the next version.

**Comment by noirbizarre** [comment]
Great! Thanks to you !!!

**Comment by noirbizarre** [comment]
You're the best ! Thanks !
