### ISSUE TITLE
Preview bar (like sublime text)

### ISSUE THREAD

**Issue by stuaxo** [gnunn1/terminix#802]
This idea isn't fully baked, as I'm not sure how it would fit in with the current UI.

It would be great if there was a preview bar like the one in sublime text.

I've been scrolling through mega syslog files and this would have made it much easier to find where I was.

**Comment by gnunn1** [comment]
It's an interesting idea but I don't see this being implemented at this time. 

I tend to think text editors/viewers should be the ones implementing this sort of functionality and not terminal emulators. Additionally there would be a number of changes from an implementation point of view as well, for example what should the minimap do when running vi, emacs, or other ncurses style apps that use the alternate screen mode.
