### ISSUE TITLE
Menu gets clipped when window too close to edge

### ISSUE THREAD

**Issue by tonylambiris** [gnunn1/terminix#805]
Trying to open a URL from Terminix clips off the 'Open Link' part of the context menu when it's too close to the top edge of the screen.

![screenshot mon feb 27 2017 16 45 26 gmt-0500 est 1561x1281](https://cloud.githubusercontent.com/assets/14058972/23381487/a71f71bc-fd0c-11e6-9f27-a8418851400a.png)

Thanks!

**Comment by gnunn1** [comment]
Lol, I think you need to buy a bigger screen 🤔

Seriously though, when you don't show the terminal title bar those menu items move to the context menu. The easy workaround would be too enable the terminal titles to make the context menu smaller.

What resolution is your screen?

**Comment by tonylambiris** [comment]
I have a Dell XPS 15 w/ a HiDPI display using Wayland.

![screenshot from 2017-02-27 17-23-48](https://cloud.githubusercontent.com/assets/14058972/23382812/a3e631c0-fd11-11e6-86ff-516b6494912d.png)

**Comment by gnunn1** [comment]
Thanks, I'll have a look

**Comment by tonylambiris** [comment]
Appreciate it! Small inconvenience just figured I'd ping you on it regardless.

**Comment by gnunn1** [comment]
I've opened a bug with GTK for this one:

https://bugzilla.gnome.org/show_bug.cgi?id=779341

**Comment by tonylambiris** [comment]
I need more thumbs! :) Thanks for digging into this, quite an obscure bug.

**Comment by gnunn1** [comment]
Closing since this appears to be an upstream issue, will re-open if gnome devs disagree with me.
