### ISSUE TITLE
Font Ligatures

### ISSUE THREAD

**Issue by marcosfede** [gnunn1/terminix#807]
Hello, Is there a way to use fonts that have ligatures, like [Fira Code](https://github.com/tonsky/FiraCode) in terminix? Right now It doesn't display certain characters like =, > and < .
Thanks!

**Comment by bil-elmoussaoui** [comment]
Not possible. It's an upstream issue (VTE widget) the issue is already open since 2011 if I still remember, but nothing was done to fix this...
