### ISSUE TITLE
Send horizontal mouse scroll event to vim (or other processes)

### ISSUE THREAD

**Issue by pmk1c** [gnunn1/terminix#808]
When using Vim in Terminix, horizontal mouse scrolling doesn't work. It's the same when using Gnome Terminal. I don't know what the problem is, and if this is a bug / feature, you could fix / implement, but I would love that.

It's not a problem with Vim itself, since using Gvim i.e. the mouse scroll left / right events get passed.

**Comment by pmk1c** [comment]
I just found this: https://bugzilla.gnome.org/show_bug.cgi?id=755183
Which reads as if this is a VTE problem.

**Comment by gnunn1** [comment]
That's correct, it's an issue with upstream VTE so not much I can do about it unfortunately.

**Comment by algj** [comment]
Seems promising:
https://gitlab.gnome.org/GNOME/vte/-/commit/3aa672788f8e5fc3a767b7c69872dcc39f637811
