### ISSUE TITLE
error while loading shared libraries: libphobos2-ldc.so ... No such file or directory

### ISSUE THREAD

**Issue by johnnydvc** [gnunn1/terminix#810]
Hi.
I've just updated terminix and I get the following error message:
`terminix: error while loading shared libraries: libphobos2-ldc.so.71: cannot open shared object file: No such file or directory`
Any ideas?
Thanks

terminix 1.5.2-1

OS: Manjaro 16.10 Fringilla
Kernel: x86_64 Linux 4.9.13-1-MANJARO
Shell: zsh 5.3.1
DE: GNOME 
WM: GNOME Shell
CPU: Intel Core i5-3337U @ 4x 1.7GHz [41.0°C]
GPU: Mesa DRI Intel(R) Ivybridge Mobile 
RAM: 1532MiB / 5856MiB

**Comment by uncarvedblock** [comment]
Confirming, same error on Arch Linux.

**Comment by Vaesper** [comment]
Do you have the ldc package installed? Might be a new dependency.

**Comment by uncarvedblock** [comment]
Appears so, AUR PKGBUILD was just updated. solved the issue for me

**Comment by gnunn1** [comment]
Looks like this is sorted out now thanks to the packager @dsboger.

**Comment by SolarLiner** [comment]
Happens here on Manjaro GNOME, using tilix. Switching to `tilix-bin` package solved the issue.

**Comment by rancidfrog** [comment]
Someone already mentioned: https://github.com/gnunn1/tilix/issues/1197#issuecomment-346307112
>  aur/libphobos-devel-beta

**Comment by janxkoci** [comment]
This happened again, with the same library, after today's update on my Manjaro. It seems tilix is AUR-only now, it's gone from the official repos. 😕

**Comment by remyd1** [comment]
Same here, either `aur/tilix` or even with `aur/tilix-git`.

I tried to manually link `/usr/lib/libphobos2-ldc-shared.so.112` to `/usr/lib/libphobos2-ldc-shared.so.111`, then `/usr/lib/libdruntime-ldc-shared.so.112` to `/usr/lib/libdruntime-ldc-shared.so.111`, but now I am stuck to an undefined symbol within the library `/usr/lib/libgtkd-3.so.0`:

```
tilix: symbol lookup error: /usr/lib/libgtkd-3.so.0: undefined symbol: _D6object9Throwable4nextMNgFNaNbNdNiNjNlNfZNgCQBsQBo
```

Best regards

EDIT: solved with [this solution](https://github.com/gnunn1/tilix/issues/2284#issuecomment-4073089436)
