### ISSUE TITLE
Feature Request: scrolling up interrupts "scroll on output"

### ISSUE THREAD

**Issue by simonwiles** [gnunn1/terminix#821]
I'm a recent convert from another tiling terminal emulator, and I'm really missing this feature.  What I would like is the current "scroll on output" behaviour, but for it to be interrupted when I scroll back through the history (and then be resumed when I scroll back to the bottom).  (This is the behaviour of the terminal emulator I've been using for some years.)

Two major use cases: the first is when I have long scrolling output (e.g. `tail -g /var/log/syslog`, or something more voluble), and I want to scroll up to check something that's just scrolled off screen; the current behaviour makes this more-or-less impossible.  The second issue is when using gnu `screen` on remote connections with a `hardstatus` line (I expect other similar configurations would suffer from the same problem).  With the current "scroll on output" behaviour, the window repeatedly jumps back to the bottom when the status line is updated (since this constitutes "output"), and makes scrolling up, again, more-or-less impossible.

It would be great if this behaviour could be added to a future release.  Thanks for reading!

**Comment by gnunn1** [comment]
You can turn this off in Profiles | Scrolling by disabling the option ```Scroll on output```. Does this do what you want?

**Comment by simonwiles** [comment]
erm, yes, that's it... so sorry -- I guess I just saw "scroll on output" and turned it on assuming I knew what it meant... apologies for wasting your time!
