### ISSUE TITLE
Pressing F11 to go Full Screen closes Terminix

### ISSUE THREAD

**Issue by Nikki1993** [gnunn1/terminix#85]
As title suggests. I am running Arch with Gnome Shell 3.18.x, latest 50 Beta of Terminix.

**Comment by edubxb** [comment]
Same problem here, Debian Testing, GNOME 3.18.x

**Comment by gnunn1** [comment]
Thanks, I added this before merging in the sidebar so I probably broke
something in the merge. I'll have a look later today.
