### ISSUE TITLE
Cant run on Fedora

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#9]
Window open for a second and the crashes: 
Thats basically on Rawhide, no Fedora. 

(terminix:7386): Gtk-WARNING **: State 1 for VteTerminal 0x20c47c0 doesn't match state 128 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 1 for VteTerminal 0x20c47c0 doesn't match state 128 set via gtk_style_context_set_state ()

(terminix:7386): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 128 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 128 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 128 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 224 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 160 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 160 set via gtk_style_context_set_state ()

(terminix:7386): Gtk-WARNING **: State 0 for VteTerminal 0x20c47c0 doesn't match state 160 set via gtk_style_context_set_state ()

**Comment by gnunn1** [comment]
Thanks, I'll have a look but it might take a bit as I'll need to install Fedora in a VM to test it. Those messages look strange though, but I see there is a bug report for this already:

https://bugs.webkit.org/show_bug.cgi?id=151520

Are you using GTK 3.19, is this the default version in Rawhide?

**Comment by alex285** [comment]
Yes is on Rawhide and 3.19.6. Rawhide updates according to Gnome unstable releases.

**Comment by gnunn1** [comment]
Can you try it now please, the new release I pushed works on the rawhide image I downloaded. However, I'll be honest with you in my VM it looks a bit crap since the CSS has changed from 3.18. Also, the drag and drop seems flaky, not sure if that's because of the VM or the new GTK version.

**Comment by gnunn1** [comment]
Closing this issue, it runs in Rawhide now even though from a UI point of view it looks pretty bad. I'll add a new issue for the UI.
