### ISSUE TITLE
Can't use custom keyboard shortcuts

### ISSUE THREAD

**Issue by klingtnet** [gnunn1/terminix#94]
The menu shows me the assigned keyboard shortcuts but regardless of which key combination I choose, it won't work. `Ctrl` keys are shown as `<primary>`.
However, the predefined shortcuts are working.

I am using terminix `0.50.1` under gnome `3.18.3` on Arch Linux.

**Comment by gnunn1** [comment]
I can reproduce, looks like an issue with them not updating properly during the current session. If you restart Terminix the shortcuts start working

**Comment by klingtnet** [comment]
I can't confirm this. Restarting `terminix` doesn't help.

**Comment by gnunn1** [comment]
In dconf-editor under /com/gexperts/Terminix/Keybindings are the shortcuts being updated?

**Comment by gnunn1** [comment]
OK I found the problem and it is working fine for me now. The issue I was accidentally creating the settings object twice in Application and the one with the attached the event listener for changes would go out of scope and be GC'ed hence no changes were being received.

**Comment by klingtnet** [comment]
Thank you for the fast response and I'm happy that you could solve the issue so quickly.
Could you create a new release `0.50.2` including this fix?

**Comment by gnunn1** [comment]
Unfortunately I'm heading out on a flight in a few hours so I won't have  a chance to do this until tomorrow night. You can always use the ```terminix-git``` arch package to get the latest version from git.
