### ISSUE TITLE
Start terminix with multiple sessions

### ISSUE THREAD

**Issue by nachevn** [gnunn1/terminix#99]
Hi all,

it is possible to start terminix with a saved json session file? E.g.:
`$terminix -s ${PATH_TO_TERMINIX_SESSION_JSON}`

It would be also great if terminix can save/open more that one opened/created sessions in the same json config something like "profile to start with..."

**Comment by phw** [comment]
It is, and exactly how you suspected it should work ;)

See `terminix --help` for a list of all command line options.

**Comment by nachevn** [comment]
I have try it but it doesn't work for me. Here my json: [terminix.json.txt](https://github.com/gnunn1/terminix/files/140613/terminix.json.txt)

And ...
`terminix -a session-load # this opens a file chooser`
or
`terminix -s ${PATH_TO_TERMINIX_SESSION_JSON} # loads only the last child from the json`

What am I doing wrong?

**Comment by phw** [comment]
The json file is broken, how did you generate it? There are multiple `child` entries at the top level, that doesn't make sense and is not even valid json.

At the top level there is only one `child`, which can contain `child1` and `child2`. Each of those can either be a configured terminal or again have `child1` and `child2`.

If you generated this manually I suggest you configure your session layout inside terminix instead and save it as json.

**Comment by nachevn** [comment]
I think my question was not properly framed, sorry. My goal would be to start terminix with multiple sessions (and each sessions has multiple childs). Is that possible?

**Comment by gnunn1** [comment]
At the moment Terminix only supports opening one session at a time. That
session can contain multiple terminals though in whatever layout you want.

Supporting opening multiple sessions is a good idea, I'll mark this as an
enhancement request.

**Comment by nachevn** [comment]
@gnunn1: Thanks for your answer. It would be great if Terminix could also define a command to be executed per terminal e.g.:
`
"child1": {
            "directory": "\/home\/user\/dev\/src\/project_two_dir",
            "height": 1153,
            "profile": "...",
            "type": "Terminal",
            "execute": "pacman -Syy",
            "width": 960
        }
`

**Comment by phw** [comment]
> It would be great if Terminix could also define a command to be executed per terminal [...]

I second this. Basically a command overriding the profile default. Terminator works this way, and I use it to define different "workspaces" for the different development environments I'm working with. I still use profiles to configure the general appearance of the single terminal (e.g. I use a smaller font in terminals for log output), but reuse the profile and just override the command.

**Comment by gnunn1** [comment]
The command override is a good idea and would be easy to support if I just
added the appropriate element to the JSON file and had the user edit it
manually.

While, I'll start with this, handling it somehow from a UI perspective
would be nice. I know Terminator let's you create the layout manually and I
was really hoping to avoid this. Any thoughts on how to manage it?

**Comment by phw** [comment]
Maybe extend the current dialog where you can change the title for a terminal to be a more generic terminal settings dialog. Not sure how to properly name it. By the way, if you override the title here does this already get saved to the JSON?

I agree on avoiding a separate configure session UI.

**Comment by gnunn1** [comment]
Overriding the title does not get saved to the JSON file, I like your idea of a title. How about if I move the Rename Title option into a more generic "Layout Options..." dialog that includes the title and overriding the command? The dialog can include a little note at the bottom to provide info about what it is used for.

**Comment by phw** [comment]
I like that idea and the naming.

**Comment by gnunn1** [comment]
One question for you guys, if you override the command and it executes successfully is the expectation that the shell should stay open after the command executes assuming it doesn't prompt for user input? I have this working locally, but if I set the command to something like "ls" in the JSON file terminix exists as soon as the command finishes.

**Comment by gnunn1** [comment]
Answering my own question, I don't think it is that's feasible to leave the shell open after the command executes. I think the assumption here is you are either executing a command that requires user input or you have the profile option enabled to keep the terminal open. If you have a different opinion feel free to reply and we can discuss.

I've completed this feature so it will be the next release, thanks for the request and input.

**Comment by mannol** [comment]
So, how would one go and load a multiple sessions from a session file?

**Comment by gnunn1** [comment]
@mannol Sorry for the delay in repy, I missed this. Basically you just repeat the session command:

```
terminix --session session1.json --session session2.json
```

**Comment by mannol** [comment]
Thanks.

**Comment by wagoodman** [comment]
@gnunn1 when I try to load multiple copies of the same session terminix crashes and the terminal where I ran `terminix -s session.json -s session.json` says:
```
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by radutomy** [comment]
> I've completed this feature so it will be the next release, thanks for the request and input.

So how does this feature work? Do we have a wiki for it? :D
Thx!

**Comment by gnunn1** [comment]
@radutomy No wiki but it,s easy, just repeat the session parameter:

```
tilix -s session1.json -s session2.json
```

**Comment by radutomy** [comment]
Thanks a lot, that works!

I've modified Unity's dash launcher so that it launches tilix with the arguments  `tilix -a session-add-right`

So now when I'm clicking tilix icon in dash I'm expecting to see tilix with two panels popping up, however all I'm getting is a default session. Writing the same command in the terminal produces the expected results. 

Any ideas?

**Comment by martin-g** [comment]
As a long time roxterm user I also missed this functionality!
Here I how I accomplished it:

- save all my sessions in a special folder
- write the following Shell script (named `tilix-all.sh`) to load them all:

````bash
#!/bin/bash

TILIX_SESSIONS_FOLDER=/home/martin/tilix-sessions

TILIX_OPTS=""

for session in $TILIX_SESSIONS_FOLDER/*; do
  TILIX_OPTS="$TILIX_OPTS -s $session"
done

tilix $TILIX_OPTS
````

Open Tilix and execute `tilix-all.sh`. Voila!

**Comment by bflorat** [comment]
Great ! thanks for the script, works like a charm. 
I didn't know tilix can parse several -s options
